### ISSUE TITLE
I want to export HTML 

### ISSUE THREAD

**Issue by arthurmmedeiros** [aspose-free-consulting/projects#10]
Project:
I used to export data from my application using Aspose. But it used to be only for lists and tables. Now, I have dashboards with various types of charts, widgets, and images. I need to be able to export them. I fetch all the data in my backend, and then render the HTML using react. 

Would there be any way to send the generated HTML to Aspose and have it printed in PDF?

Technologies:
Here I use .Net Core in the backend and React js in the Frontend.

**Comment by shahzad-latif** [comment]
@arthurmmedeiros 

Thanks for getting in touch. Yes, we can help with converting HTML to PDF using Aspose APIs. Would you be able to share the sample input HTML, so we can see how the input looks like. If you have confidential data which you do not want to share then you can update the HTML with some dummy data. 

Also, if you can share/describe/draw how the required output in PDF should look like that will be very helpful for us. Looking forward to assist you in this requirement.

**Comment by shahzad-latif** [comment]
@arthurmmedeiros Can you please share some sample PDF file with charts and widgets that you're using at your end?

**Comment by shahzad-latif** [comment]
@arthurmmedeiros 

Have you build those charts and graphs using JavaScript? Or those in image format? Please note that currently exporting of JavaScript is not supported. However, if those are in image format then the HTML including the images can be exported. Please do let me know what is the current situation.
