### ISSUE TITLE
I want to export think-cell plugin chart as image with axes values. 

### ISSUE THREAD

**Issue by skg06** [aspose-free-consulting/projects#100]
I'm using think-cell plugin for ppt and trying to export chart as image. Chart is being exported without axes values.
But I want to export chart as image with axes values. 

                var shapes = slides[0].Shapes;                
                foreach (var item in shapes)
                {
                    if (item is IChart)
                    {   
                        count++;
                        IChart chart = (IChart)item;                       
                        Image img = chart.GetThumbnail();
                        
                        img.Save(imageDir + "chartImage" + i.ToString() + count.ToString() + ".png", ImageFormat.Png);
                    }
               }

**Comment by shahzad-latif** [comment]
@skg06

We only offer support for [Aspose File Format APIs](https://www.aspose.com/) including [Aspose.Cells for Excel files manipulation](https://products.aspose.com/cells). Our [free support forums](https://forum.aspose.com/) and dedicated support team is there to help you out with our APIs. You may post only Aspose.Cells related questions in [Aspose.Cells free support forum](https://forum.aspose.com/c/cells/9).
