### ISSUE TITLE
I want to analyze a DWG file to interpret the entities in a drawing.

### ISSUE THREAD

**Issue by dzegel** [aspose-free-consulting/projects#102]
Please check if it satisfies the following requirements: 

- [x] It is a small project satisfying a particular scenario
- [x] It is related to Aspose APIs
- [x] It takes 8 or less hours for us to complete
- [x] It is not a bug
- [x] It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

I found a lot of your documentation show how to convert a DWG file to a PDF of image file of some sort but my requirements are a bit different and I'm hoping I can use https://www.nuget.org/packages/Aspose.CAD 

I want to extract the entities represented in a DWG file with a drawing of a building plan.
I **DO NOT** want to generate a PDF, PNG, JPG or other any other image.
I want to read out the basic specs contained in the file in such a way that I can store them in some simple format such as a JSON or YML file.
For example, given a DWG file with a building plan I would like to extract specifics on each:
- wall boundary: where it is placed, which way is it oriented , how tall it is, how wide it is, how thick it is
- electrical fixture: what type of fixture is it, where it is placed, how high it is placed
- door: where it is placed how wide and thick it is, how tall it is, the dimensions of the door frame
- plumbing fixtures: what type of fixture is it, where it is placed, how high it is placed
- stairs: how wide they are, how tall each step is, exactly where it is places and which direction it is oriented

< which platform you're working on -- operating system, development environment etc.> 

Windows 10, C#/dotnetcore (I'm flexible on the specific C# framework)

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by shahzad-latif** [comment]
@dzegel 

We're looking into your requirement and will provide a sample project soon. We'll get back to you if any further information will be required.

**Comment by mudassirfayyaz** [comment]
@dzegel 

In order to proceed further with your requirements we may need the source file for which you want to have a solution. Actually, it is possible only if you can determine how to distinguish door from wall regarding DWG entities. Aspose.CAD API operates on a level of DWG entities like: text, block, line etc. In your case, when you will share the file, we will investigate and formulate a solution based on that. Then you can refer that solution or tailor that as per your needs for other file as well.

**Comment by dzegel** [comment]
@mudassirfayyaz frankly I have not yet determined how I would identify a door for example and I don't have a solution with anything worth sharing with you.. I don't have previous experience with DWG files and am not familiar with what the basic entities are represented in them. My ask is to simply explain or demonstrate how to extract whatever entities are there; like it would be great if I could read all the:
- lines in the file with the coordinates of their two end points, color, and other properties
- blocks (I assume these are simply rectangles) with the coordinates of their 4 corners (or however they are represented), color, and other properties
- text with its position, size, font, color, etc
- whatever other entities may exist

**Comment by mudassirfayyaz** [comment]
@dzegel 

We request you to please share a sample DWG file that you want to process. We will  be in position to share some concrete solution with you based on some source information from your side.

**Comment by shahzad-latif** [comment]
@dzegel 

After not hearing from you on this for long time, I'm going to close this thread. You can always contact our support team via our [free support forums](https://forum.aspose.com/) for quick help.
