### ISSUE TITLE
I want to create tables in a file geodatabase?

### ISSUE THREAD

**Issue by kuntadynithesh** [aspose-free-consulting/projects#104]
I am able to create feature classes in my  file geodatabase which is created using aspose itself . But I am a unable to add a table in a file geodatabase . How can I add  ?

**Comment by shahzad-latif** [comment]
@kuntadynithesh 

Please share the file with us so we can check the issue at our end provide further help.

**Comment by shahzad-latif** [comment]
@kuntadynithesh 

Looks like you're already in discussion with our team in [Aspose.GIS  free support forum](https://forum.aspose.com/t/standalone-table-in-file-gdb/184142/6). That is the best place to get proper and timely help. So please continue the discussion there. I'll close this topic.
