### ISSUE TITLE
Elements wrapper vertical rotation positioned out of the PDF central content

### ISSUE THREAD

**Issue by aarbosa** [aspose-free-consulting/projects#106]
I want to position inside an existing pdf and out of the main central content some elements behaving like a block. Those elements consist of a barcode image, some text and another text with a link.

See the below pdf circled area to make a better idea of what I am refering to:

![ExamplePDF](https://user-images.githubusercontent.com/77447930/104606459-0c792280-5680-11eb-9a5e-fabd5db2ca76.jpg)

I want all that elements to behave like a block to have the possibity to show then vertically or horizontally in an easy way depending on a parameter.

Which is the best approach to implement this with aspose.pdf java library?

I have tried with tables, with a floating box but don´t find definitely the way to place all the elements like a whole in a concrete position and with a concrete rotation angle.

Thank you in advance!

**Comment by asadalikhan90** [comment]
@aarbosa 

We are checking your requirements and will get back to you soon.

**Comment by asadalikhan90** [comment]
@aarbosa 

> I have tried with tables, with a floating box but don´t find definitely the way to place all the elements like a whole in a concrete position and with a concrete rotation angle.

We have checked the related information at our end and found that your requirements need to be investigated in detail. For this purpose, we may need a sample PDF document that contains the vertical block you want to add using Aspose.PDF. We request you please create a post in our [official forum](https://forum.aspose.com/c/pdf) by attaching the requested PDF with it. We will surely proceed further to assist you accordingly as forums are the right place to discuss such issues.
