### ISSUE TITLE
I want to create/build function for convert html to doc, docx file

### ISSUE THREAD

**Issue by soranabox** [aspose-free-consulting/projects#107]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>
I try to create function convert html to docx, doc file for my project
< which platform you're working on -- operating system, development environment etc.> 
my platform are CentOS, .Net Core
<attach input documents>
html file input as attached https://1drv.ms/u/s!Av1LoeuvSP7mgdZXtJc2pjA3QOGXKA?e=Sc4xD8
<attach any sample required output documents if you have> 
docx file expect output as attached https://1drv.ms/w/s!Av1LoeuvSP7mgdZYec_YeP5WJgXhWA?e=anbPco
<attach any additional supporting material to help us understand the requirement>

**Comment by asadalikhan90** [comment]
@soranabox 

We have checked the HTML file and expected output DOCX shared by you. It seems like your HTML file contains form elements and you want them working in the output Word file as well. We need to investigate this particular requirement of yours as we were unable to generate the expected output using both Aspose.HTML and Aspose.Words during testing. We request you please create a post in our [official forum](https://forum.aspose.com/) where your concerns can be addressed accordingly.
