### ISSUE TITLE
Using Aspose.Email

### ISSUE THREAD

**Issue by RezaMatin** [aspose-free-consulting/projects#108]
We would like to start and use Aspose.Email for our project. Before we begin, we have some requirements that we would like to know if Aspose.Email can be used.

Briefly about the project:
The purpose of the project is that we will copy mails from user mailbox to unified group mailbox.
Mails to be copied to unified group are in subfolders. Subfolders title is specified as unified group mail mail-address. Mails in subfolder have default category (Waiting).
After mails that have the category "Waiting" have been copied to unified group, the mail category in the user mailbox must be changed to "Passed"
In case of error, the email category is changed to "Failed"

Requirements:
The code runs as Azure function (dotnet core 3.1)
We have an Azure Active directory app that has access to every user mailbox. This user principal must be used for mailbox access in IEWSCient.

Can Aspose.Email be used in this project?

**Comment by mudassirfayyaz** [comment]
@RezaMatin 

I have found that you have also reached us in [Aspose.Email support forum](https://forum.aspose.com/t/aspose-email-questions/224293/2) as well for the same requirements. 

The API can be used in Azure Functions based applications compiled using .NET Core 3.1 and I have attached the sample project in this regard with you in concerned forum thread. However there are some limitations in API at the moment that may not serve the purpose which include setting category for email and also updating the email using IEWSClient. For this purpose tickets have been created in our issue tracking system and have been associated with [concerned forum thread](https://forum.aspose.com/t/aspose-email-questions/224293/2).
