### ISSUE TITLE
I am trying to convert an .xls file to PDF. I am loading all the supported extensions of Aspose.Cells using LoadFormat() function. 

### ISSUE THREAD

**Issue by Poonamcode** [aspose-free-consulting/projects#110]
var xls = Enum.GetNames(typeof(Aspose.Cells.LoadFormat));  Output is 

![Aspose cellsSupportExtension](https://user-images.githubusercontent.com/73813017/107228265-76e46f00-6a42-11eb-8810-35a8ab143a6f.Jpg)

Please confirm Excel97to2003 supports .xls extension.

Then I compare my file (.xls) extension with aspose.cells library extension.

**Comment by amjad-sahi** [comment]
Yes, your understanding is correct. Excel97To2003 enumeration member refers to XLS and XLT file formats.

**Comment by Poonamcode** [comment]
Hi Amjad,

I am using Aspose.cells library for excel files. I want to compare 2 excel files their sheets and columns.  If A column is present in 1st file and not in 2nd file, I need to add A column into 2nd file. If B column is not present in 1st file sheet and present in 2nd file sheet.  We need to delete B column by comparing the difference between these files. Same goes for sheet also.

Kindly help me , if you provide support for this cases.

Thanks and Regards,
Poonam Mishra

**Comment by amjad-sahi** [comment]
Aspose.Cells follows MS Excel standards and specifications and supports the features which MS Excel incorporates. There is no comparison feature in MS Excel, so Aspose.Cells does not support this feature or provide any concrete option/API for it. I am afraid, there is no better way to accomplish the task. You have to compare spreadsheets’ data cell by cell manually using your own code by yourselves, you may utilize Cell.Value, Cell.StringValue attributes, etc… Also, there are built-in .NET’s String.Equals and CompareTo methods if these can be useful for your requirements.

**Comment by Poonamcode** [comment]
Hi Amjad,

I am using Apose.cells licensed version. Kindly help me to get all the sheet names and column name Header of an excel files using Aspose.cells.

Thanks and Regards,
Poonam Mishra

**Comment by amjad-sahi** [comment]
See the following sample code on how to get each sheet name and get respective column headers in it from an Excel file for your reference:
e.g.
**Sample code:**

```
Workbook workbook = new Workbook("e:\\test2\\Book12.xlsx");
            
            foreach (Worksheet sheet in workbook.Worksheets)
             {
                Console.WriteLine(sheet.Name);
                //we suppose each sheet's first row contains headers(columns)
                Cell endCell = sheet.Cells.EndCellInRow(0);
                if (endCell != null)
                {
                    for (int i = 0; i <= endCell.Column; i++)
                    {
                        Cell cell = sheet.Cells[0, i];
                        Console.WriteLine(cell.Name + ":" + cell.StringValue);
                    }
                    Console.WriteLine("-----");
                }
             }
```
 
Should you have further queries or issue, please post in Aspose.Cells [forum](https://forum.aspose.com/c/cells/9).

**Comment by Poonamcode** [comment]
Hi Amjad,

I am using Aspose.cells and trying to delete list of columns using worksheet.Cells.DeleteColumn(colindex). This do not work in foreach loop.
I am able to delete only 1st column. I am not able to delete other columns. Below is the code snippet.

                        foreach (WorkBookSheetandColumn extracol in xtraColumnInBulk)
                        {
                                //delete xtra column in bulk.
                            Worksheet worksheet = workbook.Worksheets[extracol.sheetName];
                            if (worksheet != null)
                            {

                                Console.Write("\n Are you sure you want to Delete column " + extracol.colHeaderName + " in " + extracol.sheetName + " Sheet ");
                                if (Console.ReadLine().ToLower() == "y")
                                {
                                    worksheet.Cells.DeleteColumn(extracol.colIndex);
                                    log.Info("Deleted column " + extracol.colHeaderName);
                                }
                            }
                         }
Thanks,
Poonam
From: Mishra, Poonam
Sent: 14 April 2021 09:58
To: aspose-free-consulting/projects ***@***.***>; aspose-free-consulting/projects ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [aspose-free-consulting/projects] get all sheet names and column Header Text in an string format using Apose.Cells


Hi Amjad,

I am using Apose.cells licensed version. Kindly help me to get all the sheet names and column name Header of an excel files using Aspose.cells.

Thanks and Regards,
Poonam Mishra

**Comment by Poonamcode** [comment]
Hi Amjad,

Trying to delete 3rd,4th ,5th and 6th columns in an excel sheet using Aspose.cells. With below code snippet , only 3rd (1st) column is deleted from the excel sheet.
Kindly help me on how to delete Multiple columns using columnindex in an excel sheet.

Thanks,
Poonam Mishra

From: Mishra, Poonam
Sent: 23 April 2021 23:56
To: aspose-free-consulting/projects ***@***.***>; aspose-free-consulting/projects ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [aspose-free-consulting/projects] Delete columns in workbook using Apose.Cells

Hi Amjad,

I am using Aspose.cells and trying to delete list of columns using worksheet.Cells.DeleteColumn(colindex). This do not work in foreach loop.
I am able to delete only 1st column. I am not able to delete other columns. Below is the code snippet.

                        foreach (WorkBookSheetandColumn extracol in xtraColumnInBulk)
                        {
                                //delete xtra column in bulk.
                            Worksheet worksheet = workbook.Worksheets[extracol.sheetName];
                            if (worksheet != null)
                            {

                                Console.Write("\n Are you sure you want to Delete column " + extracol.colHeaderName + " in " + extracol.sheetName + " Sheet ");
                                if (Console.ReadLine().ToLower() == "y")
                                {
                                    worksheet.Cells.DeleteColumn(extracol.colIndex);
                                    log.Info("Deleted column " + extracol.colHeaderName);
                                }
                            }
                         }
Thanks,
Poonam
From: Mishra, Poonam
Sent: 14 April 2021 09:58
To: aspose-free-consulting/projects ***@***.******@***.***>>; aspose-free-consulting/projects ***@***.******@***.***>>
Cc: Author ***@***.******@***.***>>
Subject: RE: [aspose-free-consulting/projects] get all sheet names and column Header Text in an string format using Apose.Cells


Hi Amjad,

I am using Apose.cells licensed version. Kindly help me to get all the sheet names and column name Header of an excel files using Aspose.cells.

Thanks and Regards,
Poonam Mishra

**Comment by amjad-sahi** [comment]
> Trying to delete 3rd,4th ,5th and 6th columns in an excel sheet using Aspose.cells. With below code snippet , only 3rd (1st) column is deleted from the excel sheet

Could you try the line of code:
`worksheet.Cells..DeleteColumns(2, 4, true);`

Let us know if you still find any issue.

**Comment by Poonamcode** [comment]
How to delete 4th,5th,6th and 11,12 and 16 column from an excel sheet.


Thanks,
Poonam

**Comment by amjad-sahi** [comment]
First remove 4-6 cols using the line of code:
`worksheet.Cells..DeleteColumns(3, 3, true);`

Please note, after running the above line, the indexes of 11th, 12th and 16th cols are changed now. For example, your 11th column will be 8th column, 12th col will be 9th, Now use this line:
worksheet.Cells..DeleteColumns(7, 2, true);//Remove two cols (8th and 9th)

Now your last col (which you want to delete) has become 11th, so you will use this line at the end:
`worksheet.Cells..DeleteColumn(10);`

**Comment by Poonamcode** [comment]
Hi Amjad,

I am using Aspose.Word Document DOM object to load a word document file.

Document doc = new Document(Test.docx).

Need an Xml representation of this Test document. How can I get whole content in an xml format either in Debug mode or some properties I can browse.
Eg.
<Document>
                <Node>
<paragraph><section></section></paragraph>
<Run></Run>
<shape></shape>
<Table>
                <Row><Cell></Cell></Row>
</Table>
</Node>
</Document>

Please share some of the examples for Traverse, Formatting , layout, preview and Insert static and dynamic text at run time in a paragraph. Hoping for urgent reply.

Thanks,
Poonam

**Comment by awaishafeez** [comment]
@Poonamcode

Please check if the following C# code of [Aspose.Words for .NET](https://products.aspose.com/words/net) API produces desired XML output from Word document on your end?

```
Document doc = new Document("C:\\Temp\\input.docx");
XNode node = JsonConvert.DeserializeXNode(GetJson(doc), "Root");
using (MemoryStream xmlStream = new MemoryStream(Encoding.UTF8.GetBytes(node.ToString())))
using (FileStream file = new FileStream("C:\\Temp\\xml.txt", FileMode.OpenOrCreate, FileAccess.ReadWrite))
    xmlStream.WriteTo(file);
/////////////////////////////
private static string GetJson(Document doc)
{
    StringBuilder sb = new StringBuilder();
    int indent = 1;
    sb.Append(OpenJson());
    sb.Append(OpenElement(doc, indent++));
    foreach (Section section in doc.Sections)
    {
        sb.Append(OpenElement(section, indent++));
        HandleContainer(sb, section.Body, ref indent);
        sb.Append(CloseElement(--indent, (section.NextSibling == null)));
    }
    sb.Append(CloseElement(--indent, true));
    sb.Append(CloseElement(0, true));
    return sb.ToString();
}

private static void HandleContainer(StringBuilder sb, CompositeNode container, ref int indent)
{
    if (!container.HasChildNodes)
        sb.Append(OpenAndCloseElement(container, indent, (container.NextSibling == null)));
    else
    {
        sb.Append(OpenElement(container, indent++));
        foreach (Node node in container.ChildNodes)
        {
            CompositeNode childContainer = node as CompositeNode;
            if (childContainer != null)
                HandleContainer(sb, childContainer, ref indent);
            else
                HandleNode(sb, node, ref indent);
        }
        sb.Append(CloseElement(--indent, (container.NextSibling == null)));
    }
}

private static void HandleNode(StringBuilder sb, Node node, ref int indent)
{
    switch (node.NodeType)
    {
        case NodeType.Run:
            sb.Append(OpenElement(node, indent++));
            Run run = node as Run;
            // for shorter output 
            {
                //sb.Append(WriteElement(nameof(run.Text), run.Text, indent, false));
                //HandleFont(sb, run.Font, ref indent, true);
                //sb.Append(WriteElement(nameof(run.Text), run.Text, indent, true));
            }
            sb.Append(CloseElement(--indent, (node.NextSibling == null)));
            break;
        default:
            break;
    }
}

private static void HandleFont(StringBuilder sb, Aspose.Words.Font font, ref int indent, bool isLast)
{
    sb.Append(OpenElement("Font", indent++));
    sb.Append(WriteElement(nameof(font.Name), font.Name, indent, false));
    sb.Append(WriteElement(nameof(font.Size), font.Size, indent, true));
    sb.Append(CloseElement(--indent, isLast));
}

private static string OpenJson() { return "{\n"; }
private static string OpenElement(Node node, int indent) { return OpenElement(GetNodeName(node), indent); }
private static string OpenElement(string name, int indent) { return GetIndent(indent) + GetQuoted(name) + " : {\n"; }
private static string OpenAndCloseElement(Node node, int indent, bool isLast)
{
    return GetIndent(indent) + GetQuoted(GetNodeName(node)) + " : { }" + GetComma(isLast) + "\n";
}
private static string WriteElement(string name, string value, int indent, bool isLast)
{
    return GetIndent(indent) + GetQuoted(name) + " : " + GetQuoted(value) + GetComma(isLast) + "\n";
}
private static string WriteElement(string name, double value, int indent, bool isLast)
{
    return GetIndent(indent) + GetQuoted(name) + " : " + value + GetComma(isLast) + "\n";
}
private static string CloseElement(int indent, bool isLast) { return GetIndent(indent) + "}" + GetComma(isLast) + "\n"; }
private static string GetNodeName(Node node) { return node.NodeType.ToString(); }
private static string GetQuoted(string value) { return "\"" + value + "\""; }
private static string GetComma(bool isLastElement) { return isLastElement ? string.Empty : ","; }
private static string GetIndent(int indent) { return new string(' ', indent * 2); }
```

**Comment by Poonamcode** [comment]
I am just looking the XML structure of the Document that I passed in Document constructor. This would be manually we are inserting the data for all Elements such as section,Body,Node, Run etc.
Can I get into XNode class ?

Thanks,
Poonam

**Comment by awaishafeez** [comment]
@Poonamcode 

XNode class is part of `System.Xml.Linq` namespace and you need to add following line at the top of your program:

`using System.Xml.Linq;`

I have also attached a sample console application here for your reference:

- [ExportWordNodeStructureToXML.zip](https://github.com/aspose-free-consulting/projects/files/6420877/ExportWordNodeStructureToXML.zip)

**Comment by Poonamcode** [comment]
I have a paragraph Text “I am new to Aspose.Word and R and D on API is Work In progress” .
I have a word document as below
***@***.***D74114.16EFBAC0]



I would like to add my Text in second paragraph after Table Content like below
*Plus applicable taxes. Applicable taxes include sales/property taxes, other taxes and assessments. I am new to Aspose.Word and R and D on API is Work In progress .

I am using Document ,paragraph and InsertAfter but not getting the expected Result.

using (FileStream fs = new FileStream("c:\\MacquarieQuoteProposal.docx",FileMode.OpenOrCreate,FileAccess.ReadWrite))
            {
                Document doc = new Document(fs);
                DocumentBuilder builder = new DocumentBuilder(doc);

                Paragraph paragraph = (Paragraph) doc.GetChild(NodeType.Paragraph, 4, true);
                paragraph.AppendChild(new Run(doc, " Added new Paragraph text from Aspose.Word Library "));
                                                paragraph.InsertAfter()

**Comment by awaishafeez** [comment]
@Poonamcode 
Please note that the main avenue of technical support is through our forums; so, I suggest you to please post a new query in [Aspose.Words forum](https://forum.aspose.com/c/words/8), ZIP and upload your input Word document and your expected DOCX file showing the desired behavior in your forum post for testing. You can create expected DOCX file manually by using MS Word. We will then investigate your scenario on our end and provide you code to achieve the same output by using Aspose.Words.

**Comment by Poonamcode** [comment]
Kindly reply my mail. How to add a text into the existing Paragraph in a Document using Aspose.Word API library.

**Comment by shahzad-latif** [comment]
@Poonamcode,

As suggested by @awaishafeez, please post such queries in our [free support forums](https://forum.aspose.com/c/words/8) so that we can help you in a timely manner and can track issues properly. This is not the place to discuss API related issues. So I would really appreciate your cooperation.

**Comment by Poonamcode** [comment]
Hi,

I am using Aspose.Word library and want to develop a Pie chart. My  DataSource is json object or Binary stream string data value.
Kindly confirm we can build with Document or DocumentBuilder object.

Thanks and Regards,
Poonam Mishra

From: Mishra, Poonam
Sent: 05 May 2021 09:44
To: aspose-free-consulting/projects ***@***.***>; aspose-free-consulting/projects ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [aspose-free-consulting/projects] I am trying to convert an .xls file to PDF. I am loading all the supported extensions of Aspose.Cells using LoadFormat() function. (#110)

Kindly reply my mail. How to add a text into the existing Paragraph in a Document using Aspose.Word API library.

**Comment by awaishafeez** [comment]
@Poonamcode ,

[Creating OOXML charts from scratch using Aspose.Words for .NET](https://docs.aspose.com/words/net/working-with-charts/) API is possible; for example, the following simple C# code will insert a Pie Chart in Word document:

```
Document doc = new Document();
DocumentBuilder builder = new DocumentBuilder(doc);

Shape shape = builder.InsertChart(ChartType.Pie, 432, 252);

Chart chart = shape.Chart;
chart.Series.Clear();
chart.Series.Add("AW Series 1",
                    new string[] { "High", "Significant", "Moderate", "Low" },
                    new double[] { 4, 3, 2, 1 });

doc.Save("C:\\Temp\\pie chart in word.docx");
```

**Comment by Poonamcode** [comment]
Hi,

I am using Aspose.Cells licensed version. I have a Date column and its Alignment is Right Alignment due to which I cannot see the Time stamp on it.
I need to make column 4th as Left Alignment instead of Right Alignment. How can I do. Your help is needed.

Thanks,
Poonam


From: Mishra, Poonam
Sent: 18 May 2021 00:11
To: aspose-free-consulting/projects ***@***.***>; aspose-free-consulting/projects ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [aspose-free-consulting/projects]
Importance: High

Hi,

I am using Aspose.Word library and want to develop a Pie chart. My  DataSource is json object or Binary stream string data value.
Kindly confirm we can build with Document or DocumentBuilder object.

Thanks and Regards,
Poonam Mishra

From: Mishra, Poonam
Sent: 05 May 2021 09:44
To: aspose-free-consulting/projects ***@***.******@***.***>>; aspose-free-consulting/projects ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [aspose-free-consulting/projects] I am trying to convert an .xls file to PDF. I am loading all the supported extensions of Aspose.Cells using LoadFormat() function. (#110)

Kindly reply my mail. How to add a text into the existing Paragraph in a Document using Aspose.Word API library.

**Comment by shahzad-latif** [comment]
@Poonamcode ,

Please post this query in our [free support forums](https://forum.aspose.com/) so that our team can help you properly and timely. Thanks.
