### ISSUE TITLE
I want to create/build an application where user can upload STL file upto 1 GB and it can be viewable on the browser.

### ISSUE THREAD

**Issue by tcs-jay-doshi** [aspose-free-consulting/projects#111]
I would like to confirm that using ASPOS.3D API, user can upload STL file upto 1 GB and it can be viewable on the browser. If it is possible, please do let me know that to support 1GB of file which license I need to purchase.

Also, I have checked on your demo site where I can only allow to upload 100MB file that's the reason I need the confirmation.

**Comment by asadalikhan90** [comment]
@tcs-jay-doshi 

We believe that you have posted a [similar inquiry](https://forum.aspose.com/t/225013/2) in Aspose.3D official forum and we have responded to you there accordingly. You can please follow up there and share your feedback. We will continue to provide support there.

**Comment by tcs-jay-doshi** [comment]
I replied on same thread, kindly do needful to reply there. Thanks in advance

**Comment by asadalikhan90** [comment]
@tcs-jay-doshi 

We have noticed your inquiry there and will provide our response to it shortly.

**Comment by tcs-jay-doshi** [comment]
> @tcs-jay-doshi
> 
> We have noticed your inquiry there and will provide our response to it shortly.

I will look forward to hear from you

**Comment by tcs-jay-doshi** [comment]
@asadalikhan90 @freeconsultingaspose 

By navigating to the http://localhost:4200/3d/viewer, we able to successfully open the page. However, there is also limitation of uploading 100MB of file to view in 3D viewer. We increase that limit from the code and try again to upload it however large file never loaded to the viewer. 

It would be great if you can provide us sample code where we can just upload STL file upto 1GB of size and it extract the height, weight, depth and volumn of the object. If you have any documentation which shows how to get model details you can share it with us.

Thanks

**Comment by asadalikhan90** [comment]
@tcs-jay-doshi 

We are looking into the scenario and will get back to you shortly.

**Comment by asadalikhan90** [comment]
@tcs-jay-doshi 

We have responded to [your inquiry](https://forum.aspose.com/t/225013/7) over our forum where you can please check the shared information.
