### ISSUE TITLE
Issues with activating the Aspose.PSD product license

### ISSUE THREAD

**Issue by ARVLab** [aspose-free-consulting/projects#114]
The documentation contains information on installing a license. 

But in fact, the code does not have a method for checking the license.

As a result, after activation through available methods, the processed photo indicates that the product is not activated:

During the activation process, there are no errors or warnings.

Please may you tell me how to solve this problem and how to install the license successfully?

![1](https://user-images.githubusercontent.com/30734946/108508076-ee789080-72c3-11eb-9292-2ddbc2d52f6c.jpg)
![2](https://user-images.githubusercontent.com/30734946/108508077-ef112700-72c3-11eb-88a5-eb2793bbde60.jpg)
![3](https://user-images.githubusercontent.com/30734946/108508078-efa9bd80-72c3-11eb-90d9-aa9341235823.jpg)

**Comment by shahzad-latif** [comment]
@ARVLab 

Kindly post this query in our [free support forums](https://forum.aspose.com/c/psd/34). You'll be able to get proper and time help there. Thanks.
