### ISSUE TITLE
I want to convert an HTML with external css and barcode link into PDF.

### ISSUE THREAD

**Issue by jtdev2021** [aspose-free-consulting/projects#116]
I have an HTML file 
[1.zip](https://github.com/aspose-free-consulting/projects/files/6041659/1.zip)

which contains links to external css and barcode.

<link rel="stylesheet" type="text/css" href="https://express.tnt.com/expresswebservices-website/rendering/css//label-rendering-style.css"/>
<link rel="stylesheet" type="text/css" href="https://express.tnt.com/expresswebservices-website/rendering/css//label-rendering-style-fr.css"/>

<div id="barcode" name="barcode">
<img src="https://express.tnt.com/barbecue/barcode?type=Code128C&amp;height=140&amp;width=2&amp;data=1100432167277010118435045699"></div>
<div id="barcodeLabel">1100432167277010118435045699</div>

When using aspose library (PDF and HTTML) its only converting the text. The css has barcode is missing.

**Comment by shahzad-latif** [comment]
@jtdev2021 

We're investigating this matter and will get back to you with details guidelines soon.

**Comment by asadalikhan90** [comment]
@jtdev2021 

We have tested the scenario in our environment while using Aspose.PDF for .NET 21.2 and the following code snippet. We did not notice any issue. 

```
HtmlLoadOptions options = new HtmlLoadOptions();
options.IsRenderToSinglePage = true;
var htmlBody = File.ReadAllText(dataDir + "1.html");
var htmlByteArray = Encoding.UTF8.GetBytes(htmlBody);  // The default character encoding for HTML5 is UTF-8.
using (var stream = new MemoryStream(htmlByteArray))
{
 using (Document pdfDocument = new Document(stream, options))
 {
  pdfDocument.Save(dataDir + "output.pdf");
 }
}
```
[output.pdf](https://github.com/aspose-free-consulting/projects/files/6064917/output.pdf)

An output PDF is also attached for your kind reference. Would you please make sure that you are using the API with a valid license. Please consider applying for [a free 30-day temporary license](http://purchase.aspose.com/temporary-license) in case you do not have one and let us know if issue still occurs.

**Comment by shahzad-latif** [comment]
@jtdev2021 

In case of such questions or issues, please post in our [file format APIs free support forums](https://forum.aspose.com/) so our dedicated team can help you in a timely manner. This space is only reserved for free consulting projects. Thanks.
