### ISSUE TITLE
I want to know which Aspose product can fit the requirement

### ISSUE THREAD

**Issue by gc2000** [aspose-free-consulting/projects#118]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>
**I'm looking for a product that can fit the following requirements:**
**Based on pre-defined template to generate PDF files as e-certificate
1. The template can be MS Powerpoint or MS Word. (either one will do) 
2. The parameter of the template includes text, image file(eg, image of signature)
3. Able to create watermark in the PDF file**

 
< which platform you're working on -- operating system, development environment etc.> 
**AWS cloud, Windows OS, .net. 
Host in Docker (prefer) or EC2** 

<attach input documents>
![sample template](https://user-images.githubusercontent.com/12391578/109190830-7bde4800-77d0-11eb-890d-ad7d76f47aef.jpg)

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by shahzad-latif** [comment]
@gc2000 

Our team is looking into this requirement and will share the guidelines to achieve this shortly.

**Comment by mudassirfayyaz** [comment]
@gc2000 

After observing the requirements stated in [this image](https://user-images.githubusercontent.com/12391578/109190830-7bde4800-77d0-11eb-890d-ad7d76f47aef.jpg), Aspose.Slides can be used to accomplish the requirements. In order to proceed further, can you please share the template presentation and desired output PDF file that we can process on our end. 
For adding watermark, please share specifically in your desired output. We can provide you a solution based on Visual Studio .NET Console application that you may easily use on your end.

**Comment by awaishafeez** [comment]
@gc2000 

You can also meet this requirement by using [Aspose.Words for .NET](https://products.aspose.com/words/net) API. You can use merge fields as placeholders while [defining template Word document](https://docs.aspose.com/words/net/mail-merge-template/), then use [mail merge feature of Aspose.Words](https://docs.aspose.com/words/net/mail-merge-and-reporting/) to replace merge fields with text and image, then [add a watermark](https://docs.aspose.com/words/net/working-with-watermark/) and finally [save the report in the PDF file format](https://docs.aspose.com/words/net/convert-a-document-to-pdf/). Please see these example DOCX template, output PDF, Image files and try running the following C# code:

1. [mail merge template.docx](https://github.com/aspose-free-consulting/projects/files/6059322/mail.merge.template.docx)
2. [report in pdf file format.pdf](https://github.com/aspose-free-consulting/projects/files/6059334/report.in.pdf.file.format.pdf)
3. ![aspose_words-for-net](https://user-images.githubusercontent.com/11070349/109456248-3775d500-7a7a-11eb-95ec-f7d2eb2c3c5e.png)

```
Document doc = new Document("C:\\temp\\mail merge template.docx");

doc.MailMerge.Execute(new string[] { "name", "signature" }, new object[] { "Aspose.Words", "C:\\Temp\\aspose_words-for-net.png" });

doc.Watermark.SetText("Confidential",
    new TextWatermarkOptions() { IsSemitrasparent = true, Layout = WatermarkLayout.Diagonal });

doc.Save("C:\\temp\\report in pdf file format.pdf");
```
