### ISSUE TITLE
Take a picture of barcode and decode the barcode in javascript / java in a webpage

### ISSUE THREAD

**Issue by tariqg11** [aspose-free-consulting/projects#119]
I am looking to build a function in webpage where user can take picture of a barcode and decode it, the data can then be consumed by the user. I would like to accomplish this preferably in JavaScript otherwise Java.

**Comment by asadalikhan90** [comment]
@tariqg11 

Would you please share how you want to extract the barcode image from a webpage? Do you want to use Aspose.HTML for Java in the code behind or some simple JavaScript function to carry out this functionality? We will try to create a sample application using both Aspose.HTML and Aspose.Barcode and share with you.

**Comment by tariqg11** [comment]
I would like the 'take-picture' function on webpage to allow user to take picture of a barcode, the barcode then gets decoded via Api (Aspose). I'd prefer a javascript function so that the API key does not get exposed in HTML page.

**Comment by ahsaniqbalsidiqui** [comment]
@tariqg11,
We are analyzing your requirement and need assistance as follows:

1. Please explain in detail the 'take-picture' function on the webpage. How the picture of a barcode will be taken and used by the API? Provide complete use case.
2.  Which API are you planning to use? Is it Aspose.BarCode cloud or Aspose.BarCode for Java at the server-side? As you are talking about API key, so it seems that you are using Aspose.BarCode cloud API.

Share the required details with us. We will analyze it and share our feedback accordingly.

**Comment by tariqg11** [comment]
1. User will visit a web-page of a business entity to register. The website
gives option to user to take picture of their ID card / Driving license
with PDF-417 barcode. The user takes pic of the license / ID, the website
app then uses the Aspose BarCode API to decode the PDF417 barcode to
extract data.
2. I am mainly interested in Aspose.BarCode for Java (javascript / server
side), that is my preference.

Thank you for your time and efforts into this, I hope to see a
solution soon. If you have anymore questions please let me know.

**Comment by ahsaniqbalsidiqui** [comment]
@tariqg11,
Thank you for providing more details. We are working on this requirement and will share our feedback soon.

**Comment by ahsaniqbalsidiqui** [comment]
@tariqg11,
We have prepared a working sample project for this issue and will be launching it soon. We will share the link to the project on GitHub once it is launched.

**Comment by shahzad-latif** [comment]
@tariqg11 

Please check the sample project along with detailed how to guide at the following link: [Decode-Barcode-Image-with-JavaScript-Aspose-Barcode](https://github.com/aspose-free-consulting/Decode-Barcode-Image-with-JavaScript-Aspose-Barcode). 

Please feel free to ask if you have any questions related to this. In case, you need any further assistance about our APIs, please use our [File Format APIs Free Support Forums](https://forum.aspose.com/c/cells/). We'll be able to provide quick and appropriate support there. Thanks.

**Comment by tariqg11** [comment]
@shahzad-latif : I tried to implement the sample project, when I upload the file via browser unfortunately it doesn't provide any information and times out. Can you please check and confirm if you see this issue? Browser I used is Chrome (Version 89.0.4389.90 (Official Build) (64-bit))

**Comment by ahsaniqbalsidiqui** [comment]
You may please ensure that you have created a folder "C:\TestFolder\Images" for uploading the images if you are working in C drive of your system. Otherwise create this folder in the respective drive where this code is being tested. If still issue is there, share the image of command window where you executed the "fileUpload.js" using the CMD file run_file_upload.cmd after pressing the "Submit" button in the HTML page.

**Comment by tariqg11** [comment]
I tried fresh copy / installation in c:\TestFolder and here is the output:

C:\TestFolder>node ./lib/fileUpload.js
internal/modules/cjs/loader.js:1122
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\TestFolder\node_modules\java\build\Release\nodejavabridge_bindings.node
←[90m    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
    at Object.<anonymous> (C:\TestFolder\node_modules\←[4mjava←[24m\lib\nodeJavaBridge.js:21:16)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m

**Comment by ahsaniqbalsidiqui** [comment]
@tariqg11,
Could you please display the version information of each Java, Node.js and Python in command window and share the results with us? Also please try it on some fresh Windows 10 VM if possible.

**Comment by tariqg11** [comment]
Hello Mr Ahsan,

Please find below the responses for node -v and java -version
>node -v
v14.16.0

>java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

Thanks,
Tariq

**Comment by ahsaniqbalsidiqui** [comment]
@tariqg11,
For testing purpose, is it possible to test it with Oracle JDK 15.0.2 at your end?

**Comment by ahsaniqbalsidiqui** [comment]
I have tested the scenario in a fresh Windows 10 VM and followed the exact steps mentioned above.  No other software is installed except the above three i.e. Oracle JDK 15.0.2, Python 3.9.2 and Node.js 14.16.0. Extracted the package in C:\TestFolder and it worked fine. Please give it a try by following the exact steps once and share your feedback.

**Comment by ahsaniqbalsidiqui** [comment]
We have observed following issue using OpenJDK and analyzing it further. You may please test it using Oracle JDK in the meanwhile and share your feedback.
https://github.com/aspose-free-consulting/projects/issues/119#issuecomment-808932988

**Comment by tariqg11** [comment]
@ahsaniqbalsidiqui : I installed Oracle JDK 15 and this time didn't run into the error seen earlier, however, had no luck getting the image decoded. This time I got different error:

C:\TestFolder>node ./lib/fileUpload.js
C:\TestFolder\lib\fileUpload.js:18
        if (err) throw err;
                 ^

[Error: EPERM: operation not permitted, rename 'C:\Users\TariqHP\AppData\Local\Temp\upload_1282aa49f6cb45f463f42e1b87f92347' -> 'C:\TestFolder\Images\sample2.png'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'rename',
  path: 'C:\\Users\\TariqHP\\AppData\\Local\\Temp\\upload_1282aa49f6cb45f463f42e1b87f92347',
  dest: 'C:\\TestFolder\\Images\\sample2.png'
}

**Comment by ahsaniqbalsidiqui** [comment]
Could you please explain '<>' in the path given below? Is it shown in the error by default? Try this scenario in some drive other than C-Drive as some permission issues may affect this scenario. Also try this scenario on some other system and share your feedback. Please share your environment details also for our reference.

If possible, try this scenario by running the application in Administrator mode.

**Comment by tariqg11** [comment]
The '<>' is the removed path name (too long) I removed manually. I ran the
test again with 'Administrator' mode and it worked but took lots of time
and PC resources to decode.

**Comment by ahsaniqbalsidiqui** [comment]
@tariqg11,
The performance of Java-Node.js bridge and our library as a whole depends on computer power on which the tests are being launched. The first call to node.js library requires the initialization of Java-node.js bridge and it takes additional time. The results of subsequent calls take much less time. The difference between Java and Node.js is due to consumption by Java-Node.js bridge and node.js engine that is beyond our control.
