### ISSUE TITLE
APSOSE Digital Signature

### ISSUE THREAD

**Issue by sghavare** [aspose-free-consulting/projects#12]
We have purchase aspose pdf and one of the requirement is to digitally signed each IRS form. Specially W8BEN.

Please refer attached file for more details. 
![digitalySignature](https://user-images.githubusercontent.com/51722171/66422874-7feda800-e9d8-11e9-8191-7e61e3a4b190.png)

Our requirement is that, each individual user is going to fill out W8Ben form and going to sign it digitally. Do we need pfx file for each individual user. Will ASPOSE allow user to draw a signature like docusign.

**Comment by shahzad-latif** [comment]
@sghavare 

Thanks for getting in touch. Yes, a separate PFX file will be required for each user which need to sign the PDF. The Aspose.PDF does allow to add digital signature programmatically. For example, please have a look at the following link: https://docs.aspose.com/display/pdfnet/Digitally+sign+PDF+file

The same example can be found on github as well: https://gist.github.com/aspose-pdf/7e1330795d76012fcb04248bb81d45b3#file-examples-csharp-asposepdf-security-signatures-digitallysign-digitallysign-cs

Do you think this works for you or you need any help with its customization? Or your requirement is a bit different than this? Please feel free to let us know.

**Comment by sghavare** [comment]
We are using APSOSE pdf to generate pdf along with digital signature. We are getting inconsistent error while generating pdf with digital signature. This was working fine till last week. But not sure after new version released on 15th Oct, Digital signature stops functioning consistently. Below is the error description.

Error Desc -  The Contents field is empty or missing. The digital signature is compromised
Stack trace - "at Aspose.Pdf.Forms.Signature.#=zQzLrbK_N8Ahc5pMnWcRVGKU=(#=zCSGqRHoKA8soenH3p5ChG11Uz66biA5jzQ== #=zFCA7FbA=, #=zkcDp5IS0prWj166X9$W1gb6402u5 #=znc1dJts=)    at Aspose.Pdf.Forms.Signature..ctor(#=zCSGqRHoKA8soenH3p5ChG11Uz66biA5jzQ== #=zFCA7FbA=, #=zkcDp5IS0prWj166X9$W1gb6402u5 #=znc1dJts=)    at Aspose.Pdf.Forms.PKCS7..ctor(#=zCSGqRHoKA8soenH3p5ChG11Uz66biA5jzQ== #=zFCA7FbA=, #=zkcDp5IS0prWj166X9$W1gb6402u5 #=znc1dJts=)    at Aspose.Pdf.Forms.SignatureField..ctor(#=zjIvfumiDMs7BZw2lAlZKJbGoZhq24lOBWw== #=zB6uX1f4=, Document #=znc1dJts=)    at Aspose.Pdf.Forms.Field.#=zvxSR1Yw=(#=zjIvfumiDMs7BZw2lAlZKJbGoZhq24lOBWw== #=zdJK9Fy8=, Document #=znc1dJts=)    at Aspose.Pdf.Forms.Form.#=zN69MPUI=.get_Current()    at Aspose.Pdf.Forms.Form.#=zSnfudjJ$S2w$6GQowOStPS8=(String #=zev04klS3x6pjWeUBNw==, #=zOxfbL$$hmenCu4RzcSG_dkaCtPjsi0j5Vw== #=zBntGMlA=, ICollection`1 #=z$nHgBBc=)    at Aspose.Pdf.Forms.Form.#=zRi7UZfU=(String #=z$qUIzag=)    at Aspose.Pdf.Facades.Form.FillField(String fieldName, String fieldValue)    at EY.TAX.eTFV.Common.PDFHandler.CreatePDF(IDictionary`2 fields, Stream templatefile, Stream licstream, Stream PFXStream, Boolean isSign, IDictionary`2 signvalues, String webRootPath) in /src/EY.TAX.eTFV.Common/PDFHandler.cs:line 30    at EY.TAX.TFV.Services.Concrete.CaseService.UploadCaseForm(Int64 caseId, String clientName, String dbName, Boolean Issigned, String webRootPath) in /src/EY.TAX.TFV.Services/Concrete/CaseService.cs:line 67    at EY.TAX.eTFV.WebApp.Controllers.CustomerController.PDFForm(Int64 caseid, Boolean isUpload, Boolean Issigned) in /src/EY.TAX.eTFV.WebApp/Controllers/CustomerController.cs:line 136    at lambda_method(Closure , Object , Object[] )    at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()    at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)    at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)"

We have Aspose licence and this issue is super critical. 

Any help on this issue will be highly appreciated.

**Comment by shahzad-latif** [comment]
@sghavare 

Sorry to hear about this issue. However, as this is bug in the API, please report it in our [Aspose.PDF forum dedicated for PDF API related issues and feature requests](https://forum.aspose.com/c/pdf). A dedicated team member would be able to help you quickly and if this needs to be fixed in the API then he would also log it accordingly. Thanks for your cooperation.
