### ISSUE TITLE
Modify EPS files having 2-D drawing - Is this possible ?

### ISSUE THREAD

**Issue by khaianwar** [aspose-free-consulting/projects#120]
I plan to use Aspose.Page product to load EPS file which contains 2-D drawing image.

Is it possible to amend the image to do the following ?

- delete/erase certain line vector that exist in the image
- crop/move certain part of line vector which is in a closed loop (like a circle image)
- extend the vector line length while maintaining the line curve/direction

I plan to do this programmatically using Aspose page API when the user interact with the loaded EPS inside the Viewer.

**Comment by asadalikhan90** [comment]
@khaianwar 

Regretfully, Aspose.Page does not offer functionality to manipulate the images inside EPS/PS files at the moment. Furthermore, we believe that we have responded to [your similar inquiry](https://forum.aspose.com/t/modify-eps-files-having-2-d-drawing/226338/4?u=asad.ali) in our support forum where a feature request ticket is also attached with the post. You may please follow up there to track the progress against the logged ticket.
