### ISSUE TITLE
Service to be host in private Cloud & support for web, android and ios.

### ISSUE THREAD

**Issue by shashiskm** [aspose-free-consulting/projects#121]
Can this service be hosted in a private cloud? 
Also, does it support android, ios and the web?

**Comment by shahzad-latif** [comment]
@shashiskm 

Please check this, if that helps in your scenario: https://purchase.aspose.cloud/self-hosting. Moreover, please note that our cloud APIs are REST based and can be used for any platform with any language. In case, you find any further questions, please feel free to post your query in [aspose.cloud free support forums](https://forum.aspose.cloud/). We'll be glad to help.
