### ISSUE TITLE
Saving MPP with default view, does not apply view columns, filters, styles and returns all tasks

### ISSUE THREAD

**Issue by jokincelemin** [aspose-free-consulting/projects#122]
Good afternoon,

I have a problem with the export the mpp file to excel. 
When I export the file, firstly the new mpp file weighs less than the original file. I don't know if this is normal or not.
The real problem is, i want to set new DefaultView and export it to excel in the format of the view, with their columns, styles, filters, groups, but in the excel always appears the same: all task with default columns:

"ID | Active | Task Mode | Name | Duration | Start | Finish | Predecessors | Outline Level | Notes"

//Project (2.944 KB)
var project = new Project("file.mpp");

project.DefaultView = project.Views.First(e => e.Name == _name_view); //_name_view = Name of the specific view

//Project saved (2.274 KB)
//project.Save("test.mpp", new MPPSaveOptions { WriteViewData = true });

//Excel saved without styles, without filters applied (all tasks appears)
project.Save("test.xlsx", SaveFileFormat.XLSX);

Thanks and regards.

**Comment by mudassirfayyaz** [comment]
@jokincelemin 

We have assessed your requirements and regret to share that there is no such an api fulfilling the complete requirements. The styles are not supported as API export in CSV which is text format, no styles there. The Filters are MPP objects and if it is intended to filter the tasks, you can delete them from project code only and do the export. The following sample code will be helpful to you in achieving what is possible using API.

```
var project = new Project("Apartments.mpp");
            var columns = new List<ViewColumn>
            {
                new GanttChartColumn("Task Mode", 50, Field.TaskManual),
                new GanttChartColumn("Id", 50, Field.TaskID),
                new GanttChartColumn("Name", 100, Field.TaskName),
                new GanttChartColumn("Start", 100, Field.TaskStart),
                new GanttChartColumn("Finish", 100, Field.TaskFinish),
                new GanttChartColumn("% Complete", 50, Field.TaskPercentComplete),
                new GanttChartColumn("Start Actual", 100, Field.TaskActualStart),
                new GanttChartColumn("Finish Actual", 100, Field.TaskActualFinish),
                new GanttChartColumn("Super Notes", 100, Field.TaskText4),
                new GanttChartColumn("Resource Names", 100, Field.TaskResourceNames),
                new GanttChartColumn("Predecessors", 50, Field.TaskPredecessors)
            };
            var options = new XlsxOptions
            {
                View = new ProjectView(columns), 
                PresentationFormat = PresentationFormat.GanttChart
            }; 

```

**Comment by jokincelemin** [comment]
Thank you very much for your quick reply.

Okay, we'll handle it this way.

Regards!

**Comment by jokincelemin** [comment]
Hi again!

We are worried about this matter.

The code you gave me works fine but it returns all the records and we need to get the information from a specific view that is inside the file.

We have seen that the library returns a list of views and among them is the one we need.

We do not understand how a paid library does not allow exporting the data in a specific view.

Would it be possible to obtain the records of the view? Although we have to generate the excel manually.

We have the ASPOSE.Task .NET license 999 $

Sorry for the inconvenience,

**Comment by mudassirfayyaz** [comment]
@jokincelemin 

Can you please provide is with source MPP file and desired output that you ought to generate. It will be helpful to us to understand further and come up with any possible solution if API provides support of.

**Comment by jokincelemin** [comment]
Thanks for reopen,

The data in the file is confidential and unfortunately we cannot upload it.

The example would be simple, a project with 4 lines for example, and when if you click on the view, you only see 2 of those records.

We need to be able to select this view and when export to excel only those 2 records.

For this reason I was asking if there is any way to get the records of a specific view, because the project detects the views and you can define it as DefaultView and when saving as MPP again it seems that it keeps it, but the data does not, display all the records.

Thanks in advance,

**Comment by jokincelemin** [comment]
Good afternoon,

We have achieved a similar MPP with false data for the example.

We want to see the data in the "Seguimiento Obra IT".

Thanks in advance

[P. Eolico.mpp.zip](https://github.com/aspose-free-consulting/projects/files/6198179/P.Eolico.mpp.zip)

**Comment by mudassirfayyaz** [comment]
@jokincelemin 

Thank you for sharing the information. Can you please also share the desired output that you ought to generate as that will be helpful to us for assessing if the API can serve that or not.

**Comment by jokincelemin** [comment]
Yes, of course! 

I have upload 3 photos: 1 - Origin, 2 - Destiny and 3 - View to apply 
![destiny](https://user-images.githubusercontent.com/75124119/112487658-308e6980-8d7d-11eb-848b-82ceadf1750e.png)
![view](https://user-images.githubusercontent.com/75124119/112487661-31bf9680-8d7d-11eb-8e3d-dc42c4262d58.png)
![origin](https://user-images.githubusercontent.com/75124119/112487663-31bf9680-8d7d-11eb-9a62-5c424b4e6827.png)

The colors are not important, only the data,

Thanks and regards!

**Comment by jokincelemin** [comment]
Good morning, have you been able to look at it?

It is an issue that urges us a bit.

Tranks and regards,

**Comment by mudassirfayyaz** [comment]
@jokincelemin 

Please allow us some time to work over it and we will get back to you with feedback as soon as possible in this regard.

**Comment by mudassirfayyaz** [comment]
@jokincelemin 

At present, Aspose.Tasks does not support filtering/grouping on export to XLSX format. Therefore, the desired view is currently not possible. However, we have added a ticket with ID **TASKSNET-4787** to provide the requested support. The tentative ETA for the availability of the support is Aspose.Tasks for .NET 21.5. In order to stay updated, I suggest you to please add request in [Aspose.Tasks free support forum](https://forum.aspose.com/c/tasks/15) so that we may apprise you as soon as the support will be included.

**Comment by jokincelemin** [comment]
Good morning,

Sorry, I've been on vacation for Easter.

Okay thank you very much.

We would like to know when the functionality would be done approximately.

Regards, and thank you very much.

**Comment by shahzad-latif** [comment]
@jokincelemin 

As per last comment from @mudassirfayyaz, this is expected in version 21.5, which means May 2021. However, this is a tentative plan. If you want to be notified when this is available, please create a new thread in forum [free support forums](https://forum.aspose.com/c/tasks/15), so we can link this issue to the thread and then you'll be automatically notified once the feature is available.
