### ISSUE TITLE
New functionality of Filter on Export MPP to CSV/Excel

### ISSUE THREAD

**Issue by jokincelemin** [aspose-free-consulting/projects#125]
Good morning,

I have seen in the last release, the new funtionality of filter tasks exporting to CSV/Excel.

I have try to implement the custom filter, but the method GetByFieldId does not exist.

![aspose_espec](https://user-images.githubusercontent.com/75124119/115011138-8e126380-9eae-11eb-9a19-1ca0b3251f4a.png)
![aspose_error_espec](https://user-images.githubusercontent.com/75124119/115011146-8fdc2700-9eae-11eb-8490-5cf9cfd3ff46.png)
![aspose_version](https://user-images.githubusercontent.com/75124119/115011405-e0538480-9eae-11eb-9402-18fab9432c5b.png)

Thanks and regards,

**Comment by shahzad-latif** [comment]
@jokincelemin 

Please post this issue in our free support forums: forum.aspose.com/c/tasks/. Our support team will help you and guide you properly. Thanks.
