### ISSUE TITLE
PDF Generation Modernization

### ISSUE THREAD

**Issue by Chongbeng** [aspose-free-consulting/projects#126]
Current Landscape

- We have been doing HTML-to-PDF conversion from our web content. Such content could be policy documents, acknowledgements, letters. We currently maintain a lot of HTML-based templates within our programs and what our applications does is to inject dynamic data into these templates and generated to PDF on-the-fly using the current PDF conversion software we have.

- The PDF content can include dynamic layout eg.  population of data in a table which may change depending on how much data is need to present at a runtime.

Pain Points

- As limited by our current PDF conversion approach, the PDF content layout is always subjected to how the browser engine interprets the HTML and generates the PDF accordingly.

- Our IT teams spent a lot of effort to maintain, amend and test the HTML templates every time whenever we migrate to another browser engine and this seemed to be less and less sustainable.

Our goal

- We are looking at a long term strategy to reduce our IT maintenance in terms of maintaining HTML templates as it is always subjected to how the browser engine interprets and renders the HTML. 

- is html to pdf the best way moving forward?
- At the same time, this new solution should not subjected to such volatility and possibly a much more modern or efficient approach to performing PDF conversion from template and dynamic data input to PDF template.

- The source content to be converted to pdf should be self contained and does not need to lookup external sources.

- At the same time, we also try to empower our end-users as much as possible in terms of maintaining so many different templates and not rely on the IT team to make the changes to the templates as much as possible.

- What are the possible deployment models available to reduce our IT footprint/maintenance on our end and achieve better efficiency in deploying apps with PDF generation needs?

**Comment by asadalikhan90** [comment]
@Chongbeng 

We have gone through your requirements and would like to share with you that Aspose.PDF and Aspose.HTML both offer the feature to convert HTML files into PDF documents. In case your work involves the processing of HTML files and templates - and you only need to convert them to PDF after processing is done, Aspose.HTML would be the right API for you. Following documentation article(s) put more light on the features that API can offer:

* [Working with HTML Documents](https://docs.aspose.com/html/net/working-with-documents/)
* [HTML to PDF Conversion](https://docs.aspose.com/html/net/converting-between-formats/html-to-pdf-conversion/)

Furthermore, if you could please share some of your sample HTML documents along with your expected output PDF files, we will test the scenario in our environment and share our feedback with you accordingly.

**Comment by shahzad-latif** [comment]
@Chongbeng 

Please use our free support forums for APIs related support so we can help you properly and timely. I'll close this thread. Thanks.
