### ISSUE TITLE
Html to pdf

### ISSUE THREAD

**Issue by Khadar482** [aspose-free-consulting/projects#128]
Hi team,

I have a requirement where I need to convert HTML file/string into pdf, where html will have graphs, charts, Images etc. I want all of them should render or embedded in output pdf with same styles.

Is the above requirement is possible in ASPOSE, if possible please share me the demo link.

Thanks,
Khadar M.

**Comment by asadalikhan90** [comment]
@Khadar482 

We at Aspose offer Aspose.PDF and Aspose.HTML APIs which both offer the feature to convert HTML file/string into PDF. Following documentation links can be used in order to get code demos that will help you achieve the functionality. 

* [Convert HTML to PDF using Aspose.PDF](https://docs.aspose.com/pdf/net/convert-html-to-pdf/) 
* [Convert HTML to PDF using Aspose.HTML](https://docs.aspose.com/html/net/converting-between-formats/html-to-pdf-conversion/)

Please feel free to let us know in case you need further information OR you face any issue while trying the code snippet(s) given in the above articles.

**Comment by Khadar482** [comment]
Hi @asadalikhan90 ,

I tried using above scenario but in my case html files will have graphs which are not rendering in PDF.

the same scenario am able to achieve using HIQ pdf library.

please find the below screnario am trying to achive.

![image](https://user-images.githubusercontent.com/75469516/115427714-55141f00-a21f-11eb-941d-c7c33bd0bf41.png)
![image](https://user-images.githubusercontent.com/75469516/115427842-707f2a00-a21f-11eb-9380-a14367aff43b.png)
![image](https://user-images.githubusercontent.com/75469516/115427913-812fa000-a21f-11eb-9523-5068993e8d7f.png)

**Comment by asadalikhan90** [comment]
@Khadar482 

Would you kindly share how graphs are rendering in the HTML? Are you using some JavaScript Library to render them on runtime? Please share your sample HTML file in .zip format by attaching it to your reply. We will test the scenario in our environment and address it accordingly.

**Comment by Khadar482** [comment]
Hi Asad,

Please find the below Html text .

Our team wants to contact Aspose helpdesk team from their official account. please guide how to contact (they have aspose license)
```

<!DOCTYPE html>
<html lang="en-US">
<body>
    <head>
        <link href="fontTest.css" rel="stylesheet" />
        <style>
            body {
                font-family: "Noto Sans", sans-serif;
                font-size: 16px;
            }

            h1 {
                font-family: Oswald, sans-serif;
                font-size: 46px;
            }
        </style>
    </head>
    <h1>My Web Page</h1>
    <div id="piechart"></div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>

    <canvas id="myChart" style="width:100%;max-width:600px"></canvas>

    <script>
        var xValues = [50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150];
        var yValues = [7, 8, 8, 9, 9, 9, 10, 11, 14, 14, 15];

        new Chart("myChart", {
            type: "line",
            data: {
                labels: xValues,
                datasets: [{
                    fill: false,
                    lineTension: 0,
                    backgroundColor: "rgba(0,0,255,1.0)",
                    borderColor: "rgba(0,0,255,0.1)",
                    data: yValues
                }]
            },
            options: {
                legend: { display: false },
                scales: {
                    yAxes: [{ ticks: { min: 6, max: 16 } }],
                }
            }
        });
    </script>
 <script src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
       
        // Load google charts
        google.charts.load('current', { 'packages': ['corechart'] });
        google.charts.setOnLoadCallback(drawChart);
        // Draw the chart and set the chart values
        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                ['Task', 'Hours per Day'],
                ['Work', 8],
                ['Eat', 2],
                ['TV', 4],
                ['Gym', 2],
                ['Sleep', 8]
            ]);
            // Optional; add a title and set the width and height of the chart
            var options = { 'title': 'My Average Day', 'width': 550, 'height': 400 };
            // Display the chart inside the <div> element with id="piechart"
            var chart = new google.visualization.PieChart(document.getElementById('piechart'));
            chart.draw(data, options);
        }
    </script>
    <h1>Beautiful Norway</h1>
    <p>Norway has a total area of 385,252 square kilometres and a population of 5,438,657 (December 2020). Norway is bordered by Sweeden, Finland and Russia to the north-east, and the Skagerrak to the south, with Denmark on the other side.</p>
    <p>Norway has beautiful mountains, glaciers and stunning fjords. Oslo, the capital, is a city of green spaces and museums. Bergen, with colorful wooden houses, is the starting point for cruises to the dramatic Sognefjord. Norway is also known for fishing, hiking and skiing.</p>
</body>
</html>

```

**Comment by asadalikhan90** [comment]
@Khadar482

We were also able to observe the same issue in the output PDF document generated by both Aspose.HTML and Aspose.PDF. Hence, we have logged the following issues in our issue management for the sake of correction. We will further work on resolving them and let you know once they are resolved.

* HTMLNET-3139
* PDFNET-49821

> Our team wants to contact Aspose helpdesk team from their official account. please guide how to contact (they have aspose license)

If you have a subscription to the [helpdesk](http://helpdesk.aspose.com/), you can log in there using the same email address which is used for purchasing the subscription. You can create a ticket there with references to the above-shared issue IDs and they will be escalated accordingly. Furthermore, please also try to create a post in our [official free support forum](https://forum.aspose.com/c/pdf) where you can track the progress of issue resolution properly.

We apologize for the inconvenience.
