### ISSUE TITLE
last elements is not added to the drawing 

### ISSUE THREAD

**Issue by ilitoS** [aspose-free-consulting/projects#129]
Hello,

I am trying to draw a rectangle that consist of multiple rectangles, lines and text.  However, last <g> element does not have any elements(missing left side of the large rectangle). My code is repetitive, so all side have same code but different coordinates. If I swap SideY2 and SideY1 then SideY1 would be shown and SideY2 would not. Do you know what might be causing the problem?

I would appreciate if you could look into it. Let me know if you need full code.

[Code.txt](https://github.com/aspose-free-consulting/projects/files/6359498/Code.txt)
![HTML output](https://user-images.githubusercontent.com/79296030/115742666-e76f0c80-a35e-11eb-85cd-afb2c1d268b7.JPG)
![svg_Drawing](https://user-images.githubusercontent.com/79296030/115742668-e807a300-a35e-11eb-9d6b-98e3c4f5a5f5.JPG)

**Comment by shahzad-latif** [comment]
@ilitoS 

Can you please share which Aspose API are you using?

**Comment by ilitoS** [comment]
Hello @shahzad-latif ,

I am using 21.4.0 version. Should I switch to the earlier version? I also tried different scenarios and noticed that elements start missing only when I add  text elements or/and line elements. If those two are removed then all rectangles are drawn.

**Comment by shahzad-latif** [comment]
@ilitoS 

It's because you're using an evaluation version of the API. You need a license to use this API. For evaluation, you can [get a temporary license for 30 days](https://purchase.aspose.com/temporary-license).
