### ISSUE TITLE
I want to implement word to html and add an id to each html element.

### ISSUE THREAD

**Issue by lvguoqiang** [aspose-free-consulting/projects#13]
I want to implement word to html and add an id to each html element.eg: 

<table cellspacing="0" cellpadding="0" style="border:0.75pt solid #000000; border-collapse:collapse" id="Table 27.0.0">
    <tbody>
     <tr id="Row 0.27.0.0">
      <td style="width:196.6pt; border-right-style:solid; border-right-width:0.75pt; border-bottom-style:solid; border-bottom-width:0.75pt; padding-right:5.03pt; padding-left:5.03pt; vertical-align:top" id="Cell 0.0.27.0.0"><p style="margin-top:0pt; margin-bottom:0pt; font-size:10.5pt" id="Paragraph 0.0.0.27.0.0"><span style="font-family:宋体; color:#333333" id="Run 0.0.0.0.27.0.0">表格</span><span style="font-family:'&amp;quot'; color:#333333" id="Run 1.0.0.0.27.0.0">1</span></p></td>
      <td style="width:196.6pt; border-left-style:solid; border-left-width:0.75pt; border-bottom-style:solid; border-bottom-width:0.75pt; padding-right:5.03pt; padding-left:5.03pt; vertical-align:top" id="Cell 1.0.27.0.0"><p style="margin-top:0pt; margin-bottom:0pt; font-size:10.5pt" id="Paragraph 0.1.0.27.0.0"><span style="font-family:宋体; color:#333333" id="Run 0.0.1.0.27.0.0">表格</span><span style="font-family:'&amp;quot'; color:#333333" id="Run 1.0.1.0.27.0.0">2</span></p></td>
     </tr>
     <tr id="Row 1.27.0.0">
      <td style="width:196.6pt; border-top-style:solid; border-top-width:0.75pt; border-right-style:solid; border-right-width:0.75pt; padding-right:5.03pt; padding-left:5.03pt; vertical-align:top" id="Cell 0.1.27.0.0"><p style="margin-top:0pt; margin-bottom:0pt; font-size:10.5pt" id="Paragraph 0.0.1.27.0.0" tableeditcell="true"><span style="font-family:'&amp;quot'; color:#333333; -aw-import:ignore">&nbsp;</span></p></td>
      <td style="width:196.6pt; border-top-style:solid; border-top-width:0.75pt; border-left-style:solid; border-left-width:0.75pt; padding-right:5.03pt; padding-left:5.03pt; vertical-align:top" id="Cell 1.1.27.0.0"><p style="margin-top:0pt; margin-bottom:0pt; font-size:10.5pt" id="Paragraph 0.1.1.27.0.0" tableeditcell="true"><span style="font-family:'&amp;quot'; color:#333333; -aw-import:ignore">&nbsp;</span></p></td>
     </tr>
    </tbody>
   </table>

**Comment by shahzad-latif** [comment]
@lvguoqiang 

Thanks for your request. Can you please share your sample input Word document, so we can see what type of document you would like to convert? Also, if you can elaborate a bit like how you want to add IDs to the HTML elements, that will of great help. 

Looking forward to help you out with this.

**Comment by shahzad-latif** [comment]
@lvguoqiang 

Currently, you can convert Word to HTML using the code like this https://docs.aspose.com/display/wordsnet/Converting+a+Document#ConvertingaDocument-ConvertaDocumenttoHTMLwithRoundtripInformation

However, it's not feasible to attach IDs to the elements at the moment. We're investigating at our end to see if this is a feasible feature and if so, we'll log it. But it will still take quite some time even if we decide to support it. Anyway, we'll let you know about it's feasibility after detailed investigation.
