### ISSUE TITLE
I would like to reduce dimension of pdf file size.

### ISSUE THREAD

**Issue by DINESH-HEDAOO** [aspose-free-consulting/projects#130]
Hi ,

Our organization uses aspose licensed version. One issue we are facing right now related to pdf file dimension .we want to reduce dimension of pdf file in java code. I have tried with used code but not worked. I would like to reduce pdf file dimension to A4 size. Can you please help?  pdf attached.

	String pdfOut = pdfIn.substring(0, pdfIn.length() - 4) + "_resize.pdf";
	

		// load the source PDF document
		Document document = new Document(pdfIn);

		// get page to trim white space
		com.aspose.pdf.Page pdfPage = ((IDocument) document).getPages().get_Item(1);

		// get the content boundaries
		com.aspose.pdf.Rectangle contentBBox = pdfPage.calculateContentBBox();

		// set Page CropBox and MedioBos as per content boundries to tirm white space
		pdfPage.setCropBox(contentBBox);
		pdfPage.setMediaBox(contentBBox);

		// save the resultant PDF
		document.save(pdfOut); 
	    return pdfOut;

Pdf file :- 

[sample.pdf](https://github.com/aspose-free-consulting/projects/files/6405194/sample.pdf)

**Comment by shahzad-latif** [comment]
@DINESH-HEDAOO 

Kindly post this query in our [free support forums](forum.aspose.com/c/pdf/) so that our team can properly help you and track this issue. Thanks.

**Comment by DINESH-HEDAOO** [comment]
Yes. Thanks
