### ISSUE TITLE
I want to generate png file for large excel

### ISSUE THREAD

**Issue by vincenttsai** [aspose-free-consulting/projects#131]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

We have a large excel, and we want to transform each sheet of the excel into a image. However the sheet is too large, if we try to generate png or jpg directly, it will reproduce OutOfMemoryError. The only workable solution we found is to generate as svg file. However, the svg file is too large to deal with(200MB). Then we want to crop the image into a 2000x4000 pixels 's png for user to review. But the svg file is too large and unable to transform into small image, it will cause OutOfMemoryError as well when load into Java. Can you help us figure out how to use your products to deal with such kind of excel?  

Thanks

< which platform you're working on -- operating system, development environment etc.> 
Mac OS 12.2.1 and windows 10. IntellJ IDE with Java8.
<attach input documents>
[52MB_test.xls](https://github.com/aspose-free-consulting/projects/files/6413290/52MB_test.xls)

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by amjad-sahi** [comment]
@vincenttsai,

I checked your template Excel file and found it has more than 2k pages in the sheet. Please note, you cannot render single image for such a bigger sheet (having over 2200 pages in it). I tested using the following sample code and it works fine with latest version of the API (Aspose.Cells for Java v21.4.x, please try it). It does take some time (which is obvious as it has to generate over 2200 images for the pages) and the process would be completed in a few minutes time. I found each image (rendered) is just a 10-30K in size)
e.g.
**Sample code:**

```
Workbook wb = new Workbook("f:\\files\\generate png\\52MB_test.xls");
        Worksheet ws = wb.getWorksheets().get(0);

        ImageOrPrintOptions options = new ImageOrPrintOptions();
        options.setImageType(ImageType.PNG);

        SheetRender sr = new SheetRender(ws, options);
        for (int k = 0; k < sr.getPageCount(); k++)
        {
            //Output the worksheet into png image(s)
            sr.toImage(k, "f:\\files\\generate png\\outimg"+k+".png");

        }
```

> if we try to generate png or jpg directly, it will reproduce OutOfMemoryError
It looks like you might using ImageOrPrintOptions.setOnePagePerSheet(true) option, **which should not be used as you cannot render over 2200 paged sheet to single image**, this might produce OutOfMemoryError.

**Comment by vincenttsai** [comment]
Hello Sahi

          Thanks for replying the issue. If I can't print 2200 page in one
single image, can I print only like 2000x4000 pixels from the top left
corner of the original image?

Vincent

**Comment by amjad-sahi** [comment]
> can I print only like 2000x4000 pixels from the top left
corner of the original image

Which image you are talking about? There are more than 2200 PNG images that would be generated using the above code segment. If your requirement is to extract a single image out of so many images, that would not be possible. Other possible solutions you have also tried. For example, you may render to SVG or TIFF (multi-paged image) but again there would be size matter too.
