### ISSUE TITLE
Query regarding Aspose total license 

### ISSUE THREAD

**Issue by RishabhSharda** [aspose-free-consulting/projects#133]
Hi,
I have a potential customer and I am planning to use Aspose total, please help to clearify the license requirements:-

Do we need different licence for development, quality and production environment ?  
Please note that there will be no development activity in production environment , only the final exe will be moved.

**Comment by shahzad-latif** [comment]
@RishabhSharda 

Please post this query in our purchase forum: https://forum.aspose.com/c/purchase/6. Our team will guide you appropriately. Thanks.

**Comment by RishabhSharda** [comment]
Thank you for your help and sorry for the inconvenience.
