### ISSUE TITLE
We have PDF conversion requirement for TIf

### ISSUE THREAD

**Issue by AnkitSDesai** [aspose-free-consulting/projects#134]
Please check if it satisfies the following requirements: 

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

**Note: Above Site seems down since many days' so wanted to reach out via github route.**

We are seeing issue related to Older Tif conversion for an existing project and would like to connect for few minutes to go over to see if we have any work around or solution.

We do have licensed version of Aspose for C# in the current project..
<PackageReference Include="Aspose.Pdf" Version="21.1.0" /

Official Email :  I can share a quick meeting invite to go over this. let me know the right email address etc.

Thanks!

**Comment by shahzad-latif** [comment]
@AnkitSDesai 

Our forums are working fine and were never down for even a single hour. Kindly check if our site/ip is blocked at your end. Or you're behind a firewall blocking our site. Try using a different browser or internet connection. 

Moreover, please note that we can provide proper support and then track or follow up issues via our forums. So please try to access the forums and then post your issue along with input file and source code along with the issue details. We'll help resolve this issue ASAP. Thanks.

**Comment by AnkitSDesai** [comment]
@shahzad-latif  thanks for the update.
I have posted it in your forum.  appreciate an update at the earliest.
https://forum.aspose.com/t/some-of-the-tif-file-types-are-not-getting-converted-to-pdf/229950

Thank you.

**Comment by shahzad-latif** [comment]
@AnkitSDesai 

I can see my team mate is already engaged with you on the forums. I'll close this thread.
