### ISSUE TITLE
Issue with Converting a mhtml file to a jpg or png

### ISSUE THREAD

**Issue by TiniaL** [aspose-free-consulting/projects#135]
I am attempting to convert an mhtml file to a jpg or png.  It won't convert.  NICHOLAS 84 5 MID CEN MOD SILVER GREY2.mhtml

**Comment by shahzad-latif** [comment]
@TiniaL 

Please post this issue in our [free support forum](https://forum.aspose.com/). Select the appropriate product family forum to post the issue. Thanks.
