### ISSUE TITLE
Issue removing Section from PowerPoint file using Aspose.Slides

### ISSUE THREAD

**Issue by owgpurchases** [aspose-free-consulting/projects#136]
I have found an issue when deleting the first section and only section in a pptx file.  I attach a simple code example.  The pptx file was created using Office 365 Pro Plus, version 12527.21912 Click-to-Run).

[RemoveSectionExample.zip](https://github.com/aspose-free-consulting/projects/files/6620792/RemoveSectionExample.zip)

**Comment by aspose-com-kb** [comment]
@owgpurchases 

Please post this query in our [free support forums](suchen.jiang@aspose.com) as that is the place where we can properly help manage, track, and follow up such issues. Thanks.
