### ISSUE TITLE
Image conversion does not work when converting PDF in aspose cell.

### ISSUE THREAD

**Issue by younggyun** [aspose-free-consulting/projects#137]
I am testing to purchase an aspose cell.
I am testing with the trial version, but the images in the Excel document are not converted.
Is it a trial version limitation?

**Comment by shahzad-latif** [comment]
@younggyun 

The trial versions do have some limitations. You may try a [free 30 days temporary license](https://purchase.aspose.com/temporary-license) which can allow you to test all features without any limitations. If you still find any issues, or face problem in using the APIs properly, please feel free to post your questions in our [free support forums](https://purchase.aspose.com/temporary-license) so our team can properly help you.
