### ISSUE TITLE
Issue on opening pdf created with aspose.pdf Error (111)

### ISSUE THREAD

**Issue by westheman** [aspose-free-consulting/projects#138]
Hello all I'm using aspose.pdf .net version 17.4 in a .net core 3.0 application. 
I have a fillable pdf that i need to fill up through the code and generated a new pdf with the data. 
the pdf is generated as it should, but when trying to open the pdf in adobe, i'm getting an error (111) Image of error attached 

please advise.

[1609001955-CU-2021.pdf](https://github.com/aspose-free-consulting/projects/files/6710235/1609001955-CU-2021.pdf)

![AsposePdfOpenError](https://user-images.githubusercontent.com/6386808/123285597-2e9e8880-d4db-11eb-9eeb-65f6750ac4c2.PNG)
[CU_Digital 2021_fillable_PC.pdf](https://github.com/aspose-free-consulting/projects/files/6710210/CU_Digital.2021_fillable_PC.pdf)

**Comment by asadalikhan90** [comment]
@westheman 

The support for .NET Core 2.0/2.1/2.2 was introduced in the [17.12 version of the API.](https://docs.aspose.com/pdf/net/aspose-pdf-for-net-17-12-release-notes/) Furthermore, the .NET Core 3.0 support was added in the [19.10](https://docs.aspose.com/pdf/net/aspose-pdf-for-net-19-10-release-notes/) version of the API. However, we always recommend using the latest version of the API as it contains more fixes and enhancements. Please use the latest version i.e. [Aspose.PDF for .NET 21.6](https://downloads.aspose.com/pdf/net/new-releases/aspose.pdf-for-.net-21.6/) and let us know in case you still face any issue by sharing your sample code snippet that you are using to generate the PDF. 

Also, please note that the right place to post such issues is the [official Aspose.PDF Support forum](https://forum.aspose.com/c/pdf/10) where we address them and you can track their rectification progress appropriately.

**Comment by aspose-com-kb** [comment]
I'm going to close this thread. Please discuss further with our team in our free support forums. For more [file formats related how to articles, see our Knowledge Base](https://kb.aspose.com/).
