### ISSUE TITLE
I want to Convert word files to md and your tool not working

### ISSUE THREAD

**Issue by sbandir37** [aspose-free-consulting/projects#139]
I am trying to use your docx to md converter..I know it worked last time but now it always givng " Length cannot be less than zero. (Parameter 'length')" error...may I know why and what need to be done to resolve this?

**Comment by aspose-com-kb** [comment]
@sbandir37 ,

Please post your issue and questions in our [free support forums](https://forum.aspose.com/c/words/) so that our team can properly investigate, track and follow up the issue.

**Comment by aspose-com-kb** [comment]
To learn more about Aspose APIs please check our [Knowledge Base How To Topics](https://kb.aspose.com/).
