### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Habaroff** [aspose-free-consulting/projects#140]
Hello. I want to buy Aspose.HTML. I have k8s cluster which has 4 node. In each node works application using Aspose.HTML. I am the only developer on the project and have one physical server. What license do I need?

**Comment by aspose-com-kb** [comment]
@Habaroff ,

For licensing information, please post your query in our [purchase forum](https://forum.aspose.com/c/purchase/) so our sales team can guide you properly. For technical assistance, please post questions in our[ free support forum](https://forum.aspose.com)s. For how to topics check our [file formats APIs knowledge base](https://kb.aspose.com/).
