### ISSUE TITLE
I want to create a UPS label generator with Aspose.BarCode

### ISSUE THREAD

**Issue by mommasboy364** [aspose-free-consulting/projects#141]
Please check if it satisfies the following requirements: 

✅ It is a small project satisfying a particular scenario
✅ It is related to Aspose APIs
✅ It takes 8 or less hours for us to complete
✅ It is not a bug
✅ It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

The company I am working with would like to integrate the BarCode API into their UPS shipping data and generate shipping labels. According to your API, Maxicode data can be read and generated. However, when I upload testing data of real Maxicodes, your online generator fails to "re-encode" the UPS characters because it is out of range. 

Web/Cloud SDK for Node.js/Express/Ubuntu

For testing values, we used the following [generated Maxicode](https://i.stack.imgur.com/cpG4c.png) from Shippo, the decoded string using Aspose API is below:

`[)>01969174800008400031Z94369249UPSN39Y1F007A0OOI4C%"JD*R%Y:Y/FKQ/+:E6AF0+A(,"IG&:KZLP`

![image](https://user-images.githubusercontent.com/87051172/124692121-d7f95d00-de91-11eb-8c25-bd9080f24df9.png)

We request a deeper explanation for how we generate UPS data into the Maxicode output. Currently, the decoded string is 98 characters, while Maxicode character limit is 93.

**Comment by ahsaniqbalsidiqui** [comment]
@mommasboy364,
You may try the following sample code to generate this Maxicode:

```
String txt = "[)>01969174800008400031Z94369249UPSN39Y1F007A0OOI4C%\"JD*R%Y:Y/FKQ/+:E6AF0+A(,\"IG&:KZLP";
generator.Parameters.Barcode.MaxiCode.MaxiCodeEncodeMode = 6;//4 also works but value 5 shows error you shared
generator.CodeText = txt;
Bitmap barcode = generator.GenerateBarCodeImage();
barcode.Save("MaxiCode.png");
```

Note that if we set MaxiCodeEncodeMode value to 4 or 6, it works fine however if we use value 5, it raises the same exception as shared by you. Please give it a try and share your feedback.

![MaxiCodeEncodeMode_6](https://user-images.githubusercontent.com/40785196/124790806-10766500-df7e-11eb-9b02-0a036fe18051.png)
![MaxiCodeEncodeMode_4](https://user-images.githubusercontent.com/40785196/124790822-14a28280-df7e-11eb-948c-06d5c5a7f2b5.png)

**Comment by mommasboy364** [comment]
Thanks for the quick response, @ahsaniqbalsidiqui. The nonprintable ascii characters are important for UPS labels, so I can't remove them for the Maxicode. I still get the same error codes when I use encoding 4. Here's the decoded values with the proper escaped nonprinting characters. Tell me if this still works on your end. 

`[)>\x1e01\x1d96917480000\x1d840\x1d003\x1d1Z94369249\x1dUPSN\x1d39Y1F0\x1e07A0OOI4C%"JD*R%Y:Y/FKQ/+:E6AF0+A(\x1c,"I\x1cG&:KZLP\x1e\x04`

**Comment by ahsaniqbalsidiqui** [comment]
@mommasboy364,
We have observed this issue and logged a ticket BARCODENET-37844 in our issue tracking system for further investigation. We will write back here once any update is ready for sharing.

**Comment by AsposeAG** [comment]
1. Maxicode cannot encode other symbols different from 256(0..255) bytes in normal mode. All Unicode symbols can be encoded only in ECI mode; however, we don’t support ECI modes at this time. The task already was created, but we don’t have ETA for it. 

2. All symbols are encoded in 5(A..E) encoding submodes because Maxicode can encode only digits from 0..63 and bytes are sliced on submode switch value and byte value(s) in the submode. In this way the encoding capacity can be different from amount of encoding symbols.

3. Mode 4 and 6(6 is same as 4 but used only for barcode readers programming) are standard modes and can encode 93 Maxicode data symbols (as you see in topic 2 it is not the same as encoding symbols).
Mode 5 is mode with Extended Error Correction and can encode only 77 Maxicode data symbols.

4. 0, 1 modes is unsupported by standard, 2,3 too special.

**Comment by mommasboy364** [comment]
I guess I'm just confused with how the aspose decoder can handle the nonprintable characters, while its encoder can not. I guess we are going to have to do some digging to find out what ECI mode is too, based off the comment by @AsposeAG. There is no support for ASCII character encoding either?
> 2,3 too special
What are the use cases for modes 2 and 3? I thought that was what UPS used anyways.

**Comment by AsposeAG** [comment]
@mommasboy364,

1. At this time MaxiCode supports only ISO/IEC 8859 8-bit characters
https://en.wikipedia.org/wiki/ISO/IEC_8859

In this way characters like “\x1e01” cannot be encoded. Our Maxicode encoder can encode only “\x00XX” 8-bit characters, at this time.

2. ECI is Extended Channel Interpretation. At this, it is used mostly for codepage selection which is used for automagical message encoding and decoding.
https://en.wikipedia.org/wiki/Extended_Channel_Interpretation
