### ISSUE TITLE
Aspose.CAD - Hidden line removal

### ISSUE THREAD

**Issue by PranayPanchal** [aspose-free-consulting/projects#142]
Does Aspose.CAD handle hidden line removal when converting from DXF to PDF?
See attached a sample DXF and a PDF converted using Aspose.CAD.
If you open the DXF in a CAD viewer (e.g. AutoDesk Truview) and compare it with the PDF you can see that there are lot of extra lines seen in the drawing in PDF that should really be hidden.

If there is a way to remove hidden lines when converting please provide/point us to a sample.
[Q_00000007.zip](https://github.com/aspose-free-consulting/projects/files/6775932/Q_00000007.zip)

**Comment by mudassirfayyaz** [comment]
@PranayPanchal 

Attached please find the view of the file that is from AutoDesk. Can you please share a comparison snapshot that what hidden elements are being rendered by Aspose.CAD. Moreover, please also share that which API and version you are using on your end along with possible sample code that you have tried.

<img width="1396" alt="AutoDeskView" src="https://user-images.githubusercontent.com/3595481/124806883-29095f80-df2b-11eb-90ee-7c3ca288e099.png">

**Comment by aspose-com-kb** [comment]
@PranayPanchal 

Looks like you're already in touch with our support via our free support forums here: https://forum.aspose.com/t/re-aspose-free-consulting-projects-aspose-cad-hidden-line-removal-142/232041. That's the best place to get fastest support of our APIs. So please continue there. I'll close this thread. 

Also, feel free to browse through our [how to tutorials on various file format topics](kb.aspose.com/).
