### ISSUE TITLE
xlsx to html conversion issue.

### ISSUE THREAD

**Issue by hasithwijerathna** [aspose-free-consulting/projects#143]
I am using Aspose cell java API to convert XLSX file to HTML 

`<dependency>`
`    <groupId>com.aspose</groupId>`
`    <artifactId>aspose-cells</artifactId>`
`    <version>21.6</version>`
`</dependency>`

I tried this by two ways.

- First Method (Failing) 

`File file = new File("path/to/file/TestAspose.xlsx");`
`ByteArrayInputStream in = new ByteArrayInputStream(FileUtils.readFileToByteArray(file));`
`ByteArrayOutputStream out = new ByteArrayOutputStream();`

`Workbook workbook = new Workbook(in);`
`HtmlSaveOptions options = new HtmlSaveOptions();`
`options.setPresentationPreference(true);`
` workbook.save(out, options);`

`FileOutputStream fout = new FileOutputStream("TestAspose.html");`
`fout.write(out.toByteArray());`
`fout.flush();`

Original xlsx file :  [TestAspose.xlsx](https://github.com/aspose-free-consulting/projects/files/6788981/TestAspose.xlsx)
Converted HTML file : [TestAspose.txt](https://github.com/aspose-free-consulting/projects/files/6789003/TestAspose.txt)
(it should be .html file but I have changed the extention to .txt because here not support adding html file)

This is what I can see when I open the converted file(.html) open in the chrome browser.
![image](https://user-images.githubusercontent.com/6972901/125029941-03559500-e0a8-11eb-8e63-4cc47a69033b.png)

- Second Method (Succeeded)

`File file = new File("path/to/file/TestAspose.xlsx");`
`ByteArrayInputStream in = new ByteArrayInputStream(FileUtils.readFileToByteArray(file));`
`ByteArrayOutputStream out = new ByteArrayOutputStream();`

`Workbook workbook = new Workbook(in);`
`HtmlSaveOptions options = new HtmlSaveOptions();`
`options.setPresentationPreference(true);`
` workbook.save("TestAsposeWorking.html", options);`

Original xlsx file :  [TestAspose.xlsx](https://github.com/aspose-free-consulting/projects/files/6788981/TestAspose.xlsx)
Converted HTML file : [TestAsposeWorking.txt](https://github.com/aspose-free-consulting/projects/files/6789094/TestAsposeWorking.txt)
(it should be .html file but I have changed the extention to .txt because here not support adding html file)

Both cases can convert the file without any error but first way the converted file not loading properly and in second case can load the generated html in the browser without any issue. But I need to use first way save method to do the task. Here I have attached the different of these generated files as a screenshot.

![image](https://user-images.githubusercontent.com/6972901/125031461-529cc500-e0aa-11eb-8eb9-9639ff876400.png)
(Second Method Result Left & First Method Result Right)

Appreciate if you can explain what is the issue in my code in first way. 
`OS :  Ubuntu 20.4 `
`Java Version : openjdk version "1.8.0_282"`
`Maven Version : Apache Maven 3.6.3`

**Comment by aspose-com-kb** [comment]
@hasithwijerathna 

The best place to get help for such issues related to Aspose APIs is our [free support forum](forum.aspose.com/c/cells/). 

You can also check out [how to topics on related file formats in our knowledge base](https://kb.aspose.com/).

**Comment by hasithwijerathna** [comment]
@aspose-com-kb Thanks for the quick reply and seems like free support forum link you provided is not working.

**Comment by aspose-com-kb** [comment]
@hasithwijerathna 

Sorry about that. Try this: https://forum.aspose.com/c/cells/

**Comment by hasithwijerathna** [comment]
> @hasithwijerathna
> 
> Sorry about that. Try this: https://forum.aspose.com/c/cells/

Added the question there as well https://forum.aspose.com/t/xlsx-to-html-conversion-issue/232113/1
