### ISSUE TITLE
Build PDF, Word, Excel and Visio Viewer and Editor

### ISSUE THREAD

**Issue by cravionyx** [aspose-free-consulting/projects#144]
Hi, 
We are developing a feature for our CM system. This feature is based on java, jsp (html, javascript) and we are interested on your product to be able to display the document in the browser (pdf, word, excel, visio, …) and make annotations to the document (catch those annotations to save them in another db as well).

Is it possible to have a session with an expert and go over our needs and how to use your products to satisfy our requirements?

**Comment by aspose-com-kb** [comment]
@cravionyx

Thanks for your interest. 

First of all, please check our following apps sites:
https://www.groupdocs.app/
https://www.aspose.app/

These apps are built using our APIs at the backend from the following ventures:
https://www.aspose.com/
https://www.groupdocs.com/

Now these apps show case a lot of features and usage scenarios of the APIs and as I can see most of your requirements can be fulfilled. 

For example, see for viewers and editors:
https://products.groupdocs.app/editor/total
https://products.groupdocs.app/viewer
https://products.aspose.app/words/editor

Please have a look into all these apps to get a better idea. Also note that you can get the source of these apps for free as well from our github repos, so it will be easier and quicker for you to build similar features in your products. 

Regarding the support, please note that we offer [free support via our forums](https://forum.aspose.com/) and you can ask as many questions or get as much help as you want for free. However, I'm afraid, we do not provide support via live sessions or on the phone. 

Still, if you're interested to get help on the phone or live sessions, or want us to build a solution for you, [we offer paid consulting service for our customers](https://consulting.aspose.com/home/). You can also look into that if you like. 

Let me know if you have any questions. For technical queries, I would recommend our [free support forum](https://forum.aspose.com/). Feel free to checkout our [knowledge base](https://kb.aspose.com/) as well.

**Comment by cravionyx** [comment]
Hi,

Thank you for your reply. Could you please send me the url for the annotation web tool code. That is very similar to what we need to implement and I would like to try it before purchasing the conholdate total sdk.

Thank you!

Rgs,

M.Vargas

**Comment by aspose-com-kb** [comment]
@cravionyx

Sure, please check this out: https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET/tree/master/Demos/LiveDemos/src/GroupDocs.Annotation.Live.Demos.UI/AnnotationApp. Currently, we only have code of these demos in .NET. However, the process and features are same and can be easily converted to Java as well. 

If you will need any further help with these features, please do share in our [free support forums](https://forum.groupdocs.com/).

**Comment by cravionyx** [comment]
Thank you!

**Comment by aspose-com-kb** [comment]
@cravionyx 

I'm going to close this thread. Please post any further questions, in our free support forums. 

[Aspose File Formats API Free Support Forum](https://forum.aspose.com/).
[GroupDocs File Manipulation APIs Free Support Forum](https://forum.groupdocs.com/).

Feel free to check out our [file formats APIs knowledge base](https://kb.aspose.com/) as well.
