### ISSUE TITLE
I want to convert pdf into epub, this is a commic.

### ISSUE THREAD

**Issue by alejandroxfx** [aspose-free-consulting/projects#145]
I want to convert pdf file into epub. This is a commic and sample of it is attached.

I'm using .net c# through PdfApi passing the token correctly, uploading the pdf file into a folder then getting the stream file with GetPdfInStorageToEpub method and finally uploading that and saving as epub file.

I made the first test with text and it works well, but I'm trygin to convert a comic but I got a blank page.

[Pages from The-Grackle-1997-1.pdf](https://github.com/aspose-free-consulting/projects/files/6803413/Pages.from.The-Grackle-1997-1.pdf)

**Comment by aspose-com-kb** [comment]
@alejandroxfx ,

First, give it a try at our [online free PDF to EPUB converter](https://products.aspose.app/pdf/conversion/pdf-to-epub). If you feel satisfied then you can use our [Aspose.PDF for .NET API to convert PDF to EPUB in C#](https://products.aspose.com/pdf/net). Please post any further questions related to [PDF to EPUB conversion in our Forums](forum.aspose.com/c/pdf/).
