### ISSUE TITLE
How to get position of graphic object (CadObjects) and export higher version dxf file ?

### ISSUE THREAD

**Issue by honnt** [aspose-free-consulting/projects#146]
I tried but not sure!
1. get position of graphic object (CadObjects); change position  and Clone graphic object ?
Code: 
foreach (var entity in cadImage.Entities)
                {
                    if (entity.TypeName == CadEntityTypeName.TEXT)
                    {
                           ((CadText)entity).DefaultValue = "New text here!!! :)";
                          **double x = ((CadText)entity).PointLocation.X ???**
                          break;
                    }
                    if (entity.TypeName == CadEntityTypeName.POINT)
                    {
                        double x  = ((CadPoint)entity).PointLocation.X;
                        double y = ((CadPoint)entity).PointLocation.Y;
                        //Change position  
                        CadPoint ent = new CadPoint();
                        ent.PointLocation.X = x + 5000;
                         ent.PointLocation.Y = y + 2000;
                        //Clone objects to new dxf file
                        **cadImage.Entities.Add(ent) ???**
                        break;
                    }
                    if (entity.TypeName == CadEntityTypeName.LINE)
                    {
                        double x1 = ((CadLine)entity).FirstPoint.X;
                        double y1 = ((CadLine)entity).FirstPoint.Y;
                        double x2 = ((CadLine)entity).SecondPoint.X;
                        double y2 = ((CadLine)entity).SecondPoint.Y;
                        break;
                    }
                    if (entity.TypeName == CadEntityTypeName.DIMENSION)
                    {
                        double x = ((CadDimensionBaseR12)entity).DefinitionPoint.X;
                        double y = ((CadDimensionBaseR12)entity).DefinitionPoint.Y;
                        break;
                    }
                    if (entity.TypeName == CadEntityTypeName.ARC)
                    {
                        double x = ((CadArc)entity).CenterPoint.X;
                        double y = ((CadArc)entity).CenterPoint.Y;
                        break;
                    }
                  ....
                }
                cadImage.Save(outFile);

2. export higher version dxf file ?
Code:
               ...
              var options = new Aspose.CAD.ImageOptions.DxfOptions();
              **options.Version = DxfOutputVersion.R12;// ? Aspose.CAD.FileFormats.Cad.CadConsts.CadAcadVersion.AC1018;**
              //export DWG to DXF
              image.Save(inputFileDXF, options);

**Comment by mudassirfayyaz** [comment]
@honnt 

Can you please explain the requirements in detail that what you want to achieve. I would also request you to please provide the source file and snapshot describing what is intended on your end.

**Comment by honnt** [comment]
> @honnt
> 
> Can you please explain the requirements in detail that what you want to achieve. I would also request you to please provide the source file and snapshot describing what is intended on your end.
 Thanks mudassirfayyaz!
  I submit the source code, please support:

 1. Ex I have *.dwg file in WGS84 coordinate system ( AutoCAD R11->R14 version)
     and I want to save as *.dxf file in VN2000 coordinate system (AutoCAD 2004 version). How to do?

 2. How to convert all graphic objects (Line, Point, Arc, Circle, Text, Hatch, Dimension, Spilne ...) from WGS84 coordinate system
 to VN2000 coordinate system in *.dxf file?
[Dwg2Dxf.zip](https://github.com/aspose-free-consulting/projects/files/6835676/Dwg2Dxf.zip)

**Comment by mudassirfayyaz** [comment]
@honnt 

We have analyzed the requirements concerning to VN2000 Coordinate System and regret to share at present the API doesn't support this format. However, we would like to further investigate the possibility of implementing the support for VN2000 Coordinate System in API and request you to please share the requirements in [Aspose.CAD official support forum](https://forum.aspose.com/c/cad/19) where we will log the issue request and you will be able to receive the updates in more expedite manner.
