### ISSUE TITLE
Error converting docx to pdf (java.lang.IllegalArgumentException: Cannot insert a node of this type at this location.)

### ISSUE THREAD

**Issue by cravionyx** [aspose-free-consulting/projects#147]
Hi,

I am using a simple code to convert word (docx) to html or pdf and I am getting this error:

java.lang.IllegalArgumentException: Cannot insert a node of this type at this location.

Rgs,

M.Vargas

**Comment by aspose-com-kb** [comment]
@cravionyx

Please post this query in our [free support forums](forum.aspose.com/c/words/), so that we can properly investigate, track, and follow up this issue. Thanks.
