### ISSUE TITLE
I want to create/build 

### ISSUE THREAD

**Issue by Mr-gan** [aspose-free-consulting/projects#148]
Hi,
  I encountered a problem when using aspose.html for HTML2PDF conversion.The PDF document I got was not output in CSS style in HTML.I'll post my code below,Could you give me an answer?
       `PdfRenderingOptions pdfRenderingOptions = new PdfRenderingOptions();
        pdfRenderingOptions.getCss().setMediaType(MediaType.Screen);
        pdfRenderingOptions.setBackgroundColor(com.aspose.html.drawing.Color.getGreen());
        PdfDevice pdfDevice = new PdfDevice(pdfRenderingOptions,"C:\\Users\\Administrator\\Desktop\\output.pdf");
        htmlDocument.renderTo(pdfDevice);`
![11](https://user-images.githubusercontent.com/52766099/127468777-b052bcb3-fcb4-450a-8963-aa09b4d468ab.jpg)
[
![22](https://user-images.githubusercontent.com/52766099/127468843-d2c4e5e0-4454-4a24-8f6a-7bbc1d9afe7b.jpg)
](url)

**Comment by aspose-com-kb** [comment]
@Mr-gan ,

This seems like a bug which we'll have to investigate. So please post this issue in our [free support forums](https://forum.aspose.com/c/pdf/10) along with input files and your code sample, so we can test it at our end. Please always post such issues in our forums for quick and proper help.
