### ISSUE TITLE
file cannot be uploaded on https://products.aspose.app/email/conversion/mbox-to-pst 

### ISSUE THREAD

**Issue by uniquesalman786** [aspose-free-consulting/projects#149]
I am trying to conert a mbox file to pst, but the file is not uploading, the file is about 850 MB. Kindly Guide me to convert that.

Thank you

**Comment by atirtahirgroupdocs** [comment]
This query is assisted [here](https://forum.aspose.app/t/mbox-to-pst-conversion/21545) on the support forum.
