### ISSUE TITLE
I want to create a page splitter component without extra section breaks added

### ISSUE THREAD

**Issue by mrkozma** [aspose-free-consulting/projects#15]
Hi,

Our application should be able to use the PageSplitter class. We have built a working concept, please see attached. 

However, it adds extra section breaks to the new document. 

Are we missing something or this is a bug in Aspose.Word 19.10?

Your help would be highly appreciated.
Thank you!

PS: The test document is in the root folder. Please use that.
PPS: The license file was removed form this upload
[ASPOSE_Page_Splitter_Issue.zip](https://github.com/aspose-free-consulting/projects/files/3752594/ASPOSE_Page_Splitter_Issue.zip)

**Comment by shahzad-latif** [comment]
@mrkozma 

Thanks for getting in touch to avail our free consulting service for Aspose file format APIs. 

We're looking into this case and will get back to you with further information soon.

**Comment by mrkozma** [comment]
Thank you. Looking forward to it.

**Comment by mrkozma** [comment]
Shahzad, we are not familiar with this onsulting process: 
What is the average turn-around time? 
And is there a way to directly communicate with you guys?
You may have questions and we can quickly give you answers.
Best regards!

**Comment by shahzad-latif** [comment]
@mrkozma 

Sorry for the delay. Actually, we were investigating this scenario in detail; usually, the response time is quick, but we were also looking into other options as well even though this is the default behavior of the API.  Anyway, let me explain a bit first: 

Adding section breaks is not a bug. This is how page splitter utility works. When a document passes through this utility, it adds section breaks at the end of each document's page. And based on these section breaks, the pages are separated into new document. 

Can you please elaborate why you want to exclude these section breaks? How this will help in processing your document? If you can explain the requirement further it will help us understand and we can try to find out a workaround and implement if it would be feasible in this case.

**Comment by mrkozma** [comment]
@shahzad-latif 
Shashzad, our problem is that when we use the GetDocumentOfPageRange function of the DocumentPageSplitterClass extra blank pages are added to the document. Please, see attached image.
If you comment out line 22 in Program.cs and do not use the splitter.GetDocumentOfPageRange  you'll get a document without those added section breaks.
![pageSplitter_extra_pages](https://user-images.githubusercontent.com/4894232/67573026-63a27880-f705-11e9-9bba-b0ba82faa5e5.png)

**Comment by shahzad-latif** [comment]
@mrkozma 

Thanks for the clarification. Let's review it further and we'll get back.

**Comment by tahir-manzoor** [comment]
@mrkozma

Please use the following code snippet to remove empty/extra sections from document. We are working over your document and will share our findings with you regarding page utility limitations and workaround for your issues. 

```
var splitter = new DocumentPageSplitter(document);
document = splitter.GetDocumentOfPageRange(1, document.PageCount);

foreach (Section section in document.Sections)
{
    if (section.Body.Paragraphs.Count == 0)
        section.Remove();
}
```

**Comment by mrkozma** [comment]
Thank you Tahir,
Looking forward to your findings.

**Comment by gaurav-singhal** [comment]
Hi Tahir,

We also noticed that when we ask to pick lets say page #10 and 11 of the attached document, we want the actual page 10 and 11 of the document which is section 1 and 2 rather than the page number as per the header in the document which gives section 4. Any suggestions?
[64cac5ec-93c8-4157-8680-e1d7a7903755.docx](https://github.com/aspose-free-consulting/projects/files/3803021/64cac5ec-93c8-4157-8680-e1d7a7903755.docx)

**Comment by tahir-manzoor** [comment]
@gaurav-singhal 

The Section 2 is on page 10 and Section 3 is on page 11 in the input document. The following line of code generates the correct output. 
`document = splitter.GetDocumentOfPageRange(10, 11);`

Could you please attach the expected and problematic output documents here for further testing?

**Comment by mrkozma** [comment]
@tahir-manzoor 
RE: page number issue: 
We are looking through the our code, making sure we are not creating the problem. We will update you once we have more data.

**Comment by shahzad-latif** [comment]
@mrkozma 

Please see the following repo with the code and details in the readme file: https://github.com/aspose-free-consulting/create-page-splitter-component-without-extra-section-breaks-added

You can get detailed information from the ReadMe file of above repo. However, if you still find any questions, please feel free to ask here. 

I would like to add just two points:

We logged an issue related to Layout API as WORDSNET-19460. However, the fix we did in the utility works for this issue for DOCX document. No issue in output DOCX.

For this your particular document, there are some pages in output document where content splits on two pages. For example, content of page 11 splits on two pages. If you extract/copy the same content including header using MS Word and paste it into new document, you will get the same output. So, this is not a bug. 

Anyway, do let us know your further thoughts or concerns.

**Comment by mrkozma** [comment]
@shahzad-latif 
Thank you Shahzad, we will implement the changes and report back to you.

**Comment by mrkozma** [comment]
@shahzad-latif the recommended solution did remove the extra section breaks. Thank you very much!

**Comment by mrkozma** [comment]
@shahzad-latif the recommended solution did remove the extra section breaks. Thank you very much!
