### ISSUE TITLE
Use ExtractPages methord  Missing text page tail ！ Why Lose word each page

### ISSUE THREAD

**Issue by pickyboy** [aspose-free-consulting/projects#150]
####   Document pageDoc = doc.ExtractPages(page, 1);

Fill All the page,  will lose one word every page!     It's  Aspose.Words  bug ?

![image](https://user-images.githubusercontent.com/49912469/129336807-2a4914d2-f702-46d7-b2f6-2fdcc1e07aee.png)

**Comment by tahir-manzoor** [comment]
@pickyboy 

Please note that Aspose.Words requires TrueType fonts when building the layout of document pages. You need to install fonts that are used in your document on the machine where you are calling Document.ExtractPages method.

If you still face problem, please share your **input** and **problematic output** documents for testing. We will investigate the issue and provide you more information about your issue.

**Comment by pickyboy** [comment]
For Example this Document
each Page last char!    
[Document Test.docx](https://github.com/aspose-free-consulting/projects/files/6989477/Document.Test.docx)

Thank you！Thank you！

**Comment by pickyboy** [comment]
This is may be big bug for Aspose.Words! 
Thanks for your help！

**Comment by tahir-manzoor** [comment]
@pickyboy 

We have extracted the pages of your test document using the latest version of Aspose.Words for .NET 21.8 and have not found the shared issue. So, please use [Aspose.Words for .NET 21.8](https://www.nuget.org/packages/Aspose.Words/21.8.0). 

If you still face problem, please ZIP and attach your original document in [Aspose.Words forum](https://forum.aspose.com/c/words/8). We will then investigate this issue further and provide you more information on it.

**Comment by pickyboy** [comment]
![image](https://user-images.githubusercontent.com/49912469/129533310-7a746818-aaf4-45d9-8361-be4c4f32d75f.png)
![image](https://user-images.githubusercontent.com/49912469/129533694-29b98670-4224-458f-b642-464111056289.png)
[DocumentTest-Source.docx](https://github.com/aspose-free-consulting/projects/files/6990817/DocumentTest-Source.docx)
[DocumentTest-Destination.docx](https://github.com/aspose-free-consulting/projects/files/6990818/DocumentTest-Destination.docx)
![image](https://user-images.githubusercontent.com/49912469/129534255-50a5dca4-2186-48fd-a69f-34067fc0b6e8.png)

coed:
`   var doc = new Document("C://DocumentTest-Source.docx");
                    Document DocSetOut = null;

                    for (int page = 0; page < doc.PageCount; page++)
                    {
                        Document pageDoc = doc.ExtractPages(page, 1);
                        if (DocSetOut == null)
                        {
                            DocSetOut = pageDoc;
                        }
                        else
                        {
                            DocSetOut.AppendDocument(pageDoc, ImportFormatMode.UseDestinationStyles);
                        }
                    }

                    var pdfStream = new MemoryStream();
                    DocSetOut.Save("D://DocumentTest-Destination.docx", SaveFormat.Docx);`

**Comment by pickyboy** [comment]
[aspose.Words.LoseChar.Demo.zip](https://github.com/aspose-free-consulting/projects/files/6991158/aspose.Words.LoseChar.Demo.zip)

This is my Demo!

**Comment by tahir-manzoor** [comment]
@pickyboy 

We have managed to reproduce the same issue at our end using .NET 5.0. We have logged this problem in our issue tracking system as **WORDSNET-22622**. You will be informed once this issue is resolved. We apologize for your inconvenience.

Could you please post this issue in Aspose.Words forum? We will then link this issue to your forum thread.

**Comment by pickyboy** [comment]
@tahir-manzoor 
@awaishafeez 
@aspose-com-kb 

The version Aspose.Words for .NET 21.9  will include WORDSNET-22622 ？

**Comment by tahir-manzoor** [comment]
Your issue WORDSNET-22622 has been resolved and its fix will be available in the next version of Aspose.Words for .NET i.e. 21.9. We will inform you once new version of Aspose.Words is released.

**Comment by tahir-manzoor** [comment]
It is to inform you that your issue has been fixed in the latest version of Aspose.Words for .NET 21.9. So, please use [Aspose.Words for .NET 21.9](https://www.nuget.org/packages/Aspose.Words/21.9.0).
