### ISSUE TITLE
saving image with same metadata

### ISSUE THREAD

**Issue by komfiBrigada** [aspose-free-consulting/projects#151]
Hi, I am using your tool to compress jpg and png images and saving them to folder. But when the image is saved, all metadata is lost. For my project I need the data (specifically 36867, DateTimeOriginal) for later use. Right now my project code looks like this: `using (Aspose.Imaging.Image original = Aspose.Imaging.Image.Load(source))
                                    {
                                        
                                        var jpegOptions = new Aspose.Imaging.ImageOptions.JpegOptions()
                                        {
                                            
                                            CompressionType = Aspose.Imaging.FileFormats.Jpeg.JpegCompressionMode.Progressive,
                                            BitsPerChannel = 8,
                                            Quality = 40,
                                            ResolutionSettings = new Aspose.Imaging.ResolutionSetting(96.0, 96.0),
                                            ResolutionUnit = Aspose.Imaging.ResolutionUnit.Inch,
                                            ColorType = Aspose.Imaging.FileFormats.Jpeg.JpegCompressionColorMode.Rgb,
                                        };
                                        original.Save(target, jpegOptions);
                                        original.Dispose();}`

**Comment by mudassirfayyaz** [comment]
@komfiBrigada 

Can you please possibly share the source file and compressed file. I would appreciate, if you may please also share the comparison image showing the meta information missing. It will help us narrowing down the issue.
