### ISSUE TITLE
How to replace text fields in DWG file with new text

### ISSUE THREAD

**Issue by mattczajka** [aspose-free-consulting/projects#152]
I am trying to pull in a DWG file and from that file I want to pull out all the text fields, replace them with different text and then save the file as a PNG image. 

I have the current code but can't seem to figure out how the replacing of text should work.

[AsposeConvert.txt](https://github.com/aspose-free-consulting/projects/files/7041125/AsposeConvert.txt)

**Comment by mudassirfayyaz** [comment]
@mattczajka 

The sample code that you have shared is only workable with entity type TEXT. I suggest you to please consider using the documentation article, [Search Text in DWG](https://docs.aspose.com/cad/net/search-text-in-dwg-autocad-file/). If there is still an issue then please share the source file, used code and a snapshot that may tell what portion of text is not getting replaced in file and I may check on my end further to help you.

**Comment by mattczajka** [comment]
I'm only concerned about entity type TEXT so that's not the problem. I am not sure if the code I have is the correct syntax or not to replace the value within the text field as when I try to convert the DWG file to a PNG image, the image doesn't come out correct and I see no fields or anything.

I am not sure if I am converting to PNG correctly or what's getting mixed up, but I the output image from the method I attached is coming out blank.

**Comment by mattczajka** [comment]
It would appear that I was missing the rasterizationOptions sizing. I wasn't aware that I needed to identify a size, I was thinking that there may be a default setting.

Thank you for your incredible help.
