### ISSUE TITLE
Converting excel to pdf to word

### ISSUE THREAD

**Issue by Banu1602** [aspose-free-consulting/projects#153]
Please check if it satisfies the following requirements: 

Hi Team,

We need to dynamically generate a word document using aspose. But due to our dynamic requirement we were not able to directly create a word document using Aspose. So we went to write in excel using aspose..Then will convert it to pdf and then from there to word. It converted perfectly. But if we edit anything value in the table cell is going out of the table. We were not able to find out any solution for this.

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by awaishafeez** [comment]
@Banu1602, please follow your [other thread](https://forum.aspose.com/t/234826) that you posted in [Aspose.Total forum](https://forum.aspose.com/c/total/7) for further proceedings.
