### ISSUE TITLE
Word  convert  to Pdf Lose Space and Line 

### ISSUE THREAD

**Issue by pickyboy** [aspose-free-consulting/projects#155]
###   the docx file convert to Pdf file will  Lose Space and Line 
  the convert result is  too bad! unacceptable!

## For example
![image](https://user-images.githubusercontent.com/49912469/133385640-f872b3e6-ab48-46a6-8aff-dabf5cf126b4.png)

 ~~~ environment
 using "Aspose.Words 21.9.0"

 VS 2019   .NET 5 
 ~~~
### Attach files  include  Demo Code and Demo Files
[Word2PdfDemo.zip](https://github.com/aspose-free-consulting/projects/files/7167670/Word2PdfDemo.zip)
[Demo.docx](https://github.com/aspose-free-consulting/projects/files/7167674/Demo.docx)
[Demo-Destination.pdf](https://github.com/aspose-free-consulting/projects/files/7167676/Demo-Destination.pdf)

### finally ,I also use the convert tools:
https://products.aspose.app/words/conversion/doc-to-pdf

# Thank you for help!

**Comment by pickyboy** [comment]
This is may be big bug for Aspose.Words!
Thanks for your help！

**Comment by awaishafeez** [comment]
@pickyboy,
I managed to reproduce this problem and have logged it in our bug tracking system with ID WORDSNET-22723. We will let you know once this issues will get resolved in future.

**Comment by pickyboy** [comment]
@tahir-manzoor
@awaishafeez
@aspose-com-kb

The version Aspose.Words for .NET 21.10 will include WORDSNET-22723 ？

**Comment by pickyboy** [comment]
@tahir-manzoor
@awaishafeez
@aspose-com-kb

The version Aspose.Words for .NET 21.11 will include WORDSNET-22723 ？

**Comment by tahir-manzoor** [comment]
Unfortunately, this issue has not resolved yet. We will inform you once this issue is resolved. Thanks for your patience.
