### ISSUE TITLE
Compatibilidad de Aspose.Words en aplicaciones UWP y generación de release con cadena de herramientas de .Net

### ISSUE THREAD

**Issue by aguinav29** [aspose-free-consulting/projects#156]
Buenas tardes

![image](https://user-images.githubusercontent.com/92484492/137214257-9be48a76-7a47-4e61-a1c3-3610b5555c3d.png)

Tengo el siguiente error cuando trato de compilar en modo Release una aplicación realizada en Universal Windows Plataform (UWP). Esto tambien para cuando deseo generar el publicado de la aplicación en modo release y teniendo el .net Native activado. 
![image](https://user-images.githubusercontent.com/92484492/137214455-065ad3fc-9d46-4ccb-9e8f-e66b63b3a04c.png)

Pero si se gener en modo release quitando los dos check si se puede compilar y generar el release del aplicativo. La versión que estamos usando es 20.12 de Aspose.Words

Quisera saber si esta versión es compatible con aplicaciones hechas en UWP

Gracais

**Comment by tahir-manzoor** [comment]
@aguinav29 

Cree una aplicación de la Plataforma universal de Windows (UWP) (código fuente sin errores de compilación) que nos ayude a reproducir su problema y adjúntelo aquí para probarlo. Investigaremos el problema y le proporcionaremos más información al respecto.

**Comment by tahir-manzoor** [comment]
@aguinav29 

Gracias por compartir el proyecto. Estamos investigando este problema y nos comunicaremos contigo pronto.

**Comment by tahir-manzoor** [comment]
@aguinav29 

Hemos probado el escenario y no pudimos completar la aplicación en modo de lanzamiento. Sin embargo, enfrentamos problemas diferentes. El detalle de la excepción se muestra a continuación.

> Código de gravedad Descripción Estado de supresión de línea de archivo de proyecto
> Error ILT0005: 'C: \ Archivos de programa (x86) \ Microsoft SDKs \ UWPNuGetPackages \ runtime.win10-x64.microsoft.net.native.compiler \ 2.2.10-rel-29722-00 \ tools \ x64 \ ilc \ ilc. exe --gatekeeper @ "C: \ Users \ tahirmanzoor \ Downloads \ Compressed \ App2 \ App2 \ App2 \ obj \ x64 \ Release \ ilc \ interval \ gkargs.rsp" '

En aras de la corrección, hemos registrado este problema en nuestro sistema de seguimiento de problemas como <kbd> WORDSNET-22866 </kbd>. Se le notificará una vez que se resuelva este problema. Pedimos disculpas por las molestias.

¿Podría probar la última versión de [Aspose.Words para .NET 21.10](https://www.nuget.org/packages/Aspose.Words/21.10.0) y hacernos saber cómo le va?

**Comment by aguinav29** [comment]
Buenas tardes 

Se actualizó la referencia del Aspose a la recomendada que fue la 21.10. Y ahora obtenemos este único error 
![image](https://user-images.githubusercontent.com/92484492/138184338-c2d21358-98c4-4b40-bc58-c72bbc4f6c8c.png)

**Comment by tahir-manzoor** [comment]
@aguinav29

¿Podría copiar el texto del error y pegarlo aquí? Gracias por su cooperación.
