### ISSUE TITLE
I want to create/build 

### ISSUE THREAD

**Issue by KeithPoonNS** [aspose-free-consulting/projects#158]
Hi, i am a software developer, and finding a library to produce pdf

< describe your free consulting project requirements briefly>
the project going to generate pdf from html

the result is a report like format, some ingredients is necessary:
- allows to embed css, better to allows ui framework like bootstrap css
- allows to embed fonts to support multiple languages in pdf
- tables, images
- repeating header (logo, text), footer(page num) in every page

it is aspose pdf allows to do all above?

< which platform you're working on -- operating system, development environment etc.> 
windows
.Net Core (console)

< attach input documents>
please unzip and run the index.html

[reportReference1.zip](https://github.com/aspose-free-consulting/projects/files/7465304/reportReference1.zip)

< attach any sample required output documents if you have> 
attached the output sample

[report.reference1.pdf](https://github.com/aspose-free-consulting/projects/files/7465269/report.reference1.pdf)

<attach any additional supporting material to help us understand the requirement>

**Comment by asadalikhan90** [comment]
@KeithPoonNS 

Sure, you can achieve your requirements using Aspose.PDF for .NET. You can specify the base path in `HtmlLoadOptions `where all resources, i.e. fonts, css, images are present and API will use them to generate final PDF document:

```
string basePath = dataDir + "reportReference1\\ReportReference1\\";
Aspose.Pdf.HtmlLoadOptions objLoadOptions = new Aspose.Pdf.HtmlLoadOptions(basePath);
objLoadOptions.PageInfo.Margin = new MarginInfo(0, 0, 0, 0);
Aspose.Pdf.Document doc = new Aspose.Pdf.Document(dataDir + "reportReference1\\ReportReference1\\index.html", objLoadOptions);
doc.Save(dataDir + "test.pdf", SaveFormat.Pdf);
```

Can you please share if it is possible at your side to place all resources in single directory and change their reference path in the HTML file?
