### ISSUE TITLE
create a project that does Epub to PDF, Preview PDF converter

### ISSUE THREAD

**Issue by kkoka** [aspose-free-consulting/projects#16]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

I want to create a functionality where i can convert an entire EPUB file to a PDF and also an extract of the PDF. The extract needs to start from where Chapter 1 starts and not from page 1.
If the file is big then extract 10 pages, if the file is small then just a 10% of the file.

We are looking make this functionality work in Windows environment< which platform you're working on -- operating system, development environment etc.>

**Comment by shahzad-latif** [comment]
@kkoka 

Thanks for your interest in Aspose free consulting service. We have started investigating this requirement, however if you could be able to share a sample file that would be great; otherwise, we'll use a random file at our end to create a project for this scenario. Do let me know what you think. Thanks.

**Comment by kkoka** [comment]
sure please feel free to use a random epub file from your end.

**Comment by shahzad-latif** [comment]
@kkoka 

I just found that you already posted this in our [Aspose.PDF API forum](https://forum.aspose.com/c/pdf) as well. Please see this reply from our team member to help you [convert EPUB file to a PDF file format quickly using simple code](https://forum.aspose.com/t/epub-to-pdf-coversion-and-preview-pdf/204111/2?u=shahzadlatif).

**Comment by shahzad-latif** [comment]
@kkoka 

As far as previewing the PDF file is concerned, you can either use [GroupDocs.Viewer](https://products.groupdocs.com/viewer) or if you want to achieve that using Aspose.PDF API then this can be done by first converting each PDF page to an image and then showing those images in an image container on web or desktop or mobile. 

Please let me know if you want to go forward with the second option then we can create a sample for you and share here.

**Comment by kkoka** [comment]
Hello Latif,
I wanted to create a seperate physical preview pdf  file ( a small extract of the original file ). is that possible ?


Thanks,

Karthik.

**Comment by shahzad-latif** [comment]
@kkoka 

I got the idea. So it will be a few pages from a large set of pages and created a new PDF file from those pages. Yes, that is supported. However, we have to specify a range of pages or specific page numbers. This is currently supported. We still need to check if we can filter out pages based on their content as well or not. So please let us further check this. And if you want to share any other thoughts, please do jump in.

**Comment by shahzad-latif** [comment]
@kkoka 

Here is the project which can help you extract PDF pages in three different ways and save an output file with the extracted pages: https://github.com/aspose-free-consulting/Extract-PDF-Page-by-Page-Number-or-Range-or-Text

1. Extract PDF pages by specific page numbers
2. Extract PDF pages by a range of pages
3. Extract PDF pages by some search text

As far as converting an [EPUB to PDF is concerned, you can use this code for the same](https://docs.aspose.com/display/pdfnet/Convert+a+File+to+PDF+Format#ConvertaFiletoPDFFormat-ConvertEPUBFiletoPDFFormat).

**Comment by kkoka** [comment]
Hello Shahzad,

Sorry for not able to get back to you earlier.

Does aspose link the table of contents to the individual pages ( using hyperlinks ). Currently I see the pdf generated in its entirety but the hyperlinks to individual chapters isn’t working.

Also, is there a way find out how big is a chapter, so that if we need to extract a portion of a chapter or few lines.



Thanks,

Karthik.

**Comment by asadalikhan90** [comment]
@kkoka 

You can [create hyperlinks to pages within the same PDF document](https://docs.aspose.com/display/pdfnet/Add+and+Get+Hyperlink#AddandGetHyperlink-CreatehyperlinktopagesinsamePDF) using LocalHyperlink. However, for the requirement of retrieving chapter size - could you kindly share a sample PDF document with us. It would also be better if you can post your inquiry in our [support forum](https://forum.aspose.com/c/pdf) where you will surely be assisted accordingly.

**Comment by kkoka** [comment]
Hello Asad,

Attached is an epub that I am looking to have these has the table of contents and I am looking to have

1.       Hyperlinks in Table of Contents that need to be linked to the individual chapter pages

2.       If Chapter 1 is more than 1 page, then extract few pages of Chapter 1 as a separate PDF document

3.       If Chapter 1 is 1 page, then extract few lines of Chapter 1.

Please let me know if any/all of these are possible or not using Aspose.


Thanks,


Karthik.

**Comment by asadalikhan90** [comment]
@kkoka 

We are looking into your requirements and will try to implement them in a sample project. Please spare us little time.

**Comment by kkoka** [comment]
Hello,

Do you have any update on the sample project that you have been working on last month?

Thanks,

Karthik.



Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by asadalikhan90** [comment]
@kkoka 

We are sorry for the delay. 

We have been working over other scenarios from other customers as well which caused this delay. However, we will surely share updates with you in the coming week. We really appreciate your patience.

**Comment by kkoka** [comment]
Hello,

Can you please let me know if you have any updates . We are waiting for your product demo to see if we can proceed with your product in our company and are running on a tight timeline.


So please let us know when can we get the product to test out.


Thanks,

Karthik.

**Comment by shahzad-latif** [comment]
@kkoka 

You'll receive the sample project today from our team. Thanks for your patience.

**Comment by asadalikhan90** [comment]
@kkoka 

Thanks for your patience.

Please find attached ZIP of sample project along with screenshots about its usage: 
[CreateTOCinExisitngPDF.zip](https://github.com/aspose-free-consulting/projects/files/4077237/CreateTOCinExisitngPDF.zip)
![Output1](https://user-images.githubusercontent.com/22503496/72619934-2c3c1480-3960-11ea-9485-a6d689a7e5bb.png)
![Screen2](https://user-images.githubusercontent.com/22503496/72619935-2c3c1480-3960-11ea-968d-e491f2c9e73e.png)
![Screen1](https://user-images.githubusercontent.com/22503496/72619937-2c3c1480-3960-11ea-8c8b-e48e33120ba7.png)

>  1. Hyperlinks in Table of Contents that need to be linked to the individual chapter pages
>  2. If Chapter 1 is more than 1 page, then extract few pages of Chapter 1 as a separate PDF document

The attached archive also contains a sample PDF document that was used in the sample project. The project covers the requirements of adding TOC with hyperlinks to different chapters in PDF document as well as create a separate PDF document where the chapter exceeds the length of one page. 

>  3. If Chapter 1 is 1 page, then extract few lines of Chapter 1.

Similar functionality has been added to the sample project where it extracts first line/phrase/word/heading from every page of the PDF document and use it for TOC titles. Please note that in the sample PDF document, every chapter starts with its name which has been used as markup to determine the length of chapters (on how many pages it spans).

Furthermore, the project also showcases different functionalities of extracting text and manipulating PDF documents on the basis of text extraction which you can further modify as per your needs and specifications. In case we have missed any of your requirements, please feel free to let us know by sharing some more details or an expected PDF output file. Your response is awaited.

**Comment by kkoka** [comment]
Hello Asad,

Thanks for the demo project, but inorder to test it out, the program is asking for a License File , can you please send me one so that I can test out the functionality and come back with our feedback.

Thanks,

Karthik.

**Comment by shahzad-latif** [comment]
@kkoka 

You can get a temporary license which will work fine for 30 days to completely test the APIs without any limitations: https://purchase.aspose.com/temporary-license. Thanks.

**Comment by shahzad-latif** [comment]
@kkoka 

The project and related details can also be found here https://github.com/aspose-free-consulting/Create-TOC-in-Existing-PDF-by-Extracting-Page-Titles
