### ISSUE TITLE
I want to create/build Pivot Table with Pivot Filters

### ISSUE THREAD

**Issue by dineshcdev** [aspose-free-consulting/projects#160]
We are working Aspose.Cells Java. We are already using aspose to create excel sheets with Pivot tables.
Now we want to create Pivot Filters on pivot fields. Please find the attachement for output sample.

Currently we are generating excel sheets with pivot tables, after the excel is generated we are manually dragging the Pivot fileds to Filter Section. We want to do this while excel is generated throw code.

[samplePivotTable.xlsx](https://github.com/aspose-free-consulting/projects/files/7630024/samplePivotTable.xlsx)

![image](https://user-images.githubusercontent.com/47395336/144157529-4c33a22e-8a2b-4b5d-9fb8-05c8bd43f155.png)

Thanks.

**Comment by amjad-sahi** [comment]
See the following sample code for your reference.
e.g.
**Sample code:**
```
........
PivotTable pivotTable = workbook.getWorksheets().get(1).getPivotTables().get(0);
   
pivotTable.addFieldToArea(PivotFieldType.PAGE, 0);
pivotTable.addFieldToArea(PivotFieldType.PAGE, 1);

int filterindex = pivotTable.getPivotFilters().add(1, PivotFilterType.CAPTION_EQUAL);
PivotFilter filter = pivotTable.getPivotFilters().get(filterindex);
filter.getAutoFilter().custom(0, FilterOperatorType.EQUAL, "18");

pivotTable.refreshData();
pivotTable.calculateData();

workbook.save("f:\\files\\out1.xlsx");
```

Should you have further queries  or issue, please post your queries or issue in Aspose.Cells [forum](https://forum.aspose.com/c/cells/9). We will check and help you there.

**Comment by dineshcdev** [comment]
Hi Amjad,

Thanks for quick reply. With the sample code it is auto filtering the Pivot Table but we cant see the filters in Filters sections and on top of Pivot table like shown in the image, We want code sample which generates exactly the same report with filters shown in the attached image. We should be able to change the values in filters once the excel is downloaded.

Thanks.
![SampleOutput](https://user-images.githubusercontent.com/47395336/144265898-7fa8ecf0-ad50-4fc9-9c7d-6738633a911c.png)

**Comment by amjad-sahi** [comment]
Please provide the following:
1) Your current output Excel file by your sample code after including the suggested lines of code (using Aspose.Cells (latest version)).
2) Your expected Excel file containing your desired pivot table.
3) Screenshot taken in MS Excel regarding filters when viewing your expected file into it. 

We will check and help you soon.

**Comment by dineshcdev** [comment]
Hi Amjad,

This is the code that generating the PivotTable
-----
Workbook wb = new Workbook(dataDir + "source.xlsx");
        Worksheet sheet = wb.getWorksheets().get(0);
        PivotTableCollection pivotTables = sheet.getPivotTables();

        int index = pivotTables.add("=A1:C8", "E1", "PivotTable2");
        PivotTable pivotTable1 = pivotTables.get(index);

        pivotTable1.setRowGrand(false);
        pivotTable1.addFieldToArea(PivotFieldType.ROW, 0);
        pivotTable1.addFieldToArea(PivotFieldType.COLUMN, 1);
        pivotTable1.addFieldToArea(PivotFieldType.DATA, 2);

        wb.save(dataDir + "output.xlsx");
        System.out.println("Workbook saved to disk");
------

Also here i am attaching source.xlsx file, present_output.xlsx file which is generated by the above code and the expected_output.xlsx file.

I am expecting the PageFields as in the screen shot and expecting_out.xlsx file
![image](https://user-images.githubusercontent.com/47395336/144352246-9128b71f-456c-443f-b87d-a2e51e150c44.png)
[expected_output.xlsx](https://github.com/aspose-free-consulting/projects/files/7638693/expected_output.xlsx)
[present_output.xlsx](https://github.com/aspose-free-consulting/projects/files/7638694/present_output.xlsx)
[source.xlsx](https://github.com/aspose-free-consulting/projects/files/7638695/source.xlsx)

Thank you

**Comment by amjad-sahi** [comment]
Please try the following sample code with your template file for your needs:
e.g.
**Sample code:**
```java
Workbook wb = new Workbook(dataDir + "source.xlsx");
Worksheet sheet = wb.getWorksheets().get(0);
PivotTableCollection pivotTables = sheet.getPivotTables();

int index = pivotTables.add("=A1:C8", "E1", "PivotTable2");
PivotTable pivotTable1 = pivotTables.get(index);

pivotTable1.setRowGrand(false);
pivotTable1.addFieldToArea(PivotFieldType.DATA, 2);
pivotTable1.addFieldToArea(PivotFieldType.PAGE, 0);
pivotTable1.addFieldToArea(PivotFieldType.PAGE, 1);

wb.save(dataDir + "output.xlsx");
System.out.println("Workbook saved to disk");
```
Hope, this helps a bit.

**Comment by dineshcdev** [comment]
Thanks a lot Amjad, I got the expected output from your sample code.

**Comment by amjad-sahi** [comment]
You are welcome and good to know that the suggested code segment works for your needs.
