### ISSUE TITLE
I need to create an app to read datamatrix qr code, I've tested your online tool but doesn't recognize my datamatrix.

### ISSUE THREAD

**Issue by martiniluca81** [aspose-free-consulting/projects#162]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by martiniluca81** [comment]
![Untitled](https://user-images.githubusercontent.com/36545248/145829207-e3a9baf6-d04a-411b-87f7-628297243a02.png)

**Comment by amjad-sahi** [comment]
Could you please share your sample code that you are using? Or you are using [free app](https://products.aspose.app/barcode/recognize) to read the barcode? I also found the barcode quality is low in the picture, so it would be hard to recognize the barcode in your attached picture.

**Comment by martiniluca81** [comment]
Yes I tested the free app, 
I tested the same picture on a competitor and worked but I wanted to use your component as is free of charge on deployments.
Here the screenshot on another websites with beside the code from the datamatrix.
![image](https://user-images.githubusercontent.com/36545248/146020777-f5b5a967-57c4-458b-9acb-4ab27610ec74.png)

**Comment by martiniluca81** [comment]
Thanks , I will be extremaly happy if your component can read my barcodes

**Comment by amjad-sahi** [comment]
I checked and found our free app cannot detect barcode in your attached picture. This is purely due to low or poor barcode quality in the picture. You talked about some competitor who can detect your barcode from the picture fine. Could you please give us online url (for the competitor), so we could test it?

Moreover, Barcode Reader Online (free app) is a free online application to read barcodes from image. This free app is provided by [Aspose.BarCode](https://products.aspose.com/barcode) API which is not free.

**Comment by martiniluca81** [comment]
but also this works, with the same picture I gave you
https://demo.dynamsoft.com/barcode-reader/

![image](https://user-images.githubusercontent.com/36545248/146076317-b2e3a3ca-6ed3-4692-9bbb-4b3730fb7091.png)

**Comment by amjad-sahi** [comment]
@martiniluca81,

Thanks for sharing further details.

Please notice, I am able to reproduce the issue as you mentioned. Aspose.BarCode for .NET API does not recognize the datamatrix barcode. Although the barcode quality in the picture is low but using some online tools (other vendors) you as suggested can detect the barcode from the picture. I have logged a ticket with an id "BARCODENET-38031" for your issue. We will look into it soon.

Once we have an update on it, we will let you know.

PS. as mentioned earlier, you may post your general issues or queries in dedicated [forum](https://forum.aspose.com/c/barcode/13).
