### ISSUE TITLE
I want to create/build PPTX manipulation tool

### ISSUE THREAD

**Issue by sravan-naikini** [aspose-free-consulting/projects#163]
Hi,
We are looking to make an pptx manipulation tool where user can select multiple slides from different ppts and generate custom ppt with selected slides. By using aspose slides cloud. we are able to split slides from ppt and get urls of images which are being stored in internal storage of aspose. But we are unable to view those images when we copy paste images in brower throwing an error message that "ClientId is undefined. Please check authorization." we are stuck at this. It will be glad if u guys respond back.

below are the project details:
Middleware framework:  NodeJS
Storage used: DropBox
Frontend: Angular(HTML & CSS) ->where we need to display those images.
![Screenshot (27)](https://user-images.githubusercontent.com/90748770/146532592-8ad7b034-8f61-465d-be9b-9d38a568d78c.png)

**Comment by andreypotapovaspose** [comment]
@sravan-naikini,
Thank you for the issue description.

To investigate the issue on our side, please share the following:

- code example that reproduces the error
- input presentation files

It would be great if you could describe the issue with the additional data on [Aspose.Slides Cloud forum](https://forum.aspose.cloud/c/slides/).
