### ISSUE TITLE
How to read append supplier name dynamically in a pdf?

### ISSUE THREAD

**Issue by ThotaAshok** [aspose-free-consulting/projects#164]
I have to append supplier name, address etc to a .pdf document in table cells and the above and below are signed content to be prepended and appended to this table. How i do it? I am using Document object to create a .pdf. See below sample code which i am trying to use. I don't know how to position these matrix stuff and the content.  Totally lost. Reading through he documentation for help, but no luck so far. Any help is much appreciated.

Example pdf: ==> https://www.tax.ny.gov/pdf/current_forms/st/st123_fill_in.pdf

I want to fill in "Name of seller"  and so on

(I) FIRST CODE ALTERNATE I TRIED

`		// Initialize document object
        Document document = new Document();
        // Add page
        Page page = document.getPages().add();

        

//             FormEditor editor = new FormEditor();

            // Load source PDF document
            String filePath = "C:/src/main/resources/assets/tax/exempt/Form 4 NY IDA ST-123.pdf";

            // Open document
            Document pdfDocument = new Document(filePath);

            // Create TextAbsorber object to find all instances of the input search phrase
            TextFragmentAbsorber textFragmentAbsorber = new TextFragmentAbsorber("Name of seller");

            // Accept the absorber for all the pages
            pdfDocument.getPages().accept(textFragmentAbsorber);

            // Get the extracted text fragments
            TextFragmentCollection textFragmentCollection = textFragmentAbsorber.getTextFragments();

            // Loop through the fragments
            for (TextFragment textFragment : (Iterable<TextFragment>) textFragmentCollection) {
                // Update text and other properties
                textFragment.setText(textFragment.getText() + "\n" + "Wallmart");
//                textFragment.getTextState().setFont(FontRepository.findFont("Verdana"));
//                textFragment.getTextState().setFontSize(12);
//                textFragment.getTextState().setForegroundColor(Color.getBlue());
//                textFragment.getTextState().setBackgroundColor(Color.getGray());
            }

            // Save the updated PDF file
            pdfDocument.save(_dataDir+"Updated_Text.pdf");`

(II)  SECOND CODE ALTERNATE I TRIED
`// Initialize document object
        Document document = new Document();
        // Add page
        Page page = document.getPages().add();// PART - 1
            // Add image
            Path imageFileName = Paths.get(_dataDir, "form4Part1.png");
            // Path imageFileName = Paths.get(filePartsPath, "form4Part1.png");
            java.io.FileInputStream imageStream = new java.io.FileInputStream(imageFileName.toString());

            // 1. Add image to Images collection of Page Resources
            page.getResources().getImages().add(imageStream);

            // Using GSave operator: this operator saves current graphics state
            page.getContents().add(new GSave());
            // Rectangle _logoPlaceHolder = new Rectangle(20, 730, 120, 830);
            Rectangle _logoPlaceHolder = new Rectangle(10, 180, 560, 350);
            // Rectangle _logoPlaceHolder = new Rectangle(200, 1730, 1200, 1830);

            // Create Matrix object
            Matrix matrix = new Matrix(new double[] {
            _logoPlaceHolder.getURX() - _logoPlaceHolder.getLLX(), 0, 0,
            _logoPlaceHolder.getURY() - _logoPlaceHolder.getLLY(),
            _logoPlaceHolder.getLLX(), _logoPlaceHolder.getLLY() });

            ConcatenateMatrix conMatrix = new ConcatenateMatrix(matrix);
            page.getContents().add(conMatrix);

            // page.getContents().add(new ConcatenateMatrix(matrix));
            XImage ximage = page.getResources().getImages().get_Item(page.getResources().getImages().size());
            // Using Do operator: this operator draws image
            page.getContents().add(new Do(ximage.getName()));

            // ??????????????????????????????
            // PART - 2
            // TODO_TAK_12212021_2_PM

            // PART - 3
            // Add image
            Path imageFileName3 = Paths.get(_dataDir, "form4Part3.png");
            // Path imageFileName = Paths.get(filePartsPath, "form4Part3.png");
            java.io.FileInputStream imageStream3 = new java.io.FileInputStream(imageFileName3.toString());

            // 1. Add image to Images collection of Page Resources
            page.getResources().getImages().add(imageStream3);

            // Using GSave operator: this operator saves current graphics state
            page.getContents().add(new GSave());

            // Rectangle _logoPlaceHolder = new Rectangle(20, 730, 120, 830);
            Rectangle _logoPlaceHolder3 = new Rectangle(10, 180, 560, 350);
            // Rectangle _logoPlaceHolder = new Rectangle(200, 1730, 1200, 1830
            // Create Matrix object
            Matrix matrix3 = new Matrix(new double[] {
                    _logoPlaceHolder3.getURX() - _logoPlaceHolder3.getLLX(), 0, 0,
                    _logoPlaceHolder3.getURY() - _logoPlaceHolder3.getLLY(),
                    _logoPlaceHolder3.getLLX(), _logoPlaceHolder3.getLLY() });

            ConcatenateMatrix conMatrix3= new ConcatenateMatrix(matrix3);
            page.getContents().add(conMatrix3);

            // Using GRestore operator: this operator restores graphics state
            page.getContents().add(new GRestore());`

**Comment by asadalikhan90** [comment]
@ThotaAshok 

We are testing this case in our environment and will get back to you soon.

**Comment by asadalikhan90** [comment]
@ThotaAshok 

We have used below code snippet in order to fill form fields and add an image as signature in your PDF. We filled a text box and checked a check box for your reference as well as added an image stamp at the position of signatures. For your kind reference, generated PDF is also attached:

```
Document doc = new Document(dataDir + "st123_fill_in.pdf");

for(Field field : doc.getForm().getFields()) {

 //System.out.println(field.getPartialName());
 if(field.getPartialName().equalsIgnoreCase( "Seller_name"))
 {
  field.setValue("Seller Name");
 }
 if(field instanceof CheckboxField && field.getPartialName().equalsIgnoreCase( "Utility"))
 {
  ((CheckboxField) field).setChecked(true);
 }
}

TextFragmentAbsorber absorber = new TextFragmentAbsorber("Signature of purchaser or purchaser’s representative (include title and relationship)");
doc.getPages().accept(absorber);

for(TextFragment tf : absorber.getTextFragments())
{
 System.out.println(tf.getText());
 Rectangle rectangle = tf.getRectangle();
 ImageStamp signImage = new ImageStamp(dataDir + "aspose.png");
 signImage.setXIndent(rectangle.getLLX());
 signImage.setYIndent(rectangle.getLLX() + 15); // Shift Y-Position to get image below the found text
 signImage.setHeight(25);
 signImage.setWidth(50);
 tf.getPage().addStamp(signImage);
}

doc.save(dataDir + "output.pdf");
```
[output.pdf](https://github.com/aspose-free-consulting/projects/files/7775112/output.pdf)

In case you face any issues, please feel free to create a post in official support forum of [Aspose.PDF](https://forum.aspose.com/c/pdf). We will assist you accordingly.
