### ISSUE TITLE
convert obj and mtl file to 3d_pdf

### ISSUE THREAD

**Issue by lawrenceglewis** [aspose-free-consulting/projects#167]
I want to create/build a program that converts an .obj file and its .mtl textures into a 3dpdf. I would also like to load a config file that is a simple ascii file like xml and displays a table with the information from the xml above the 3d model inside the 3df. We use windows and most commonly use .net applications but c++ would work too. As long as we can get the executable from it. I've been trying to do this with your free library but maybe that is why it doesn't work. I can convert the obj to a 3d pdf but not add a table and the textures get lost.
My email is lawrence.lewis@aerobotix.net
Thank you

**Comment by asadalikhan90** [comment]
@lawrenceglewis 

We are looking into your requirements and will get back to you shortly.

**Comment by asadalikhan90** [comment]
@lawrenceglewis 

Could you please share your sample source .obj file along with the sample code snippet that you have tried at your end and faced the issue? We will test the scenario in our environment from the perspective of your requirements and will get back to you with feedback. Also, please note that you can post such issues in the [official Aspose.3D forum](https://forum.aspose.com/c/3d) which is the right place to discuss such things and you can track the progress of issue resolution there conveniently.

**Comment by lawrenceglewis** [comment]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Aspose.ThreeD;
using Aspose.ThreeD.Formats;
using Aspose_obj_txt_to_3dpdf;
using Aspose.ThreeD.Entities;
using Aspose.ThreeD.Utilities;
using Aspose.ThreeD.Shading;
using PdfSharp;
using PdfSharp.Drawing;
using PdfSharp.Pdf;
using PdfSharp.Pdf.IO;



namespace Aspose_obj_txt_to_3dpdf
{
    class AsposeObjTxtTo3dpdf
    {
        public static string[] Load_Txt(string file_name)
        {
            string[] lines = System.IO.File.ReadAllLines(file_name);
            return lines;
        }
        public static void ObjSaveOption(string save_dir)
        {
            // ExStart:ObjSaveOption
            // The path to the documents directory.
            //string dataDir = RunExamples.GetDataDir();
            // Initialize an object
            ObjSaveOptions saveObjOpts = new ObjSaveOptions();
            // Import materials from external material library file
            saveObjOpts.EnableMaterials = true;
            // Flip the coordinate system.
            saveObjOpts.FlipCoordinateSystem = true;
            // Configure the look up paths to allow importer to find external dependencies.
            saveObjOpts.LookupPaths = new List<string>(new string[] { save_dir });
            // Serialize W component in model's vertex position
            saveObjOpts.SerializeW = true;
            // Generate comments for each section
            saveObjOpts.Verbose = true;
            // ExEnd:ObjSaveOption
        }
        public static ObjLoadOptions ObjLoadOption(string load_dir)
        {
            // Initialize an object
            ObjLoadOptions loadObjOpts = new ObjLoadOptions();
            // Import materials from external material library file
            loadObjOpts.EnableMaterials = true;
            // Flip the coordinate system.
            loadObjOpts.FlipCoordinateSystem = true;
            // Configure the look up paths to allow importer to find external dependencies.
            loadObjOpts.LookupPaths = new List<string>(new string[] { load_dir });
            // ExEnd:ObjLoadOption
            return loadObjOpts;
        }
        public static Scene ReadExistingSceneFromDisc(string read_file, ObjLoadOptions opt )
        {
            // ExStart:ReadExistingScene
            // The path to the documents directory.

            // Initialize a Scene class object
            Scene scene = new Scene();
            // Load an existing 3D document
            scene.Open(read_file, opt);

            // ExEnd:ReadExistingScene
            Console.WriteLine("\n3D Scene is ready for the modification, addition or processing purposes.");
            return scene;
        }
        public static void Save3dInPdf(Scene Object, string outfile, string matPath, string objPath)
        {
            PdfSaveOptions opt = new PdfSaveOptions();
            opt.LightingScheme = PdfLightingScheme.CAD;
            opt.RenderMode = PdfRenderMode.Solid;
            List<string> listOftextures = new List<string>();
            listOftextures.Add(matPath);
            listOftextures.Add(objPath);

            opt.LookupPaths = listOftextures;
            opt.FileName = matPath;
            // Save in the PDF format
            try
            {
                Object.Save(outfile, opt);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                Console.WriteLine("\n Try closing the pdf that is curently open.");
                return;
            }
        }
        public static void MakePdfTable(string[] objPath)
        {
        }
        static void Main()
        {
            string inputFile  = @"C:\dev\obj_files\giraffe_ball.obj";
            string matFile    = @"C:\dev\obj_files\giraffe_ball.mtl";
            string inputDir   = @"C:\dev\obj_files\obj_giraffe_ball";
            string outputFile = @"giraffe_ball.pdf";
            string outputDir  = @"";
            string txtFile    = @"C:\dev\xml_config\PartNumber_SerialNumber.xml";


            ObjLoadOptions loadObjOpts = ObjLoadOption(inputDir);

            string[] config_file = Load_Txt(txtFile);



            Scene model = ReadExistingSceneFromDisc(inputFile, loadObjOpts);
            model.AssetInfo.Comment = config_file[1];
            foreach (string line in config_file)
            {
                Console.WriteLine(line);
            }
            

            //display loaded model
            Camera cam = new Camera(ProjectionType.Perspective)
            {
                NearPlane = 0.1,
                FarPlane = 200,
                RotationMode = RotationMode.FixedDirection
            };

            //
            ObjSaveOption(outputDir);
            

            Save3dInPdf(model, outputFile, matFile, inputDir);
            Console.WriteLine("\nSaved file successfully");

            // from here on out add the config file to a new page (working)
            PdfDocument pdfDocument = PdfReader.Open(outputFile, PdfDocumentOpenMode.Modify);
            pdfDocument.AddPage();
            //Document pdf_with_table =
            var secondpage = pdfDocument.Pages[1];
            XGraphics gfx = XGraphics.FromPdfPage(secondpage);

            XFont font = new XFont("Times New Roman", 20);
            int y_height = 0;
            int spacing = 50;
            foreach (string line in config_file)
            {
                // Draw the text
                gfx.DrawString(line, font, XBrushes.Black,
                new XRect(0, y_height * spacing, secondpage.Width, secondpage.Height),
                XStringFormats.TopCenter);
                y_height++;
            }

            // Save the document...
            pdfDocument.Save(outputFile);
            // ...and start a viewer.
            //Process.Start(filename);
        }
    }
}

**Comment by lawrenceglewis** [comment]
I can't seem to login to your website for free support I apologize. I will try to figure out what is wrong over there. 
[obj_giraffe_ball.zip](https://github.com/aspose-free-consulting/projects/files/7870719/obj_giraffe_ball.zip)

**Comment by lawrenceglewis** [comment]
I had to clear my browsing history and restart my computer to be able to log into the Aspose free support. I'm moving my question over there right now. Here is the link to where the question is. https://forum.aspose.com/t/convert-obj-to-3d-pdf/229948/4
