### ISSUE TITLE
Ttf file font is written to pptx, but it is not written successfully through your API. What is the reason!

### ISSUE THREAD

**Issue by xuboot** [aspose-free-consulting/projects#168]
byte[] memoryFont1 = Files.readAllBytes(Paths.get("C:\\Users\\xuhui\\Documents\\Tencent Files\\1905659868\\FileRecv\\zh46hmmt.ttf"));
        System.out.println(memoryFont1);

        LoadOptions loadOptions = new LoadOptions();

        loadOptions.getDocumentLevelFontSources().setMemoryFonts(new byte[][] { memoryFont1});

        Presentation pres = new Presentation("D:\\usr\\1.pptx", loadOptions);

        if (pres != null) {
            pres.dispose();
        }

**Comment by andreypotapovaspose** [comment]
@xuboot,
Thank you for the code example. We have replied to you [here](https://forum.aspose.com/t/ttf-font-file-is-written-to-pptx-but-it-is-not-written-successfully/240545).
