### ISSUE TITLE
I want to create/build 

### ISSUE THREAD

**Issue by adiguptac** [aspose-free-consulting/projects#169]
I am doing an EXCEL PROJECT AND WANT PASSWORD PROTECTION on the file which is difficult to crack.
The Protection Services on your website can be Decrypted on your website and even on others I checked on https://products.groupdocs.app/unlock/excel
Looking for a foolproof solution which can't be easily cracked by finding a few websites on google

Also looking for Digital RIghts Management Solutions for the same- for disabling the file if copied to another computer.

**Comment by atirtahirgroupdocs** [comment]
@adiguptac 

I am afraid but we don't offer any such feature. You may need some third party tool(s) to achieve it (e.g. [digify](https://digify.com/digital-rights-management.html?gclid=EAIaIQobChMI_8bDwoO79QIVms13Ch3LhQAgEAAYASAAEgIO2fD_BwE)).

**Comment by amjad-sahi** [comment]
@adiguptac ,

Please note, Aspose.Cells provides password protection/encryption features which MS Excel supports. But one can decrypt or remove password if he specifies the correct password. Your requirements seem beyond the scope of MS Excel or Aspose.Cells. If you still think that MS Excel supports such a feature or have other queries/doubts, please elaborate your requirements further with sample Excel file(s) (also mention steps details, etc.). We will check and help you soon,.
