### ISSUE TITLE
I want to create/build a web page to take coordinates from a PDF file

### ISSUE THREAD

**Issue by Cirunz** [aspose-free-consulting/projects#170]
Hi,
I need to insert in my asp.net application a page where the user upload a pdf file, than select with the mouse an area, from wich I take the pdf coordinates to extract the text in that area.

I don't need help in extracting the text: I already have a procedure in place for that.
All I need is to let the user select the area from the PDF file with the mouse.

Is there an Aspose product that would help me doing this? wich one?

**Comment by tahir-manzoor** [comment]
@Cirunz 
Aspose.PDF does not offer UI editor or web control for performing these PDF processing tasks.

**Comment by Cirunz** [comment]
Ok, thank you very much for the quick reply :)
