### ISSUE TITLE
I want to translate a document in Arabic to English. I haven't been able to do so on aspose. 

### ISSUE THREAD

**Issue by psandz** [aspose-free-consulting/projects#173]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>
[CamScanner 01-19-2022 11.19 (1).pdf](https://github.com/aspose-free-consulting/projects/files/7936572/CamScanner.01-19-2022.11.19.1.pdf)

**Comment by psandz** [comment]
[CamScanner 01-19-2022 11.19 (1).pdf](https://github.com/aspose-free-consulting/projects/files/7936579/CamScanner.01-19-2022.11.19.1.pdf)
I have uploaded the Arabic file I want to translate into English.

**Comment by atirtahirgroupdocs** [comment]
@psandz 

You are trying to translate a scanned PDF. However, [GroupDocs.Translation](https://products.groupdocs.app/translation/total) doesn't process/translate scanned files.
Please always post such a queries/requests on our free support [forum](https://forum.groupdocs.com/).
