### ISSUE TITLE
Office document to high quality raster conversion in Embedded environment

### ISSUE THREAD

**Issue by ghadithrissur** [aspose-free-consulting/projects#174]
Hello

We have a new requirement to convert doc/docx, XLS/XLSX, ppt to high quality raster. The solution is meant for an embedded environment. The solution should work on 128 mb RAM and ROM size of 64 MB.  I downloaded the Aspose.Words, Aspose.cells and Aspose.Slides and the shared libraries are all coming in the range of 80 to 98 MB. We are looking for a solution that should have a tiny footprint, Is it possible for Aspose to provide us with a scale down version of these libraries to meet our requirement?  We require C++ SDK that should run on Linux.

Also, is there any other solution to meet our requirements?

Thanks
Praveen

**Comment by andreypotapovaspose** [comment]
@ghadithrissur,
Thank you for posting the inquiry.

Unfortunately, it is not yet possible to use the Aspose.Slides library with a smaller size. But some optimizations have already been planned to significantly reduce the library size. The tentative ETA is version 22.7. This version will be released in July 2022. You will be notified if you post the inquiry on our [free forum](https://forum.aspose.com/).

My colleagues will reply to you about Aspose.Words and Aspose.Cells libraries.

**Comment by amjad-sahi** [comment]
@ghadithrissur,

Same is the case with Aspose.Cells. There is no such compact version available of the library. But we are already working on it although we cannot share any ETA no it at the moment. Currently, we suggest you to kindly try using [Aspose.Cells for Cloud](https://websites.aspose.com/aspose/cloud/#cells) (REST APIs.) for your requirements. 

Should you have further queries, feel free to post on the dedicated [forums](https://forum.aspose.com/).

**Comment by AlexNosk** [comment]
@ghadithrissur Unfortunately there is no way to provide such compact version of Aspose.Words for C++. We have plans to reduce size of C++ version, but the reduction will not be so radical. As I already suggested in the [forum ](https://forum.aspose.com/t/office-document-to-raster-conversion-solution-in-embedded-environment/241292/2) you can use our Cloud API to convert your documents.

**Comment by ghadithrissur** [comment]
Thanks for the response for my query related to Words, Cells and Slides.
Additional query as follows.



From your portal I understand that the Aspose libraries – let’s take an
example of Aspose.Words for C++ supports multiple inputs and outputs.

Is there a possibility to reduce the library size if the library supports
only the input as mentioned in the Input/Output table and the output as
Images only ?  We are expecting output only as Raster. So if we restrict
the output to Raster only, is there a possibility to reduce the library
size?







Other query is that , during conversion whether Aspose libraries generate
any temporary files in memory or Disk before converting to the supported
output format?   We have memory and hard disk size restrictions in our
requirement and hence the question.

**Comment by AlexNosk** [comment]
@ghadithrissur I am afraid it is not possible to reduce size of Aspose.Words library by reducing the number of output formats to Raster only. To convert a document to Raster it is required to build document layout, the layout engine is huge part of Aspose.Words codebase. Document model is another big part of Aspose.Words. File formats codecs (reading/writing code) quite small if compare to the mentioned above. Even if we exclude file formats writing code except the raster this will not give a significant library size reduction.

Aspose.Words does not create temporary files upon saving documents unless you specify [SaveOptions.TempFolder](https://apireference.aspose.com/words/cpp/class/aspose.words.saving.save_options#get_tempfolder_const). Also you can specify [SaveOptions.MemoryOptimization ](https://apireference.aspose.com/words/cpp/class/aspose.words.saving.save_options#get_memoryoptimization_const) flag that determines if memory optimization should be performed before saving the document.
