### ISSUE TITLE
Help needed to evaluate the project requirement from Aspose.pdf

### ISSUE THREAD

**Issue by E6AM** [aspose-free-consulting/projects#175]
As of today, we have been using iTextSharp 5 for PDF document generation. We would like to use Aspose.PDF for .net for our needs. In general, I would like to discuss and see if our requirements match the existing features or not. If any of the features don't support it, please do let me know.

We are looking at the windows platform.

High-level requirements are documented and attached. 

Thanks,
Vinay
[Information_Aspose.pdf](https://github.com/aspose-free-consulting/projects/files/8023196/Information_Aspose.pdf)

**Comment by tahir-manzoor** [comment]
@E6AM 

We are checking your requirement and answer your query as soon as possible.

**Comment by asadalikhan90** [comment]
@E6AM 

We would like to share with you that Aspose.PDF can perform the functionalities that you are looking for. Please check the following help topics in the API documentation that are related to your requirements:

> It should embed any type of ttf file (UNI Code), features - bold, italic, sizes, underline, symbols.

* [Add Text to PDF](https://docs.aspose.com/pdf/net/add-text-to-pdf-file/)

> Margin:- Left, Right, Top, Bottom margin as in below snip.
Page Layout:- Landscape / Portrait (A4 / US Letter)
Page Break:- To print page break

* [Working with Pages](https://docs.aspose.com/pdf/net/working-with-pages/)

> Watermark:- Tilted 45 degree upward from horizontal axis, light grey

* [Text stamps in PDF File](https://docs.aspose.com/pdf/net/text-stamps-in-the-pdf-file/)

> Header:- PNG logo, convertible to binary
Two rows separated by thick solid line, each row having 3 columns
Page number format – current page number / total number of pages
Bordered and borderless (both at table and cell level)

* [Add Header and Footer to PDF](https://docs.aspose.com/pdf/net/add-headers-and-footers-of-pdf-file/)
* [Image stamps in PDF File](https://docs.aspose.com/pdf/net/image-stamps-in-pdf-page/)
* [Working with Tables](https://docs.aspose.com/pdf/net/working-with-tables/)

> XHTML/HTML Content:- Item list and nested list with formatting, color and styling, text should not float after margin
Hyperlinked Text:- Blue in color and linked (eg., email id)

* [Add HTML String using DOM](https://docs.aspose.com/pdf/net/add-text-to-pdf-file/#add-html-string-using-dom)

> Compression:- Pdf compression to lower the file size, Signature / Image compression

* [Optimize PDF](https://docs.aspose.com/pdf/net/optimize-pdf/)

Please note that most of the requirements are related to tables in PDF. The sample code to add tables and text has already been given in the topics of the documentation that has been shared above. You can please try exploring the documentation and in case you face any issue or find difficulty while implementing some functionality, please create a post/topic in our [official support forum](https://forum.aspose.com/c/pdf) which is the right place to discuss. We will be more than happy to assist you there.

**Comment by E6AM** [comment]
Thanks for the quick response @asadalikhan90.

Could you please also help me confirm the following?

1. In a  single paragraph, do we have the option to have different formatting?
2. Within a document, is there a way to have the option to enable hyperlink? For instance, the initial page might have a code: ABC and in the other pages, where we have more information about ABC when the user clicks from the initial page where ABC is listed, it should be pointing to another page where we have more information.
3. Let's say, I'm generating the table and if the last row of the table has more content, which cannot be completely fit into the space available in pdf, Does that whole content would go to the next page? or does it split the content into the previous page how much ever fits there and balance in the next page? Is both of such things can be configurable?
4. Can we merge two pdf documents? If yes, does it support physical files only? or In memory also will it support or not?

Thanks,
Vinay

**Comment by asadalikhan90** [comment]
@E6AM 

> In a single paragraph, do we have the option to have different formatting?

A paragraph consists of multiple TextFragments and TextSegments. You can surely apply different styles and formatting at TextSegment as well as TextFragment Level by accessing their [TextState](https://apireference.aspose.com/pdf/net/aspose.pdf.text/textstate).

> Within a document, is there a way to have the option to enable hyperlink? For instance, the initial page might have a code: ABC and in the other pages, where we have more information about ABC when the user clicks from the initial page where ABC is listed, it should be pointing to another page where we have more information.

You can surely add Hyperlinks (Local within the PDF, Web, File) in the PDF as well as the TOC which can serve the above requirements. Please check below article(s):

* [Navigation and interaction](https://docs.aspose.com/pdf/net/navigation-and-interaction/)
* [Working with TOC](https://docs.aspose.com/pdf/net/manipulate-pdf-document/#working-with-toc)

> Let's say, I'm generating the table and if the last row of the table has more content, which cannot be completely fit into the space available in pdf, Does that whole content would go to the next page? or does it split the content into the previous page how much ever fits there and balance in the next page? Is both of such things can be configurable?

As a default behavior, when creating a table inside a PDF file, the table flows to subsequent pages when it reaches the table Bottom margin. However, you can forcefully insert a page break when a certain number of rows are added to the table. The [Table.IsBroken](https://apireference.aspose.com/pdf/net/aspose.pdf/table/properties/isbroken), and [Table.IsInNewPage](https://apireference.aspose.com/pdf/net/aspose.pdf/baseparagraph/properties/isinnewpage) Properties are used to achieve such requirements.

> Can we merge two pdf documents? If yes, does it support physical files only? or In memory also will it support or not?

You can merge two or multiple PDF documents using file paths as well as memory streams using Aspose.PDF. Please check the below documentation articles:

* [Merge PDF files](https://docs.aspose.com/pdf/net/merge-pdf-documents/)
* [Concatenate multiple PDF files using MemoryStreams](https://docs.aspose.com/pdf/net/concatenate-pdf-documents/#concatenate-multiple-pdf-files-using-memorystreams)
