### ISSUE TITLE
I want to format html code in a xls/csv file and save into another xls/csv

### ISSUE THREAD

**Issue by omkar62** [aspose-free-consulting/projects#176]
Hello,

I am working on a project which has a list of csv/xls files. One of the column within the file has html code which needs to be formatted  before we import this file into JIRA. 
JIRA is unable to format the html within the files and is importing the html code as is.

For example, there is a html table in one of the cell which needs to be formatted in such a way that <th> tags become the columns in the excel and <td> tags convert to values below respective columns.

Attached is the excel file which has three columns. One of the column has html code. This code should be changed to a format where <th> changes to a new column in the output excel and <td> below it becomes its value. 

Please let me know if any questions
[input.xlsx](https://github.com/aspose-free-consulting/projects/files/8057424/input.xlsx)

**Comment by amjad-sahi** [comment]
You need to re-insert those html codes in the cells of the column to set these as HTML strings via Cell.HtmlString attribute before rendering/saving to other file. See the documents for your reference.
[Display Bullets by setting Cell Value using HTML](https://docs.aspose.com/cells/net/display-bullets-by-setting-cell-value-using/)
[Adding HTML Rich Text inside the Cell](https://docs.aspose.com/cells/net/adding-html-rich-text-inside-the-cell/)

Alternatively, you may first export data from the file to fill a datatable (including your html  (code) column),  see the document on [how to export data to datatable](https://docs.aspose.com/cells/net/export-data-from-worksheet/).  Then, you will [import data (including html data)](https://docs.aspose.com/cells/net/import-data-into-worksheet/#importing-html-formatted-data) from that data table to be inserted into your new file (XLS/CSV). Now the html strings would be automatically parsed in the pasted data. 

Should you have any issue or queries, you may also post your queries/issue in the dedicated [forums](https://forum.aspose.com/c/cells/9).
