### ISSUE TITLE
Aspose.Slides : I am not able to focus the slide which has the search result.

### ISSUE THREAD

**Issue by kiranbcode** [aspose-free-consulting/projects#177]
Aspose.Slides

I am able to search the content of pptx file and highlight the search result. 
But I am not able to focus the slide which has the search result.

Expected :
 When I open back the file I have to see that slide as selected

**Comment by andreypotapovaspose** [comment]
@kiranbcode,
Thank you for contacting support. I've replied to you [here](https://forum.aspose.com/t/how-to-focus-the-slide-which-has-the-search-result/241897).
