### ISSUE TITLE
could aspose api share  and  edit excel files with other guys  and save in server  for a long time when we pay it?

### ISSUE THREAD

**Issue by tdejack** [aspose-free-consulting/projects#178]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by amjad-sahi** [comment]
@tdejack,

I am not sure about your requirements, so could you please elaborate your requirements and provide more details. We will check and assist you better. Please not [Aspose.Cells](https://products.aspose.com/cells/) is a spreadsheet management library and MS Excel file format API which can be used to manipulate (read, write, edit) Excel files at every level for all types of environments/platforms. Aspose.Cells library supports almost all the features which MS Excel supports. You can load Excel files into Aspose.Cells object model from server, manipulate/modify it and then can save on the server. How could you accomplish the task ("share and edit excel files with other guys...") in MS Excel manually, please elaborate with sample Excel file(s)? We will evaluate it and then help you accordingly.

To get efficient support on queries or issues related to Aspose.Cells, we also recommend to post your inquiries or questions on dedicated [forums](https://forum.aspose.com/c/cells/9).
