### ISSUE TITLE
I want to convert excel sheet into pdf

### ISSUE THREAD

**Issue by Prasanna8405** [aspose-free-consulting/projects#179]
Hi,

We are thinking to use your pdf component in our application. Before we are going to purchase a license we would like to verify your component will satisy all our requirements.

We downloaded your free version from visual studio nuget package.

This is our scenario we want to convert .xlsx into .pdf using .net application. we can able to convert but the output is not proper in pdf, i can see the columns are breaking.

Could you please give me some suggestion how to fix this problem.

I'm attaching the generated pdf as well as excel sheet for your reference.
[Köptjänst.pdf](https://github.com/aspose-free-consulting/projects/files/8123221/Koptjanst.pdf)
[Köptjänst.xlsx](https://github.com/aspose-free-consulting/projects/files/8123217/Koptjanst.xlsx)

Thanks,
Prasanna

**Comment by amjad-sahi** [comment]
@Prasanna8405 ,

I have checked your scenario/case a bit. Please open your template Excel file into MS Excel manually and take the Print Preview of the sheet. You will see almost similar display as per the output PDF file generated by Aspose.Cells. You will also see similar column breaks are there in the print preview. This may not be an issue with the Aspose.Cells APIs as Aspose.Cells follows MS Excel standards and specifications and by default, generates the PDF file of Excel template as per print preview display. 

By the way, if  you need to render one PDF page per sheet, see the document for your reference:
[Render One PDF Page Per Excel Worksheet - Excel to PDF Conversion](https://docs.aspose.com/cells/net/render-one-pdf-page-per-excel-worksheet-excel-to-pdf-conversion/)

Moreover, if you need to render all columns to be pasted on the page, you may refer to the document:
[Fit Worksheet Columns on Single PDF Page](https://docs.aspose.com/cells/net/fit-all-worksheet-columns-on-single-pdf-page/)

To get efficient support, you may also post your queries or issue on dedicated [forums](https://forum.aspose.com/c/cells/9).

**Comment by Prasanna8405** [comment]
Thank you so much for your answer.
