### ISSUE TITLE
Aspose.Cells Mac problem

### ISSUE THREAD

**Issue by z7396206dd** [aspose-free-consulting/projects#18]
When the new Workbook (path) is reported, an exception was thrown by the type initializer for System.Drawing.GDIPlus Why is this caused, the file path is correct.

**Comment by shahzad-latif** [comment]
@z7396206dd 

Sorry for the trouble you had to face, however, this place is dedicated for consulting projects only. For other questions, bug reports and feature requests, please post in relevant f[orum for Aspose.Cells file format APIs.](https://forum.aspose.com/c/cells) I appreciate your cooperation and looking forward to help you.
