### ISSUE TITLE
Metered License Implementation not working

### ISSUE THREAD

**Issue by vrkamal18** [aspose-free-consulting/projects#181]
Hi,

We purchased the metered license in order to consume Aspose words in Java. Implemented the metered license as per the code snippet mentioned here
https://docs.aspose.com/words/java/licensing/#apply-metered-license

But still I see the rendered PDF saying "This document was truncated here because it was created in the Evaluation Mode.". 
Can you please let us know the code snippet is for the latest version aspose-words-22.1.0-java or the code sample has to be updated since I don't see the License object has any method lic.isLicensed().

We need your support at the earliest.

Here is the code I implemented in my project.

Metered m = new Metered();
m.setMeteredKey(publicKey, privateKey);
License lic = new License();
System.out.println("License is set = " + lic);

Thanks
Kamal

**Comment by AlexNosk** [comment]
@vrkamal18 `License .isLicensed()` method has been removed from Aspose.Words API. To set the license it is enough to run this code:
``` java
Metered m = new Metered();
m.setMeteredKey(publicKey, privateKey);
```
But make sure the license is set before instantiating `Document` or any other `Aspose.Words` classes.
