### ISSUE TITLE
ADA Compliance Support for Aspose.Word to save word document to PDF document

### ISSUE THREAD

**Issue by vrkamal18** [aspose-free-consulting/projects#182]
We are working on the Aspose.Word to convert word document to PDF document. Does Aspose.Word verify whether the word document or the converted PDF document is in ADA Compliance. Can you let us know.

Thanks
Kamal

**Comment by 2econd** [comment]
@vrkamal18 At the moment Aspose.Words do not verify the source MS Word document accessibility. When saving document to PDF, you could select PdfCompliance.PdfUa1 to produce accessible output. This way Aspose.Words will try to save the most accessible information which is available in source document (logical structure, alt text for images etc.). Unfortunately we do not verify the ADA compliance particularly but all accessibility standards (like PDF/UA, WCAG, ADA) have mostly common requirements regarding PDF documents.

Please contact us in the [Free Support Forum](https://forum.aspose.com/) if you encounter any particular accessibility issue in our PDF output or if you want to request new features like accessibility check of MS Word document.
