### ISSUE TITLE
Aspose.Imaging TIFF to PDF

### ISSUE THREAD

**Issue by vrkamal18** [aspose-free-consulting/projects#186]
We are working on the Aspose.Imaging to convert word Image to PDF document. I am trying to save the image byte to a PDFOptions using the below syntax gives me error.

PdfSaveOptions saveOptions = new PdfSaveOptions();
image.save(byteArrayOutputStream, saveOptions);

This gives me error saying 
The method save(String, ImageOptionsBase) in the type Image is not applicable for the arguments (ByteArrayOutputStream, PdfSaveOptions)

If the above syntax is wrong then how to save the byte stream(image) to PDF

Thanks

**Comment by samer199008** [comment]
@vrkamal18 If you use Aspose.Imaging library to Load Tiff image and export it to Pdf you can use such code example https://products.aspose.com/imaging/net/conversion/tiff-to-pdf/ If you use another Aspose library for loading you can ask it on Aspose forum in related product topic https://forum.aspose.com/

**Comment by samer199008** [comment]
@vrkamal18 Please provide for us file that you use. Also, please provide full code snippet how do you load initial file. Thanks.

**Comment by ESidenko** [comment]
Hello, @vrkamal18 !
As I can see you use the wrong argument for Image.save method. There is no PdfSaveOptions class in Aspose.Imaging for Java. Most likely you take PdfSaveOptions from Aspose.Word for Java or any other products.
You can solve this issue using PdfOptions instead of PdfSaveOptions. Please, take a look at the following example.
``` java
byte[] byteDocument = Base64.decodeBase64(inputBase64Str);
BufferedInputStream byteArrayInputStream = new BufferedInputStream(new ByteArrayInputStream(byteDocument));
// this is strongly recommended to avoid memory leaking.
try (Image image = Image.load(byteArrayInputStream))
{
    PdfOptions saveOptions = new PdfOptions();
    ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
    image.save(byteArrayOutputStream, saveOptions);
}
```

**Comment by vrkamal18** [comment]
Thank you for the support
