### ISSUE TITLE
PDF2TIFF - Purchased License says evaluation mode

### ISSUE THREAD

**Issue by vrkamal18** [aspose-free-consulting/projects#187]
We have purchased the metered license for Aspose.Total for Java. While I am trying to convert PDF to TIFF image I am using the purchased license for the API that I have written. When tried to execute the API I am getting error message saying:
_**class com.aspose.pdf.exceptions.IndexOutOfRangeException: At most 4 elements (for any collection) can be viewed in evaluation mode.**_

The same metered license used for DOC to PDF works fine. 

Not sure what is going wrong here.

**Comment by tahir-manzoor** [comment]
@vrkamal18 

You are facing this issue because license is not properly set or it is expired. We suggest you please post your query in our official [fee support forum](https://forum.aspose.com/c/pdf/10) to get the accurate response.
