### ISSUE TITLE
does aspose.Tex support cjk？

### ISSUE THREAD

**Issue by HiramAllen** [aspose-free-consulting/projects#188]
I use xelatex to make a .tex file that contains Chinese. I try to use aspose.tex convert it to pdf but the console wrote “latex error can not find ctex.sty” Is there a way to fix that?

**Comment by a-kolodyazhnyy** [comment]
XeTeX is a TeX engine that understands characters in unicode encoding. But the Aspose.TeX library provides the basic TeX engine that can deal only with characters in ASCII encoding. This is the main reason why your problem cannot be easily fixed. In addition, Aspose.TeX operates only packages that are embedded into it. Unfortunately.
