### ISSUE TITLE
Questions before purchace of Aspose.PDF

### ISSUE THREAD

**Issue by bleze** [aspose-free-consulting/projects#189]
Hi

Looking for software which can do the following;

1. Remove all text from PDF, leaving essentially only other visible objects like images and paths.
2. OPTIONAL: Render PDF to multipage TIFF or vector of PNG's.
3. Overlay two PDF's with same number of pages. One contains "invisible" text and goes on top of the other.
4. Forgiving with "corrupt" PDF's. Adobe Reader can read most PDF's even if they are non-standard.
5. Read properties like producer etc.

Not asking for sample code, but of course would be nice to get going fast.

Thanks

**Comment by asadalikhan90** [comment]
@bleze 

Please check below documentation articles for your requirements:

> Remove all text from PDF, leaving essentially only other visible objects like images and paths.

* [Remove All Text from PDF Document](https://docs.aspose.com/pdf/net/replace-text-in-pdf/#remove-all-text-from-pdf-document)

> OPTIONAL: Render PDF to multipage TIFF or vector of PNG's.

* [Convert PDF to Images](https://docs.aspose.com/pdf/net/convert-pdf-to-images-format/)

> Read properties like producer etc.

* [Get PDF file information](https://docs.aspose.com/pdf/net/get-pdf-file-information/)

> Overlay two PDF's with same number of pages. One contains "invisible" text and goes on top of the other.
Forgiving with "corrupt" PDF's. Adobe Reader can read most PDF's even if they are non-standard.

We could actually get what you want to achieve in your above requirements. Can you please elaborate a bit more and share some PDF documents for our reference? 

Also, please note that the official [Aspose.PDF Support forum](https://forum.aspose.com/c/pdf) is the right place to discuss such topics where you will be assisted accordingly. Please try to create a topic there.
