### ISSUE TITLE
Aspose Email not saving correctly the content of .MSG to TIFF

### ISSUE THREAD

**Issue by virenderconduent** [aspose-free-consulting/projects#190]
Hi,

We have a licensed version of Aspose within organisation and we are seeing an issue, when any .MSG file (outlook file) have images in body of email they are not saving correctly to TIFF, the images in each frame is cut from one side. Please help. Attached is the sample .msg and C# code file.
[EM20220323003345.zip](https://github.com/aspose-free-consulting/projects/files/8363897/EM20220323003345.
[Program.zip](https://github.com/aspose-free-consulting/projects/files/8363929/Program.zip)
zip)

**Comment by tahir-manzoor** [comment]
@virenderconduent 

Unfortunately, we are unable to download your ZIP file. Please share it again. Thanks.

**Comment by virenderconduent** [comment]
Hi Team,

Can I share it on email?

Thanks,
Virender

From: Tahir Manzoor ***@***.***>
Sent: Wednesday, March 30, 2022 12:43 PM
To: aspose-free-consulting/projects ***@***.***>
Cc: Kumar, Virender ***@***.***>; Mention ***@***.***>
Subject: [External] - Re: [aspose-free-consulting/projects] Aspose Email not saving correctly the content of .MSG to TIFF (Issue #190)

This email is from an external source.  Use caution responding to it, opening attachments or clicking links.


@virenderconduent<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvirenderconduent&data=04%7C01%7Cvirender.kumar%40conduent.com%7C10520a8e30e148a2be7b08da121cc8e1%7C1aed4588b8ce43a8a775989538fd30d8%7C0%7C0%7C637842212086970455%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=U33Z4680ZqmNWAU6LwyxwBTvkKg7GiEoUGn2ACdENaU%3D&reserved=0>

Unfortunately, we are unable to download your ZIP file. Please share it again. Thanks.

-

**Comment by virenderconduent** [comment]
It is below method that we are calling in console application:

static void ConvertToTIFF()
        {
            // ExStart:ConvertMSGToTIFF
            // The path to the File directory  and load the MSG file using Aspose.Email for .NET
            string dataDir = @"LOCALFOLDER"; //RunExamples.GetDataDir_KnowledgeBase();
            MailMessage msg = MailMessage.Load(dataDir + "EM20220323003345.msg", new MsgLoadOptions());

            // Convert MSG to MHTML and save to stream
            MemoryStream msgStream = new MemoryStream();
            msg.Save(msgStream, SaveOptions.DefaultMhtml);
            msgStream.Position = 0;

            // Load the MHTML stream using Aspose.Words for .NET and Save the document as TIFF image
            Document msgDocument = new Document(msgStream);
            msgDocument.Save(dataDir + "EM20220323003345
[EM20220323003345.zip](https://github.com/aspose-free-consulting/projects/files/8378801/EM20220323003345.zip)
.tif", SaveFormat.Tiff);
            // ExEnd:ConvertMSGToTIFF
        }

**Comment by tahir-manzoor** [comment]
@virenderconduent 

Please use the following code example to get the desired output. 

```cs
MailMessage msg = MailMessage.Load(MyDir + "EM20220323003345.msg", new MsgLoadOptions());

// Convert MSG to MHTML and save to stream
MemoryStream msgStream = new MemoryStream();
msg.Save(msgStream, SaveOptions.DefaultMhtml);
msgStream.Position = 0;

// Load the MHTML stream using Aspose.Words for .NET and Save the document as TIFF image
Document msgDocument = new Document(msgStream);

foreach (Shape shape in msgDocument.GetChildNodes(NodeType.Shape, true))
    ResizeLargeImage(shape);
msgDocument.Save(MyDir + "EM20220323003345.tiff", SaveFormat.Tiff);
```
```cs
public static void ResizeLargeImage(Aspose.Words.Drawing.Shape image)
{
    // Return if this shape is not an image.
    if (!image.HasImage)
        return;

    // Calculate the free space based on an inline or floating image. If inline we must take the page margins into account.
    PageSetup ps = image.ParentParagraph.ParentSection.PageSetup;
    double freePageWidth = image.IsInline ? ps.PageWidth - ps.LeftMargin - ps.RightMargin : ps.PageWidth;
    double freePageHeight = image.IsInline ? ps.PageHeight - ps.TopMargin - ps.BottomMargin : ps.PageHeight;


    ImageSize size = image.ImageData.ImageSize;
    Boolean exceedsMaxPageSize = size.WidthPoints > freePageWidth || size.HeightPoints > freePageHeight
        || image.Width > freePageWidth || image.Height > freePageHeight;

    if (exceedsMaxPageSize)
    {
        // Calculate the ratio to fit the page size based on which side is longer.
        Boolean widthLonger = (size.WidthPoints > size.HeightPoints);
        double ratio = widthLonger ? freePageWidth / size.WidthPoints : freePageHeight / size.HeightPoints;

        // Set the new size.
        image.Width = size.WidthPoints * ratio;
        image.Height = size.HeightPoints * ratio;
    }
}

```

**Comment by virenderconduent** [comment]
@tahir-manzoor : can you please recheck this code, It seems that for some emails this is throwing exception as below:

System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Shape width cannot be greater than 1584 points.
Parameter name: value
  Source=Aspose.Words
  StackTrace:
   at G7.a(ShapeBase a, Double b, Boolean c, String d)
   at Aspose.Words.Drawing.ShapeBase.xc(Double a, Boolean b)
   at Aspose.Words.Drawing.ShapeBase.set_Height(Double value)

**Comment by tahir-manzoor** [comment]
@virenderconduent 

Your query will be answered in https://github.com/aspose-free-consulting/projects/issues/235 post.
