### ISSUE TITLE
Scan Files Processing

### ISSUE THREAD

**Issue by moranuk** [aspose-free-consulting/projects#191]
We produce printed gifts from drawings that kids do in school.

Kids draw these pictures on templates and we then scan these, crop and save in the project folder.

We would like to add IDs /barcodes to these forms so that we can automate the processing of these templates.

Therefore when scanned a process can analyse each scanned image, find the associated IDs and then save the image in the relevant project folder.

Then we would like to run a process that automates croping the image into two images, one of the child's drawing and one for the childs details written on the form.

How can aspose help us with this?

**Comment by amjad-sahi** [comment]
@moranuk 

I think you may try to use [Aspose.BarCode](https://products.aspose.com/barcode/net/) and [Aspose.Imaging](https://products.aspose.com/imaging/net/) APIs to accomplish your major tasks. Aspose.BarCode library will be used to add/render, manipulate or recognize barcodes. Similarly to manipulate, crop, resize and merge images, you may use Aspose.Imaging API. 

> We would like to add IDs /barcodes to these forms so that we can automate the processing of these templates
See the documents on how to [add/generate different types of barcodes](https://docs.aspose.com/barcode/net/generate-barcode-with-different-symbology/) for your reference. You can create barcodes and then save to image format. To recognize barcodes from the images, you may refer to the documents in [recognizing barcodes](https://docs.aspose.com/barcode/net/barcode-recognition/) section.

> Then we would like to run a process that automates croping the image into two images, one of the child's drawing and one for the childs details written on the form.
See the document on how to to [crop, rotate or resize images](https://docs.aspose.com/imaging/net/crop-rotate-and-resize-images/) by Aspose.Imaging for your reference. Moreover, to merge images, see the documents on [merging images](https://docs.aspose.com/imaging/net/merge-images/) for your reference.

We also recommend you to kindly post your requirements/issues in dedicated [forums](https://forum.aspose.com/), we handle clients' issues and requirements efficiently in the forums.
