### ISSUE TITLE
Aspose.word .net Page Height 

### ISSUE THREAD

**Issue by kyto88** [aspose-free-consulting/projects#192]
We have downloaded a trial from your website.   We are manipulating the height of existing word documents.  Existing word documents have a page height, for example, 10 inches.  We want to change the height, for example, to 5 inches.  Is this possible?  If it is possible, how do we do it?  Can you provide a sample code?    

There is another product, Aspose.pdf.  Can we change the height in the Aspose.pdf .net?

**Comment by AlexNosk** [comment]
@kyto88  You can change page dimensions in MS Word document using [PageSetup](https://apireference.aspose.com/words/net/aspose.words/pagesetup) class and it's properties. For example see [PageSetup.PageHeight](https://apireference.aspose.com/words/net/aspose.words/pagesetup/properties/pageheight)
