### ISSUE TITLE
Problem in EMF to SVG conversion

### ISSUE THREAD

**Issue by DhruvPatel823** [aspose-free-consulting/projects#193]
I have tried to convert .emf to .svg file from https://products.aspose.app/imaging/conversion here.
PFA.
our organization wants to buy software but it don’t match the output after conversion
[ImageConversion.zip](https://github.com/aspose-free-consulting/projects/files/8441863/ImageConversion.zip)
.

**Comment by alex-i-feigin** [comment]
@DhruvPatel823 
We're able to reproduce the issue with your file and created the internal ticket  **IMAGINGNET-5369** to process in the next releases.

**Comment by DhruvPatel823** [comment]
I provide you some sample .emf files which I want to convert .emf to .svg file.
PFA.
Can you please provide me tentative dates for your next releases regarding ticket **IMAGINGNET-5369**?
[SampleImages.zip](https://github.com/aspose-free-consulting/projects/files/8505334/SampleImages.zip)

**Comment by alex-i-feigin** [comment]
@DhruvPatel823
I see, you've shared more images so we need review them before making estimations.
Please make yout request via our forum https://forum.aspose.com/c/imaging/14 so you'll 
be able to review the progress for the mentioned task.
