### ISSUE TITLE
PPTX to HTML5 Conversion issue - internal server error [500] 

### ISSUE THREAD

**Issue by Chandana1609** [aspose-free-consulting/projects#195]
Hi,
When converting PPTX to HTML works fine. However, converting from PPTX to HTML5 throws the error shown below.

Aspose\Slides\Cloud\Sdk\Api\ApiException: [500] Server error: POST https://api.aspose.cloud/v3.0/slides/convert/Html5 resulted in a 500 Internal Server Error response: {“error”:{“code”:“internalError”,“message”:"SolidFillColor is unavail (truncated…) in Aspose\Slides\Cloud\Sdk\Api\ApiBase->httpCall() (line 89 of C:\xampp\htdocs\MyDemoWebsite\drupal-7.82\sites\default\modules\form_example\vendor\aspose\slides-sdk-php\sdk\Api\ApiBase.php).

**Comment by andreypotapovaspose** [comment]
Thank you for contacting support. I've replied to you here:
https://forum.aspose.cloud/t/pptx-to-html5-conversion-in-php-throws-500-internal-server-error/9950
