### ISSUE TITLE
Questions before purchase

### ISSUE THREAD

**Issue by Soclokiko** [aspose-free-consulting/projects#196]
Hello,

I have a few questions on Aspose.HTML for Java, before considering buying this service. Hope you can help me out here:

- Do you support HTML templating also with Handlebar or Mustache? If yes, can those templates be saved on your side?
- Do you support CSS 2 ideal 3?
- How does the PDF generation work, in case of long running processes? Is there a asynchronous way to go with?
- Do you support page numbering + Page numbering on merged documents?
- Are remote resources supported? F.e. images given from external URL or it has to be uploaded with template?
- Is there any limit on number of pages in one document, or size limit?
- Downloading documents - are results publicly available? Is there any way to restrict access to the results?

Thank you in advance for your help!

Best regards
Vu

**Comment by asadalikhan90** [comment]
@Soclokiko 

We are in process of porting all features from Aspose.HTML for .NET API to Aspose.HTML for Java. However, we are collecting information related to your all questions and will soon get back to you with a feedback. Please give us little time.

**Comment by asadalikhan90** [comment]
@Soclokiko 

Can you please also confirm if you are interested in using Aspose.HTML Cloud SDK for Java? Because, if you are interested in Aspose.HTML for Java then some questions like "Downloading documents - are results publicly available?" are irrelevant. Downloading results only makes sense in a Cloud product.

**Comment by Soclokiko** [comment]
@asadalikhan90 

Yes I´m interested in the Aspose.HTM Cloud SDK for Java. I would like to create different documents through HTML, in order to convert them into PDF documents. Those documents are related to application documents for rent apartments in germany.

**Comment by tilalahmad** [comment]
@Soclokiko

Please find below the answers to your questions.  Hopefully, it helps. You may [signup](https://docs.aspose.cloud/total/getting-started/quickstart/) with aspose.cloud for a free account and test your use case. And please feel free to post your query in [Aspose.HTML Cloud forum](https://forum.aspose.cloud/c/html/24) for any suggestions or issues.

>Do you support HTML templating also with Handlebar or Mustache? If yes, can those templates be saved on your side?

Yes, it supports HTML templating with Mustache markers, please check the [documentation article](https://docs.aspose.cloud/html/archive_v_3_0/template-merge/#template-markup) on how to add markers for a single field marker and repeatable section. You can save the template on cloud storage(Aspose Internal Storage and [third-party Storages](https://docs.aspose.cloud/total/getting-started/dashboard/how-to-configure-3rd-party-cloud-storages/))

>Do you support CSS 2 ideal 3?

CSS3

>How does the PDF generation work, in case of long running processes? Is there a asynchronous way to go with?

I am afraid the current release does not support asynchronous API calls. However, we have a plan to introduce the feature in the upcoming release

>Do you support page numbering + Page numbering on merged documents?

Aspose.HTML Cloud API is not supporting the feature but you can add page numbers to output PDF using [Aspose.PDF Cloud API](https://docs.aspose.cloud/pdf/working-with-stamps/)

>Are remote resources supported? F.e. images given from external URL or it has to be uploaded with template?

Publicly accessible external resources are supported

>Is there any limit on number of pages in one document, or size limit?

No page numbers limit, however, you can process a document size upto 100MB in an API call

>Downloading documents - are results publicly available? Is there any way to restrict access to the results?

No, the downloading files are available via authenticated API Calls. If you want to share the results then you need to implement your own workflow for it

**Comment by Soclokiko** [comment]
Thanks for the answers!
