### ISSUE TITLE
We are trying to build web viewer for excel/word/pwerpoint/pdf/images/textfiles.

### ISSUE THREAD

**Issue by srinivasarajui-tn** [aspose-free-consulting/projects#198]
We want to understand if this can be accomplished with Aspose For Nodejs or Should we use (Java or .Net).
Can we integrate the viewer into our existing angular app on the front end?

Our Current Tech stack is NodeJS/Angular and Python.

What are minimum licences of aspose are required to build such a soultion.

**Comment by AlexNosk** [comment]
@srinivasarajui-tn Aspose.Words is document processing library and does not provide a viewer control. You can use Aspose.Words to save document in format that can be used for viewing document, such as FixedHtml, SVG or image. 
Unfortunately, Aspose.Words currently does not have a version for NodeJS, however, we have Python version, you can use in your application: https://pypi.org/project/aspose-words/

**Comment by srinivasarajui-tn** [comment]
I was looking at https://products.aspose.app/words/viewer and expecting that you have viewer.

**Comment by andreypotapovaspose** [comment]
@srinivasarajui-tn,
As for Aspose.Slides, you can convert presentation slides to images or HTML documents to display them in your app using [Aspose.Slides for Python via .NET](https://products.aspose.com/slides/python-net/).
Examples: [Presentation Viewer](https://docs.aspose.com/slides/net/presentation-viewer/)

**Comment by AlexNosk** [comment]
@srinivasarajui-tn You can get sources of viewer demo on our [GitHub](https://github.com/aspose-words/Aspose.Words-for-.NET/tree/master/Demos).

**Comment by asadalikhan90** [comment]
@srinivasarajui-tn 

As far as Aspose.PDF for .NET is concerned, you can download the source code for [PDF Viewer](https://products.aspose.app/pdf/viewer) from our [Demos](https://github.com/aspose-pdf/Aspose.PDF-for-.NET/tree/master/Demos) hosted over GitHub. Please also try to check [GroupDocs.Viewer](https://products.groupdocs.com/viewer/) (one of our ventures) that can also be used to achieve what you require.
