### ISSUE TITLE
XLS to XLSX conversion changes the two-color gradient of conditional formats

### ISSUE THREAD

**Issue by MiniCassie** [aspose-free-consulting/projects#199]
**Step：**
1.Create a new conditional format
2.Sets fill formatting for a shape
3.Sets the specified fill to a two-color gradient
![image](https://user-images.githubusercontent.com/49870259/165255078-c43027c7-f4b3-4a13-9f1d-f30a469b4448.png)

**Code:**
string src = "C:\\test.xls";
string dst = "C:\\test.xlsx";
Aspose.Cells.Workbook workbook = new Aspose.Cells.Workbook(src);
workbook.Save(dst, Aspose.Cells.SaveFormat.Xlsx);
[test.zip](https://github.com/aspose-free-consulting/projects/files/8561178/test.zip)
![image](https://user-images.githubusercontent.com/49870259/165255260-20504dcf-f2b5-478f-ad3b-a30801da9b4a.png)

**Comment by amjad-sahi** [comment]
Thanks for the template file and details.
Please notice, I am able to reproduce the issue as you mentioned by using your template XLS file to convert to XLSX file format. I found in the output XLSX file, the two-color gradient of conditional format is changed. I have logged a ticket with an id "CELLSNET-50952" for your issue. We will look into it to figure it out soon.

By the way,  you may also post your queries/issues in the dedicated [forums](https://forum.aspose.com/c/cells/9), we handle users inquiries efficiently there.

**Comment by amjad-sahi** [comment]
We fixed the issue. The fix will be included in our regular (next) release (Aspose.Cells for .NET v22.5) which is due in the second week of May 2022. So, you should check back at that time and get it there ([Download](https://downloads.aspose.com/cells/net) | [NuGet](https://www.nuget.org/packages/Aspose.Cells/)). We will also notify you once the next release is published.

**Comment by amjad-sahi** [comment]
Please try our latest version/fix: Aspose.Cells for .NET v22.5 ([Download](https://downloads.aspose.com/cells/net) | [NuGet](https://www.nuget.org/packages/Aspose.Cells/)). Your issue is fixed in it.
