### ISSUE TITLE
System.ArgumentOutOfRangeException：specified argument was out of the range of valid values

### ISSUE THREAD

**Issue by MiniCassie** [aspose-free-consulting/projects#204]
System.ArgumentOutOfRangeException：specified argument was out of the range of valid values
Arg_ParamName_Name: textFlow
**Code**
string src = "C:\\test.doc";
string dst = "C:\\test.docx";
Aspose.Words.Document document = new Aspose.Words.Document(src);
document.Save(dst, Aspose.Words.SaveFormat.Docx);
[test.zip](https://github.com/aspose-free-consulting/projects/files/8580124/test.zip)
The document was created with WPS Office

**Comment by AlexNosk** [comment]
@MiniCassie  Thank you for reporting this problem to us. For a sake of correction it has been logged as **WORDSNET-23806**. We will keep you informed and let you know once it is resolved.

**Comment by AlexNosk** [comment]
@MiniCassie The issue you have found earlier is already resolved in the latest version of Aspose.Words. 
<https://www.nuget.org/packages/Aspose.Words>
