### ISSUE TITLE
When I Save excel to PDF or Doc then the content of cell is missing 

### ISSUE THREAD

**Issue by Uday32123** [aspose-free-consulting/projects#206]
When I Save excel to PDF or Doc then the content of cell is missing.
I am using Aspose version 2019.4 
![image](https://user-images.githubusercontent.com/104886814/166632262-fe14b255-6206-4343-ae48-2ca4c2f61feb.png)

**Comment by amjad-sahi** [comment]
Please try using latest version and if you still find any issue, kindly share your template Excel file to evaluate your issue on our end.
By the way,  you may also post your queries in the dedicated [forum](https://forum.aspose.com/c/cells/9) as we handle users inquiries/issues efficiently there.

**Comment by Uday32123** [comment]
@amjad-sahi  I am using 2022.4 latest version. I am trying to convert the attached excel file into pdf but it is not converting.

[StatementReports04122022 (3).xlsx](https://github.com/aspose-free-consulting/projects/files/8639048/StatementReports04122022.3.xlsx)
