### ISSUE TITLE
I want to create/build 

### ISSUE THREAD

**Issue by Cover31** [aspose-free-consulting/projects#207]
word转换成pdf之后，怎么把word的导航窗口变成pdf左侧的窗口，保留word文件的目录

**Comment by AlexNosk** [comment]
@Cover31 您可以指定 [PdfSaveOptions.OutlineOptions](https://apireference.aspose.com/words/net/aspose.words.saving/pdfsaveoptions/properties/outlineoptions) 来实现您的需要。 您可以使用书签或标题来构建大纲。
