### ISSUE TITLE
How to install and configure Aspose Total.net on windows server 2012

### ISSUE THREAD

**Issue by pavanjoshi48588** [aspose-free-consulting/projects#208]
We had Aspose 2013 version installed on windows machine with previous version of Domino 8.5.3 version.
After in-place upgrade of of Domino V10 we are unable to see Aspose configured. We are trying to install Aspose for the first time and dont have steps to carry nor understanding which are available on the internet forums. Can any one help with actual steps to install it and attached is the files we have currently for installation with license.
![2022-05-05 11_24_39-Aspose2013_files - OneDrive and 5 more pages - Profile 1 - Microsoft​ Edge](https://user-images.githubusercontent.com/104966103/166877444-8b540e34-f67d-4af1-9192-73c118b12cee.png)

**Comment by tahir-manzoor** [comment]
@pavanjoshi48588 

Please completely remove the Aspose.Total from your machine and install it again. Hope this helps you.

If you still face problem, please share the complete detail of your scenario along with environment detail. We will then provide you more information on it.
