### ISSUE TITLE
我想获取文档中指定页面的所有文本，并设置段落样式在放回文档中。 环境： java8

### ISSUE THREAD

**Issue by FengHaoa** [aspose-free-consulting/projects#21]
例如： 获取文档中第三页到文档最后一页的文本，并设置一些属性，其中文档中包含图片，且图片的位置还是在原来文本的位置。

**Comment by FengHaoa** [comment]
更改一下：我想设置文档中指定页面段落的样式。 环境： java8 、 aspose.word

**Comment by shahzad-latif** [comment]
感谢您的关注。 我们正在调查您的要求，并将尽快提供更多详细信息。

**Comment by FengHaoa** [comment]
您好，我有一个功能就是很多小word ,拼接成一个大的word,我想在小word插入到大word之前，调整一下小word的段落格式。就是这个功能。
非常感谢您能关注我。谢谢

**Comment by shahzad-latif** [comment]
您是否也可以共享一些样本文档，以便我们检查您的特定情况？

**Comment by FengHaoa** [comment]
额，不好意思，我还是一个菜鸟对于使用github，不会上传文档。

**Comment by FengHaoa** [comment]
就是在通过api获取到word时，将文档内的段落格式化一下。

**Comment by FengHaoa** [comment]
[test.docx](https://github.com/aspose-free-consulting/projects/files/3949413/test.docx)
例如：将这个文档的段落格式设置为  段落后间距0磅，行距最小值，0

**Comment by FengHaoa** [comment]
补充一下
注意事项：不建议您使用读取文档中的所有段落，然后遍历写在新文档中，因为文档中可能会存在图片
具体写法： ParagraphCollection para = document.getFirstSection().getBody().getParagraphs();
        for (int i = 0; i < para.getCount(); i++) {
            builder.writeln(para.get(i).getText());
        }

**Comment by FengHaoa** [comment]
[test.zip](https://github.com/aspose-free-consulting/projects/files/3953349/test.zip)
一共三个文档，result.docx是我想要的效果，请注意段落格式，图片位置等

**Comment by FengHaoa** [comment]
请问这个问题有什么其他的办法吗？

**Comment by shahzad-latif** [comment]
@FengHaoa 

感谢您与示例文档共享更多详细信息。 我们正在详细研究您的要求，并将尽快回复更新。

**Comment by FengHaoa** [comment]
你好，非常感谢，问题已经解决了

**Comment by tahir-manzoor** [comment]
@FengHaoa

> 例如： 获取文档中第三页到文档最后一页的文本，并设置一些属性，其中文档中包含图片，且图片的位置还是在原来文本的位置。

Aspose.Words.Layout命名空间提供了一些类，当将文档格式化为页面时，这些类允许访问特定文档元素所处位置（例如，在页面上以及页面上的位置）的信息。 以下代码示例显示了如何在第三页上设置段落样式。
```
Document doc = new Document("input.docx");
LayoutCollector lc = new LayoutCollector(doc);
int page = 3;
for (Paragraph paragraph : (Iterable<Paragraph>)doc.getChildNodes(NodeType.PARAGRAPH, true))
{
    if (lc.getStartPageIndex(paragraph) == page && paragraph.getRuns().getCount() > 0)
    {
        paragraph.getParagraphFormat().setStyleName("Normal");
    }
}
doc.save("output.docx");
```

**Comment by tahir-manzoor** [comment]
@FengHaoa
>  一共三个文档，result.docx是我想要的效果，请注意段落格式，图片位置等

请使用下面的代码示例获取所需的输出。

```
Document doc1 = new Document(MyDir +"test1.docx");
Document doc2 = new Document(MyDir +"test2.docx");
for (Paragraph paragraph : (Iterable<Paragraph>) doc1.getChildNodes(NodeType.PARAGRAPH, true)){
    paragraph.getParagraphFormat().setSpaceBefore(0);
    paragraph.getParagraphFormat().setSpaceAfter(0);
    paragraph.getParagraphFormat().setLineSpacing(0);
    paragraph.getParagraphFormat().setLineSpacingRule(LineSpacingRule.AT_LEAST);
}

doc2.getFirstSection().getPageSetup().setSectionStart(SectionStart.CONTINUOUS);
doc1.appendDocument(doc2, ImportFormatMode.KEEP_SOURCE_FORMATTING);

doc1.save(MyDir + "result.docx");
```

**Comment by FengHaoa** [comment]
非常感谢，解决了我的问题
