### ISSUE TITLE
如何将TIF转jpg

### ISSUE THREAD

**Issue by leijie-jlei** [aspose-free-consulting/projects#212]
已购买total,如何将多页的TIF转为多张JPG图片

**Comment by sam199008** [comment]
@leijie-jlei 您可以嘗試我們的示例 https://docs.aspose.com/imaging/net/manipulating-tiff-images/#export-multi-page-frames-to-different-image-format 將 tiff 幀轉換為 bmp 圖像，以及 使用您的參數指定您自己的 JpegOptions。
