### ISSUE TITLE
Issues with New License

### ISSUE THREAD

**Issue by sgeierAsbru** [aspose-free-consulting/projects#217]
We just purchased a new license. We had pre-existing code that was compiled into an executable via C#. When we use the new license, the output always has the watermark stating our license isn't valid. We need help to figure out what the issue is.

**Comment by tahir-manzoor** [comment]
@sgeierAsbru 

Please make sure that you are setting the license correctly. If you still face problem, please send your license file via private message in [Aspose forum](https://forum.aspose.com/c/total/7).

Could you please share which Aspose product you are using?

**Comment by sgeierAsbru** [comment]
We are using ASPOSE Slides. Below is a link to the code we are using. After a little more testing, I found that it works when I am debugging locally, but when we push it out to the server we get the watermark.  Is there a special installation that needs to be done on the server?

https://drive.google.com/file/d/1anNOT7stMhvaj2oUnFwQDlIRG6z0YsL-/view?usp=sharing

**Comment by sgeierAsbru** [comment]
The file upload in the private message is not working. I get this:

Sorry, there was an error uploading that file. Please try again.

**Comment by sgeierAsbru** [comment]
Even if I try to do another google drive link in the private messages, it sits in a spinning Saving status and does not complete.

**Comment by andreypotapovaspose** [comment]
@sgeierAsbru,
Please do not share license files openly. They can be blacklisted if someone else wants to use them too. The the license will not work. You should remove the license files from the archive above. I am already working on your problem.

**Comment by andreypotapovaspose** [comment]
@sgeierAsbru,
Your license file is valid. It looks like the license was not applied on your server.

> Is there a special installation that needs to be done on the server?

No additional actions are required to use the license other than calling the method `License.SetLicense`.
Documents: [Licensing](https://docs.aspose.com/slides/net/licensing/)

**Comment by sgeierAsbru** [comment]
Does it need to be anywhere other than the folder the executable is in?

**Comment by andreypotapovaspose** [comment]
@sgeierAsbru,
You can store the file somewhere in one place. You then need to provide the correct path to the file. Alternatively, you can store the license data into a string variable in your code.

**Comment by sgeierAsbru** [comment]
Do you have example code of how to store it as a string variable. I think that would be a great way to go.

Thanks!
Shanea

**Comment by sgeierAsbru** [comment]
Got it to work that way. Thanks so much for your help!

**Comment by andreypotapovaspose** [comment]
@sgeierAsbru,
Thank you for using Aspose.Slides.
