### ISSUE TITLE
Providing Aspose central in my company for several applications

### ISSUE THREAD

**Issue by FabianDATEV** [aspose-free-consulting/projects#22]
Hello Support Team,
my company is currently using Aspose total for .NET as "Site OME" license.
We have several applications which are using Aspose. We have the problem that when we like to update to a newer version of Aspose every application needs to rebuild again against the new Aspose dll. The reason for that is, that Aspose changes the assembly version every time. That causes a huge amount of organisation and effort to update Aspose in our company and we are not able to react fast for possible security issues. What we like to do is, writing a wrapper with a stable assembly version which uses the Aspose functionality and provides this functionality to our applications **(only to our own applications)**. When we have to update Aspose, we only have to update Aspose for this wrapper instead of in all our applications. This wrapper and the Aspose Dlls will be deployed at our customers systems.
I will provide you a pdf which shows two possible scenarios to accomplish our needs ("Possible variants for Aspose usage.pdf"). One scenario uses the Global Assembly Cache, the second the program directory of our applications.
**My question is, are we allowed with our license to implement one or both of those scenarios?**
If not, maybe you have an other suggestion how we can accomplish this goal.
I already read the pricing table and came to the conclusion that a metered license is not possible for us because our developers don't have a direct internet connection in our company and not every customer has necessary a direct internet connection ether. 
Thank you in advance for your help.
Best regards ,
Fabian

Atachement:
[Possible variants for Aspose usage.pdf](https://github.com/aspose-free-consulting/projects/files/3977840/Possible.variants.for.Aspose.usage.pdf)

**Comment by shahzad-latif** [comment]
@FabianDATEV 

Thanks for getting in touch. Basically, what I understand from your above post is that you guys want to create a separate project which uses all of our APIs and then exposes your own API (interface) for your applications and when newer versions of Aspose APIs are released you'll have to update only one project (Your own interface) and then use that with all your applications. And your basic concern is if this is allowed as per our license terms? Am I right?

**Comment by FabianDATEV** [comment]
Hello shahzad-latif,
thank's for your fast reply.
Yes that's correct.

**Comment by shahzad-latif** [comment]
@FabianDATEV 

In that case, I would recommend you to post the same query in our Purchase forum where our business team will guide you appropriately: https://forum.aspose.com/c/purchase

I would have moved this query to the same forum but I do not have your email address. So it would be great if you could please post it in our Purchase forum and our team will guide you accordingly.
