### ISSUE TITLE
While accessing SharePoint online Word document I am facing an issue if the file is already opened by some users

### ISSUE THREAD

**Issue by Sankarp1974** [aspose-free-consulting/projects#220]
I am working with Sharepoint online word documents through c# code with .NET Framework 6.0
When I try to use the feature acceptTrackChanges (AcceptAllRevisions) I am facing an issue as follows

Below are the steps that i used to incorporate the feature AcceptAllRevisions
1) Connect with SharePointOnline
2) Download the particular word document to a local folder
3) Apply AcceptAllrevisions 
4) upload the file back to Sharepoint portal
When i try to execute the step 4 I am facing an error if any users opened that particular document through office online 
How to unlock the file which is locked by the user during performing step 4

Request your support thanks

**Comment by AsposeDmitrySokolov** [comment]
@Sankarp1974 you should to check-out file and perform chick-in after editing.
MS site has common [descriptions](https://support.microsoft.com/en-us/office/check-out-check-in-or-discard-changes-to-files-in-a-sharepoint-library-7e2c12a9-a874-4393-9511-1378a700f6de) about these operations. Also CSOM has appropriate methods: 
[CheckOut](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/ee542611(v=office.15))
[CheckIn](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/ee537383(v=office.15))
