### ISSUE TITLE
Combine Word, PDF, Web documents using PHP REST API This API is not working and showing ERROR: 500

### ISSUE THREAD

**Issue by saleem005** [aspose-free-consulting/projects#221]
I am working on small task where, I have to merge multiple .docx files. So, for that , I am using "Combine Word, PDF, Web documents using PHP REST API" API but it is not working in my project and also on your web IDE and showing the error : 500.

**Comment by saleem005** [comment]
I am trying to merge docx files but it is not merging. If it is
possible please send file merging code
that can merge multiple docx files into a single docx file.

**Comment by tilalahmad** [comment]
@saleem005

The above shared code appends two Word documents and the following code appends four Word documents. You can amend this code to append as many documents as you like. If you still face any issues, then please share your sample code and the error message for investigation.


```
<?php

require_once('D:\xampp\htdocs\aspose-words-cloud-php-master\vendor\autoload.php');

//TODO: Get your ClientId and ClientSecret at https://dashboard.aspose.cloud (free registration is required).

$ClientSecret="xxxxxxxxxxxxxxxxxxxxxxxxx";
$ClientId="xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";

// Initiate Aspose.Words Cloud API
$wordsApi = new Aspose\Words\WordsApi($ClientId,$ClientSecret);


try {

        $requestDocument = "data/Input1.docx";
        $localFile = "data/Input2.docx";
        $remoteFileName = "Input2.docx";
	$localFile1 = "data/Input3.docx";
        $remoteFileName1 = "Input3.docx";
	$localFile2 = "data/Input4.docx";
        $remoteFileName2 = "Input4.docx";	
	$remoteDataFolder = "Temp";

        //Upload documents to cloud Storage
	$uploadRequest = new Aspose\Words\Model\Requests\UploadFileRequest($localFile,$remoteDataFolder."/".$remoteFileName,null);
	$wordsApi->uploadFile($uploadRequest);
	$uploadRequest1 = new Aspose\Words\Model\Requests\UploadFileRequest($localFile1,$remoteDataFolder."/".$remoteFileName1,null);
	$wordsApi->uploadFile($uploadRequest1);
	$uploadRequest2 = new Aspose\Words\Model\Requests\UploadFileRequest($localFile2,$remoteDataFolder."/".$remoteFileName2,null);
	$wordsApi->uploadFile($uploadRequest2);
	
	//Create DocumentEntry for list
        $requestDocumentListDocumentEntries0 = new Aspose\Words\Model\DocumentEntry(array(
            "href" => $remoteDataFolder . "/" . $remoteFileName,
            "import_format_mode" => "KeepSourceFormatting",
        ));
	$requestDocumentListDocumentEntries1 = new Aspose\Words\Model\DocumentEntry(array(
            "href" => $remoteDataFolder . "/" . $remoteFileName1,
            "import_format_mode" => "KeepSourceFormatting",
        ));
        $requestDocumentListDocumentEntries2 = new Aspose\Words\Model\DocumentEntry(array(
            "href" => $remoteDataFolder . "/" . $remoteFileName2,
            "import_format_mode" => "KeepSourceFormatting",
        ));
	
        $requestDocumentListDocumentEntries = [
            $requestDocumentListDocumentEntries0,$requestDocumentListDocumentEntries1,$requestDocumentListDocumentEntries2,
        ];
        $requestDocumentList = new Aspose\Words\Model\DocumentEntryList(array(
            "document_entries" => $requestDocumentListDocumentEntries,
        ));
	
	//Append Word Documents
        $request = new Aspose\Words\Model\Requests\AppendDocumentOnlineRequest(
            $requestDocument,
            $requestDocumentList,
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            NULL
        );

        $result = $wordsApi->appendDocumentOnline($request);		
    
} catch (Exception $e) {
    echo  "Something went wrong: ",  $e->getMessage(), "\n";
    PHP_EOL;
}

?>
```

**Comment by saleem005** [comment]
Here is my sample code that I am using to merge two files. But it is not
merging them into one file, only returning the second file. I need to merge
two files and store them in local storage.
Please help me to find out the solution.
Thank you

public function mergrFile(){
    $ClientSecret="";
    $ClientId="";

        $wordsApi = new WordsApi($ClientId,$ClientSecret);


        try {

            $requestDocument = "public/HS003b - Basic Health and
Safety Rules Induction (1).docx";
            $localFile = "public/TestingFile.docx";
            $remoteFileName = "Input2.docx";
            $remoteDataFolder = "Temp";


            $uploadRequest = new
UploadFileRequest($localFile,$remoteDataFolder."/".$remoteFileName,null);
            $wordsApi->uploadFile($uploadRequest);

            $requestDocumentListDocumentEntries0 = new DocumentEntry(array(
                "href" => $remoteDataFolder . "/" . $remoteFileName,
                "import_format_mode" => "KeepSourceFormatting",
            ));
            $requestDocumentListDocumentEntries = [
                $requestDocumentListDocumentEntries0,
            ];
            $requestDocumentList = new DocumentEntryList(array(
                "document_entries" => $requestDocumentListDocumentEntries,
            ));
            $request = new AppendDocumentOnlineRequest(
                $requestDocument,
                $requestDocumentList,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            );

            $result = $wordsApi->appendDocumentOnline($request);
            dd($result);
        } catch (Exception $e) {
            echo  "Something went wrong: ",  $e->getMessage(), "\n";
            PHP_EOL;
        }
}

**Comment by saleem005** [comment]
The following code is also not working and returning error:500 on your web
site.
use Aspose\Words\WordsApi;

$wordsApi = new WordsApi('####-####-####-####-####', '##################');

$document = "HS003b - Basic Health and Safety Rules Induction (1).docx";

// Load a document to append from the Cloud storage.
$mergeDocument = new DocumentEntry(array(
    "href" => "HS003a - Agency Worker Checklist.doc",
    "import_format_mode" => "KeepSourceFormatting",
));
$documentEntries = [ $mergeDocument, ];
$documentList = new DocumentEntryList(array(
    "document_entries" => $documentEntries,
));
$appendDocumentOnline = new AppendDocumentOnlineRequest(
    $document, $documentList, NULL, NULL, NULL, NULL, NULL, NULL
);
$wordsApi->appendDocumentOnline($appendDocumentOnline);

**Comment by saleem005** [comment]
Now I'm also getting another error.

[403] Error connecting to the API (
https://api.aspose.cloud/v4.0/words/encryption/publickey)
