### ISSUE TITLE
I want to create/build 

### ISSUE THREAD

**Issue by ksleep** [aspose-free-consulting/projects#223]
我使用html转word的方式导出，我的html里面含有img，但导出word之后 word里面的图片破掉了x 不显示，
在本地代码调试 和iis能正常导出并显示，但在部署在服务器的iis上图片就会破掉，请问有什么解决方法
![image](https://user-images.githubusercontent.com/43952661/176809167-b44180c6-a566-448d-9ff0-5eb3cc8dc45b.png)

**Comment by AlexNosk** [comment]
@ksleep 最有可能的是，该图像无法访问，并且 Aspose.Words 无法下载它。 您可以尝试使用 [IResourceLoadingCallback](https://reference.aspose.com/words/net/aspose.words.loading/iresourceloadingcallback/) 来控制外部资源的加载方式。
