### ISSUE TITLE
exception on Ishape.setY 

### ISSUE THREAD

**Issue by jxy604803280** [aspose-free-consulting/projects#224]
![image](https://user-images.githubusercontent.com/7273362/177026017-00d5acc1-bdb9-4a89-8fc7-aa99c4a9456f.png)
![image](https://user-images.githubusercontent.com/7273362/177026039-7eae914c-e629-450b-bf85-d88256dd733e.png)
the exception happened unexpectedly，and i do not know how to fix  it, but when i retry , it works normal

**Comment by jxy604803280** [comment]
![image](https://user-images.githubusercontent.com/7273362/177032409-bdd50a30-9dac-4901-93c5-c48b63d75e77.png)
not only set occurs exception, get method also occurs sometimes

**Comment by andreypotapovaspose** [comment]
@jxy604803280,
Please check your results using the latest version of [Aspose.Slides](https://releases.aspose.com/slides/java/) if it is possible. If the issue persists, please share the following data and information:

- presentation file
- code examples that reproduce the errors
- OS version where the code was executed
- JDK version in your app
- Aspose.Slides version you used
