### ISSUE TITLE
Duplicate images are saving for outlook email message

### ISSUE THREAD

**Issue by virenderconduent** [aspose-free-consulting/projects#225]
Hi Team,

We are getting multiple TIFF images for the one .msg having JPEG as attachment, the output saves the msg body to a TIFF which contains JPEG as well in third frame. However we have another logic where we are checking the attachments of msg and then converting it, this causes duplicate for the JPEG, can you please help?

Attached is a sample code, since portal is not allowing to attach .msg, please let me know if I can share over email?
[sampleCode.txt](https://github.com/aspose-free-consulting/projects/files/9060713/sampleCode.txt)

**Comment by tahir-manzoor** [comment]
@virenderconduent 

Could you please share your input email messages for which you are facing this issue? Please also share the screenshot of the issue. We will investigate the issue and provide you more information on it.

**Comment by virenderconduent** [comment]
@tahir-manzoor : Email server is not allowing it to be delivered to you so not able to send it, is there any other way to share?

**Comment by virenderconduent** [comment]
![Sample-jpg-image-5mb](https://user-images.githubusercontent.com/102535926/177949368-2257223a-ab71-420c-89e3-b6fedec0d413.jpg)
this is the email which is attached to the outlook email item I have mentioned

**Comment by virenderconduent** [comment]
[FW Large excel and big JPG file.zip](https://github.com/aspose-free-consulting/projects/files/9070277/FW.Large.excel.and.big.JPG.file.zip)
anyways this got attached after compressing

**Comment by tahir-manzoor** [comment]
@virenderconduent 

You are using Aspose.Email and Aspose.Words in evaluation mode. Please get [30 days temporary license](https://purchase.aspose.com/temporary-license) and apply it before converting MSG to TIFF. 

If problem still remains, please create a standalone console application (source code without compilation errors) that helps us to reproduce your problem on our end and attach it here for testing. 

You may post the details in our [free support forum](https://forum.aspose.com/c/email/12).

**Comment by virenderconduent** [comment]
@tahir-manzoor : Please find attached code and sample images and output in zip, this is from the permanent license we have.
Code:  SampleApp*****.zip
Sample : FW.Large.excel.and.big.JPG.file.zip

[SampleAppEmailConvert.zip](https://github.com/aspose-free-consulting/projects/files/9081172/SampleAppEmailConvert.zip)
[FW Large excel and big JPG file.zip](https://github.com/aspose-free-consulting/projects/files/9081177/FW.Large.excel.and.big.JPG.file.zip)


[FW Large excel and big JPG file.zip](https://github.com/aspose-free-consulting/projects/files/9081095/FW.Large.excel.and.big.JPG.file.zip)

**Comment by virenderconduent** [comment]
Hi,

This is done, please check the ticket once.

Thanks,
Virender

From: Tahir Manzoor ***@***.***>
Sent: Friday, July 8, 2022 11:41 PM
To: aspose-free-consulting/projects ***@***.***>
Cc: Kumar, Virender ***@***.***>; Mention ***@***.***>
Subject: [External] - Re: [aspose-free-consulting/projects] Duplicate images are saving for outlook email message (Issue #225)

This email is from an external source.  Use caution responding to it, opening attachments or clicking links.


@virenderconduent<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvirenderconduent&data=05%7C01%7Cvirender.kumar%40conduent.com%7C98bd0525f88c46f76e0008da610d27ff%7C1aed4588b8ce43a8a775989538fd30d8%7C0%7C0%7C637929006395657887%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XIcf7jB0HrYiCrFq393Lmn%2B65YwlKWlSYHLUZjk%2BrP0%3D&reserved=0>

You are using Aspose.Email and Aspose.Words in evaluation mode. Please get 30 days temporary license<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpurchase.aspose.com%2Ftemporary-license&data=05%7C01%7Cvirender.kumar%40conduent.com%7C98bd0525f88c46f76e0008da610d27ff%7C1aed4588b8ce43a8a775989538fd30d8%7C0%7C0%7C637929006395657887%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9fVnVQSKji3Uot3hDCr8dSOoMEdLxwnFKeIVXe%2F6nOE%3D&reserved=0> and apply it before converting MSG to TIFF.

If problem still remains, please create a standalone console application (source code without compilation errors) that helps us to reproduce your problem on our end and attach it here for testing.

You may post the details in our free support forum<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforum.aspose.com%2Fc%2Femail%2F12&data=05%7C01%7Cvirender.kumar%40conduent.com%7C98bd0525f88c46f76e0008da610d27ff%7C1aed4588b8ce43a8a775989538fd30d8%7C0%7C0%7C637929006395657887%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zTRfYiBuQPXmGmav%2B4u5L5xeWjkgwICETHzyNjBJzfg%3D&reserved=0>.

-

**Comment by virenderconduent** [comment]
ZIP contains a TIFF which have 3 frames and the last frame contains the view from JPEG and then when the attachment code runs it again downloads the same JPEG, this makes it duplicate and the multi-tiff will be converted to single tiff later on and we have no way to know which image is duplicate if we have multiple images attached to such outlook item
