### ISSUE TITLE
I want to create/build 

### ISSUE THREAD

**Issue by ksleep** [aspose-free-consulting/projects#229]
DocumentBuilder build = new DocumentBuilder(doc);   
Paragraph paragraphs = build.InsertParagraph();
                build.MoveToHeaderFooter(HeaderFooterType.FooterPrimary);
                Run run = new Run(doc, "");
                build.Write("Page ");
                build.InsertField("PAGE", "");
                // Add any custom text
                build.Write(" of ");
                build.InsertField("NUMPAGES", "");
                run.Font.Size = 10.5;
                run.Font.Name = "Calibri";
如此 我为页尾设置size  name都没有生效。请问页尾设置字体的方式不对吗？如果不对应该怎样设置

**Comment by AlexNosk** [comment]
@ksleep 您将字体一指定为新创建的`Run`节点，但不插入到文档中。 由于您使用 DocumentBuilder 插入内容，因此您应该指定 DocumentBuilder 的字体。 请看下面的代码：
```cs
DocumentBuilder build = new DocumentBuilder(doc);
build.MoveToHeaderFooter(HeaderFooterType.FooterPrimary);
build.Font.Size = 10.5;
build.Font.Name = "Calibri";
build.Write("Page ");
build.InsertField("PAGE", "");
// Add any custom text
build.Write(" of ");
build.InsertField("NUMPAGES", "");
```

**Comment by ksleep** [comment]
已解决，感谢
