### ISSUE TITLE
REF : Issue 190 - Emails are getting exception while using sample code

### ISSUE THREAD

**Issue by virenderconduent** [aspose-free-consulting/projects#235]
Hi Team,

We are getting an exception while trying to convert a MSG to TIFF using the sample code shared with us with ticket/issue 190

https://github.com/aspose-free-consulting/projects/issues/190

MailMessage msg = MailMessage.Load(MyDir + "Sample.msg", new MsgLoadOptions());

// Convert MSG to MHTML and save to stream
MemoryStream msgStream = new MemoryStream();
msg.Save(msgStream, SaveOptions.DefaultMhtml);
msgStream.Position = 0;

// Load the MHTML stream using Aspose.Words for .NET and Save the document as TIFF image
Document msgDocument = new Document(msgStream);

foreach (Shape shape in msgDocument.GetChildNodes(NodeType.Shape, true))
    ResizeLargeImage(shape);
msgDocument.Save(MyDir + "Sample.tiff", SaveFormat.Tiff);

public static void ResizeLargeImage(Aspose.Words.Drawing.Shape image)
{
    // Return if this shape is not an image.
    if (!image.HasImage)
        return;

    // Calculate the free space based on an inline or floating image. If inline we must take the page margins into account.
    PageSetup ps = image.ParentParagraph.ParentSection.PageSetup;
    double freePageWidth = image.IsInline ? ps.PageWidth - ps.LeftMargin - ps.RightMargin : ps.PageWidth;
    double freePageHeight = image.IsInline ? ps.PageHeight - ps.TopMargin - ps.BottomMargin : ps.PageHeight;

    ImageSize size = image.ImageData.ImageSize;
    Boolean exceedsMaxPageSize = size.WidthPoints > freePageWidth || size.HeightPoints > freePageHeight
        || image.Width > freePageWidth || image.Height > freePageHeight;

    if (exceedsMaxPageSize)
    {
        // Calculate the ratio to fit the page size based on which side is longer.
        Boolean widthLonger = (size.WidthPoints > size.HeightPoints);
        double ratio = widthLonger ? freePageWidth / size.WidthPoints : freePageHeight / size.HeightPoints;

        // Set the new size.
        image.Width = size.WidthPoints * ratio;
        image.Height = size.HeightPoints * ratio;
    }
}

can you please recheck this code, It seems that for some emails (a sample email item is attached) this is throwing exception as below:

System.ArgumentOutOfRangeException
HResult=0x80131502
Message=Shape width cannot be greater than 1584 points.
Parameter name: value
Source=Aspose.Words
StackTrace:
at G7.a(ShapeBase a, Double b, Boolean c, String d)
at Aspose.Words.Drawing.ShapeBase.xc(Double a, Boolean b)
at Aspose.Words.Drawing.ShapeBase.set_Height(Double value)

[SampleEmailItem.zip](https://github.com/aspose-free-consulting/projects/files/9191512/SampleEmailItem.zip)

**Comment by AlexNosk** [comment]
@virenderconduent  The problem occurs because `AspectRatioLocked` is set for the problematic shape and when you set height of the shape, it's width is recalculated to preserve the aspect ratio and the recalculated width exits the maximum allowed width of shape in MS Word (1584 points). As a workaround you can disable this options before setting shape size:
```cs
image.AspectRatioLocked = false;
```
Also, I think your code does not do what you expect since you are using size of the actual image, which can be already scaled in the document. I think you should modify your code to use shape size insted:
```cs
public static void ResizeLargeImage(Aspose.Words.Drawing.Shape image)
{
    // Return if this shape is not an image.
    if (!image.HasImage || !image.IsTopLevel)
        return;

    // Calculate the free space based on an inline or floating image. If inline we must take the page margins into account.
    PageSetup ps = image.ParentParagraph.ParentSection.PageSetup;
    double freePageWidth = image.IsInline ? ps.PageWidth - ps.LeftMargin - ps.RightMargin : ps.PageWidth;
    double freePageHeight = image.IsInline ? ps.PageHeight - ps.TopMargin - ps.BottomMargin : ps.PageHeight;


    bool exceedsMaxPageSize = image.Width > freePageWidth || image.Height > freePageHeight;

    if (exceedsMaxPageSize)
    {
        // Calculate the ratio to fit the page size based on which side is longer.
        bool widthLonger = (image.Width > image.Height);
        double ratio = widthLonger ? freePageWidth / image.Width : freePageHeight / image.Height;

        // Set the new size.
        image.Width = image.Width * ratio; ;
        image.Height = image.Height * ratio; ;
    }
}
```

**Comment by virenderconduent** [comment]
Let me check and confirm because I think the earlier code was given for one of the requirement we had and need to see if it is still going good or not with this new code of resizeLargeImage method

**Comment by virenderconduent** [comment]
@AlexNosk : this workaround (image.AspectRatioLocked = false;) is working fine for us but not the method changes.

Seems like if we have images in body of email then the frame size squeeze the content to fit in and that's what making the images look blurry and information could not be read. Anyways we will take this workaround right now and test few more items to see how it goes
