### ISSUE TITLE
 aspose.cells version 22.8    xls to pdf   Exception:Argument_InvalidOffLen    

### ISSUE THREAD

**Issue by wangchengwen** [aspose-free-consulting/projects#241]
com.aspose.cells.CellsException: Argument_InvalidOffLen
	at com.aspose.cells.zcmh.a(Unknown Source)
	at com.aspose.cells.zcmh.a(Unknown Source)
	at com.aspose.cells.zki.a(Unknown Source)
	at com.aspose.cells.Workbook.a(Unknown Source)
	at com.aspose.cells.Workbook.save(Unknown Source)
	at com.aspose.cells.Workbook.save(Unknown [Source)[](url)](u
[工作簿3 - 副本.xlsx](https://github.com/aspose-free-consulting/projects/files/9306858/3.-.xlsx)
rl)

**Comment by amjad-sahi** [comment]
@wangchengwen,

Thanks for the template file.

Please notice, I am able to reproduce the issue as you mentioned by converting your template XLSX file to PDF. I got an exception "java.lang.OutOfMemoryError: Java heap space" on rendering to PDF file format:
e.g.
**Sample code:**
```java
Workbook workbook = new Workbook("f:\\files\\3.-.xlsx");
workbook.save("f:\\files\\out1.pdf"); 
```

I have logged a ticket with an id "CELLSJAVA-44842" for your issue. We will look into it soon.

Once we have an update on it, we will let you know here.

**Comment by amjad-sahi** [comment]
@wangchengwen,

This is to inform you that your issue has been resolved now. The fix will be included in our upcoming release (Aspose.Cells v22.9) scheduled in the second week of September 2022. You will also be notified when the next version is released.

Keep in touch.

**Comment by amjad-sahi** [comment]
@wangchengwen,

Please try our latest version, Aspose.Cells Aspose.Cells for Java v22.9 ([Download](https://releases.aspose.com/cells/java/) | [Maven](https://repository.aspose.com/cells/)). Your issue is fixed in it. 

Let us know your feedback.
