### ISSUE TITLE
Aspose.HTML Out of memory exception

### ISSUE THREAD

**Issue by E6AM** [aspose-free-consulting/projects#242]
We were looking for an HTML to PDF converter for a huge HTML string builder object. As Aspose.HTML has this capability, we tried generating a sample doc of 20 pages pdf without the PageSetup margin property of pdfSaveOptions.
It was successful but when we tried it by applying page setup, we are getting out of memory exception. PFA, attached error screenshot and code snippet with exception line of code and comments.

Questions:
1. Is this the correct way of defining the page margins? 
2. Can we use Aspose.HTML Converter.ConvertHTML capability to generate large pdf document(~80,000 pages)
3. If not, Are there any capabilities in Aspose to generate a large pdf document from HTML string builder either as a stream or pdf document?

![image](https://user-images.githubusercontent.com/99254981/184126106-b575d27e-a52e-4dfc-ba04-a93cf13e9726.png)

Code:
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Aspose.Html;
using Aspose.Html.Converters;
using Aspose.Html.Drawing;
using Aspose.Html.Saving;

namespace Aspose.HTML
{
    class Program
    {
        static void Main(string[] args)
        {
            SetLicense.SetAsposeHtmlLicenseFromStream();
            ConvertHTMLToPDF();

        }

        private static void ConvertHTMLToPDF()
        {
            try
            {
                StringBuilder stringBuilder = new StringBuilder(); // in actual code we are filling this stringBuilder with huge HTMl string.
                var htmlFilePath = @"C:\Workspace\Repos\B2I.CLRS\Projects\Presentation.Web.Api\App_Data\TestDf_c1.html";
                var pdfFilePath = @"C:\Workspace\Repos\B2I.CLRS\Projects\Presentation.Web.Api\App_Data\TestDf_c1.pdf";

                using (System.IO.StreamWriter file = new System.IO.StreamWriter(htmlFilePath))
                {
                    file.Write(stringBuilder);
                }

                var htmlDocument = new HTMLDocument(htmlFilePath);
                // Initialize PdfSaveOptions 
                var pdfSaveOptions = new PdfSaveOptions()
                {
                    HorizontalResolution = 200,
                    VerticalResolution = 200,
                    JpegQuality = 100,
                };

                //This line causes the outof memory exception even for as small as 20 pages pdf document. if commented, pdf generates without any issue
                pdfSaveOptions.PageSetup.AnyPage = new Aspose.Html.Drawing.Page(new Margin(40, 40, 40, 40));
                // Convert HTML to PDF
                Console.WriteLine("Started PDf conversion from HTML document to PDF local drive");
                Converter.ConvertHTML(htmlDocument, pdfSaveOptions, pdfFilePath);
                Console.WriteLine("Completed PDf conversion from HTML document to PDF local drive");

            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }
    }
}

**Comment by asadalikhan90** [comment]
@E6AM 

Would you kindly share your sample HTML in .txt or .zip format with us so that we can test the scenario in our environment and address it accordingly?
