### ISSUE TITLE
Finding length of a MergeField which populates 2 lines

### ISSUE THREAD

**Issue by tomEploy** [aspose-free-consulting/projects#243]
In my software i want to create a div surrounding the whole of a merge field which i can do by  using the LayoutCollector of the Field Start and End of the Merge Field. This then returns the X and Y of each position.

However, this fails if the mergefield is over 2 lines

Scenario-
Want to add a Div around a merge field

Issue-
Fails if the MergeField goes over 2 lines

Code Sample-
In Visual Studio create a simple Web Forms Web Application - add the Aspose Words dlls for references  Also overwite the default file with one attached in zip
In the code sample attached Lines - 170 : 190 (Default.aspx) that does the logic to figure out size of field 
FilePath will need to change on line 34 to point to where ever solution is running from

[Test.docx](https://github.com/aspose-free-consulting/projects/files/9315935/Test.docx)
[Default.aspx.designer.zip](https://github.com/aspose-free-consulting/projects/files/9315936/Default.aspx.designer.zip)

**Comment by AlexNosk** [comment]
@tomEploy To calculate rectangle of multiline mergefield you should create a union of rectangles of all entities between start and end of the corresponding field. I have create a small demonstration code:
```cs
Document doc = new Document(@"C:\Temp\Test.docx");
LayoutCollector collector = new LayoutCollector(doc);
LayoutEnumerator enumerator = new LayoutEnumerator(doc);

// Draw a rectangle around mergefields.
List<Field> mergefields = doc.Range.Fields.Where(f => f.Type == FieldType.FieldMergeField).ToList();
foreach (Field f in mergefields)
{
    enumerator.Current = collector.GetEntity(f.Start);
    RectangleF rect = enumerator.Rectangle;

    // Union with all entitis rectangles between start and end
    // In case of multi-line mergefield the loop will exit on MoveNext condition
    // becasue we reach the end of line.
    object endEntity = collector.GetEntity(f.End);
    while ((enumerator.Current != endEntity) && enumerator.MoveNext())
        rect = RectangleF.Union(rect, enumerator.Rectangle);

    // Move to end entity and union with it's rectangle.
    enumerator.Current = endEntity;
    rect = RectangleF.Union(rect, enumerator.Rectangle);

    // Add the resulting shape to the first paragrah.
    // This is for demonstraction purposes only.
    Shape rectShape = CreateRectangleShapeAroundField(f, rect);
    doc.FirstSection.Body.FirstParagraph.AppendChild(rectShape);
}

doc.Save(@"C:\Temp\out.docx");
```
```cs
private static Shape CreateRectangleShapeAroundField(Field f, RectangleF rect)
{
    Shape rectShape = new Shape(f.End.Document, ShapeType.Rectangle);
    rectShape.Width = rect.Width;
    rectShape.Height = rect.Height;

    rectShape.WrapType = WrapType.None;
    rectShape.RelativeHorizontalPosition = RelativeHorizontalPosition.Page;
    rectShape.RelativeVerticalPosition = RelativeVerticalPosition.Page;
    rectShape.Top = rect.Top;
    rectShape.Left = rect.Left;

    rectShape.Stroke.Color = Color.Red;
    rectShape.Stroke.Weight = 1;
    rectShape.Filled = false;

    return rectShape;
}
```
Here is the result:
![image](https://user-images.githubusercontent.com/31235892/184469617-c8ba48be-4e3d-40ac-b300-f237023e2707.png)
As you can see rectangle around multi-line mergefield is calculated properly.

**Comment by tomEploy** [comment]
Thank you for your solution
