### ISSUE TITLE
I want convert xlsb to csv format with semicolon or other type of separator 

### ISSUE THREAD

**Issue by Chandrappaoj** [aspose-free-consulting/projects#245]
Hi Team,
I want convert xlsb to csv format with semicolon or other type of separator using aspose.cells. kindly help me with this
Thanks,
Chandru

**Comment by amjad-sahi** [comment]
@Chandrappaoj,

See the following sample code on how to convert an XLSB file to CSV file format with semicolon as separator, you may specify your desired separator using `Separator` attribute of TxtSaveOptions:
e.g.
**Sample code:**
```cs
TxtSaveOptions opts = new TxtSaveOptions()
{
      Separator = ';',
};
Workbook workbook = new Workbook("sample.xlsb");
Worksheet worksheet = workbook.Worksheets[0];
workbook.Save("sample_out.csv", opts); 
```
Hope,  this  helps a bit.
