### ISSUE TITLE
creating sections from html div/span

### ISSUE THREAD

**Issue by johny2nd** [aspose-free-consulting/projects#247]
I have converted a pdf to html and saved formatting. The html is not laid out into many divs and span classes, it did not create any table tags or p tags. I used IEnumerate to create list of the nodes. From there I need to figure out a way to create sections i.e. header, body, etc... using the innertext of the html tags. I would like to create a start point using inner text and end point using inner text to create the sections. Using class ID is not possible because many of the use the same ID. Do I need to create new lists of nodes for each section?

**Comment by AlexNosk** [comment]
@johny2nd Could you please specify which of Aspose products you use for conversion from PDF to HTML? Also, please attach your input PDF and output HTML documents here for testing. We will check the issue and provide you more information.
You should also note that PDF and HTML documents are quite different in document structure and it is not always possible to perform accurate conversion from PDF to HTML.

**Comment by johny2nd** [comment]
im using the Aspose total family among other libraries. the conversion isnt the problem. but the HTML looks like 
`<body>
		<div class="stl_ stl_02">
			<div class="stl_03">
				<object data="BAE_IFF230-232PDFtoHTML_files/img_02.svg" type="image/svg+xml" class="stl_04" style="position:absolute; width:51em; height:66em;">
					<embed src="BAE_IFF230-232PDFtoHTML_files/img_02.svg" type="image/svg+xml" />
				</object>
			</div>
			<div class="stl_view">
				<div class="stl_05 stl_06">
					<div class="stl_01 stl_07" style="left:32.1699em;top:3.019em;"><span class="stl_08 stl_09 stl_10" style="word-spacing:0.0044em;">Document:</span><span class="stl_08 stl_09 stl_11" style="word-spacing:0.5133em;">&nbsp;</span><span class="stl_08 stl_09 stl_12">10 &nbsp;</span></div>
					<div class="stl_01 stl_07" style="left:37.8099em;top:4.1689em;"><span class="stl_08 stl_09 stl_13" style="word-spacing:0.5039em;">text 1 &nbsp;</span></div>
					<div class="stl_01 stl_07" style="left:37.9702em;top:5.3188em;"><span class="stl_08 stl_09 stl_14" style="word-spacing:0.5128em;">text 2 &nbsp;</span></div>
					<div class="stl_01 stl_07" style="left:6em;top:7.2187em;"><span class="stl_08 stl_09 stl_14" style="word-spacing:0.2507em;">text 3</span><span class="stl_08 stl_09 stl_11" style="word-spacing:0.0103em;">&nbsp;</span><span class="stl_08 stl_09 stl_15">text 4 &nbsp;</span></div>
					<div class="stl_01" style="left:30.5097em;top:8.3688em;"><span class="stl_16 stl_17 stl_18" style="word-spacing:0.0027em;">text 5 &nbsp;</span></div>
					<div class="stl_01" style="left:6em;top:9.3091em;"><span class="stl_16 stl_17 stl_19" style="word-spacing:0.0025em;">text 6 &nbsp;</span></div>
					<div class="stl_01" style="left:6em;top:11.1988em;"><span class="stl_16 stl_17 stl_20" style="word-spacing:-0.008em;">text 7 &nbsp;</span></div>
					<div class="stl_01" style="left:6em;top:12.1488em;"><span class="stl_16 stl_17 stl_21">text 8&nbsp;</span></div>
					<div class="stl_01" style="left:6em;top:13.089em;"><span class="stl_16 stl_17 stl_22">text 9 &nbsp;</span></div>
		`

what i am wanting to do is use the actual text from the nodes to create a section or range and be able to name it as a section so i can iterate through its own without having to iterate through the whole doc again. so like in the span classes
range1 = document-text3
range 2 = text 4-text8

**Comment by AlexNosk** [comment]
@johny2nd Aspose.Total includes all Aspose products and it is not clear what exact product you use for conversion. Could you please share your input and full output document (zip it and attach here)? Also please provide code you use for conversion.

**Comment by johny2nd** [comment]
I cannot share the files. I used the PDF to HTML conversion Aspose PDF. I then use INodeIterator to iterate through each line of the html document. I am simply just trying to use innertext to define the beginning of a section and a different innertext to define the end of the section.

**Comment by asadalikhan90** [comment]
@johny2nd 

It is difficult to control everything like tags generation during PDF to HTML conversion in Aspose.PDF. However, we need to further investigate the feasibility of your actual requirement and for that, we need sample PDF document from your side so that we can investigate accordingly. Furthermore, such issues and scenarios are recommended to be reported in our [dedicated support forum](https://forum.aspose.com/c/pdf/10) which is the right place for such discussions. We request you please create a topic there along with your sample file so that we can further proceed to assist you accordingly.
