### ISSUE TITLE
Working with List<Node> c#

### ISSUE THREAD

**Issue by johny2nd** [aspose-free-consulting/projects#248]
I have a List<Node> allNodes that I generated from iterating through an HTML.

 In a new class "headers" I am calling List<Node> allNodes.

in headers I will be creating a new List<Node> or sublist. whichever is best. 

I want to loop through List<Node> allNodes, find all nodes that have text content string "Word" define it as the start point of the new List<Nodes> newList.

I want to do the same thing as above for Regex dashes (@"-{40,}") and define it as the end of List<Nodes> newList. 

It will also need to return all nodes in between "Word" and dashes to the List<Node> newList

This needs to be a loop because there are multiple sections with the same words that will all be added to newList, I will later then split newList even further. 

I am not sure if newList needs to be a LInkedList<Node> or just List<Node> 

Please help prepare code that will satify these needs written in c#

**Comment by AlexNosk** [comment]
@johny2nd Could you please specify which of Aspose produces do you use? Also, please attach your sample input document and expected output. We will check the documents and provide you more information.
