### ISSUE TITLE
I want to create/build 

### ISSUE THREAD

**Issue by johny2nd** [aspose-free-consulting/projects#249]
using aspose.total / pdf for the conversion of a pdf to html. the conversion displays clean but upon further inspection we found that the div elements are actually out of order based on style left/top coordinates. How can we correct this or is there a way to reorder the div elements using c#. I cannot provide sample documents.  attached is a screen shot of the elements out of order. 

![image](https://user-images.githubusercontent.com/109473927/190827116-0e2148e0-ce96-48f8-a095-3e767bbbf062.png)

					<div class="stl_01" style="left:13.5032em;top:16.229em;">
					<div class="stl_01" style="left:30.5014em;top:13.5089em;">
					<div class="stl_01" style="left:30.5014em;top:14.4187em;">
					<div class="stl_01" style="left:30.5014em;top:15.3188em;">
					<div class="stl_01" style="left:30.5014em;top:16.229em;">
					<div class="stl_01" style="left:13.5032em;top:17.1287em;">
					<div class="stl_01" style="left:30.5097em;top:17.1287em;">
					<div class="stl_01" style="left:30.5097em;top:18.039em;">
					<div class="stl_01" style="left:36.5106em;top:17.1287em;">
					<div class="stl_01" style="left:6em;top:18.039em;">
					<div class="stl_01" style="left:6em;top:18.9387em;">
					<div class="stl_01" style="left:6em;top:19.8489em;">
					<div class="stl_01" style="left:8.9963em;top:20.749em;">
					<div class="stl_01" style="left:36.5106em;top:18.039em;">
					<div class="stl_01" style="left:30.5014em;top:18.9387em;">
					<div class="stl_01" style="left:6em;top:21.6487em;">

The conversion of PDF to XML keeps them in order so i tried to then convert from xml to html but am getting the error 
Aspose.Tasks.TasksReadingException: 'The project format is undefined.'

please help fix either problem or both. thanks

**Comment by asadalikhan90** [comment]
@johny2nd 

Would you please share your sample source file(s) along with sample code snippet that you have been using? We will test the scenario in our environment and address it accordingly. Also, it would be better and recommended posting this issue in Aspose.PDF official [support forum](https://forum.aspose.com/c/pdf) which is the right place to discuss and report such issues.
