### ISSUE TITLE
I want to create/build a file converter application that will convert rtf to pdf without using office

### ISSUE THREAD

**Issue by jsdgsevilla** [aspose-free-consulting/projects#25]
I have already tried the trial (with watermark) and it seems to work properly for my application. However, I am wondering if I need to purchase both Aspose.Words and Aspose.PDF or do I just need Aspose.Words

**Comment by shahzad-latif** [comment]
@jsdgsevilla 

Thanks for getting in touch. 

You only need Aspose.Words to convert RTF to PDF: https://docs.aspose.com/display/wordsnet/Saving+a+Document. You can use the temporary license to try without any limitations: https://purchase.aspose.com/temporary-license

Please note that this place is reserved for free consulting projects. For general questions, you may ask in our forums for quick help: https://forum.aspose.com/

I appreciate your cooperation. Thank you.
