### ISSUE TITLE
Word generation with HTML as input

### ISSUE THREAD

**Issue by mark-kan** [aspose-free-consulting/projects#250]
HI!

We are considering a change of our Word generation software and would need to understand how capable Aspose is to render a Word file from HTML.

Enclosing a link here for an example:

https://app.cinode.com/cinode/resume/87958/mark-eng

Thank you in advance.
Mark (CPO @ Cinode)

**Comment by AlexNosk** [comment]
@mark-kan You can easily convert HTML document to Word document using Aspose.Words. Please see our documentation about file formats supported by Aspose,Words:
<https://docs.aspose.com/words/net/supported-document-formats/>
Code is pretty simple:
```cs
Document doc = new Document("in.html");
doc.Save("out.docx");
```
Also, see the following link to learn what HTML features are supported upon loading HTML document:
<https://docs.aspose.com/words/net/load-in-the-html-html-xhtml-mhtml-format/>
