### ISSUE TITLE
How to reset the coordinates and rotation of a node to 0 without changing the geometry.

### ISSUE THREAD

**Issue by yagamiko11** [aspose-free-consulting/projects#251]
[Aspose.3D]
I have a model with non-zero coordinates and I want to reset the coordinates of the model node to 0 while keeping the geometry unchanged in its current position.

Or change the position and rotation of the geometry while keeping the coordinates of the model node constant at 0.

What should I do?

**Comment by yagamiko11** [comment]
It would be great if there is corresponding documentation or C# code, thanks.

**Comment by yagamiko11** [comment]
![image](https://user-images.githubusercontent.com/115074496/194033907-441cf018-a20a-48cb-98c4-8ab032b96220.png)

Like this,resets the coordinates to 0 while keeping the geometry in the center.

**Comment by asadalikhan90** [comment]
@yagamiko11 

We are checking your requirements and will try to create a code example for you to achieve them. We will get back to you soon. Please spare us little time.

**Comment by yagamiko11** [comment]
@asadalikhan90 Is there a solution?

**Comment by asadalikhan90** [comment]
@yagamiko11 

The node Pyramid001 in the attachment FBX file has a non-identity transform, the following code snippet reset the transform to identity(including translation, scaling, and rotation) without changing the geometry, this is done by applying the transformation matrix to the geometry's control point:
```cs
            var file = Scene.FromFile(@"reset_transform.FBX");
            //The node Pyramid001 has some transformation
            var pyramid = file.RootNode.GetChild("Pyramid001");
            var mesh = pyramid.GetEntity<Mesh>();
            // Evaluate the node's global transform matrix and apply it to the control points of the mesh
            var transform = pyramid.EvaluateGlobalTransform(true);
            for(int i = 0; i < mesh.ControlPoints.Count; i++)
            {
                mesh.ControlPoints[i] = transform * mesh.ControlPoints[i];
            }
            //reset the transformation matrix, so translation scaling and rotation will become identity value.
            pyramid.Transform.TransformMatrix = Matrix4.Identity;
            //save the result
            file.Save(@"reset_transform_output.FBX");
```
[reset_transform.zip](https://github.com/aspose-free-consulting/projects/files/9776952/reset_transform.zip)

**Comment by yagamiko11** [comment]
My problem was solved perfectly, nice, thanks.
