### ISSUE TITLE
Creating a file viewer using Aspose.3D

### ISSUE THREAD

**Issue by kevinanscombe** [aspose-free-consulting/projects#252]
I need to add a viewer for glTF and/or UM3 files (and possibly other 3D formats) to an ASP.NET application (4.7.2 Web Forms) or a Vue.js application (ideally both). 

Please can you show me how to do this so I can recommend purchase of Aspose.3D. 

I just need to open and view these files.

Thanks, Kevin Anscombe

**Comment by asadalikhan90** [comment]
@kevinanscombe 

We are preparing an article in the API documentation to explain how this requirement can be achieved. The corresponding task is **THREED-180** and as soon as it is resolved, we will update you. Please spare us some time.

**Comment by asadalikhan90** [comment]
@kevinanscombe 

Please check the documentation as related article has been added in it:

* [Render 3D scene in web page](https://docs.aspose.com/3d/net/render-3d-scene-in-web-page/)
