### ISSUE TITLE
We are trying to load our reporting data onto an xlsm/xlsx file by using an exsiting xls/xslm template having macro and active checkboxes already in place.

### ISSUE THREAD

**Issue by psethu01** [aspose-free-consulting/projects#254]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>
We are trying to load our reporting data onto an xlsm/xlsx file by using an exsiting xls/xslm template having macro and active checkboxes already in place.

< which platform you're working on -- operating system, development environment etc.> 
Linux

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by psethu01** [comment]
I have used Aspose.Cells for Python via .NET so far, it is able to read and write the xlsm file, but doesnt retain active x controls and checkboxes which in turn corrupts my macros which is dependent on it.

**Comment by amjad-sahi** [comment]
@psethu01,

Could you please zip your and attach your input Excel file and output Excel file. Also, share your sample code (runnable) that you are using. We will check your issue soon.
