### ISSUE TITLE
How to create a VertexElementSmoothingGroup

### ISSUE THREAD

**Issue by Blinking1992** [aspose-free-consulting/projects#258]
Aspose.3D How to create a VertexElementSmoothingGroup.
The development documentation does not go into detail.

**Comment by asadalikhan90** [comment]
@Blinking1992 

Would you please share a FBX that has smoothing group? We will try to create a code example for it and add it into API documentation?

**Comment by Blinking1992** [comment]
If I understand correctly, the FBX file does not contain the actual smoothing group data, and according to the available documentation hints, when regenerating the model normals, the normals will be smoothed by the VertexElementSmoothingGroup.
[generate-normal](https://docs.aspose.com/3d/net/generate-normal-data-for-all-meshes-in-a-3d-file/)

For example:
![NL}2T@I4Q}PZOF)F4NS%3QB](https://user-images.githubusercontent.com/115074496/196170802-ad691c2e-047b-430b-aa37-9a2de4527b72.png)
![SUOZAYMEAZN 9(JSR K3L_K](https://user-images.githubusercontent.com/115074496/196170819-27a485e7-e0f6-4f5c-bfae-190af575dc99.png)
![)7_AVJX}7OM6{BNO39FKT1Y](https://user-images.githubusercontent.com/115074496/196170834-13a393b5-1953-4e97-b086-691dd147147b.png)
![YZ18MH)} A2_GL$TLWLMH_S](https://user-images.githubusercontent.com/115074496/196170851-fb7026eb-4bd8-4179-8a89-b8b670d027ad.png)

Suppose I want to implement automatic generation of smooth groups, 45°.

My English is not good, please understand.


[Trunk_Lumber Unsmooth.zip](https://github.com/aspose-free-consulting/projects/files/9800274/Trunk_Lumber.Unsmooth.zip)

[Trunk_Lumber.zip](https://github.com/aspose-free-consulting/projects/files/9800275/Trunk_Lumber.zip)

@asadalikhan90

**Comment by asadalikhan90** [comment]
@Blinking1992 

A task as **THREEDNET-1264** has been logged in our issue tracking system to create code example related to this requirement. We will be updating you once it is added. Also, please note that [Aspose.3D free support forum](https://forum.aspose.com/c/3d) is the right and recommended place to post such scenarios and issues where we can link the ticket ID with thread and you are able to track the progress of the logged task.

**Comment by asadalikhan90** [comment]
@Blinking1992 

Please check the example posted in the API documentation for creating smoothing group for mesh.

* [Programming Sample](https://docs.aspose.com/3d/net/create-smoothing-group-for-mesh/#programming-sample)
