### ISSUE TITLE
Assigning materials to objects

### ISSUE THREAD

**Issue by Blinking1992** [aspose-free-consulting/projects#259]
when an object has a material of its own, and I give it a new material in the above way the result is normal, the object gets a new material.
However, the material explorer of the modeling software still shows that the old material is retained, and I don't know how to remove these by code.

![image](https://user-images.githubusercontent.com/115074496/196220780-4d3ef41e-331e-4fd0-8671-ce1c8749434c.png)

```cs
Scene scene = Scene.FromFile("test.fbx");
Node testNode = scene.RootNode.GetChild("polySurface3158");
testNode.Material = new PhongMaterial("newMaterial");
scene.Save("newTest.fbx",FileFormat.FBX7500Binary );
```

![image](https://user-images.githubusercontent.com/115074496/196221210-86c3e2b2-17e7-48df-bde6-f27f4c78323c.png)

[test.zip](https://github.com/aspose-free-consulting/projects/files/9802262/test.zip)

**Comment by asadalikhan90** [comment]
@Blinking1992 

The FBX file tracks all objects even when it's not used in the file, please use
```cs
scene.Library.Clear();
```
to remove all references. Then only the directly used objects will be saved to the file.

Furthermore, as shared in your other queries, this is not the right place for such discussions related to the API functionality. The recommended site is the [official support forum](https://forum.aspose.com/c/3d). We request you please prefer it to create such topics in the future.

**Comment by Blinking1992** [comment]
@asadalikhan90 Ok, but at the end I would still like to know why the material is not applied to the object in the very beginning part of this problem.
