### ISSUE TITLE
I want to convert a DOCX to PDF

### ISSUE THREAD

**Issue by ad504g** [aspose-free-consulting/projects#26]
I need to convert a docx to pdf and save it locally for sending through attachment

I need this to work in node.js

I have successfully generated the pdf to my local file system ready for use. I would like to speak to someone to move forward with a pricing and a plan that works best for me.

**Comment by shahzad-latif** [comment]
@ad504g 

Thanks for your interest in Aspose products. You may either get in touch with our sales team via the following forum: https://forum.aspose.com/c/purchase 

Or may contact the team via other options as given on the following page: https://company.aspose.com/contact

If you come across any questions regarding the features or need help, please feel free to ask in our support forums: https://forum.aspose.com/
