### ISSUE TITLE
I want to this sample on c# https://products.aspose.app/pdf/editor

### ISSUE THREAD

**Issue by wyahmed** [aspose-free-consulting/projects#265]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by atirtahirgroupdocs** [comment]
@wyahmed 

Please download this [source code](https://github.com/aspose-pdf/Aspose.PDF-for-.NET/tree/master/Demos/src/Aspose.PDF.Live.Demos.UI) for the Editor application.

**Comment by wyahmed** [comment]
This old example i need the new one
![Capture](https://user-images.githubusercontent.com/66774543/205652647-784c7c98-d282-48b4-a93e-b2c9c7975055.PNG)

**Comment by atirtahirgroupdocs** [comment]
@wyahmed 

Could you please share more details? We already shared source code for this [app](https://products.aspose.app/pdf/editor) that you requested.
