### ISSUE TITLE
An online document viewer with inline editing capibailites. 

### ISSUE THREAD

**Issue by nstrain17** [aspose-free-consulting/projects#267]
I would like a solution to allow users to open word and pdf documents in an mvc application but also allow inline editing to change the text, formatting ect.  I know you have the Viewer which will display and render the documents. However, from reading I believe the editor only allows back-ended updates of the document?

Is this something I would be able to achieve with your APIs ?

**Comment by atirtahirgroupdocs** [comment]
@nstrain17 

Please take a look at this [Document Editor](https://products.groupdocs.app/editor/total) App by our sister company GroupDocs. It allows you to open and edit supported file formatted documents. 
You can [download source code](https://github.com/groupdocs-editor/GroupDocs.Editor-for-.NET/tree/master/Demos) for this online demo or for the MVC app.
