### ISSUE TITLE
Comparing and merging of two word doc is not happening properly 

### ISSUE THREAD

**Issue by adutta90** [aspose-free-consulting/projects#27]
I was trying the below code. The idea is to get the changes in sample2.doc as track changes in the original doc. But the original.doc is not getting modified at all. Can anyone please help ??

Document docA = new Document(“D:/sample2.doc”);
Document docB = new Document(“D:/original.doc”);
docB.acceptAllRevisions();
CompareOptions options = new CompareOptions();
options.setIgnoreFormatting(true);
// Relates to Microsoft Word “Show changes in” option in “Compare Documents” dialog box.
options.setTarget(ComparisonTargetType.NEW);

        docB.compare(docA, "user", new Date(), options);

**Comment by shahzad-latif** [comment]
@adutta90 

Thanks for getting in touch. Please note that this space is to manage free consulting projects. For other queries, I would request you to post in our support forum, so our team can help you quickly and properly: https://forum.aspose.com/c/words

I would have moved this query to the forums, but I don't have your email address. So kindly post the same in the Aspose.Words forum and also attach the sample files so we can test it properly. 

Thanks for your understanding and cooperation.
