### ISSUE TITLE
A question on the INTELLECTUAL PROPERTY RIGHTS

### ISSUE THREAD

**Issue by Fleabane1h** [aspose-free-consulting/projects#273]
As stated in the End User License Agreement:
"INTELLECTUAL PROPERTY RIGHTS. All title and intellectual property rights in and to the Product
(including but not limited to any Aspose trademarks, copywritten images, demos, source code,
intermediate files, packages, photographs, Redistributables, animations, video, audio, music, text, and
"applets" incorporated into the Product and any copies of the Product that You are expressly permitted
to make herein) and **any derivative works are owned by Aspose** or its suppliers. All rights not expressly
granted are reserved by Aspose."

**The question is**: if I develop a whole system with only a small part of the system using Aspose, will the intellectual property rights of the whole system belongs to Aspose?

**Comment by awaishafeez** [comment]
@Fleabane1h 

> **The question is**: if I develop a whole system with only a small part of the system using Aspose, will the intellectual property rights of the whole system belongs to Aspose?

Please post above question in [Aspose.Purchase forum](https://forum.aspose.com/c/purchase/6) so that our Sales team can be able to guide you appropriately. Thanks.

**Comment by Fleabane1h** [comment]
> 

Got it, thanks!
