### ISSUE TITLE
Upgrade Aspose Cells 8.9.0, Aspose Words 16.5.0.0 to the latest version in .NET

### ISSUE THREAD

**Issue by edmundtt** [aspose-free-consulting/projects#274]
Upgrade Aspose Cells 8.9.0, Aspose Words 16.5.0.0 to the latest version in .NET, does it involve any code change? It will be great if it is just a in-place upgrade---I mean no code changes are required.

**Comment by AlexNosk** [comment]
@edmundtt  Currently you are using quite old versions of Aspose.Cells and Aspose.Words. For example, Aspose.Words version you are using was released more than 6 years ago. While the general API was not changed, there were API changes made during this time of Aspose.Words evolution. You can learn about all breaking API changes from Aspose.Words and Aspose.Cells release notes:
<https://docs.aspose.com/words/net/aspose-words-for-net/>
<https://docs.aspose.com/cells/net/release-notes/>
Please feel free to ask in case of any issues while update, we will be glad to help you.
