### ISSUE TITLE
Compress XML larger than 40 MB

### ISSUE THREAD

**Issue by cibhinbharathi** [aspose-free-consulting/projects#275]
I am trying to use this product of your 

https://products.aspose.app/total/compress/xml#

However the XML files i have are 170 - 200MB in size. Is it possible to compress them to less than 100MB. I am okay to make a purchase if it is necessary.

Thanks & Regards,

**Comment by atirtahir** [comment]
@cibhinbharathi 

Do you want to compress the XML files with respect to it's size only (e.g. test.xml 170mb, after compression test.xml 100mb) or compress them to an archive (e.g. test.xml 170mb, after compression to an archive test.zip 100mb)? 
Also, could you please share a sample/source XML file with us? 
Moreover, we'd recommend you to always raise such issues on our [forum](https://forum.aspose.app/).

Thanks

**Comment by atirtahirgroupdocs** [comment]
@cibhinbharathi

Do you want to compress the XML files with respect to it's size only (e.g. test.xml 170mb, after compression test.xml 100mb) or compress them to an archive (e.g. test.xml 170mb, after compression to an archive test.zip 100mb)?
Also, could you please share a sample/source XML file with us?
Moreover, we'd recommend you to always raise such issues on our [forum](https://forum.aspose.app/).

Thanks
