### ISSUE TITLE
DocumentHandler().AddPassword

### ISSUE THREAD

**Issue by tilankak** [aspose-free-consulting/projects#276]
hi

I am using following code to add password to word document. It works before but from recenly it stops works and shows this error on 
DocumentHandler().AddPassword(fs, options);

this is the error shows.

GroupDocs.Merger.Exceptions.GroupDocsMergerException: 'Could not load type 'Aspose.Words.LoadOptions' from assembly 'Aspose.Words, Version=22.5.0.0, Culture=neutral, PublicKeyToken=716fcc553a201e56'.'

inner exception
TypeLoadException: Could not load type 'Aspose.Words.LoadOptions' from assembly 'Aspose.Words, Version=22.5.0.0, Culture=neutral, PublicKeyToken=716fcc553a201e56'.

here is my code

using (FileStream fs = new FileStream(FilePath, FileMode.Open))
                {

                    AddPasswordOptions options = new AddPasswordOptions(FileFormat.Docx, Password);
                    GroupDocs.Merger.Domain.Result.DocumentResult result = new DocumentHandler().AddPassword(fs, options);

                    fs.Close();
                    Stream documentStream = result.Stream;
                    var filestream = File.Create(OutputPath);

                    documentStream.CopyTo(filestream);
                    documentStream.Close();
                    filestream.Close();

                }

Please help me on this

Thanks
Tilanka

**Comment by atirtahirgroupdocs** [comment]
@tilankak 

We already answered this query on [forum](https://forum.groupdocs.com/t/documenthandler-addpassword-not-works/12135/2).
