### ISSUE TITLE
Im trying to extract text from PDF like the Aspose SaaS Pdf-> Text service 

### ISSUE THREAD

**Issue by Brettk80** [aspose-free-consulting/projects#277]
I've tried Aspose Java for PDF using TextAbsorber
I've tried Aspose Java for OCR using a PDF

I can't get the text to generate from PDF.
I've only ben able to get OCR to work on PNG and Tiff which hasnt been the best.  Since my files are PDF I just need to extract the text and other free unix systems has not formatted the text as well.

Sample pdf attached.
[HB0037.pdf](https://github.com/aspose-free-consulting/projects/files/10406769/HB0037.pdf)

**Comment by asadalikhan90** [comment]
@Brettk80 

We believe that we already have responded to your [similar inquiry](https://forum.aspose.com/t/cant-extract-text-from-pdf/257903/1) in out dedicated support forum. You may please follow up there and create a new topic there in case you need further assistance. Please always prefer to post such topics in our support forum as it is recommended place for such discussions.
