### ISSUE TITLE
Get tables from each page in PDF & merge tables in one sheet

### ISSUE THREAD

**Issue by vssaini** [aspose-free-consulting/projects#279]
I'm trying to retrieve tables from each page in the PDF document. Then use each table in the resultant excel file to create another excel file with rows under specific columns to merge as a single table.

I'm working on Windows 10 using .NET 4.0 

Input file - [PriceBook.pdf](https://github.com/aspose-free-consulting/projects/files/10531267/PriceBook.pdf)
Output file - [Vikram Example.xlsx](https://github.com/aspose-free-consulting/projects/files/10531268/Vikram.Example.xlsx)

I tried in the project - [UpwPdfToExcel.zip](https://github.com/aspose-free-consulting/projects/files/10531269/UpwPdfToExcel.zip)

**Comment by asadalikhan90** [comment]
@vssaini 

We believe that we have responded to your [similar inquiry](https://forum.aspose.com/t/get-tables-from-each-page-in-pdf-and-create-single-table-in-one-sheet/258881/9) in our dedicated support forum. You may please follow up there.
