### ISSUE TITLE
Can’t recognize barcodes from base 64 image in request body

### ISSUE THREAD

**Issue by ligorio86** [aspose-free-consulting/projects#281]
Hello I’m trying to make a call to /barcode/recognize passing an image containing barcodes, encoded as Base64 string but I receive an error code “internalError”.

The message is “The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.”

But I’m sure that it is a Base64 valid string, what I am doing wrong?

I don’t know if you can see my requests, in case the last request id is “2af23755-11ed-426a-8a83-659b3873917c”
Thanks

My code snippet

...

url = URI("https://api.aspose.cloud/v3.0/barcode/recognize?Type=Code128")

https = Net::HTTP.new(url.host, url.port)
https.use_ssl = true

request = Net::HTTP::Post.new(url)
request["Content-Type"] = "multipart/form-data"
request["Accept"] = "application/json"
request["x-aspose-client"] = "Containerize.Swagger"
request["authorization"] = "Bearer myToken"

form_data = [['image', 'base64encodedimage']]

request.set_form form_data, 'multipart/form-data'

response = https.request(request)

**Comment by tilalahmad** [comment]
@ligorio86

Please find a sample code to recognize barcodes from base 64 image string. You have posted a similar query on [Aspose.BarCode Cloud Free Support Forum](https://forum.aspose.cloud/c/barcode/6). If you need any further assistance in this regard, you can use our forum as well. 

```
url = URI("https://api.aspose.cloud/v3.0/barcode/recognize")

https = Net::HTTP.new(url.host, url.port)
https.use_ssl = true

image_data = File.read("image.jpg")
base64_data = Base64.strict_encode64(image_data)

request = Net::HTTP::Post.new(url)
request["Authorization"] = "Bearer #{access_token}"
request["Content-Type"] = "text/plain"
request.body = base64_data

response = https.request(request)
puts response.code
puts response.read_body
```
