### ISSUE TITLE
I want to extract the text from  HPG files which has HPGL .hpg file content using c# .net

### ISSUE THREAD

**Issue by Arapahoe** [aspose-free-consulting/projects#283]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

extract the text from  HPG files which has HPGL .hpg file content using c# .net
 I tried to upload an example file but it says "We don’t support that file type."

**Comment by amjad-sahi** [comment]
@Arapahoe,

Could you please compress your file(s) into ZIP format and then upload here.
