### ISSUE TITLE
Want to search and Highlight  text.

### ISSUE THREAD

**Issue by sachinjindal23** [aspose-free-consulting/projects#285]
I want to use aspose cloud API in Sharepoint online.
I have custom search page where I want user to type any text which should be searched in document library and want a custom solution where the document is visible to user with highlighted text.

**Comment by tilalahmad** [comment]
@sachinjindal23 

You can search and highlight text in a PDF document using Aspose.PDF Cloud. But unfortunately, currently it only works with [supported storages](https://docs.aspose.cloud/total/getting-started/dashboard/how-to-configure-3rd-party-cloud-storages/). You can proceed in two steps: first, find the rectangle coordinates of your text in the PDF document, and then annotate the text. For any further questions, please feel free to post your query in [Aspose Cloud Forums](https://forum.aspose.cloud/).

Step 1: Get the text position

[GET ​/pdf​/{name}​/text](https://apireference.aspose.cloud/pdf/#/Text/GetText) Read document text. 

```
    curl -X GET "https://api.aspose.cloud/v3.0/pdf/02_pages.pdf/text?format=origami&splitRects=true&folder=Temp&LLX=0&LLY=0&URX=0&URY=0" 
    -H "accept: application/json" 
    -H "authorization: Bearer [Access_Token]" 
    -H "x-aspose-client: Containerize.Swagger"
```

Step 2: Add Annotation to the specified rectangle location

[POST ​/pdf​/{name}​/pages​/{pageNumber}​/annotations​/highlight](https://apireference.aspose.cloud/pdf/#/Annotations/PostPageHighlightAnnotations) Add document page highlight annotations.

```
    curl -X POST "https://api.aspose.cloud/v3.0/pdf/02_pages.pdf/pages/1/annotations/highlight?folder=Temp" 
    -H "accept: application/json" 
    -H "authorization: Bearer [JWT_Access_Token]" 
    -H "Content-Type: application/json" 
    -H "x-aspose-client: Containerize.Swagger" 
    -d "[ { "Color": { "A": 255, "R": 255, "G": 255, "B": 0 }, "Name": "highlight_annot", "Rect": { "LLX": 259.27580539703365, "LLY": 743.4707997894287, "URX": 332.26148873138425, "URY": 765.5148007965088 }, "PageIndex": 1, "ZIndex": 0, "Subject": "subject", "Title": "test", "RichText": "rich text" }]"
```
