### ISSUE TITLE
I want to create/build 

### ISSUE THREAD

**Issue by shadowaxe99** [aspose-free-consulting/projects#289]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

I have a ton of different emailing lists all formatted in various different ways. I am trying to get all the pages to have just full name and email 

sheets and excel - on mac

**Comment by amjad-sahi** [comment]
@shadowaxe99,

Do you need to export emails to Excel spreadsheets? Could you please give more details of your use-case along with sample input file(s) and your expected output file(s). We will understand your requirements and assist you accordingly.
