### ISSUE TITLE
Merged PDF file is too large

### ISSUE THREAD

**Issue by chittumge** [aspose-free-consulting/projects#29]
Hi, I am using Aspose.PDF in Asp.Net Core to create a form from an existing PDF file memory stream and then fill the form with data from a database model.  Then, I save the form to a memory stream and add it to a memory stream array.  Next, I merge the memory stream array into an output memory stream using pdfEditor.Concatenate().  Lastly, I convert the output memory stream back to a byte array and return the byte array as a FileContentResult of type "application/pdf".  The problem is, the resulting PDF file size is too large.  I am using your optimizationOptions as described on your website but, it only reduces the size of the PDF by half and takes four times as long to create the merged PDF.  Is there some other tweeks or optimizations I can do to reduce the size of the merged PDF and reduce the amouth of time it takes to create it?

**Comment by chittumge** [comment]
[Aspose PDF too large.txt](https://github.com/aspose-free-consulting/projects/files/4193938/Aspose.PDF.too.large.txt)

**Comment by chittumge** [comment]
See attachment.

**Comment by chittumge** [comment]
[Aspose PDF too large.txt](https://github.com/aspose-free-consulting/projects/files/4193964/Aspose.PDF.too.large.txt)

**Comment by chittumge** [comment]
see attachment.

**Comment by asadalikhan90** [comment]
@chittumge 

Sorry for the delayed response.

We have checked the code snippet that you have shared and it seemed fine. Usually saving the PDF into a memory stream takes more time than saving the file to the physical disk. You may please try saving the PDF physically and see if there is any improvement in terms of time taken by the API.

Furthermore, the time taken to process the PDFs depends upon their structure and content complexity. In case you still notice any issue, please share a sample PDF document that can be tested using the code snippet that you have shared already. We will try to observe the issue in our environment and get back to you with feedback.
