### ISSUE TITLE
I want to create a View and Print Project that loads PDF files, views them and print them in WPF. 

### ISSUE THREAD

**Issue by nyendwa** [aspose-free-consulting/projects#290]
I am working on a WPF project that stores PDF files, however, I want users to be able to navigate around the project, find a book they like view it and be able to print it. I have already worked on the interface but I need to add the logic that loads the books from a local disk, view it and then print it. A link to my project on GitHub is here https://github.com/nyendwa/BookPrinter.

**Comment by asadalikhan90** [comment]
@nyendwa

Aspose.PDF does not provide any control or feature to display the PDF documents in your application. Instead, you can use its features in the code behind to convert/create/modify the PDF documents. For your case, you can [convert the PDF Pages into Images using Aspose.PDF for .NET](https://docs.aspose.com/pdf/net/convert-pdf-to-images-format/) and display those images in any panel in your WPF application. Printing the images shown in the application can also be implemented then using C# methods.
