### ISSUE TITLE
I want to migrate api to dotnet6 and containerize it using Docker on linux server. How can i use my existing aspose words in docker

### ISSUE THREAD

**Issue by KPK015** [aspose-free-consulting/projects#291]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

Need to understand how can we use **Aspose.Words for .NET**  containerized environment.

My project is in dotnet core and recently we migrated our project to **dotnet 6.** We want to dockerize the api and for this we want to know how we can achieve this as aspose.word has dependency on System.Drawing library.

Can I use the same licence in cloud env ?   
OrderId : 200909101759 and  LicenseVersion 3.0 

Docker file would be helpful along with other information.

Kindly respond.

Kishor Kadam

**Comment by AlexNosk** [comment]
@KPK015 Aspose.Words for .NET6 does not have dependency on System.Drawing. Please see our documentation to learn how to use Aspose.Words in Docker:
<https://docs.aspose.com/words/net/how-to-run-aspose-words-in-docker/>

In sort, Aspose.Words for .NET Standard and .NET6 use SkiaSharp to deal with graphics, to make it work on Linux you have to add reference either to [SkiaSharp.NativeAssets.Linux](https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux) or to [SkiaSharp.NativeAssets.Linux.NoDependencies](https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux.NoDependencies)

If you add reference to [SkiaSharp.NativeAssets.Linux](https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux), you should also install libfontconfig1 in your system. `SkiaSharp.NativeAssets.Linux` depends on this library. You can use the following command to install it:

```
apt-get update && apt-get install -y libfontconfig1
```
If you do not have rights to install packages, or other reasons not to install libfontconfig1, you can simply use [SkiaSharp.NativeAssets.Linux.NoDependencies](https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux.NoDependencies), which does not require installation of libfontconfig1.

I would recommend to use 2.80.3 version of `SkiaSharp.NativeAssets`.

For example here a Dokerfile for Ubuntu docker:
```sh
FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app
RUN apt-get update && apt-get install -y libfontconfig1

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["TestNet6.csproj", "."]
RUN dotnet restore "./TestNet5.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "TestNet6.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TestNet6.csproj" -c Release -r linux-x64 --no-self-contained -o /app/publish

FROM base AS final

WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TestNet6.dll"]
```
and here is .csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  
   <PropertyGroup>
     <InvariantGlobalization>false</InvariantGlobalization>
   </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Aspose.Words" Version="23.4.0" />
	  <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="2.80.3" />
  </ItemGroup>

</Project>
```

Regarding using the license in cloud, please ask the question in [Aspose.Purchase forum](https://forum.aspose.com/c/purchase/6). My colleagues from sales team will help you shortly.

PS: the main place for getting support is Aspose support forums. So please post your questions in the public [Aspose.Words support forum](https://forum.aspose.com/c/words/8).
