### ISSUE TITLE
Converting pdf to docx in Ruby - not able to download the converted document

### ISSUE THREAD

**Issue by sasiprabha-999** [aspose-free-consulting/projects#292]
Hi Team,

I  have used aspose_words_cloud gem to convert the pdf(.pdf) to word document(.docx) by using the below code. I can see the response as success in aspose dashboard but where it will be saved in my local setup , am unable to figure it out. How can I download the converted the file? Please help to fix this issue. Below is the sample code used for conversion.

AsposeWordsCloud.configure do |config|
      config.client_data['ClientId'] = '#################################'
      config.client_data['ClientSecret'] = '#############################'
end
    doc = File.open("test_pdf.pdf")
    request = ConvertDocumentRequest.new(document: doc, format: 'docx')
    @words_api = WordsApi.new
    convert = @words_api.convert_document(request)

**Comment by tilalahmad** [comment]
@sasiprabha-999 

Please find the sample code for the conversion and save the output file to local drive. Hopefully, it will help you to accomplish the task. If you still have any question, then please feel free to post it to our free support forums.

```
require 'aspose_words_cloud'

class Document

include AsposeWordsCloud

# Get App key and App SID from https: //dashboard.aspose.cloud/
APP_KEY = "xxxxxxxxxxxxxxxxxxxxxxxxx"
APP_SID = "xxxxxxx-xxxx-xxxxx-xxxx-xxxxxxxxx"
FILE_PATH = "C:/Temp/"

def initialize
AsposeWordsCloud.configure do | config |
    config.client_data['ClientId'] = APP_SID
  config.client_data['ClientSecret'] = APP_KEY
end
@words_api = WordsApi.new
end

# Convert local file
def test_convert_document
request_document = File.open('C:/Temp/Test.pdf')
request = ConvertDocumentRequest.new(document: request_document, format: 'docx')
result = @words_api.convert_document(request)
# Save output file to local drive
File.open('test_result.docx', 'wb').write(result)
puts "File Converted......"
end
end

document = Document.new()
document.test_convert_document
```
