### ISSUE TITLE
We cant open unity software on pc by using Aspose.Slides

### ISSUE THREAD

**Issue by 86K** [aspose-free-consulting/projects#293]
- Unity version is 2023.3.33f1c2
- Aspose.Slides v23.3

Q：We dont know what version of System.Drawing.Common that Aspose.Slides used？

Please help us to resolve this problem. Best regrads!

**Comment by andreypotapovaspose** [comment]
@86K,
Please check the Aspose.Slides for .NET requirements here:
https://www.nuget.org/packages/Aspose.Slides.NET/
