### ISSUE TITLE
I want to create image replacer for PSD

### ISSUE THREAD

**Issue by abdelrahmansaud** [aspose-free-consulting/projects#295]
The use case is as follow: 

1- We have a psd file, along with the info of which layer that has the target image 
2- we need to replace the target image with another one (from disk, sites, etc.. let's assume from disk for simplicity)
How to do that using aspose.psd java library?

**Comment by dimsa** [comment]
@abdelrahmansaud please this showcase https://docs.aspose.com/psd/net/using-psd-files-as-templates-for-automation-business-cards-case/ 
Also, the second interesting way to implement your idea is to use [Smart Objects](https://reference.aspose.com/psd/net/aspose.psd.fileformats.psd.layers.smartobjects/smartobjectlayer/) and the methods like [ReplaceContents](https://reference.aspose.com/psd/net/aspose.psd.fileformats.psd.layers.smartobjects/smartobjectlayer/replacecontents/)

For the different Layer Types should be used different methods of replacing (Yes, you can just remove any layer and replace it with regular one, but you'll lose the ability of [PSD Warp Transforming](https://reference.aspose.com/psd/net/aspose.psd/graphicspath/warp/) that is quite powerful)
