### ISSUE TITLE
I trying to implement on PDF e-sing

### ISSUE THREAD

**Issue by restapitest3321** [aspose-free-consulting/projects#296]
But I am unable to do it. 
Showing error on files getting. I connected my storage but the files are not showing

**Comment by tilalahmad** [comment]
@restapitest3321 
Please share your sample code with us. We will look into it and guide you accordingly. Furthermore, you can post your query in our [free support forum](https://forum.aspose.cloud/) as well.

**Comment by restapitest3321** [comment]
Here i am share the sample code for add signature field. 
<?php
//protected $pdfApi;
// Get App key and App SID from https://dashboard.aspose.cloud/
$appSid = '1015961532858-em6qh7qtt6pvn1fvth53j0dtr2r5skfg.apps.googleusercontent.com';
$appKey = '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';
$host = 'https://api.aspose.cloud/v3.0';

// configuration object
$this->config = new Configuration();
$this->config->setAppKey($appKey);
$this->config->setAppSid($appSid);
$this->config->setHost($host);

// create PdfApi instance
$this->pdfApi = new PdfApi(null, $this->config);

// name of input PDF document
$name = 'pdf.pdf';

// upload file to cloud storage
$this->uploadFile($name);

$signatureFileName = 'C:\wamp64\bin\php\php7.4.26\extras\ssl\cacert.pem';
$this->uploadFile($signatureFileName);

$folder = $this->tempFolder;

$signature = new Aspose\PDF\Model\Signature();
$signature->setAuthority('Nayyer Shahbaz');
$signature->setContact('nayyer.shahbaz@aspose.com');
$signature->setDate('08/01/2012 12:15:00.000 PM');
$signature->setFormFieldName('Signature1');
$signature->setLocation('Australia');
$signature->setPassword('sIikZSmz');
$signature->setRectangle(new Aspose\PDF\Model\Rectangle(['llx' => 100, 'lly' => 100, 'urx' => 0, 'ury' => 0]));
$signature->setSignaturePath($folder . '/' . $signatureFileName);
$signature->setSignatureType(Aspose\PDF\Model\SignatureType::PKCS7);
$signature->setVisible(true);
$signature->setShowProperties(false);

$field = new Aspose\PDF\Model\SignatureField();
$field->setPartialName('sign1');
// page index where signature field needs to be added
$field->setPageIndex(1);
$field->setSignature($signature);
// specify the rectangular region for the Signature field
$field->setRect(new Aspose\PDF\Model\Rectangle(['llx' => 100, 'lly' => 100, 'urx' => 160, 'ury' => 140]));

// call the API to add signature field
$response = $this->pdfApi->postSignatureField($name, $field, null, $this->tempFolder);
$this->assertEquals(200, $response->getCode());
 ?>

**Comment by restapitest3321** [comment]
Here i am sharing the sample code for adding signature field
`<?php
//protected $pdfApi;
// Get App key and App SID from https://dashboard.aspose.cloud/
$appSid = '1015961532858-em6qh7qtt6pvn1fvth53j0dtr2r5skfg.apps.googleusercontent.com';
$appKey = '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';
$host = 'https://api.aspose.cloud/v3.0';

// configuration object
$this->config = new Configuration();
$this->config->setAppKey($appKey);
$this->config->setAppSid($appSid);
$this->config->setHost($host);

// create PdfApi instance
$this->pdfApi = new PdfApi(null, $this->config);

// name of input PDF document
$name = 'pdf.pdf';

// upload file to cloud storage
$this->uploadFile($name);

$signatureFileName = 'C:\wamp64\bin\php\php7.4.26\extras\ssl\cacert.pem';
$this->uploadFile($signatureFileName);

$folder = $this->tempFolder;

$signature = new Aspose\PDF\Model\Signature();
$signature->setAuthority('Nayyer Shahbaz');
$signature->setContact('nayyer.shahbaz@aspose.com');
$signature->setDate('08/01/2012 12:15:00.000 PM');
$signature->setFormFieldName('Signature1');
$signature->setLocation('Australia');
$signature->setPassword('sIikZSmz');
$signature->setRectangle(new Aspose\PDF\Model\Rectangle(['llx' => 100, 'lly' => 100, 'urx' => 0, 'ury' => 0]));
$signature->setSignaturePath($folder . '/' . $signatureFileName);
$signature->setSignatureType(Aspose\PDF\Model\SignatureType::PKCS7);
$signature->setVisible(true);
$signature->setShowProperties(false);

$field = new Aspose\PDF\Model\SignatureField();
$field->setPartialName('sign1');
// page index where signature field needs to be added
$field->setPageIndex(1);
$field->setSignature($signature);
// specify the rectangular region for the Signature field
$field->setRect(new Aspose\PDF\Model\Rectangle(['llx' => 100, 'lly' => 100, 'urx' => 160, 'ury' => 140]));

// call the API to add signature field
$response = $this->pdfApi->postSignatureField($name, $field, null, $this->tempFolder);
$this->assertEquals(200, $response->getCode());
 ?>
`

**Comment by restapitest3321** [comment]
I refer this article 
https://blog.aspose.cloud/pdf/digitally-sign-pdf-document-online-using-php/

**Comment by tilalahmad** [comment]
@restapitest3321 

We are looking into the issue and will share an update with you shortly.

**Comment by tilalahmad** [comment]
@restapitest3321 

Please see the updated sample PHP code to add a signature field to a PDF document and sign it. Hopefully, it will help you accomplish the task. For any further assistance, please feel free to contact us via the [support forum](https://forum.aspose.cloud/c/pdf/13).
```
<?php

require_once('D:\xampp\htdocs\aspose-pdf-cloud-php-master\test\vendor\autoload.php');

use Aspose\PDF\Api\PdfApi;
use Aspose\PDF\Configuration;

//TODO: Get your AppSID and AppKey at https://dashboard.aspose.cloud (free registration is required).

$AppKey="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
$AppSid="xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx";

$config = new Configuration();
$config->setAppSid($AppSid);
$config->setAppKey($AppKey);

$pdfApi = new PdfApi(null, $config);

try {
	//upload pdf file	
 	$fileName = 'Test.pdf';
	$folder= null;
	$path = $fileName;

	$file = $fileName;
	$uploadResponse = $pdfApi->uploadFile($path, $file);

	//upload signature file
        $signatureFileName = '33226.p12';
	$folder= null;
	$path1 = $signatureFileName;

	$file1 = $signatureFileName;
	$uploadResponseSignature = $pdfApi->uploadFile($path1, $file1);

        $folder = null;

	//Add signature field and sign the PDF document
        $signature = new Aspose\PDF\Model\Signature();
        $signature->setAuthority('Sergey Smal');
        $signature->setContact('test@mail.ru');
        $signature->setDate('08/01/2012 12:15:00.000 PM');
        $signature->setFormFieldName('Signature1');
        $signature->setLocation('Ukraine');
        $signature->setPassword('sIikZSmz');
        $signature->setRectangle(new Aspose\PDF\Model\Rectangle(['llx' => 100, 'lly' => 100, 'urx' => 0, 'ury' => 0]));
        $signature->setSignaturePath($signatureFileName);
        $signature->setSignatureType(Aspose\PDF\Model\SignatureType::PKCS7);
        $signature->setVisible(true);
        $signature->setShowProperties(false);

        $field = new Aspose\PDF\Model\SignatureField();
        $field->setPartialName('sign1');
        $field->setPageIndex(1);
	//Please note if you want to add only empty signature field then do not pass signature object
        $field->setSignature($signature);
        $field->setRect(new Aspose\PDF\Model\Rectangle(['llx' => 100, 'lly' => 100, 'urx' => 160, 'ury' => 140]));

        $response = $pdfApi->postSignatureField($fileName, $field, null, null);
	print_r($response);

    
} catch (Exception $e) {
    echo  "Something went wrong: ",  $e->getMessage(), "\n";
    PHP_EOL;
}

?>
```
