### ISSUE TITLE
Ability to parse a resultant HTML File created by comparing 2 similar HTML files

### ISSUE THREAD

**Issue by cg17troon** [aspose-free-consulting/projects#297]
We are using the ASPOSE Library to compare 2 HTML documents (10K Filings from the SEC) for the users of our product. 
We were able to create a resultant HTML file that shows the additions and redactions between the 2 files.

We want to be able to use the library to implement other features, and want to understand if the ASPOSE library can help us with it:
Want to be able to extract certain sections from the resultant file
Want to be able to add links to html sections
Change formatting of redactions and additions in the resultant file
We are planning to purchase the yearly package and would love to get on a call to discuss this further.

**Comment by amjad-sahi** [comment]
@cg17troon ,

Could you please specify which Aspose APIs you are using? Also, share some sample files and screenshots to demonstrate your requirements. We will check and assist you soon.
