### ISSUE TITLE
I want edit the docx file in Aspose word library 

### ISSUE THREAD

**Issue by Lakshmibabukandula** [aspose-free-consulting/projects#299]
Hi,
I have ASP.net web application for Document management portal, we have Docx files to open in edit mode in browser. Current implementation was working with Activexobject component and now we migrate to Edge browser,Activexobject not supporting Edge. 
Can we implement Existing docx file view/edit requirements in Aspose word.

Steps:
1. When user clicks on Edit then luch the window to Document edit mode 
2. After edit then save back to server with same file name

Please provide the same implementation code with .aspx file.

**Comment by AlexNosk** [comment]
@Lakshmibabukandula Aspose.Words is a library for processing documents programmatically it does not provide UI components for viewing or editing documents. However, Aspose.Words can be used as a backend component in such UI components.
You can consider using our sisters company product [GroupDocs.Editor](https://products.groupdocs.com/editor/).
