### ISSUE TITLE
I want to create/build an Iframe to display Powerpoint Presentation from sharepoint to be rendered on the web portal that has a reference to the PPT on sharepoint

### ISSUE THREAD

**Issue by RazDynamics** [aspose-free-consulting/projects#3]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by shahzad-latif** [comment]
@RazDynamics ,

Thanks for getting in touch. What are the specs of the "Web Portal" you referred to? How would you like to refer the PowerPoints from the SharePoint? Please elaborate your idea so we can better understand and then build something which suits your needs.

**Comment by shahzad-latif** [comment]
@RazDynamics ,

If you can share some details about the public and private interfaces of the portal that will be great.

**Comment by shahzad-latif** [comment]
@RazDynamics 

One option could be to create a viewer as .aspx and then embed that in SharePoint. One approach we can use here is to convert the slides to high fidelity images and then create create a viewer inside .aspx. Something along these lines https://i.imgur.com/ctzMVJt.png. However, the interface can be improved, this is just a rough demo or illustration. 

Please feel free to share your thoughts in detail as well so we make sure we're on the same page. Thanks.

**Comment by shahzad-latif** [comment]
@RazDynamics

I couldn't here from you further on this, however based on our understanding of your need we have built a basic project. Please have a look into this: https://github.com/aspose-free-consulting/web-viewer-for-powerpoint-presentation

This gives you an idea how slides from a PowerPoint can be converted to high fidelity images and then a viewer can be established from those.

This can further be extended to show thumbnails of the slides as a slider at the bottom or the top of the viewer. However, that will require a little more power and might cause some delay if slides are too complex or too many.

Anyway, please see if your development team can reuse this code and move it to SharePoint. This will be eaay as SharePoint development is based to .NET as well.

Please do share your further thoughts. Thanks

**Comment by RazDynamics** [comment]
Hi Shahzad, we need to expose this PPT stored in Sharepoint via the web viewer using Javascript or Jquery as the Portal doesnt use ASPX, it only supports Liquid Syntax and Javascript/ Jquery? Any guidance please? Thanks!

**Comment by shahzad-latif** [comment]
@RazDynamics 

Thanks for your response. Now I get a better picture. We were not sure how exactly you'll use it. So let us explore it further keeping your requirement in mind and we'll get back to you with a solution.

**Comment by shahzad-latif** [comment]
@RazDynamics 

We have explored this scenario further and this is our understanding: 

1. The slides are uploaded using SharePoint and placed on the server
2. Public web portal is separate from SharePoint and will use jQuery/JavaScript etc, to show the slides

Now, if my understanding is correct, let me explain, how we can work this out: 

1. We can't directly display PowerPoint slides on the web page, rather we need to first convert those individual slides to each individual high fidelity image and then store that images in a folder
2. This conversion process will be done by Aspose.Slides for .NET. And for this API to work, we need to use it with .NET. The SharePoint allows us to extend the functionality using .NET maybe using WebParts or some other feature. So you can reuse the .NET part of the code which I shared already to convert the slide to images first and place in a folder inside SharePoint
3. At the front end, we can create a viewer using jQuery/JavaScript/HTML which will show an interface of a presentation and show the individual slides which can be navigation with Next or Previous buttons or even slide numbers

Please also have a look at the current interface: https://github.com/aspose-free-consulting/web-viewer-for-powerpoint-presentation

The backend code to convert slides to images will remain the same, but for the front end, we'll replace .NET code with jQuery/JavaScript code. 

Please share if this makes sense or you want to add something. And will this be a workable solution for you? If you also want to engage one of your developers working on this feature/epic, and let him discuss as well. Please let me know your further thoughts.
