### ISSUE TITLE
I want to build a module to generate the document from Server and upload the document to Server

### ISSUE THREAD

**Issue by darshitpatel90** [aspose-free-consulting/projects#30]
I am working on a module where there is a requirement to generate PDF dynamically (data mostly coming from database) from the server. 

The generated PDF is a fillable PDF with labels, text boxes and button on it, which will allow user to fill the required data.  

On top of that we want to keep some metadata, which is basically custom properties of PDF. Once everything is filled, with click of button we want to send (submit complete pdf) the whole PDF to the server with the help of web service, web service will receive the whole PDF on server.

Now, once we receive the PDF, we want to read all the data within text boxes as well as custom properties within PDF to perform required operation to save the PDF data.

< which platform you're working on -- operating system, development environment etc.> 
Windows Operating System, Java

<attach input documents>
It is some what confidential, so I can't share any input or sample documents.

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by shahzad-latif** [comment]
@darshitpatel90 

Thanks for your request. We're looking into it and will get back to you with the detailed answer and sample soon.

**Comment by asadalikhan90** [comment]
@darshitpatel90 

We have noticed your similar inquiry over our forum and responded to you there with the required information. As per your latest feedback in [respective forum thread](https://forum.aspose.com/t/pdf-doc-api-for-java-create-action-on-page-open/187365/15?u=asad.ali), it seems like your requirements have been accomplished by the code snippet we provided. Please feel free to let us know in case you need further assistance.

**Comment by darshitpatel90** [comment]
I am fine for now, if I do need more information, I will contact you guys.
