### ISSUE TITLE
I want to read a PDF document

### ISSUE THREAD

**Issue by dundas7** [aspose-free-consulting/projects#300]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>
I read a PDF and I have to write a DOCX document.but I can not read a table in a PDF.
so using aspose.PDF library,I try to read a table.but It doesn't it and I can't read every text in a document.
I could read just a particular text.I don't know the reason.

< which platform you're working on -- operating system, development environment etc.> 
development env. : window 10, eclipse
operating system : linux(maybe)
<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by asadalikhan90** [comment]
@dundas7 

Can you please share your sample PDF document for our reference so that we can test the scenario in our environment and address it accordingly?
