### ISSUE TITLE
XmlMailMergeDataSet Class not found for aspose-words maven jar

### ISSUE THREAD

**Issue by udbhav2303** [aspose-free-consulting/projects#301]
Hi,

I am not able to use the XmlMailMergeDataSet class with executeWithRegions.
I am using [aspose-words-23.4-jdk17.jar](https://releases.aspose.com/java/repo/com/aspose/aspose-words/23.4/aspose-words-23.4-jdk17.jar) in my local. 
Is there any other jar where this class can be available as we want to use nested region functionality for mail merge.

Below is the code snippet which we are using-

Document doc = new Document(getDataDir("NestedGroup_Template.docx"))
DataSet customersAndOrders = new DataSet();
customersAndOrders.readXml(getDataDir("Customers1.xml"));
doc.getMailMerge().executeWithRegions(new XmlMailMergeDataSet(customersAndOrders));

**Comment by AlexNosk** [comment]
@udbhav2303  `XmlMailMergeDataSet` is not a part of Aspose.Words API. It looks like this is some custom implementation of [IMailMergeDataSource](https://reference.aspose.com/words/java/com.aspose.words/imailmergedatasource/).
By the way you can pass `DataSet` as a data source into `executeWithRegions` method directly.
Also, please see our documentation for more information:
<https://docs.aspose.com/words/java/mail-merge-with-xml-data-source/>
