### ISSUE TITLE
I want to build a simple blazor server map feature selection program

### ISSUE THREAD

**Issue by dalguy1972** [aspose-free-consulting/projects#303]
I wish to build a blazor server application where you can display a map and allow the user to select a polygon/feature that can be sent back to do additional processing.  This would be using your Aspose.GIS product.   The input would normally be from a postgresql/postgis database, but geojson would also be fine (I am attaching a sample geojson file).   What I need to do is to be able to display the features defined in the geojson file.    The user would then be able to select one or more of the displayed features, and the program would be able to get the id's of the features selected to do further geoprocessing and analysis.   I can handle the geoprocessing and analysis, but I am unsure about the map display and selection.
I am running on Windows 11, Visual Studio 2022, using .NET Core 6 (though 7 is also an option).
[gz_2010_us_500_11_5m.zip](https://github.com/aspose-free-consulting/projects/files/11472046/gz_2010_us_500_11_5m.zip)

**Comment by evgeniy-timofeev-aspose** [comment]
I took the task into development and plan to finish this week

**Comment by evgeniy-timofeev-aspose** [comment]
I developed the code. Repository will be published soon

**Comment by dalguy1972** [comment]
I appreciate it, and look forward to seeing the code.

**Comment by dalguy1972** [comment]
Just checking, has the repository been published yet?

**Comment by evgeniy-timofeev-aspose** [comment]
@dalguy1972 
please check: https://github.com/aspose-free-consulting/gis-blazor-map
