### ISSUE TITLE
project with specific columns

### ISSUE THREAD

**Issue by projectmanagerspain** [aspose-free-consulting/projects#305]
Hello, i would like to save an existing project file in Project mpp to a csv with a specific columns, can you orientate me please?
thanks

**Comment by sva1000** [comment]
@projectmanagerspain ,
you can use Project.Save and pass instance of CsvOptions class as shown in this simple example:
`
string dir = "c:\\work\\";
var project = new Project(dir + "InputFile.mpp");
CsvOptions options = new CsvOptions();
List<ViewColumn> columns = new List<ViewColumn>();
columns.Add(new GanttChartColumn("Id", 50, Field.TaskID));
columns.Add(new GanttChartColumn("Name", 50, Field.TaskName));
columns.Add(new GanttChartColumn("Start", 50, Field.TaskStart));
columns.Add(new GanttChartColumn("Finish", 50, Field.TaskFinish));
columns.Add(new GanttChartColumn("Duration", 50, Field.TaskDuration));
columns.Add(new GanttChartColumn("Cost", 50, Field.TaskCost));
options.View = new ProjectView(columns);
project.Save(dir + "output.csv", options);
`

If you need any further assistance, you can use our [free support forum](https://forum.aspose.com/c/tasks/15).

**Comment by projectmanagerspain** [comment]
Thank you very much for your help it was very useful. My code is in python so i have trouble to translate it to python, this is where i arrived can you help me? it would be great! thanks a lot

import aspose.tasks as tsk
   
    prj = tsk.Project('C:\\Users\\rurqui\\schedule\\' + "Prueba proyecto waisr.mpp")

    options = tsk.saving.CsvOptions()
    columns = tsk.visualization.ViewColumn
    columns.add.GanttChartColumn("Id", 50, Field.TaskID);
    options.view = tsk.visualization.ProjectView.columns;

    prj.save('C:\\Users\\rurqui\\schedule\\' + "Prueba proyecto waisr.xlsx",options)

**Comment by sva1000** [comment]
@projectmanagerspain ,
the following code works for me:

````
prj = ...
options = tsk.saving.CsvOptions()
columns = []
columns.append(tsk.visualization.GanttChartColumn("Id", 50, tsk.Field.TASK_ID));
options.view = tsk.visualization.ProjectView(columns);
prj.save ...
````

API Reference for Aspose.Tasks for Python can be found here: 
https://reference.aspose.com/tasks/python-net/aspose.tasks

**Comment by projectmanagerspain** [comment]
Thank you very much!!!it is working now. This was really useful!
