### ISSUE TITLE
If there a free API'S for viewing word excel and pdf image power point in browser?

### ISSUE THREAD

**Issue by xon27** [aspose-free-consulting/projects#306]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by atirtahirgroupdocs** [comment]
@xon27 

Our sister company GroupDocs offers [GroupDocs.Viewer](https://products.groupdocs.com/viewer/) API using that you could view Word, Excel, PDF, Image, PowerPoint or any other [supported](https://docs.groupdocs.com/viewer/net/supported-document-formats/) document.
Please note that we do not offer free APIs. However, you can evaluate GroupDocs.Viewer with a [temporary license](https://purchase.groupdocs.com/temporary-license/). A temporary license is a time-restricted full license that lets you test every aspect of a product before buying it.
Moreover, you can explore our free document viewer web [app](https://products.groupdocs.app/viewer/) that is developed on top of GroupDocs.Viewer for .NET.   
Could you please share more details about your development environment (e.g. looking for a .NET or Java API)? We can share more details about Viewer API accordingly.
