### ISSUE TITLE
Aspose GLB viewer inquiry

### ISSUE THREAD

**Issue by appload2** [aspose-free-consulting/projects#307]
Dear Aspose,

As a dotnet developer but very new to 3d animation, I have a 3ds Max.Net api project that involves loading a GLB file (converted from FBX) that requires MaxScript editing of colors
(of 3d characters' team uniform colors) upon loading to  GLB viewer.

Per Aspose webpage  https://products.aspose.com/3d/net/viewer/glb/
Aspose.3D can " Render GLB files without any 3D modeling and rendering software."

Before purchasing Aspose.3D , any advice if the above mentioned task
is doable would be very much appreciated.

Thank you.

Kind Regards,
Ron Navar

**Comment by asadalikhan90** [comment]
@appload2 

We are checking your requirements and gathering related information. We will get back to you soon.

**Comment by asadalikhan90** [comment]
@appload2 

Aspose.3D has a Vulkan-backend renderer, which can be used to render scene that can be imported. Examples can be found in our [Github repository](https://github.com/aspose-3d/Aspose.3D-for-.NET). However, the examples are too old. We have created a task as **THREEDNET-1393** in our issue tracking system to update the examples. As soon as it is resolved. We will inform you. Please spare us some time.

**Comment by appload2** [comment]
Thank you kindly. And my sincere apologies for late replydue to unfortunate oversight.
Kind regards,Ron
    On Saturday, May 27, 2023 at 07:51:42 AM PDT, Asad Ali ***@***.***> wrote:  
 
 


@appload2

We are checking your requirements and gathering related information. We will get back to you soon.

**Comment by appload2** [comment]
Hi Asad Ali,
Thank you very much for your advice. Looking forward to an upcoming projectinvolving dot net, Aspose3D, and 3dMax.
Again, my apologies for the late reply as just now catching up to emails.
Kind regards,Ron
    On Tuesday, May 30, 2023 at 09:54:28 AM PDT, Asad Ali ***@***.***> wrote:  
 
 


@appload2

Aspose.3D has a Vulkan-backend renderer, which can be used to render scene that can be imported. Examples can be found in our Github repository. However, the examples are too old. We have created a task as THREEDNET-1393 in our issue tracking system to update the examples. As soon as it is resolved. We will inform you. Please spare us some time.

**Comment by asadalikhan90** [comment]
@appload2 

We would like to share the earlier logged ticket **THREEDNET-1393** has been resolved. Please feel free to let us know if you face any issues. Please note that we recommend you post your inquiries or issues in our official and dedicated [support forum](https://forum.aspose.com/c/3d). You can properly have follow ups and updates in there accordingly.

**Comment by appload2** [comment]
Thank you very much  Asad Ali.We have been following up on details you assisted with...as initial result we were able to complete a patent application 
with the much needed info.
Shall be updating.
Again, Thank you !
Kind regards,Ron Navarro

    On Thursday, December 21, 2023 at 01:16:47 PM PST, Asad Ali ***@***.***> wrote:  
 
 


@appload2

We would like to share the earlier logged ticket THREEDNET-1393 has been resolved. Please feel free to let us know if you face any issues. Please note that we recommend you post your inquiries or issues in our official and dedicated support forum. You can properly have follow ups and updates in there accordingly.
