### ISSUE TITLE
load successors when there is more than one from mpp to csv in python

### ISSUE THREAD

**Issue by projectmanagerspain** [aspose-free-consulting/projects#309]
Hello,
    with this code i cannot load the successors correctly, as they are more than one. Is there a method to design successors (or predecessors) as a list and include them in the csv as only one element of the values list? thanks!

     prj = tsk.Project('C:\....\' + "...")

    
    options = tsk.saving.CsvOptions()
    options.text_delimiter = tsk.saving.CsvTextDelimiter.COMMA
    columns = []
    columns.append(tsk.visualization.GanttChartColumn("Id", 20, tsk.Field.TASK_ID));
    columns.append(tsk.visualization.GanttChartColumn("Exclusive ID", 20, tsk.Field.TASK_UNIQUE_ID));
    columns.append(tsk.visualization.GanttChartColumn("Exclusive ID", 20, tsk.Field.TASK_NAME));
    columns.append(tsk.visualization.GanttChartColumn("Start", 100, tsk.Field.TASK_START));
    columns.append(tsk.visualization.GanttChartColumn("End", 100, tsk.Field.TASK_FINISH));
    columns.append(tsk.visualization.GanttChartColumn("Predecessors", 150, tsk.Field.TASK_PREDECESSORS));
    columns.append(tsk.visualization.GanttChartColumn("Successors", 150, tsk.Field.TASK_SUCCESSORS));
    columns.append(tsk.visualization.GanttChartColumn("Duration", 50, tsk.Field.TASK_DURATION));
    options.view = tsk.visualization.ProjectView(columns);

    prj.save('C:....\' + "...",options)

**Comment by sva1000** [comment]
I've encountered the same issue: when you try to open .csv file using Excel's File\Open command, it assumes that separator is semicolon.
In order to open csv with comma separator "Data/From Text/CSV" command should be used. See more details
here: https://www.copytrans.net/support/how-to-open-a-csv-file-in-excel/

**Comment by projectmanagerspain** [comment]
Yes, you are right, it is working!
Thank you very very much.
Roser.

**Comment by sva1000** [comment]
TASKSNET-10912 was fixed in version 23.7, so the scenario should work for CsvTextDelimiter.SEMICOLON.
