### ISSUE TITLE
I want to create/build a ppt with native charts

### ISSUE THREAD

**Issue by avi-nehama** [aspose-free-consulting/projects#31]
Hello,

My company provides its customers with an online report that contains various visualizations such as charts, images and textual elements.   There are two requirements that hold us back at the moment:
1.  Granular control of chart colors 
2.  Dynamic display of labels, i.e. handling labels that are too long ("too long" being a relative term based on the chart size)
In addition, we need to support multiple master slides while creating the ppt file.

Our project is built in Python (2.7) and runs on Linux.

I would love to talk before you spend any effort on this.

**Comment by mudassirfayyaz** [comment]
@avi-nehama ,

Questions from Aspose.Slides team:
My company provides its customers with an online report that contains various visualizations such as charts, images and textual elements.

Aspose.Slides has no front end component associated with it. Therefore, it does not provide any viewer. However, the API does support exporting presentation slides to [HTML](https://docs.aspose.com/display/slidesnet/Convert+Powerpoint+PPT+and+PPTX+to+HTML), [SVG](https://docs.aspose.com/display/slidesnet/Presentation+Viewer#PresentationViewer-GeneratinganSVGImagefromaSlide) or [generating slide thumbnails](https://docs.aspose.com/display/slidesnet/Presentation+Viewer#PresentationViewer-CreatingSlidesThumbnailImage). Will this suffice your needs that you generate any of these output  for respective display in your online page.


1.	Granular control of chart colors
Do you mean by setting the chart data points colors here. One thing that we like to clarify here is that Aspose.Slides supports and allow to manipulate only MSO charts supported in PowerPoint. It does not support any other chart type that are available in different web viewing components or themes. The API allows you liberty for setting the chart datapoints (chart bars or line) colors. You can then generate the SVG, thumbnail or HTML of slide with chart and its respective display where ever you intend to.

2.	Dynamic display of labels, i.e. handling labels that are too long ("too long" being a relative term based on the chart size)

Aspose.Slides lets you work with chart labels. There is NO provision of dynamic display of labels as it is not even supported in PowerPoint too. However, API does allow you to [set the custom text](https://docs.aspose.com/display/slidesnet/Formatting+Charts#FormattingCharts-DisplayingPercentageAsLabels) for chart data label, setting its position within chart plot area and formatting text inside chart label. 

3.	In addition, we need to support multiple master slides while creating the ppt file.
In any PowerPoint presentation, there can be multiple master slides. Each master slide has set of different layout slides. So, any normal slide using a particular master actually utilize any of Layout Slide in that particular master slide. In case of Aspose.Slides, you can have as many as you like to have master slides in presentation. The normal slides in your presentation can utilize multiple master slides. But it is pertinent to mention that at any given time, one normal slide can only be associated with any one layout slide inside a particular master slide. I suggest you to please [visit this documentation article](https://docs.aspose.com/display/slidesnet/Slide+Master#SlideMaster-WhatisSlideMaster) for your convenience about available support.


4. Our project is built in Python (2.7) and runs on Linux.

I like share that we do not have any examples in Python but in other languages like C# and Java at the moment. You may consider using Aspose.Slides for .NET in your application via **[pythonnet runtime](http://pythonnet.github.io/)**, but with additional customization of  library. Generally, .NET Framework Aspose.Slides can be used via pythonnet, to run .NET Core Aspose.Slides pythonnet. The other option available is it to use REST based API Aspose.Slides for Cloud that provides the [SDKs in different languages including Python](https://docs.aspose.cloud/display/slidescloud/Available+SDKs) to suit your requirements.

I have elaborated the features that API can offer and mechanisms in which it can be used. I hope the shared information will be helpful to you.

**Comment by avi-nehama** [comment]
Hello and thank you for the detailed reply.   I'd like to mention that we
currently use the popular python-pptx
<https://python-pptx.readthedocs.io/en/latest/> package, are you familiar
with it?  Can you please tell what functionality the Python SDK provide
that python-pptx does not?

Regards,
Avi.

**Comment by tilalahmad** [comment]
@avi-nehama 

I’m afraid I’m not familiar with the python-pptx. However, after looking into the supported feature list of [python-pptx](https://python-pptx.readthedocs.io/en/latest/#feature-support) and [Aspose.Slides](https://docs.aspose.com/display/slidesnet/Features+Overview), I can confirm Aspose.Slides supports more features. Furthermore, please note Aspose.Slides Cloud is developed on top of the Aspose.Slides for .NET. So it inherits almost all of the features of Aspose.Slides for .NET except Header & Footers, Shapes in layout/master Slides and some other recent features like text highlighting and alternating hyperlinks. These features will be supported in Aspose.Slides Cloud in the near future.

[Aspose.Slides Cloud SDK for Python](https://github.com/aspose-slides-cloud/aspose-slides-cloud-python) is a wrapper around the REST APIs, that allows you to work with Aspose.Slides Cloud REST APIs in Python. All you need is to [sign up](https://docs.aspose.cloud/display/totalcloud/Creating+and+Managing+Account) with the Aspose Cloud service. Once you have signed up, you are ready to try the powerful file processing features offered by Aspose.Slides Cloud.
