### ISSUE TITLE
I want a simple Java project on maven to extract text from PDF

### ISSUE THREAD

**Issue by markkerzner** [aspose-free-consulting/projects#312]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

I want a simple Java project on maven to extract text from PDF

< which platform you're working on -- operating system, development environment etc.> 

Ubuntu, Intelliej

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by asadalikhan90** [comment]
@markkerzner 

You can simply create a maven project, [include dependency of Aspose.PDF for Java](https://docs.aspose.com/pdf/java/installation/#define-asposepdf-for-java-api-dependency) and use linked code example to [extract text from PDF](https://docs.aspose.com/pdf/java/search-and-get-text-from-pdf/). However, if you notice any issues, please feel free to create a topic in our dedicated [support forum](https://forum.aspose.com/c/pdf) which the right place for such discussions and we will assist you there accordingly.

**Comment by markkerzner** [comment]
[ERROR] Failed to execute goal on project backend: Could not resolve dependencies for project com.casify:backend:jar:1.0-SNAPSHOT: Could not find artifact com.aspose:aspose-pdf:jar:21.7 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by markkerzner** [comment]
I found that i had to include this

<repositories>
        <repository>
            <id>AsposeJavaAPI</id>
            <name>Aspose Java API</name>
            <url>https://repository.aspose.com/repo/</url>
        </repository>
    </repositories>
