### ISSUE TITLE
What is the memory usage of this software when handling file merging?

### ISSUE THREAD

**Issue by swoneeye** [aspose-free-consulting/projects#313]
I would like to know how much memory will be used to merge three 1000 page docx files with this software? When I use POI for processing, it will occupy a large amount of memory and cause the program to OOM.

**Comment by AlexNosk** [comment]
@swoneeye Memory usage depends on many factors, such as document file format, document complexity and it's content. Please see our documentation for more information:
<https://docs.aspose.com/words/net/memory-requirements/>

For reducing memory usage upon processing extremally large documents, you can try using [LoadOptions.TempFolder](https://reference.aspose.com/words/net/aspose.words.loading/loadoptions/tempfolder/), [SaveOptions.TempFolder](https://reference.aspose.com/words/net/aspose.words.saving/saveoptions/tempfolder/) and [SaveOptions.MemoryOptimization](https://reference.aspose.com/words/net/aspose.words.saving/saveoptions/memoryoptimization/) properties.
