### ISSUE TITLE
Wrong year in the date 

### ISSUE THREAD

**Issue by projectmanagerspain** [aspose-free-consulting/projects#314]
Hello,
   i want to load a proyect and the year is wrong in start and finish dates (the year is always 2000).
   I do not know why is picking 2000 all the time.
   This is my code in python, can you have a look? Thanks a lot.
   
   import aspose.tasks as tsk
   
    prj = tsk.Project('...\' + "...")

    
    options = tsk.saving.CsvOptions()
    options.text_delimiter = tsk.saving.CsvTextDelimiter.COMMA
    columns = []
    columns.append(tsk.visualization.GanttChartColumn("Summary", 20, tsk.Field.TASK_SUMMARY));
    columns.append(tsk.visualization.GanttChartColumn("Summary name ", 20, tsk.Field.TASK_SUMMARY_NAME));
    columns.append(tsk.visualization.GanttChartColumn("Id", 20, tsk.Field.TASK_ID));
    columns.append(tsk.visualization.GanttChartColumn("Exclusive ID", 20, tsk.Field.TASK_UNIQUE_ID));
    columns.append(tsk.visualization.GanttChartColumn("Percentage completed", 20, tsk.Field.TASK_PERCENT_COMPLETE));
    columns.append(tsk.visualization.GanttChartColumn("Name", 20, tsk.Field.TASK_NAME));
    columns.append(tsk.visualization.GanttChartColumn("Start", 20, tsk.Field.TASK_START));
    columns.append(tsk.visualization.GanttChartColumn("End", 20, tsk.Field.TASK_FINISH));
    columns.append(tsk.visualization.GanttChartColumn("Predecessors", 150, tsk.Field.TASK_PREDECESSORS));
    columns.append(tsk.visualization.GanttChartColumn("Successors", 150, tsk.Field.TASK_SUCCESSORS));
    columns.append(tsk.visualization.GanttChartColumn("Duration", 50, tsk.Field.TASK_DURATION));
    
    prj.date_format=tsk.DateFormat.DATE_DD_MM_YYYY
    options.view = tsk.visualization.ProjectView(columns);

    prj.save('.....' + "........",options)

**Comment by sva1000** [comment]
@projectmanagerspain ,
it's a evaluation version limitation: https://docs.aspose.com/tasks/net/licensing/.

You can apply for a temporary license to remove limitation:
 
https://purchase.aspose.com/temporary-license/
