### ISSUE TITLE
tags

### ISSUE THREAD

**Issue by smanchem30** [aspose-free-consulting/projects#316]

**Comment by smanchem30** [comment]
Technology : Java , Aspose

**Comment by AlexNosk** [comment]
@smanchem30 Could you please attach your sample input and output documents here for testing? We will check the issue and provide you more information.

Also, please note the main place for getting support is Aspose.Words support forum <https://forum.aspose.com/c/words/8>. So, please post your further questions in the forum to get timely response.

**Comment by smanchem30** [comment]
way of implementation changed
