### ISSUE TITLE
I have a visio file, that has a shape with 3 level child shapes. I'm reading and printing the shape in QT C++. Should I cosider the X, Y position for the placement of a child object with reference to immediate parent X, Y pos or 1st level parent's X, Y pos?

### ISSUE THREAD

**Issue by James-Arulraj** [aspose-free-consulting/projects#317]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by asadalikhan90** [comment]
@James-Arulraj 

Would you please share your sample Visio document for our reference? Also, it would be great if you can please post this topic in official [Aspose.Diagram](https://forum.aspose.com/c/diagram/17) support forum where you can share your files easily and it is recommended place to discuss such matters. We will further proceed to assist you accordingly.
