### ISSUE TITLE
Japanese garbled code problem when using apose to convert RTF files to PDF on Linux

### ISSUE THREAD

**Issue by mlionxy** [aspose-free-consulting/projects#318]
Japanese garbled code problem when using apose to convert RTF files to PDF on Linux
I have no problem using Windows. I tried to install CSEUCPKDFMTJAPANESE and utf-8 Character encoding on the Linux server, and installed the Japanese font library,
But the conversion still failed
![Screenshot 2023-06-25 162112](https://github.com/aspose-free-consulting/projects/assets/19201712/076e3ff2-7d2b-49e4-a3c1-5c43281ae003)
Can you help me solve this problem

**Comment by mlionxy** [comment]
set("asposeWordsVersion", "21.5.0")

**Comment by AlexNosk** [comment]
@mlionxy  Please note, to build an accurate document layout the fonts are required. If Aspose.Words cannot find the fonts used in the document the [fonts are substituted ](https://docs.aspose.com/words/java/manipulate-and-substitute-truetype-fonts/). This might lead into the layout and appearance difference. You can implement [IWarningCallback](https://reference.aspose.com/words/java/com.aspose.words/iwarningcallback/) to get a notification when font substitution is performed.
The following articles can be useful for you:
https://docs.aspose.com/words/java/specify-truetype-fonts-location/
https://docs.aspose.com/words/java/install-truetype-fonts-on-linux/
Please try either installing or providing the fonts required to render the document. This should resolve the problem.

If the problem still persist, please attach your input and output documents here for our reference. We will check the issue and provide you more information. 

Also, please note the main place for getting support is Aspose.Words support forum https://forum.aspose.com/c/words/8. So, please post your further questions in the forum to get timely response.
