### ISSUE TITLE
Client credentials

### ISSUE THREAD

**Issue by sfrancesco1** [aspose-free-consulting/projects#319]
I recently signed-up for Aspose Curl API to convert docx to pdf formats.  I have tried to utilize the Client ID and Client Secret Key provided by the application site, but was rejected when trying to attain oAuth key.  Am I using the correct keys presented within the application dashboard?

utilizing the below
curl -v "https://api.aspose.cloud/oauth2/token" \
-X POST \
-d 'grant_type=client_credentials&client_id=$clientID&client_secret=$secretKey' \
-H "Content-Type: application/x-www-form-urlencoded" \
-H "Accept: application/json"

Steven Francesco / email sfrancesco@coherecyber.com

**Comment by tilalahmad** [comment]
@sfrancesco1 

Please note that Aspose Cloud APIs use JSON Web Token(JWT) for API request authentication, OAuth2 is obsolete now. Please check the following documentation for more details.

[Authenticating Aspose Cloud API Requests](https://docs.aspose.cloud/total/getting-started/rest-api-overview/authenticating-api-requests/#what-is-a-json-web-token-jwt)

Sample cURL command to get the access token:

```
# Get Client ID and Client Secret from https://dashboard.aspose.cloud/
curl -X POST "https://api.aspose.cloud/connect/token" -d "grant_type=client_credentials&client_id=xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx&client_secret=xxxxxxxxxxxxxxxxx" -H "Content-Type: application/x-www-form-urlencoded" -H "Accept: application/json"
```
