### ISSUE TITLE
Company wants to create Java service to convert complex HTML that contains SVG diagrams to PDF (in result pdf text in Svg images must be selectable and searchable)

### ISSUE THREAD

**Issue by Giedrius14** [aspose-free-consulting/projects#32]
Before buying the license we want to try out this capability:
We want to convert in Java complex HTML (that contain SVG diagrams) to PDF (in result pdf text in Svg images must be selectable and searchable).

![image](https://user-images.githubusercontent.com/13120209/75870252-6a5b9d80-5e13-11ea-9ac1-dc442cacb7f2.png)

[fileExample.zip](https://github.com/aspose-free-consulting/projects/files/4286741/fileExample.zip)

**Comment by asadalikhan90** [comment]
@Giedrius14 

Thanks for showing interest in our API.

The HTML file that you shared contains SVG image reference URL in it which renders as a complete image. If you convert this file using both Aspose.PDF or Aspose.HTML, it would render as an image inside generated PDF. On the other hand, Aspose.PDF provides the feature to convert SVG image into PDF where SVG data would be drawn as graphics inside PDF and text objects will be searchable as well.

```
SvgLoadOptions svgoptions = new SvgLoadOptions();
Document doc = new Document(dataDir + "Diagram.html", svgoptions);
doc.save(dataDir + "HTMLtoPDF_20.1.pdf");
```

From your post, it seems you are interested in Aspose.HTML for Java. The required feature request has been logged as **HTMLJAVA-364** in our issue tracking system for the sake of implementation. We will surely inform you as soon as the feature is available. Please spare us some time.

We are sorry for the inconvenience.

**Comment by Giedrius14** [comment]
What about if  in the HTML file  you have an entire SVG (not a svg url)
no it seems to fail:
![image](https://user-images.githubusercontent.com/13120209/75900005-f0dca300-5e44-11ea-800a-6742a3506ae8.png)

[diagramSVG.zip](https://github.com/aspose-free-consulting/projects/files/4288385/diagramSVG.zip)

**Comment by asadalikhan90** [comment]
@Giedrius14 

We used the following code snippet with Aspose.PDF for Java 20.2 and your SVG data was successfully converted into PDF. For your kind reference, an output PDF is also attached:

```
SvgLoadOptions svgoptions = new SvgLoadOptions();
Document doc = new Document(dataDir + "diagramSVG.html", svgoptions);
doc.save(dataDir + "HTMLtoPDF_20.2.pdf");
```

[HTMLtoPDF_20.2.pdf](https://github.com/aspose-free-consulting/projects/files/4289296/HTMLtoPDF_20.2.pdf)

**Comment by arjanalt** [comment]
Is my understanding correct that when HTMLJAVA-364 is implemented then SVG diagrams that are referenced within an html template will become searchable?

**Comment by asadalikhan90** [comment]
@arjanalt 

Yes, your understandings are correct. We will inform you as soon as the feature is implemented and available to use.

**Comment by shahzad-latif** [comment]
@Giedrius14 @arjanalt 

Could you guys please move your query to our relevant forum: https://forum.aspose.com/c/html? The reason is through the forums, you guys will be automatically updated once this issue is resolved, while this thread might be missed. The reason is, this space is only reserved for consulting projects. 

I would appreciate your cooperation. I would have moved it myself, but at github we don't have your email address, which is required to post a query in the forums. Thanks

**Comment by arjanalt** [comment]
Is there a way to move the entire discussion to forum.aspose.com? Or should we copy the initial description of the problem to a new topic there?

**Comment by shahzad-latif** [comment]
@arjanalt ,

You can create a new thread there and link this page instead of copying the whole discussion. 

I'm afraid, github doesn't allow to move a thread/discussion somewhere else. So just creating a new thread and linking this page would be good enough. 

@Giedrius14, @asadalikhan90  FYI.

**Comment by arjanalt** [comment]
It appears that Giedrius had already recreated the discussion in forum.aspose.com : https://forum.aspose.com/t/convert-complex-html-that-contains-svg-diagrams-to-pdf-in-result-pdf-text-in-svg-images-must-be-selectable-and-searchable/209619

**Comment by shahzad-latif** [comment]
@arjanalt 

That's great. I just checked and my colleague has already logged the issue in our issue tracking system. Please make sure you're watching that thread (watching option under the thread) so that you're also properly notified. Thanks.
