### ISSUE TITLE
word to pdf, the end is more than one letter of the alphabet, the automatic line feed, how not to let the line feed.

### ISSUE THREAD

**Issue by leiyong88** [aspose-free-consulting/projects#321]
word to pdf, the end is more than one letter of the alphabet, the automatic line feed, how not to let the line feed.

windows,

**Comment by AlexNosk** [comment]
@leiyong88 Could you please attach your input and output documents here for testing? We will check the issue and provide you more information. 

PS: The main place or getting support is Aspose.Words support forum. So please post your questions in the forum to get timely response:
https://forum.aspose.com/c/words/8

**Comment by leiyong88** [comment]
When I convert word to pdf, I have this problem.
![image](https://github.com/aspose-free-consulting/projects/assets/67526904/71037fa2-8db8-400b-a8e1-cd8b177024ef)

[mb.docx](https://github.com/aspose-free-consulting/projects/files/11890586/mb.docx)
[mb_result.pdf](https://github.com/aspose-free-consulting/projects/files/11890587/mb_result.pdf)

**Comment by AlexNosk** [comment]
@leiyong88 As I can see you are using a very old version of Aspose.Words.  The problem is not reproducible using [the latest 23.6 version of Aspose.Words.](https://releases.aspose.com/words/java/). I would suggest you to update to the latest version to resolve the problem.
