### ISSUE TITLE
UpdateText 对文本层使用该方法 原有的字体并没有被使用，没有字体效果

### ISSUE THREAD

**Issue by kkgg0521** [aspose-free-consulting/projects#322]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by awaishafeez** [comment]
@kkgg0521 

请关注您的其他帖子以了解任何进一步的程序。 谢谢。
https://github.com/aspose-free-consulting/projects/issues/320
