### ISSUE TITLE
Change font type and size in Aspose Words Cloud not working

### ISSUE THREAD

**Issue by mtoportales** [aspose-free-consulting/projects#323]
We're having trouble changing the font type and font size when exporting to Word through the service.

We are following the example of the documentation: https://docs.aspose.cloud/words/paragraphs/update-font-properties/ for Java and the service does not return the document with the changed font and size.

No error is thrown, the service only returns the original document without changes.

Our code is as follows:

WordsApi wordsApi = new WordsApi(credentials.getAsposeClientId(), credentials.getAsposeClientSecret(), null);
ConvertDocumentRequest convertDocumentRequest = new ConvertDocumentRequest(html.getBytes(StandardCharsets.UTF_8), "DOCX", null, null, null, null, null, null, null);
convertedDocument = wordsApi.convertDocument(convertDocumentRequest);
Font requestFontDto = new Font();
requestFontDto.setName("Calibri");
requestFontDto.setSize(11.0);
UpdateRunFontOnlineRequest updateRequest = new UpdateRunFontOnlineRequest(convertedDocument, "paragraphs/0", requestFontDto, 0, null, null, null, null, null, null);
UpdateRunFontOnlineResponse updateRunFontOnlineResponse = wordsApi.updateRunFontOnline(updateRunFontOnlineRequest);

We have also tested via Postman to the service: https://api.aspose.cloud/v4.0/words/online/put/paragraphs/0/runs/0/font with the parameters:

Document --> data:application/vnd.openxmlformats-officedocument.wordprocessingml
FontDto --> {"Name","Calibri","Size","11.0"}

And we get the same response, the original document without any changes.

Could you tell us if we are doing something wrong or how we can proceed to change the font and size in the document?

Thanks.

**Comment by YaroslawEkimov** [comment]
I have just tested the specified scenario, and I didn't find any issues. The documents were returned with the changed font. Could you please share the document that you tried to update? Additionally, please double-check what exactly the 'paragraphs/0/runs/0' path points to. It could be some text in the header/footer if you have one.

**Comment by mtoportales** [comment]
@YaroslawEkimov 
Thanks for you response, we have managed to change the font but we want to change it throughout the document, how can we do it?

**Comment by mtoportales** [comment]
@YaroslawEkimov 
Ok, thanks, we think it's quite useful that such functionality exists.
