### ISSUE TITLE
I want to create/build automatic PDF translator tool

### ISSUE THREAD

**Issue by Marant2000** [aspose-free-consulting/projects#324]
I'm trying to test if it will be possible to create a tool allowing translation of the existing pdf documents to other language versions. The main idea is to loop through all texts, extract a single "text fragment", query external API for translation, and then replace the original text with translated one.

My main concern was if the document will be still correctly formatted after such operation (if the document layout will be intact). 

I found an example ([Text Replacement should automatically re-arrange Page Contents](https://docs.aspose.com/pdf/net/replace-text-in-pdf/#text-replacement-should-automatically-re-arrange-page-contents)), however it seems not to work in my case - e.g. if the replaced text is much longer, line is not fitting on the page (text goes outside the page and is cut then). Also, I saw a problem with highlighted texts - I need to be able to detect which part of the sentence is highlighted, but I do not see any property of TextFragment object allowing me to get such information.

For my development I'm using c# with .net 7.0 in VS2022.

-------------------------------------------

Nevermind, I just saw your "offical" online service under [https://products.groupdocs.app/translation/total/pdf](https://products.groupdocs.app/translation/total/pdf) and results are very, very bad...

**Comment by asadalikhan90** [comment]
@Marant2000 

We are sorry for the disappointment. We request you please share any sample PDF along with an expected output. We will definitely investigate the feasibilities to generate as much better results as we can.
