### ISSUE TITLE
I want to remove URI action from the PDF document dictionary

### ISSUE THREAD

**Issue by GrolarDan** [aspose-free-consulting/projects#325]
I'm using Java Aspose API library to redact PDF document from PII information.
I'm searching in text and link annotations.
But with link annotations I have a problem, because when the action targets the PDF dictionary URI object I'm not able to delete it and therefor the data are still accessible when opening pdf in text editor.

Here is the pdf part:
```
7 0 obj
<< /URI (mailto:xxxwhatevername@hotmail.com)
/S /URI >>
endobj
8 0 obj
<< /Type /Annot
/Subtype /Link
/Rect [ 21.6 703.381 151.86 713.219 ]
/C [ 0 0 0 ]
/Border [ 0 0 0 ]
/A 7 0 R
/H /I
/StructParent 1

>>
endobj
9 0 obj
<< /URI (https://www.linkedin.com/in/xxxwhatevername)
/S /URI >>
endobj
10 0 obj
<< /Type /Annot
/Subtype /Link
/Rect [ 21.6 678.887 171.31 689.194 ]
/C [ 0 0 0 ]
/Border [ 0 0 0 ]
/A 9 0 R
/H /I
/StructParent 2

>>
endobj
11 0 obj
<< /Type /Annot
/Subtype /Link
/Rect [ 21.6 664.487 183.586 674.794 ]
/C [ 0 0 0 ]
/Border [ 0 0 0 ]
/A 9 0 R
/H /I
/StructParent 3

>>
endobj

```

There are three link annotations targeted two URI objects.
Please provide me with an example how to delete not only annotation links but the URI dictionary objects too.
When the action is part of the annotation link I'm able to delete them with this code

```java
    for (Page page : pages) {
      AnnotationSelector annotationSelector = new AnnotationSelector(new LinkAnnotation(page, Rectangle.getTrivial()));
      page.accept(annotationSelector);
      List<Annotation> annotations = annotationSelector.getSelected();
      for (Annotation annotation : annotations) {
        if (annotation instanceof LinkAnnotation linkAnnotation) {
          if (linkAnnotation.getAction() instanceof GoToURIAction action) {
              obfuscateRectangle(page, linkAnnotation.getRect());
              // explicitly remove the action to remove uri from the file
              linkAnnotation.setAction(new com.aspose.pdf.GoToURIAction(" "));
              page.getAnnotations().delete(linkAnnotation);
          }
        }
      }
    }

...

  private void obfuscateRectangle(Page page, Rectangle rectangle) {
    var annot = new RedactionAnnotation(page, rectangle);
    annot.redact();
    page.getAnnotations().add(annot);
  }

```

I would appreciate any help
Daniel

**Comment by asadalikhan90** [comment]
@GrolarDan 

We need to investigate the possibility to delete/modify the URI dictionary. Can you please provide us with a sample PDF in question? We will log an investigation ticket in our issue management system and share the ID with you. Also, please note that it is recommended you post such issues in official [Aspose.PDF support forum](https://forum.aspose.com/c/pdf) which is the right place for such discussions and proper tracking of the logged tickets.

**Comment by GrolarDan** [comment]
[Masek-Profile-origin.pdf](https://github.com/aspose-free-consulting/projects/files/12000394/Masek-Profile-origin.pdf)
@asadalikhan90 

Hi, sorry for delay.
Here is one of the file I'm working with.

Thanks
Daniel

**Comment by GrolarDan** [comment]
I found finally the solution. 
Instead of setting new action `linkAnnotation.setAction(new com.aspose.pdf.GoToURIAction(" "));` 
I'm setting the action directly `action.setURI(" "))`

**Comment by asadalikhan90** [comment]
@GrolarDan 

It is nice to know that your issue has been sorted out. In case you face any issues - as requested earlier - please try to create a post in Aspose.PDF forum for a timely response.
