### ISSUE TITLE
I want to create a automated word doc that has a table-like structure using a JSON

### ISSUE THREAD

**Issue by asitparida** [aspose-free-consulting/projects#328]
< describe your free consulting project requirements briefly>
Want to generate a `table` in the document. PFA a image for a illustration. The JSON might have array of objects per row to print the tablecells.

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>
<img width="1119" alt="Screenshot 2023-07-09 at 11 18 21 AM" src="https://github.com/aspose-free-consulting/projects/assets/5743601/0def2c43-603e-4cc9-ba78-17fa91787f53">

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by AlexNosk** [comment]
@asitparida You can achieve this using 3 different ways:
1. You can generate the table from scratch using your data:
<https://docs.aspose.com/words/net/create-a-table/> 
2. You can create a table in your template and fill it with data using mail merge with regions feature:
<https://docs.aspose.com/words/net/types-of-mail-merge-operations/#mail-merge-with-regions>
3. You can create a table in your template and fill it with data using LING Reporting Engine:
<https://docs.aspose.com/words/net/outputting-sequential-data/#working-with-table-row-data-bands>

I would recommend you to choice between the last two options. If you have additional question, please ask in our [support forum](https://forum.aspose.com/c/words/8), which is the main place for getting support.

**Comment by asitparida** [comment]
Thanks for the inputs.
Will check it out.
