### ISSUE TITLE
I want to decrypt and analyze my own medical charts [pdf to text for llm/ 171+ MB per file] 

### ISSUE THREAD

**Issue by acdc-digital** [aspose-free-consulting/projects#329]
Please check if it satisfies the following requirements: 

1. It is a small project satisfying a particular scenario:
* i would like to build a chat-bot so i can analyze my own medical charts. They are provided in single document pdf's, that are huge lengths of medical history in the 1900+ page length. The data includes a variety of structured and unstructured data that has been scanned and uploaded to the hospital system. But I'm having trouble specifically with graphs and diagrams, eg; the first few pages are actual charts. The text conversion seems to work fine, but I don't want to lose the context of the document by skipping over certain information. 
2. It is related to Aspose APIs
I don't think so. I've used the web-tool provided to perform OCR on the first 26 pages, and it seems to work well with text, but per above it fails regarding finding the characters that are embedded into charts. My first impression was that there is encrption preventing the api from recognizing the text in the charts, but the adobe ocr in their acrobat portfolio seems to work fine, I don't know why it doesn't work with other upload tools, which is why i want to convert using OCR first, prior to processing the data. 
3. It takes 8 or less hours for us to complete
I don't think so, I'm just trying to figure out how to make the document readable so that as much context as possible is retained from the document in order to generate embeddings that will actually be useful. 
4. It is not a bug
not to my knowledge 
5. It is not a feature request
correct, this is not a feature request, rather than a scenario specific situation that I'm just looking for some help to resolve in order to understand my healthcare better. t

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>
I have a medical chart document where all files have been scanned and stored via a single pdf file. The file is 171 MB. For my project, I've setup a quick pipeline in Langchain and I'd like to ingest, and then retrieve information from this document via the openai gpt3.5-turboo-16k model. 

Here's a typical ingest.py file code for reference (pulled from privateGPT - confirmed functions correctly): 
"#!/usr/bin/env python3
import os
import glob
from typing import List
from dotenv import load_dotenv
from multiprocessing import Pool
from tqdm import tqdm

from langchain.document_loaders import (
    CSVLoader,
    EverNoteLoader,
    PyMuPDFLoader,
    TextLoader,
    UnstructuredEmailLoader,
    UnstructuredEPubLoader,
    UnstructuredHTMLLoader,
    UnstructuredMarkdownLoader,
    UnstructuredODTLoader,
    UnstructuredPowerPointLoader,
    UnstructuredWordDocumentLoader,
)

from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.vectorstores import Chroma
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.docstore.document import Document
from constants import CHROMA_SETTINGS

load_dotenv()

# Load environment variables
persist_directory = os.environ.get('PERSIST_DIRECTORY')
source_directory = os.environ.get('SOURCE_DIRECTORY', 'source_documents')
embeddings_model_name = os.environ.get('EMBEDDINGS_MODEL_NAME')
chunk_size = 500
chunk_overlap = 50

# Custom document loaders
class MyElmLoader(UnstructuredEmailLoader):
    """Wrapper to fallback to text/plain when default does not work"""

    def load(self) -> List[Document]:
        """Wrapper adding fallback for elm without html"""
        try:
            try:
                doc = UnstructuredEmailLoader.load(self)
            except ValueError as e:
                if 'text/html content not found in email' in str(e):
                    # Try plain text
                    self.unstructured_kwargs["content_source"]="text/plain"
                    doc = UnstructuredEmailLoader.load(self)
                else:
                    raise
        except Exception as e:
            # Add file_path to exception message
            raise type(e)(f"{self.file_path}: {e}") from e

        return doc

# Map file extensions to document loaders and their arguments
LOADER_MAPPING = {
    ".csv": (CSVLoader, {}),
    # ".docx": (Docx2txtLoader, {}),
    ".doc": (UnstructuredWordDocumentLoader, {}),
    ".docx": (UnstructuredWordDocumentLoader, {}),
    ".enex": (EverNoteLoader, {}),
    ".eml": (MyElmLoader, {}),
    ".epub": (UnstructuredEPubLoader, {}),
    ".html": (UnstructuredHTMLLoader, {}),
    ".md": (UnstructuredMarkdownLoader, {}),
    ".odt": (UnstructuredODTLoader, {}),
    ".pdf": (PyMuPDFLoader, {}),
    ".ppt": (UnstructuredPowerPointLoader, {}),
    ".pptx": (UnstructuredPowerPointLoader, {}),
    ".txt": (TextLoader, {"encoding": "utf8"}),
    # Add more mappings for other file extensions and loaders as needed
}

def load_single_document(file_path: str) -> List[Document]:
    ext = "." + file_path.rsplit(".", 1)[-1]
    if ext in LOADER_MAPPING:
        loader_class, loader_args = LOADER_MAPPING[ext]
        loader = loader_class(file_path, **loader_args)
        return loader.load()

    raise ValueError(f"Unsupported file extension '{ext}'")

def load_documents(source_dir: str, ignored_files: List[str] = []) -> List[Document]:
    """
    Loads all documents from the source documents directory, ignoring specified files
    """
    all_files = []
    for ext in LOADER_MAPPING:
        all_files.extend(
            glob.glob(os.path.join(source_dir, f"**/*{ext}"), recursive=True)
        )
    filtered_files = [file_path for file_path in all_files if file_path not in ignored_files]

    with Pool(processes=os.cpu_count()) as pool:
        results = []
        with tqdm(total=len(filtered_files), desc='Loading new documents', ncols=80) as pbar:
            for i, docs in enumerate(pool.imap_unordered(load_single_document, filtered_files)):
                results.extend(docs)
                pbar.update()

    return results

def process_documents(ignored_files: List[str] = []) -> List[Document]:
    """
    Load documents and split in chunks
    """
    print(f"Loading documents from {source_directory}")
    documents = load_documents(source_directory, ignored_files)
    if not documents:
        print("No new documents to load")
        exit(0)
    print(f"Loaded {len(documents)} new documents from {source_directory}")
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap)
    texts = text_splitter.split_documents(documents)
    print(f"Split into {len(texts)} chunks of text (max. {chunk_size} tokens each)")
    return texts

def does_vectorstore_exist(persist_directory: str) -> bool:
    """
    Checks if vectorstore exists
    """
    if os.path.exists(os.path.join(persist_directory, 'index')):
        if os.path.exists(os.path.join(persist_directory, 'chroma-collections.parquet')) and os.path.exists(os.path.join(persist_directory, 'chroma-embeddings.parquet')):
            list_index_files = glob.glob(os.path.join(persist_directory, 'index/*.bin'))
            list_index_files += glob.glob(os.path.join(persist_directory, 'index/*.pkl'))
            # At least 3 documents are needed in a working vectorstore
            if len(list_index_files) > 3:
                return True
    return False

def main():
    # Create embeddings
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)

    if does_vectorstore_exist(persist_directory):
        # Update and store locally vectorstore
        print(f"Appending to existing vectorstore at {persist_directory}")
        db = Chroma(persist_directory=persist_directory, embedding_function=embeddings, client_settings=CHROMA_SETTINGS)
        collection = db.get()
        texts = process_documents([metadata['source'] for metadata in collection['metadatas']])
        print(f"Creating embeddings. May take some minutes...")
        db.add_documents(texts)
    else:
        # Create and store locally vectorstore
        print("Creating new vectorstore")
        texts = process_documents()
        print(f"Creating embeddings. May take some minutes...")
        db = Chroma.from_documents(texts, embeddings, persist_directory=persist_directory, client_settings=CHROMA_SETTINGS)
    db.persist()
    db = None

    print(f"Ingestion complete! You can now run privateGPT.py to query your documents")

if __name__ == "__main__":
    main()"

< which platform you're working on -- operating system, development environment etc.> 
I am working within VS-studio. I work on a mac studio m1 max. My OS is Mac Ventura 13.4.1. I write in Python. 

<attach input documents>
I've attached the first 26 pages of my patient records. This file is 594 KB, and includes both text that cannot be recognized in the current OCR tools, and text that can be. To be able to retain all the text in the included file would be success. 

[10- K867210 Simon, Theodore.pdf](https://github.com/aspose-free-consulting/projects/files/11995821/10-.K867210.Simon.Theodore.pdf)

<attach any sample required output documents if you have> 
Here are some snippets from the PDF to OCR tool. These are snippets from the same document provided, and attached; 
1. Pages 1-10 (guessing based on output length, no mention of pages in the final file):                                                                                                        "5 %
                                                H* H
                                                 t  3                                                 V:
                                                                                                                * 3
               Q                                  
                                                                                                               (Q (t
               Q                                                                                      *3   ęt
               *t                                (                                                         E:ii (D r*
                                                                                                                 (D
               ţţ                               Q I                                                   Jż
                                                                                                           $    )J
               J                                 C                  (
                                                  (                                                             * )
               (/                                                   
                                                                                                           Q    ( t
            *  Ö                                  
                                         "     

2. Pages 10+ (per above, not totally important), this is where the recognized text begins:
"]4 Feb 202ß
Dr. Michael J. Vincer
IIK Health Centre
Nesnatal Pediatrics
Halifax. NS B3k ÉR8
Phsne ţ:
Next of Kin:
Rpt #:
Lscatian Code:
Seen in Clinic
Dear Col leagues:
I evaluated Baby Siman (Theo) in cnsultatisn on February 3, 2020 and
again February 4. 2020.
REÀSOt FOR CONSULTATTON:
Irrsgular heart rate.
MÀTERNÀL ÀND OBSTETRIC HISTORY:
G1PU healthy mother. Reassuring antenatal"

<attach any additional supporting material to help us understand the requirement>
I just want the code to be able upload and pre-process the file, prior to the ingestion portion of my application. The sample file provided is only 26 pages, whereas the full text is over 1900 pages and 171 MB in length. While the objective here is character recognition in the unstructured charts, and so on, it should be noted that my medical files are gigantic documents. I'd like to make this as clean as possible. upload, chop the document if necessary, transition to ocr text realization, and then I can begin with cleaning and partitioning further from there in order to generate embeddings. 

As always, thanks for your help. I've been using the web-application and its various OCR tools, but I'll begin experimenting with the API now.

**Comment by acdc-digital** [comment]
here's a better ingest file:
import os
import json
from tqdm import tqdm
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.document_loaders import UnstructuredAPIFileLoader
from langchain.vectorstores import MyScale, MyScaleSettings

# Set API keys as environment variables for security
os.environ['OPENAI_API_KEY'] = "sk-hX**********JthHPQ3uEhtJs1oebUTTQ"
os.environ['MYSCALE_API_KEY'] = "6B71Num********apGBjCEWqM27p"

# Configure MyScale settings
config = MyScaleSettings(host='msc-****.us-east-1.aws.myscale.com', port=456, username='smatty662', password='passwd_CA********7GNt')
index = MyScale(OpenAIEmbeddings(), config)

# Initialize LlamaIndex components
embed_model = OpenAIEmbeddings()

def process_files(directory):
    # Initialize an empty list to hold file loaders
    file_loaders = []

    # Loop through all files in the directory
    for filename in os.listdir(directory):
        # Check if the file is a PDF
        if filename.endswith(".pdf"):
            # Construct the full file path
            file_path = os.path.join(directory, filename)

            # Create a file loader for the PDF file
            # The file loader uses the MyScale API key and a 'fast' strategy
            file_loader = UnstructuredAPIFileLoader(
                file_path,
                api_key=os.environ['MYSCALE_API_KEY'],
                strategy="fast",  # use the 'fast' strategy
                request_kwargs={"timeout": 600}  # set a timeout of 600 seconds
            )

            # Add the file loader to the list
            file_loaders.append(file_loader)

    # Create a text splitter
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=5500, chunk_overlap=1000)

    # Wrap your file_loaders with tqdm for progress bar
    # Loop through each file loader and process the file
    for loader in tqdm(file_loaders, desc="Processing files"):
        # Load the document
        doc = loader.load()

        # Split the document into chunks
        docs = text_splitter.split_documents(doc)

        # Initialize an empty dictionary to hold the embeddings
        doc_embeddings = {}

        # Loop through each chunk
        for i, d in enumerate(docs):
            # Set the source metadata to the file path
            d.metadata = {"source": loader.file_path}

            # Generate embeddings for the chunk and store them in the dictionary
            doc_embeddings[i] = embed_model.embed_documents([d.page_content])

            # Add the chunk to the LlamaIndex
            vector_store.add_documents([d])

        # Write the embeddings to a JSON file
        with open(f"{loader.file_path}.json", "w") as f:
            f.write(json.dumps(doc_embeddings, default=str))

# Directory containing PDF files to process
directory = "/Users/ma*****/Documents/-/Source_Documents"
# Call the process_files function to process all PDF files in the directory
process_files(directory)

**Comment by acdc-digital** [comment]
I am using Python, on my mac.

**Comment by asadalikhan90** [comment]
@acdc-digital 

In that case we would recommend you to use Aspose.OCR Cloud API. Also, the online free app from Aspose implements Aspose.OCR Cloud in its backend. We request you please create a post in official [Aspose.OCR Cloud support forum](https://forum.aspose.cloud/) where your concerns can be addressed accordingly. Please note that such matters are always suggested to be discussed in the dedicated support forum.

**Comment by acdc-digital** [comment]
Wonderful, thank you for pointing me in the right direction. I'll hop into the fourm and take it from here. I appreciate the quick response on Aspose.OCR and I'll begin to research that component. Cheers.
