### ISSUE TITLE
Filling out PDF documents with no textfields

### ISSUE THREAD

**Issue by phecdaret** [aspose-free-consulting/projects#33]
Dear Aspose,

I’m working on a web site that handles the authorization process of psychologists. On the web site, the users can enter and save their data, and then I will create/generate the official required documents for them. 

I need to find out, if I can use Aspose for filling out the official required documents that I do not own.  I need to fill out the “dotted lines”, checkboxes and the table in the following document:

[ansogningsskema.pdf](https://github.com/aspose-free-consulting/projects/files/4355050/ansogningsskema.pdf)

Mant thanks for your help.

Kenneth

**Comment by shahzad-latif** [comment]
@phecdaret 

We're investigating your requirement and will get back to you shortly. We'll ask if further information will be required.

**Comment by asadalikhan90** [comment]
@phecdaret 

We have checked the PDF document shared by you and would like to share with you that Aspose.PDF allows you to [fill forms in PDF documents](https://docs.aspose.com/display/pdfnet/Working+with+Forms). Sadly, your PDF document does not contain any form fields. However, we will still investigate the feasibility of achieving what you require. Would you kindly share if this is the only PDF that you need to fill or there could be different documents with different content structures? We will further proceed to assist you accordingly.

**Comment by phecdaret** [comment]
@asadalikhan90 

Thanks for your reply.

There are several documents with different structures that need to be filled. I have attached them.

[arbejdsforhold-ansat.pdf](https://github.com/aspose-free-consulting/projects/files/4394054/arbejdsforhold-ansat.pdf)
[arbejdsforhold-selvstaendig-1.pdf](https://github.com/aspose-free-consulting/projects/files/4394055/arbejdsforhold-selvstaendig-1.pdf)
[egenterapi.pdf](https://github.com/aspose-free-consulting/projects/files/4394056/egenterapi.pdf)
[supervision.pdf](https://github.com/aspose-free-consulting/projects/files/4394057/supervision.pdf)

Thanks.
Kenneth

**Comment by asadalikhan90** [comment]
@phecdaret 

All of your PDF documents contain only textual information, not form fields. We are afraid that filling them programmatically would not be feasible as text placement over pages without knowing the target location will produce unwanted results. You could try [replacing text](https://docs.aspose.com/display/pdfnet/Replace+Text+in+a+PDF+Document) if there are some text markups present in the documents OR you could [add text stamps](https://docs.aspose.com/display/pdfnet/Adding+Stamp+in+a+PDF+file#AddingStampinaPDFfile-AddingTextStampinthePDFFile) if you have coordinates of targeted location over a page.

Adding more to our feedback, we will still investigate if there could be some way to achieve what you require and for the purpose, we have logged an investigation ticket in our issue tracking system as **PDFNET-47889**. We will investigate the logged ticket in details and inform you as soon as we have some certain updates regarding its resolution. Please spare us some time.

**Comment by phecdaret** [comment]
@asadalikhan90 

Adding text placeholders, N1, N2…NN (dummytext), and then overwriting them programmatically might work. Not pretty, but pragmatic. 

Thanks for investigating further. I will be looking forward to your findings.

All best
Kenneth

**Comment by asadalikhan90** [comment]
@phecdaret 

Yes, you are right. Replacing the text (i.e. placeholders) can work in your scenario if PDF document has it. The helpful link to perform text replacement has already been shared in our previous response. Nevertheless, we will certainly inform you as soon as we have some findings regarding the logged ticket.
