### ISSUE TITLE
I want to create/build to analyze a file to see if it is an XFA PDF, and if so convert it to a non XFA PDF format

### ISSUE THREAD

**Issue by JohnFx** [aspose-free-consulting/projects#332]
I'd like to use the Aspose API to analyze a PDF file to see if it is an XFA form, and if so convert it to a standard PDF saving the values entered into the form as a static image of the PDF as it might render in Adobe Acrobat. 

I need to do this because we are running another tool on these files that does not support the XFA PDF format so I'd like to pre-process them with a simple utility using Aspose before handing the file off to another tool. 

I am working in a Windows environment with C#.NET

Attached is an example of a file I have been using to test.
[XFA-PDF-Sample-test.pdf](https://github.com/aspose-free-consulting/projects/files/12045171/XFA-PDF-Sample-test.pdf)

**My test case is:**
Open this file in Adobe Acrobat and see how it renders
Run some code using Aspose to "flatten" or whatever to get rid of the XFA format
Drop the output PDF into a chrome window to render the file.

**Expected Output**
Output File Renders in chrome as close as possible to what I saw in Acrobat.

here is what I am seeing  when I run my test
![output](https://github.com/aspose-free-consulting/projects/assets/978008/737947b4-0d22-4c07-9305-325dee8263c9)

I've been playing with the free trial, but I can't get it to work the way I want. Here is my test code.

static void main()
{
    try
    {
        Console.WriteLine("Converting!");
        string filepath = @"C:\Users\jfuex\Documents\IMAGES\PDF\XFA-PDF-Sample.pdf";
        string outPath = @"C:\Users\jfuex\Documents\IMAGES\PDF\XFA-PDF-Sample-Flat.pdf";

        Aspose.Pdf.Document document = new Aspose.Pdf.Document(filepath);
        int fieldCount = document.Form.Count();
        Console.WriteLine(String.Format("formtype out: {0}- {1} {2}", document.PdfFormat, document.Form.Type.ToString(), fieldCount.ToString()));
        document.Form.Type = FormType.Static;

        //Form.FlattenSettings settings = new Form.FlattenSettings();
        document.Form.Flatten();
        document.Flatten();

        
        fieldCount = document.Form.Count();
        Console.WriteLine(String.Format("formtype out: {0}- {1}", document.PdfFormat, document.Form.Type.ToString()));
        document.Save(outPath);

        // Console.WriteLine("Success! Any key to continue");

    }
    catch (Exception x)
    {
        Console.WriteLine(x.ToString());
    }
}

**Comment by asadalikhan90** [comment]
@JohnFx 

We have already noticed your similar issue in our dedicated support forum. We at the moment are performing initial investigation and will be responding you in the [original thread](https://forum.aspose.com/t/aspose-pdf-flatten-xfa-pdf-not-working/268387) shortly.
