### ISSUE TITLE
getDoubleValue cant't get correct value for big long number,how can i get correct value?

### ISSUE THREAD

**Issue by han-chen** [aspose-free-consulting/projects#333]
There is a column in Excel which type  is Number, it's value is 20-digit number like 20230101000034177039.
when i use` cell.getDoubleValue() `it returns 2.0230101000034177E19 , it's not correct value
then i use `new BigDecimal(cell.getDoubleValue()).toPlainString()` it returns 20230101000034177024, it's also wrong.
how can i get correct value?

**Comment by amjad-sahi** [comment]
@han-chen,

We checked and it is MS Excel's limit, you cannot input such kind of number and then get it back exact number even in MS Excel manually.  Please note, MS Excel only keeps 15-digits for numeric value when you insert a number into a cell. To keep the original digits, you cannot use value as numeric type, rather you should just input/set it as string value.

Should you have further queries or comments, please use our dedicated [forums](https://forum.aspose.com/c/cells/9).

**Comment by han-chen** [comment]
> @han-chen,
> 
> We checked and it is MS Excel's limit, you cannot input such kind of number and then get it back exact number even in MS Excel manually. Please note, MS Excel only keeps 15-digits for numeric value when you insert a number into a cell. To keep the original digits, you cannot use value as numeric type, rather you should just input/set it as string value.
> 
> Should you have further queries or comments, please use our dedicated [forums](https://forum.aspose.com/c/cells/9).

Thank you for your answer. But I get this excel from the other system,  Can i change the cell from number to string when i read the excel?

**Comment by han-chen** [comment]
I try it, but lost more digital, I get data like 2.02307E+19. And I find a funny thing ,when i save as this excel to a new excel manual (no change data,no change  file extension), i can get the correct data from  the new excel. But when i try to save as by code,i can only get data like 2.02307E+19 from new file

**Comment by han-chen** [comment]
As I said，when I save as the file ,it becomes correct file. So i can't upload file. But today I think I find the reason , the file must be  covert from html by C# apose .

**Comment by amjad-sahi** [comment]
@han-chen,

To evaluate your issue we need your sample JAVA program/project. So, we request you to kindly share your sample (runnable) Java code or program with sample files to reproduce the issue on our end. We will check your issue soon.

You can also post your issues or queries in relevant [forum](https://forum.aspose.com/c/cells/9).

**Comment by han-chen** [comment]
The excel is convert from html, if we open it with sublime,it looks like :
`<tr><td style='vnd.ms-excel.numberformat:@'>20230101000034177039</td>`
so we can read it as read a html file, then we can get corrent value.
Anyway, thank you for continued help from @amjad-sahi

**Comment by amjad-sahi** [comment]
@amjad-sahi ,

Aspose.Cells processes and parses file format (e.g., XLSX) data (source XML data of the file) and works the same way as MS Excel does. As we told you, for Excel file formats, you can only keep 15-digits for a number/numeric value, this is the limit. You have to set a long number as string value by yoursleves if the digit is >=16.
