### ISSUE TITLE
I want to create/build Aspose PDF , to request to read the content from two different pdf files  and highlight the common text.

### ISSUE THREAD

**Issue by BRMT386** [aspose-free-consulting/projects#334]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by asadalikhan90** [comment]
@BRMT386 

Your requirements can be achieved using below steps:

* Extract text from PDF file

```
// Open document
Document pdfDocument = new Document(dataDir + "ExtractTextAll.pdf");

// Create TextAbsorber object to extract text
TextAbsorber absorber = new TextAbsorber();
absorber.TextSearchOptions.LimitToPageBounds = true;
absorber.TextSearchOptions.Rectangle = new Aspose.Pdf.Rectangle(100, 200, 250, 350);

// Accept the absorber for first page
pdfDocument.Pages[1].Accept(absorber);

// Get the extracted text
string extractedText = absorber.Text;
```

* Use [String.Compare](https://www.bing.com/search?form=SKPBOT&q=String.Compare) method to find out common text
* Use Highlight Annotation to [highlight the text in PDF](https://kb.aspose.com/pdf/net/how-to-search-text-and-highlight-in-pdf-using-csharp/) after searching the common text

In case you face any issues, please feel free to create a topic in [Aspose.PDF official forum](https://forum.aspose.com/c/pdf). We will further proceed to assist you accordingly.
