### ISSUE TITLE
Unable to extract custom font text from pdf to html

### ISSUE THREAD

**Issue by tzehangs** [aspose-free-consulting/projects#335]
[test.pdf](https://github.com/aspose-free-consulting/projects/files/12102262/test.pdf)
I am trying to convert this pdf to html. The text is not extracted out to the html if i use this custom font. If i changed it back to Arial font it will work. I already have the font installed in my local machine. Any settings do i missed?

Technology .NET

            HtmlSaveOptions htmlOptions = new HtmlSaveOptions();
           
            htmlOptions.SplitIntoPages = true;
            htmlOptions.FixedLayout = true;
            htmlOptions.FontSavingMode = HtmlSaveOptions.FontSavingModes.AlwaysSaveAsTTF;
            htmlOptions.RasterImagesSavingMode = HtmlSaveOptions.RasterImagesSavingModes.AsEmbeddedPartsOfPngPageBackground;
            htmlOptions.HtmlMarkupGenerationMode = HtmlSaveOptions.HtmlMarkupGenerationModes.WriteOnlyBodyContent;
            htmlOptions.SaveTransparentTexts = true;

**Comment by asadalikhan90** [comment]
@tzehangs 

Using your code snippet, we were unable to notice the issue. Can you please share how you are using the custom font? Please check the attached output we obtained in our environment using 23.7 version of the API. 
[outputHTML1.zip](https://github.com/aspose-free-consulting/projects/files/12117848/outputHTML1.zip)

Also, please note that [Aspose.PDF support forum](https://forum.aspose.com/c/pdf) is the right and the recommended place to post such inquiries and the issues where you can have timely response. You will also be able to follow up on the discussion and the issues status appropriately there. You can please create a new topic there as well and we will assist you accordingly.
