### ISSUE TITLE
I want to create a project to convert a word(docx) with catalogue to svg with clickable catalogue link. I can convert docx to svg,but the catalogue link is not work.

### ISSUE THREAD

**Issue by ZhengJvming** [aspose-free-consulting/projects#338]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by AlexNosk** [comment]
@ZhengJvming  The question is already answered in the support forum:
<https://forum.aspose.com/t/how-can-i-convert-a-word-docx-with-catalogue-to-svg-with-clickable-catalogue-link/269373>
