### ISSUE TITLE
Having a License error 

### ISSUE THREAD

**Issue by erohner55** [aspose-free-consulting/projects#339]
This is the error I am getting now.
 | $exception | {"Exception of type 'System.Exception' was thrown."} | System.Exception

This comes when the this code runs: 
Aspose.Pdf.License license = new Aspose.Pdf.License();
license.SetLicense("./Aspose.pdf.lic");

I have also tried to refer to the lic file in another directory and get the same error:
Aspose.Pdf.License license = new Aspose.Pdf.License();
license.SetLicense(@"c:\logs\Aspose.pdf.lic");

It is highly important to get this fixed as it has never happened before.

**Comment by asadalikhan90** [comment]
@erohner55 

Have you updated to the latest version lately? OR have you renewed your subscription and tried to use the new license with the older version of the API? Please make sure to test with the latest version and if issue still persist, we recommend you post your issue in [Aspose.PDF official support forum](https://forum.aspose.com/c/pdf) as it is related to the license file and we cannot discuss it in the details here. You can securely share your license file in the forum with us and we can test the case in our environment to address it.
