### ISSUE TITLE
DOC to PDF Conversion Issue

### ISSUE THREAD

**Issue by Porwal1986** [aspose-free-consulting/projects#34]
I am using Aspose.word.dll for converting DOC/DOCX file  to PDF format. It was successfully converted to PDF but one Text on middle of page is trimming from Right hand side, when i had copied that trimmed text and paste on notepad it is showing me full text/string.But when when we checked  .docx file it is correct and full text is showing. 

There is some problem in conversion from word to pdf. The Text which are trimming on PDF file have Font " OCR Regular Std". Please find attachment of same
[DOCX.pdf](https://github.com/aspose-free-consulting/projects/files/4358553/DOCX.pdf)
[Word.DOCX](https://github.com/aspose-free-consulting/projects/files/4358564/Word.DOCX)

**Comment by shahzad-latif** [comment]
@Porwal1986 

Sorry to hear about your issue.. Actually this space is just for consulting projects. For the queries like above, we have our forums where our dedicated team replies you quickly and properly. Can you please post your query in this forum https://forum.aspose.com/c/words? Our team will help you shortly. Thanks.
