### ISSUE TITLE
I want to convert win32 codes into aspose codes

### ISSUE THREAD

**Issue by ShivKode** [aspose-free-consulting/projects#342]
There are basically two things I need help in.

I am working on python win32 program codes which mainly uses xlwings and win32com.client. As I am doing the execution of these programs on AKS Linux(Common Base Linux Mariner) these programs dont work because of dependency on MS Office application. Hence, I have chosen aspose to do the same functionality which xlwings and win32com.client are doing.

I have successfully completed conversion for various codes with help from the forum, but I am stuck in mainly 2 scenarios that are:

1. To refresh pivot tables (https://forum.aspose.com/t/refreshing-a-workbook/269937/9)
2. Converting wmf(windows meta file) image into jpeg image (https://forum.aspose.com/t/converting-wmf-to-jpg/269936/12)

Above I have attached the support forums links where I have reported the issues.

NOTE: Before I share any kind of file can we somehow ensure that this remains a private space not a public one.

**Comment by amjad-sahi** [comment]
@ShivKode,

Thanks for considering Aspose.

Yes, we ensure that both your threads are private, so only you and Aspose staff members could see or download your attachments. No other users could see or download your attachments. You may safely share your resource files and details in your forum threads. 

Please follow up your threads to get latest updates on your issues and requirements.
