### ISSUE TITLE
Usage of Aspose.Words with Borders

### ISSUE THREAD

**Issue by FrankUray** [aspose-free-consulting/projects#343]
Hi there

I am extracting data from my website https://briefmarken.world/ 
Based on this data I would like to generate a PDF (it will have many pages) like this (finally the PDF will have maybe 6 columns).
![image](https://github.com/aspose-free-consulting/projects/assets/31851809/81cfa668-2868-4f88-8f6d-cb9d0d284934)

I have now made a 5 column Word Template file.
I open this document using “Aspose.Words.Document” and “Aspose.Words.DocumentBuilder”.
Than I basically use WriteLn and InsertImage to insert all the data.
It looks now like this (its not too bad, just layout issues):
![image](https://github.com/aspose-free-consulting/projects/assets/31851809/3d66b7d5-cc52-497d-bfe6-4867956cfb2b)

There are two thinks I need:
-	I need a white Border around the products
-	And products should stay in the same column.
Currently, after the text is on the end of the page, the rest of the text continues on the next column.
![image](https://github.com/aspose-free-consulting/projects/assets/31851809/b9c32355-bb39-4bf6-91e7-4b8599d358fa)

Here is the code I have written for that:

_DocumentBuilder.ParagraphFormat.Alignment = Aspose.Words.ParagraphAlignment.Center;
_DocumentBuilder.InsertImage(new briefmarken.uray.windows.image.clsImage().GetThumbnailBytes((byte[])_DataRowView["Image"], 100));

_DocumentBuilder.Writeln("");
_DocumentBuilder.ParagraphFormat.Alignment = Aspose.Words.ParagraphAlignment.Justify;
_DocumentBuilder.Font.Size = 8;
_DocumentBuilder.Font.Bold = false;
_DocumentBuilder.Writeln(_DataRowView["ID"].ToString() + ": " + _DataRowView["Title"].ToString());

_DocumentBuilder.Font.Bold = true;
if (_DataRowView["PriceOffer"].ToString() == "")
{ _DocumentBuilder.Writeln("CHF " + _DataRowView["Price"].ToString()); }
else
{
    _DocumentBuilder.Write("CHF " + _DataRowView["Price"].ToString());
    _DocumentBuilder.Write("    ");
    _DocumentBuilder.Font.Color = System.Drawing.Color.Red;
    _DocumentBuilder.Write("CHF " + _DataRowView["PriceOffer"].ToString());
    _DocumentBuilder.Font.Color = System.Drawing.Color.White;
    _DocumentBuilder.Writeln("");
}

_DocumentBuilder.ParagraphFormat.Alignment = Aspose.Words.ParagraphAlignment.Center;
_DocumentBuilder.Writeln("");
_DocumentBuilder.ParagraphFormat.Alignment = Aspose.Words.ParagraphAlignment.Left;

Thanks a lot for your help and best regards
Frank Uray

**Comment by AlexNosk** [comment]
@FrankUray The easiest way to achieve what you need is using [Mail Merge](https://docs.aspose.com/words/net/mail-merge-and-reporting/) or [LINQ Reporting Engine](https://docs.aspose.com/words/net/linq-reporting-engine/). For example see the attached template for mail merge:
[in.docx](https://github.com/aspose-free-consulting/projects/files/12436002/in.docx)
As you can see I have configured a regions with two paragraphs, the first paragraph has all borders set, contains regions start and two merge fields separated by soft line break and has the following options set:
![image](https://github.com/aspose-free-consulting/projects/assets/31235892/dc9ebe42-360d-4b52-9838-4a1334fec6f6)
The second paragraph contains the region end. Here is the code I used for filling the template with data:
```cs
DataTable dt = new DataTable("Images");
dt.Columns.Add("img");
dt.Columns.Add("desc");

for (int i = 0; i < 20; i++)
    dt.Rows.Add(@"C:\Temp\img.png", $"Description of the image {i}.");

Document doc = new Document(@"C:\Temp\in.docx");
doc.MailMerge.ExecuteWithRegions(dt);
doc.Save(@"C:\Temp\out.docx");
```
Here is the produced output: 
[out.docx](https://github.com/aspose-free-consulting/projects/files/12436037/out.docx)

**Comment by FrankUray** [comment]
Hi @AlexNosk 
Thank you a lot for your message :-)
I almost got it, but in the word template (in.docx), I did not find where to add another column to Images table.
Can you give a little hint where I have to search for that ?
Thanks and best regards
Frank Uray

**Comment by FrankUray** [comment]
Hi @AlexNosk 
I managed somehow with copy/paste to add a new field.
Now, how do I change this spacing ?
![image](https://github.com/aspose-free-consulting/projects/assets/31851809/7702818e-d2d2-46da-94b7-6d1f64e99903)

Thanks a lot and best regards
Frank Uray

**Comment by AlexNosk** [comment]
@FrankUray You can simply increase paragraph spacing of the second paragraph ot simply add an additional paragraph break before it.

**Comment by FrankUray** [comment]
Hi @AlexNosk 
Thank you for your answer, but I am not sure if MailMerge is really the right thing to use.
First it is hard to format right, I dont really understand how paragraph is working.
Regarding the spacing above, I need less spacing but it did not work.

And there are several data fields I have to add code for it.
For example: I have two prices. One is the regular price and one is the offer price.
If OfferPrice is 0, then only the regular price has to be shown, else regular price has to be strike through and offer price has to be shown also.
I have no idea how I should do that ?

How about DocumentBuilder ?
There I have format options and I basically only have to find a way to make a border around it and keep it together.

Thank you again for your answer and best regards
Frank Uray

**Comment by AlexNosk** [comment]
@FrankUray I believe, mail merge is the right approach in your case, since you can format the template in MS Word, that is much easier than formatting through the code. Please see our documentation to learn how to setup template:
<https://docs.aspose.com/words/net/mail-merge-template/>
Also, in mail merge template, you can use [IF field](https://support.microsoft.com/en-gb/office/field-codes-if-field-9f79e82f-e53b-4ff5-9d2c-ae3b22b7eb5e) to show or hide content depending on the marge field value.

Of course you can fully generate the document using `DocumentBuilder` if this approach is preferable for you. Here is a simple code that generates similar document using `DocumentBuilder`:
```cs
Document doc = new Document();
DocumentBuilder builder = new DocumentBuilder(doc);

// Format page.
builder.PageSetup.Orientation = Orientation.Landscape;
builder.PageSetup.TextColumns.SetCount(5);

for (int i = 0; i < 50; i++)
{
    // Configure paragraph's border and to keep lines togather.
    builder.ParagraphFormat.Borders.LineStyle = LineStyle.Single;
    builder.ParagraphFormat.KeepTogether = true;
    builder.ParagraphFormat.KeepWithNext = true;

    // Insert image.
    builder.InsertImage(@"C:\Temp\image1.png");
    // Insert soft line break.
    builder.InsertBreak(BreakType.LineBreak);
    // Write some text content.
    builder.Write("some image description.");
    // Mode content can be inserted here. Use BreakType.LineBreak if required.
    // .....
    // Insert paragrph break.
    builder.Writeln();
    // Clear formatting of the current paragraph.
    builder.ParagraphFormat.ClearFormatting();
    builder.Writeln();
}

doc.Save(@"C:\Temp\out.docx");
```
[out.docx](https://github.com/aspose-free-consulting/projects/files/12445567/out.docx)

**Comment by FrankUray** [comment]
Hi @AlexNosk 
I am sorry for my late reply, I was away for some weeks and was not able to continue on that.
But in the meantime I was able to continue my work and it looks good now !
It is little difficult with the formatting when to use LineBreak and when Writeln, but it works :-)
Thank you a lot for your help and best regards
Frank Uray
