### ISSUE TITLE
I want to build a backend application to extract ppt data

### ISSUE THREAD

**Issue by ds-teams** [aspose-free-consulting/projects#344]
We are looking for a python based backend application to extract data details that includes (text, images, shapes, links, animations) and their location on the ppt slide

We will be working on a python platform deployed on the cloud 

![input](https://github.com/aspose-free-consulting/projects/assets/113005474/d112d97b-0dfa-4808-b701-269ae7d89d36)

![sample1](https://github.com/aspose-free-consulting/projects/assets/113005474/d6635153-4e5e-40e1-ac71-05631bb6a779)

**Comment by andreypotapovaspose** [comment]
@ds-teams,
Could you please clarify if you are using [Aspose.Slides for Python](https://products.aspose.com/slides/python-net/) or [Aspose.Slides Cloud SDK for Python](https://products.aspose.cloud/slides/python/)?

**Comment by ds-teams** [comment]
Hi, we are using Aspose.Slides Cloud SDK for Python.

**Comment by andreypotapovaspose** [comment]
@ds-teams ,
Thank you for the information. We will answer you here:
https://forum.aspose.cloud/t/how-to-extract-data-in-json-format-from-ppt-along-with-the-position-coordinates/20542
