### ISSUE TITLE
I want to create/build 

### ISSUE THREAD

**Issue by SBigDay** [aspose-free-consulting/projects#346]
![image](https://github.com/aspose-free-consulting/projects/assets/46736385/6578f8d0-33fa-4d85-a6fc-1b88bf4700a6)
将pdf中这段替换更长的文本 比如"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"  右侧会超出右侧边框了

**Comment by asadalikhan90** [comment]
恐怕我们在这里帮不了什么忙。我们请求您在我们的[专用支持论坛](https://forum.aspose.com/c/pdf) 中创建帖子以及您的示例文档和代码片段。我们将在我们的环境中测试该场景并相应地解决它。我们的专门支持论坛是发布此类问题以进行适当的跟进和解决的正确且推荐的地方。
