### ISSUE TITLE
I want to create/build 

### ISSUE THREAD

**Issue by SBigDay** [aspose-free-consulting/projects#347]
![image](https://github.com/aspose-free-consulting/projects/assets/46736385/e9954f53-2bf5-4a5e-bc4c-2fc892b364d0)
怎么将换行的字符 "中国银行"  替换成 "美国银行"

代码:
public class Test {

    public static final Set<String> set = new HashSet();

    public static void main(String[] args) {
        // Open document
        Document pdfDocument = new Document("D:\\word_test\\copy_pdf_test.pdf");

        replace(pdfDocument,"中国银行","美国银行");

        pdfDocument.save("D:\\word_test\\qq.pdf");

    }

    public static void replace( Document pdfDocument,String source,String target){
        TextFragmentAbsorber textFragmentAbsorber = new TextFragmentAbsorber(source);

        // Accept the absorber for all pages of document
        pdfDocument.getPages().accept(textFragmentAbsorber);
        // Get the extracted text fragments into collection
        TextFragmentCollection textFragmentCollection = textFragmentAbsorber.getTextFragments();

        // Loop through the fragments
        for (TextFragment textFragment :  textFragmentCollection) {
            textFragment.getRectangle();
            textFragment.setInLineParagraph(true);
            Position baselinePosition = textFragment.getBaselinePosition();
            double xIndent = baselinePosition.getXIndent();
            double yIndent = baselinePosition.getYIndent();
            if(!set.contains(baselinePosition.getXIndent() + "-" + baselinePosition.getYIndent())){
                set.add(xIndent + "-" + yIndent);
                // Update text and other properties
                textFragment.setText(target);
            }
        }
    }
}

**Comment by asadalikhan90** [comment]
@SBigDay 

请与我们分享您的示例 PDF 文档，以便我们可以在我们的环境中测试该场景并相应地解决它。但是，您可以尝试使用“\s+”运算符使用 TextFragmentAbsorber("your\s+text", new TextSearchOptions(true)); 来搜索带换行符的文本。

另请注意，为了讨论和报告此类问题，我们建议您使用我们的[专用支持论坛](https://forum.aspose.com/c/pdf)，您可以在其中安全地共享您的文件，我们可以相应地解决该问题。您还可以在那里适当地跟踪问题的进展情况。
