### ISSUE TITLE
Redact a PDF in my application where the PDF is embedded in HTML

### ISSUE THREAD

**Issue by anil8288** [aspose-free-consulting/projects#348]
Hi, I have a requirement where the user is to be shown a PDF document embedded in a webpage and the user needs the ability to redact certain parts of the PDF. The PDF files can be text or image files, meaning the texts that are shown on the document may or may not be selectable (aka Images that have been converted to PDF). I have tested the piece of code where a section of a PDF can be redacted by an annotation rectangle. But the requirement to show the PDF on a browser and the user's to be able to select the section to be redacted, is the reason I am seeking help here.
Is there an option to do this.

Thanks,
AM

**Comment by asadalikhan90** [comment]
@anil8288 

We are afraid that Aspose.PDF does not offer or come with any type of control that you can embed or integrate with you application to show the PDF documents. It can be used in the backend to perform different kind of operations on the PDF files. However, you may please check [GroupDocs.Viewer](https://products.groupdocs.com/viewer/) (one of Aspose products) which offers such functionality that you are looking for. You can also create an inquiry with your detailed requirements in the [dedicated support forum](https://forum.groupdocs.com/) where you will be assisted accordingly.

**Comment by anil8288** [comment]
Thanks for the response.

So I was able to redact the pdf in the backend (C# code) by using the coordinates of a rectangle on the document.
Is there a way to find out the coordinates of a section on the PDF so that I can pass it to the back end?

Thanks,
Anil

**Comment by asadalikhan90** [comment]
> Is there a way to find out the coordinates of a section on the PDF so that I can pass it to the back end?

@anil8288 

We are afraid that there is no way to find out the coordinates of the section on the PDF from front end or UI using the API. In the back end though, you can [search and get a text in PDF to get its position](https://docs.aspose.com/pdf/net/search-and-get-text-from-pdf/) or coordinates using Aspose.PDF.
