### ISSUE TITLE
Export tabular data to a chart in Excel and PowerPoint n IronPython

### ISSUE THREAD

**Issue by leungi** [aspose-free-consulting/projects#349]
#### Background
Our codebase is written for IronPython (a .NET implementation of Python).

The goal is to export tabular data to a chart in Excel and PowerPoint.

We currently have Aspose Total .NET license.

#### Development Environment
OS: Windows 10.

Language: IronPython

#### Input Data
Any time-series data.

#### Output
Time-series data plotted as a line chart in Excel/PowerPoint.

**Comment by andreypotapovaspose** [comment]
Could you please share examples of tabular data and Excel/PowerPoint documents with the expected output?

**Comment by leungi** [comment]
@andreypotapovaspose, appreciate the prompt response; template attached.

[aspose_template.xlsx](https://github.com/aspose-free-consulting/projects/files/12821245/aspose_template.xlsx)

**Comment by amjad-sahi** [comment]
@leungi,

Thanks for the sample Excel file.

Could you please elaborate your requirements and provide more details with sample file(s) on it. 
1) Do you need to import data from some source (which source?) to an Excel file which has some existing charts to be updated by the imported data in the worksheet(s) or you want to insert data cell by cell manually into the existing spreadsheet to update/refresh the charts based on new dataset? 
2) If 1) is not the case, then do you only need to export source data in the worksheet (e.g., from your provided Excel file) to some text format (e.g., TXT, CSV, etc.) or save to some other objects?

**Comment by leungi** [comment]
@amjad-sahi 

1. The data source is a SQL-like data table. Current workflow is:
  - Read data row-wise and store as arrays.
  - Populate row in Excel with arrays.
  - Existing charts are linked to cells from previous step, and will update with new data (per sample .xlsx provided).
  
  Based on your experience, which approach is more performant: (1) opening a template .xlsx with existing charts to be updated 
  by new data, or (2) create a workbook from scratch, insert data to cells, and add charts?

   Method 1, which is what we currently use has high overhead on opening .xlsx due to the existing data and charts; however,
  it's still more efficient than having to code to format the chart to its desired state.

2. The main goal is to export the data, with the charts as Excel or PowerPoint. For the latter, Excel would still be an intermediate step, where the generated charts are then copied over to PowerPoint, ideally linked - i.e., changes in Excel updates charts in PowerPoint.

**Comment by amjad-sahi** [comment]
@leungi ,

Thanks for providing further details and workflow.

I think method 1 would be better than method 2,  so you may use what you are currently doing.

2). If you want Excel charts should be embedded into PowerPoint and linked accordingly, you may insert Excel sheet (having charts and data) as an OLE object. See the document with example code on embedding Excel chart as OLE object in PowerPoint presentation for your reference.
https://docs.aspose.com/slides/net/creating-excel-chart-and-embedding-it-in-presentation-as-ole-object/

We also recommend you to kindly post your queries/issues in dedicated [forums](https://forum.aspose.com/).

**Comment by leungi** [comment]
Thanks for feedback and reference @amjad-sahi.

For method #1, the .xls template provided has a single tab. In real use case, there may be up to 35 tabs, each containing the same set of charts, but with different underlying data (but with the same data dimensions).

Are you able to share sample code for Aspose.Cells to:
1. Open an existing .xlsx.
2. Copy an existing tab and rename it.

**Comment by amjad-sahi** [comment]
@leungi,

See the following sample code for your reference. It will open your template Excel file and makes 35 copies (each with unique name) of the "template" worksheet.
e.g.
**Sample code:**
 ```cs
var workbook = new Workbook("g:\\test2\\aspose_template.xlsx");
var sourceSheet = workbook.Worksheets["template"];
for (int i=0; i<35; i++)
{
    var targetSheet = workbook.Worksheets.Add("Copy" +(i+1));
    targetSheet.Copy(sourceSheet);
}
workbook.Save("g:\\test2\\out1.xlsx");
```
Hope, this helps a bit.

**Comment by leungi** [comment]
Thanks @amjad-sahi.

If you may, I'll leave issue open in case questions arise, as we refactor code to Aspose.

Will close upon completion.

**Comment by leungi** [comment]
@amjad-sahi, I noticed that the output .xlsx always opened as _read-only_, even when relevant privacy settings -i.e., Protected View, Protect Workbook - are turned off.

I don't see a parameter in `SaveOptions` arg in `Save()` for `Workbook` that may affect the above.

Please advise.

**Comment by amjad-sahi** [comment]
@leungi ,

Please zip and attach your input Excel file, output Excel file and sample runnable code to reproduce the issue on our end, we will check it soon.

**Comment by leungi** [comment]
@amjad-sahi, per request.

.zip contains:

1. aspose_template.xlsm (input)
2. aspose_output.xlsm (output)
3. aspose_script.py

[aspose_demo.zip](https://github.com/aspose-free-consulting/projects/files/12885309/aspose_demo.zip)

**Comment by amjad-sahi** [comment]
@leungi ,

Thanks for the files.

Are you talking about "Protected View" (yellow) message on top bar by MS Excel? If so, this is prompted by MS Excel (as MS Excel thinks the file is got from potentially unsafe location, so it will be opened as read-only or in Protected View) and nothing to do with Aspose.Cells APIs. I opened your input Excel file and got the same "Protected View" message on top bar. Please click Enable Editing button to work with the file. Also, see the document on how to precisely remove the message using MS Excel options and settings.
https://support.microsoft.com/en-au/office/what-is-protected-view-d6f09ac7-e6b9-4495-8e43-2bbcdbcb6653

Hope, this helps a bit.

**Comment by leungi** [comment]
@amjad-sahi, thanks for testing,

I'm aware of the Protected View banner that displays at the top of the workbook, but it doesn't show up for me in this case; hence my initial thought that it may have to do with the manipulation done via Aspose.Cells. This is not the case since you're able to bypass it.

Will review internal Excel settings.

**Comment by amjad-sahi** [comment]
@leungi ,

You are welcome. Should you have further queries or issue, feel free to write us back.

**Comment by leungi** [comment]
@amjad-sahi, in IronPython, `float` data type with `nan` values are written back as `#N/A`.

Is it possible to replace with a blank without converting to a `string` data type?

**Comment by amjad-sahi** [comment]
@leungi ,

In IronPython, the float data type with NaN (Not a Number) values is represented as "#N/A" when written back. NaN is a special value used to represent the result of an undefined or unpresentable mathematical operation. I think you may cope with it by replacing "#N/A" with blank/null/empty manually in code using Cell.PutValue("") for your needs.

**Comment by leungi** [comment]
@amjad-sahi thanks for suggestion.

However, replacing manually is slow given the amount of cells (>10000).

Is there no way to encode a blank `float` in Aspose API? Aside from blank `string`, what other values/data types can be used in Aspose to write back a blank?

**Comment by amjad-sahi** [comment]
@leungi,

Apparently, there is no better way to cope with it. Anyways, we will look into it further and get back to you soon.

**Comment by leungi** [comment]
@amjad-sahi , happy 2024!

Question regarding [`DataSorter`](https://reference.aspose.com/cells/net/aspose.cells/datasorter/), with reference to sample code below.

Given that a key (i.e., column A) is already specified via `Key1` attribute, why is it that `Sort()` still requires user to specify a cell range/area? Why can't it sort the whole of column A, by default?

```{python}
sorter = workbook.DataSorter;
sorter.Order1 = SortOrder.Ascending;
sorter.Key1 = 0;
sorter.Sort();
```

**Comment by amjad-sahi** [comment]
@leungi,

I checked using Sort feature in MS Excel manually a bit.  I found you got to select the specific area or whole column to get data sorting feature working. Aspose.Cells works the same way as MS Excel does.
