### ISSUE TITLE
Aspose.Pdf.InvalidPdfFileFormatException: 'Startxref not found'

### ISSUE THREAD

**Issue by sps2019** [aspose-free-consulting/projects#35]
We are exploring Aspose PDF for HTML to PDF conversion in our C# .Net project and getting the exception with sample code using local file. I.e  the fileName in below code.

Document pdfDocument = new Document(fileName);

Has anyone faced similar issue and/or know what could be the reason?

Thanks.

**Comment by shahzad-latif** [comment]
@sps2019 

Thanks for getting in touch. Actually this space is just for consulting projects. For the queries like above, we have our forums where our dedicated team replies you quickly and properly. Can you please post your query in this forum https://forum.aspose.com/c/pdf? Our team will help you shortly. Thanks.
