### ISSUE TITLE
A bug in which smart filters on the layer do not work.

### ISSUE THREAD

**Issue by LoadingT** [aspose-free-consulting/projects#351]
```
internal static async Task test()
{
    var loadOptions = new PsdLoadOptions() {};
    using (var image = Image.Load($"Documents/poland.psd", loadOptions))
    {
        if (image is PsdImage psdImage)
        {
            var TextP = psdImage.Layers.FirstOrDefault(p => p.Name == "TEXT_EDITOR");
            if (TextP != null && TextP is SmartObjectLayer smartObject)
            { 
                var img = smartObject.LoadContents(loadOptions);
                smartObject.ReplaceContents(img);
                smartObject.SmartFilters.UpdateResourceValues();
                smartObject.UpdateModifiedContent();
                var saveOptions = new PngOptions() { };
                psdImage.Save("Result.png", saveOptions);
            }
        }
        else
        {
            throw new InvalidOperationException("Документ не является PSD-файлом.");
        }
    }
}
```
        
 No matter how hard I try, but it doesn't want to accept any filters on my layer with smart filters, I have a file with text layers in the layer

**Comment by aspose-yaroslav-lisovskyi** [comment]
@LoadingT I checked your code with my own created source file, and it works correctly for me.
Maybe your source file uses smart filters that are not supported by Aspose.PSD.
Currently, we support rendering for these smart filers:
- Gaussian Blur;
- Sharpen;

Also, we support the ability to create custom smart filters, if it's interesting for you I can send a code example for it.

**Comment by LoadingT** [comment]
![image](https://github.com/aspose-free-consulting/projects/assets/86262661/97212d5f-3c9e-4c55-a9d3-40fc311c2cb8)
I use standard smart filters from Photoshop, will I have to make them myself?
please send me an example code that will help me do this..

**Comment by LoadingT** [comment]
![image](https://github.com/aspose-free-consulting/projects/assets/86262661/5e1b7007-cac1-46b5-bff0-549e62947c08)
in the first photo, the result is after Aspose.PSD
![image](https://github.com/aspose-free-consulting/projects/assets/86262661/2146b00b-a7b8-4e62-b293-08df7b64eeaa)
in the second in Photoshop

also, when saving via Photoshop, the file is less by 5 MB than via Aspose.PSD

**Comment by aspose-yaroslav-lisovskyi** [comment]
> I use standard smart filters from Photoshop, will I have to make them myself? please send me an example code that will help me do this..
>
> I suggest that in the future you add all smart filters to the library or, if it is time-consuming, write instructions on how to create your own>
>
Here in the 'Examples' section, you can find code that helps you create the custom smart filter.
https://reference.aspose.com/psd/net/aspose.psd/pixelsdata/#examples
> 
> also the question is, what effects are supported? I still have a shadow standing here
>
Supported effects:
- Drop Shadow
- Outer Glow
- Pattern Overlay
- Gradient Overlay
- Color Overlay
- Inner Shadow
- Stroke

Unsupported effects:
- Satin
- Inner Glow
- Bevel & Emboss

**Comment by aspose-yaroslav-lisovskyi** [comment]
>  in the first photo, the result is after Aspose.PSD  in the second in Photoshop
>
> also, when saving via Photoshop, the file is less by 5 MB than via Aspose.PSD
>
If you use unsupported smart filters the result can be unsatisfactory.
Otherwise, provide please your source file so I can check the issue and give a more accurate response.

**Comment by LoadingT** [comment]
Ok , reject
