### ISSUE TITLE
the checkbox not been properly converted in the pdf file

### ISSUE THREAD

**Issue by andrew97s** [aspose-free-consulting/projects#353]
i'm using the aspose to convert a word file into a pdf file , find out the checkbox sympol not been converted properly ,it just vanished in the pdf file;

(below is original word file)
![image](https://github.com/aspose-free-consulting/projects/assets/66058819/2da129db-f752-4394-8f68-dbe4045a5651)

(below is the converted pdf file , and the checkbox just vanished !)
![image](https://github.com/aspose-free-consulting/projects/assets/66058819/c81b2c6b-4a35-45a6-baf4-95a0519c0b88)

1. platform: Debian 4.19.249-2 , jdk1.8 
2. aspose: 
         <dependency>
            <groupId>com.aspose</groupId>
            <artifactId>aspose-words</artifactId>
            <version>20.6</version>
            <classifier>jdk17</classifier>
        </dependency>

the input word file:
[backup - 副本.docx](https://github.com/aspose-free-consulting/projects/files/13039215/backup.-.docx)

**Comment by andrew97s** [comment]
the aspose's maven dependency:

![image](https://github.com/aspose-free-consulting/projects/assets/66058819/091fe420-7c8e-4922-9597-f58a118d3dd6)

**Comment by AlexNosk** [comment]
@andrew97s Checkbox symbols in your document are represented by Wingdings and Wingding2 symbols. The problem on your side occurs because these fonts are not available in your environment. 
Here is PDF produced on my side with these fonts: 
[out.pdf](https://github.com/aspose-free-consulting/projects/files/13040059/out.pdf)

**Comment by andrew97s** [comment]
thanks , i install the fonts , and it worked !
