### ISSUE TITLE
Aspose.Pdf cloud or Aspose.Html cloud? 

### ISSUE THREAD

**Issue by gpdhillon** [aspose-free-consulting/projects#354]
I want to convert html template (that get filled with data and a image) to pdf documents. which is better choice for this. I'm looking at cloud versions of both.

Please advise 

Thanks 
Guri

**Comment by tilalahmad** [comment]
@gpdhillon 

Please use Aspose.HTML Cloud for [HTML to PDF conversion](https://docs.aspose.cloud/html/convert-html-to-pdf/). Please feel free to contact us via the [Aspose.HTML Cloud Free Support Forum](https://forum.aspose.cloud/c/html/24) for any further assistance in this regard.
