### ISSUE TITLE
Scene.open() does not open file (aspose-3d-19.3.jar)

### ISSUE THREAD

**Issue by fafayqa** [aspose-free-consulting/projects#355]
Aspose.3d v19.3 (I have to use exactly this version as my NetBeans13 can use only major version 52 builds and this version is the last one with mv52): `scene.open()` does not work, and the file definitely exist at the specified path/directory (checked several times, even checked what path is sent to `scene.open()`). BTW that .dae file is produced by Blender 3.6.5 (I can provide the file if needed).

I used this example from your website (with no error in NetBeans):

```
// Load and open the input DAE file with the Scene class
Scene scene = new Scene();
scene.open(string-abs-pth-to-my-dae-file);

// Initialize an instance of ObjSaveOptions class
ObjSaveOptions options = new ObjSaveOptions();
options.setEnableMaterials(true);
            
// Convert DAE to OBJ File 
scene.save("Sample.obj", options);
```

It stops at the `scene.open()` - checked by adding simple `System.err.println("OK")` right before and after the `scene.open()`: the first one fires up but the 2nd one never outputs, which means there it stops as my app also hung-up/freeze there.

There is absolutely no need for any code/app sample as this is clearly only problem of this specific little piece of code of yours - my code stops wortking right at/after your `scene.open()`.

And here is my very simple test file Java code:

```
package daetoobj;

import com.aspose.threed.ObjSaveOptions;
import com.aspose.threed.Scene;

import java.io.File;
import java.io.IOException;

public class DaeToObj {

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    public static void main(String[] args) throws IOException {

        // Initialize new Scene class
        Scene scene = new Scene();

        System.err.println("++++++++++ OK1");
        String inputFile = "Z:/test.dae";
        System.err.println(inputFile);
        System.err.println("Does the input DAE file exist = " + new File(inputFile).exists());

        // Load the input DAE file
        scene.open(inputFile);

        System.err.println("++++++++++ OK2 - input DAE file opened successfully");

        // Initialize an instance of ObjSaveOptions class
        ObjSaveOptions options = new ObjSaveOptions();
        options.setEnableMaterials(true);

        scene.save("Z:/test.obj", options);
    }

}
```

But if I use the same file with your online DAE to OBJ converter [here](https://products.aspose.app/3d/conversion/dae-to-obj) and I use exactly the same DAE file, it converts it with no problem.

**Comment by fafayqa** [comment]
I think I found where the problem is: this problem happens if a Collada DAE file contains any UV map!
If a Collada DAE file doe snot contain any UV map, it converts the file without any problem whatsoever...so possible BUG???

**Comment by asadalikhan90** [comment]
@fafayqa 

Looks like you have posted a [similar inquiry](https://forum.aspose.com/t/273774/2) in our official support forum where we have responded you accordingly. You may please follow up there.
