### ISSUE TITLE
Which solution can complete the following functions and how much does it cost?

### ISSUE THREAD

**Issue by davidchou6397** [aspose-free-consulting/projects#358]
Which solution can complete the following functions and how much does it cost?
1. Add digital signatures to PDF files, encrypt them, and decrypt PDF files if the password is known
2. Extract content and metadata, including fonts, images, and text. You can extract and query various properties and page content from PDF files.
3. Can merge multiple pages or files into a single PDF or split pages into separate PDFs. It can also rotate pages, copy or add metadata, and other document properties such as document outlines (bookmarks), form fields, transport device color profiles, and flattened form fields.
4. Convert images to PDF documents
Convert PDF files to images
Sign and certify PDF documents

**Comment by asadalikhan90** [comment]
@davidchou6397 

Aspose.PDF supports all of these features. Please check below sample articles and code examples in the API documentation for further details:

> Add digital signatures to PDF files, encrypt them, and decrypt PDF files if the password is known

[Encrypt and Decrypt PDF File](https://docs.aspose.com/pdf/net/set-privileges-encrypt-and-decrypt-pdf-file/)

> Extract content and metadata, including fonts, images, and text. You can extract and query various properties and page content from PDF files.

[Extract Images](https://docs.aspose.com/pdf/net/extract-images-from-pdf-file/)
[Get All Fonts from PDF Document](https://docs.aspose.com/pdf/net/formatting-pdf-document/#get-all-fonts-from-pdf-document)
[How to set PDF expiry date](https://docs.aspose.com/pdf/net/manipulate-pdf-document/#how-to-set-pdf-expiry-date)
[Search and Get Text](https://docs.aspose.com/pdf/net/search-and-get-text-from-pdf/)

> Can merge multiple pages or files into a single PDF or split pages into separate PDFs. It can also rotate pages, copy or add metadata, and other document properties such as document outlines (bookmarks), form fields, transport device color profiles, and flattened form fields.

[Merge PDF files](https://docs.aspose.com/pdf/net/merge-pdf-documents/)
[Split PDF files](https://docs.aspose.com/pdf/net/split-pdf-document/)
[Get and Set Page Properties](https://docs.aspose.com/pdf/net/get-and-set-page-properties/)
[Rotate PDF Pages](https://docs.aspose.com/pdf/net/rotate-pages/)
[Bookmarks](https://docs.aspose.com/pdf/net/bookmarks/)
[Working with Forms](https://docs.aspose.com/pdf/net/working-with-forms/)

>Convert images to PDF documents
Convert PDF files to images
Sign and certify PDF documents

[Convert PDF document](https://docs.aspose.com/pdf/net/converting/)
[Digitally sign PDF](https://docs.aspose.com/pdf/net/digitally-sign-pdf-file/)

Furthermore, please note that our official forum are the recommended place for the communication related to the API features, cost and issues. We recommend you create a post in our [Purchase forum](https://forum.aspose.com/c/purchase) to get cost related information. In case you face any issues while testing the API, please feel free to create posts in [Aspose.PDF](https://forum.aspose.com/c/pdf) support forum where we will assist you accordingly.
