### ISSUE TITLE
PDF to docx conversion Alignment and font issues - Aspose.PDF for .NET

### ISSUE THREAD

**Issue by anandababu-annadurai-anth** [aspose-free-consulting/projects#359]
Hi Team,

While converting the PDF into docx file using aspose.pdf for .net package,the converted document has alignment issues and font mismatch in few places. The PDF has graphik font, in the converted docx file, the font is getting replaced with other font only in few places.

Please find the below code, passing the pdf file as stream and converting it to docx/doc with help of Aspose.pdf package. 

Kindly help on these issues.

Document document = new Document(stream);
document.DisableFontLicenseVerifications = true;
.
.
byte[] data;
using (var ms = new MemoryStream())
{
if (fileType.ToLower() == “docx”)
document.Save(ms, SaveFormat.DocX);
else
document.Save(ms, SaveFormat.Doc);
data = ms.ToArray();
}
return data;

Converted docx file issues:
![image003](https://github.com/aspose-free-consulting/projects/assets/146032521/e8503b17-974e-460a-8d82-5eb568296ae3)

Source PDF file: 
[IRCY11502477.pdf](https://github.com/aspose-free-consulting/projects/files/13445291/IRCY11502477.pdf)

![thumbnail_image002](https://github.com/aspose-free-consulting/projects/assets/146032521/e1b4c525-dd9d-4bc1-88d1-c05f4d5ae4bf)

**Comment by asadalikhan90** [comment]
@anandababu-annadurai-anth 

We believe that we have already responded to your [similar inquiry](https://forum.aspose.com/t/pdf-to-docx-conversion-alignment-and-font-issues-aspose-pdf-for-net/274996/4) in our official support forum. We have logged an issue in our issue tracking system and have linked it to the forum thread as well. You can please keep following up there and we will also keep you posted on issue progress there.

**Comment by anandababu-annadurai-anth** [comment]
Sure..Thanks for your response. I will followup on the support forum.
