### ISSUE TITLE
Remove content based on a set of rules?

### ISSUE THREAD

**Issue by thegorilla** [aspose-free-consulting/projects#365]
Is there a way to remove content based on a set of rules, likely inline CSS styles?

We are using Kentico Version 13 on a Windows server; c# visual studio.

Thanks

**Comment by AlexNosk** [comment]
@thegorilla You can use Aspose.HTML to with with HTML documents and edit them. Please see our documentation for more information about editing HTML document:
<https://docs.aspose.com/html/net/edit-html-document/>

PS: Please note the main place for getting support is [Aspose support forums.](https://forum.aspose.com/)
