### ISSUE TITLE
Proxy Error When Converting Shape or Officematch Nodes to HTML Using aspose.word.python on Linux

### ISSUE THREAD

**Issue by yeq81253** [aspose-free-consulting/projects#368]
I encountered a problem while using the aspose.word.python . My code runs fine on Windows, but when I migrated it to Linux, I started encountering errors.

my code:
![image](https://github.com/aspose-free-consulting/projects/assets/43661773/87eb7da8-5bad-4314-ae5a-108ab6ac2256)

error message:  Proxy error(ArgumentOutOfRangeException): Expected a value between 0 and 3291. (Parameter 'index')

Expected Behavior:
I expect to successfully convert shape or officematch nodes to HTML format on Linux for display on a webpage.

Please assist in resolving this issue. Thank you!

**Comment by AlexNosk** [comment]
@yeq81253 Could you please attach the problematic document here for testing? We will check the issue and provide you more information.

PS: The main place for getting support is [Aspose.Words support forum](https://forum.aspose.com/c/words/8). So please post your further questions in the forum.

**Comment by yeq81253** [comment]
I have created a new topic in the Aspose.Words support forum and uploaded the problematic document for testing. You can find the topic [here](https://forum.aspose.com/t/proxy-error-when-converting-shape-or-officematch-nodes-to-html-using-aspose-word-python-on-linux/276129). I appreciate your assistance in checking the issue and providing more information.

Thank you

**Comment by AlexNosk** [comment]
@yeq81253 Thank you for additional information.  I have managed to reproduce the problem and logged an issue in our defect database. We will keep you updated and let you know once it is resolved.

**Comment by AlexNosk** [comment]
@yeq81253 You need to install `libgdiplus` library and the problem will go away.
```
RUN apt install -y libgdiplus
```
