### ISSUE TITLE
I would like to know about the conversion of the API conversion from MPP to XML

### ISSUE THREAD

**Issue by italobaracho** [aspose-free-consulting/projects#369]
I want to know if there are more details about API converting MPP to XML, I did a small test on the website with our file and it showed this error, could it be a version problem in the Microsoft project or something similar that is not working or a confidential file with a security label that is causing this error, I would like to know more.

See the image below,

![thumbnail_image](https://github.com/aspose-free-consulting/projects/assets/94207768/3794a0f1-229f-42e4-9dec-5f3ca0bb6b06)

**Comment by sva1000** [comment]
@italobaracho , 
could you attach your MPP file so that we can examine it?

You can post it here, but it's better to post it to Aspose.Tasks' Free Support Forum : https://forum.aspose.com/c/tasks/15

**Comment by italobaracho** [comment]
Yes, I'm going to post our file here, here's the one drive link : 

https://onedrive.live.com/?authkey=%21AOb21%2DCg1SOv9U8&id=FE3FC981B03F485B%2112978&cid=FE3FC981B03F485B

**Comment by italobaracho** [comment]
Yes, I will post our file here, see the attachment below: 

[TESTEPD_Custo.zip](https://github.com/aspose-free-consulting/projects/files/13704018/TESTEPD_Custo.zip)

**Comment by sva1000** [comment]
@italobaracho ,
your file is correct, we need to update the application.
You can obtain the same resulting XML using trial version of Aspose.Tasks for .NET using the following code:

string dir = "c:/test";
var project = new Project(dir + "TESTEPD_Custo.mpp");
project.Save(dir + "TESTEPD_Custo.xml", SaveFileFormat.Xml);

I've checked the snippet with 23.12 and it exported the XML successfully.

**Comment by italobaracho** [comment]
Thank you very much for the possible resolution of our problem, but is it possible to send 2 types of API, say one in Python and one in Nodejs? why do I need to do an ETL, based on one of these APIs mainly in nodejs

**Comment by sva1000** [comment]
@italobaracho ,
we have high code API for .NET, Java, C++ and Python.

Also we have low code APIs (which are SDK for calling our Cloud-based solution) for Node.js, .NET, Java, PHP, Python and Go.

You can check https://products.aspose.cloud/tasks/family/ page for the details.

**Comment by italobaracho** [comment]
Hello everything is fine ? I would like to know about this request if it is to pass the path with the credentials or just the credentials and like the link, I already have the credentials and the login in Aspose and I have this doubt about how it behaves, or send me an example in this API :

curl -X GET "https://api.aspose.cloud/v3.0/tasks/Home%20move%20plan.mpp/format?format=csv&returnAsZipArchive=false" -H "accept: multipart/form-data" -H "x-aspose-client: Containerize.Swagger"



And if possible, can you give me some examples with the SDKS in Python so I can have a base, or send me the path with the directory or just the file without the directory, I would also like some examples of how it would look:

filename = 'Home_move_plan.mpp'
self.upload_file(filename)
get_request = GetTaskDocumentWithFormatRequest(filename, ProjectFileFormat.CSV)
get_result = self.tasks_api.get_task_document_with_format(get_request)
self.assertIsNotNone(get_result)
with open(get_result, encoding='utf-8', errors='ignore') as f:
  self.assertTrue(f.readable())
  self.assertIn('ID;Task_Name;Outline_Level;Duration;Start_Date;Finish_Date;Percent_Comp;Cost;Work',
          f.readline())
  self.assertIn(
    '1;Five to Eight Weeks Before Moving;1;16 days;Thu 01.01.04 08:00;Thu 22.01.04 17:00;0%;$0;0 hrs',
    f.readline())

I looked in the aspose documentation and didn't find practical examples, I wanted help if possible.

**Comment by sva1000** [comment]
@italobaracho ,
sorry for not replying sooner.

Examples for Aspose.Tasks Cloud SDK for Python can be found here: 
https://github.com/aspose-tasks-cloud/aspose-tasks-cloud-python/tree/master/test.

Sample files used in tests (including 'Home_move_plan.mpp') can be found here:
https://github.com/aspose-tasks-cloud/aspose-tasks-cloud-python/tree/master/testData
