### ISSUE TITLE
I want to convert html to pdf and it does not fit Page size A4

### ISSUE THREAD

**Issue by Giedrius14** [aspose-free-consulting/projects#37]
We want to convert in Java complex HTML containing tables to PDF.  Result does not fit A4 page, tried limiting with CSS, not sure why it does not work, tried adding widths on columns, but it does not work.
also tried setFitWindow(false)

Is there a specific way how to work with CSS in aspose ?
![image](https://user-images.githubusercontent.com/13120209/78563210-45e44e00-7823-11ea-9bbd-5bd2aeee65b9.png)

Result should fit A4 page,  this is how html is looking on the browser:
![image](https://user-images.githubusercontent.com/13120209/78568932-83e57000-782b-11ea-9993-200077d598dc.png)

[asposehtml.zip](https://github.com/aspose-free-consulting/projects/files/4438626/asposehtml.zip)

**Comment by asadalikhan90** [comment]
@Giedrius14 

Thanks for posting your inquiry.

The height and width values work differently between CSS and PDF Specifications. Nevertheless, we were able to reproduce the issue in our environment with Aspose.PDF for Java 20.3. The HTML content was not fit within A4 size boundaries of PDF Page. For the sake of detailed investigation and correction, we have logged it as **PDFJAVA-39335** in our issue tracking system. 

We will definitely look into its details and keep you informed about the status of its rectification. Please be patient and spare us some time.

We are sorry for the inconvenience.

**Comment by shahzad-latif** [comment]
@Giedrius14 

This place is to handle any free consulting projects. Could you please move your query to our forums? https://forum.aspose.com/c/pdf So the issue can be properly tracked and followed up? I would really appreciate your cooperation.

**Comment by asadalikhan90** [comment]
@Giedrius14 

Regarding earlier logged ticket, due to some reasons the CSS option: "display: inline-block" of class .table-element-paragraph make text not wrap. After removing this option (or changing it to "inline") the table is almost fit. Just a last column bit cut off as table is extremely wide.

To avoid this cut off it is possible to resize the document after the import by the code snippet below (pay attention to scaleFactor variable):

```
float scaleFactor = 0.9f;

HtmlLoadOptions options = new HtmlLoadOptions();
options.getPageInfo().setMargin(new MarginInfo(0, 0, 0, 0));

options.getPageInfo().setWidth(PageSize.getA4().getWidth()/scaleFactor);
options.getPageInfo().setHeight(PageSize.getA4().getHeight()/scaleFactor);
Document doc = new Document(dataDir + "aspose.html", options);

PdfFileEditor fileEditor = new PdfFileEditor();
PdfFileEditor.ContentsResizeParameters parameters = new PdfFileEditor.ContentsResizeParameters(
PdfFileEditor.ContentsResizeValue.units(0),
PdfFileEditor.ContentsResizeValue.units(PageSize.getA4().getWidth()),
PdfFileEditor.ContentsResizeValue.units(0),
PdfFileEditor.ContentsResizeValue.units(0),
   PdfFileEditor.ContentsResizeValue.units(PageSize.getA4().getHeight()),
   PdfFileEditor.ContentsResizeValue.units(0));
fileEditor.resizeContents(doc, parameters);

doc.save(dataDir + "HTMLtoPDF_20.3.pdf");
```
