### ISSUE TITLE
I want aspose API for .NET MVC 4.8.1

### ISSUE THREAD

**Issue by CloseOutSoft** [aspose-free-consulting/projects#371]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by amjad-sahi** [comment]
Could you please provide more details on your scenario/case? Which Aspose API/library you are using or you want to use? We will then check your requirements and assist you accordingly.

**Comment by CloseOutSoft** [comment]
Hi

We would like to integrate the Aspose tools in our application such as PDF, CAD, 3D and GIS and so on. But your demo source not running comes with error. Can please advise me how to integrate the Aspose plugins in our application?.

Application Technology

.NET MVC c# 4.8.1 with SQL Server

Thanks & Best Regards,

[signature_1100490330]

Senthilkumar N

Senior  Software Engineer
[Envelope outline]
***@***.******@***.***>
[Receiver outline]
+971 (02) 672 9802 | +971 (54) 363 2826
[Marker outline]
PO Box: 3282, 12th Floor, Office No: 1203/1204,

Sultan International Tower, Corniche, Abu Dhabi, UAE
[World outline]
www.rebus.ae<http://www.rebus.ae/>
[signature_1622149930][signature_3937797332] [About AL Kheera Steel Works]  [A logo with a leaf and text  Description automatically generated with medium confidence]  [Accreditation services marks & logos]
[facebook icon]<https://www.facebook.com/rebuscloseout>[linkedin icon]<https://www.linkedin.com/company/rebus1996/mycompany/>[twitter icon]<https://twitter.com/rebus1996/>[instagram icon]<https://www.instagram.com/rebus1996/>[youtube icon]<https://www.youtube.com/user/MyCompanyChannel>
[A blue background with white text  Description automatically generated]
The content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without the written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.

**Comment by CloseOutSoft** [comment]
Hi 
we already purchase Aspose.Total Metered OEM License.. how to update license key and use API's?

Please advise...

Thanks
Senthilkumar N
Senior  Software Engineer

**Comment by asadalikhan90** [comment]
@CloseOutSoft 

In order to apply metered license key and start using the API, please check sample code snippet and details in the API documentation. 

* [Metered Licensing](https://docs.aspose.com/pdf/net/licensing/#metered-license)

Above article is about Aspose.PDF for .NET only. If you are using multiple Aspose APIs, you would need to set license for every API explicitly at the start of your application. The methods to set the license are same for all Aspose APIs.

> We would like to integrate the Aspose tools in our such as PDF, CAD, 3D and GIS and so on. But your demo source not running comes with error. Can please advise me how to integrate the Aspose plugins in our application?.

Sadly, the source code present over GitHub is quite older and has not been being maintained. If you can please share some basic requirements with us like what you actually intend to achieve using Aspose APIs, we will be able to share some more details with you.

Also, please note that we recommend posting such issues and start discussions on our [dedicated support forum](https://forum.aspose.com/c/pdf) which is the right place. You can please create a topic there as well and we will assist you at our maximum.

**Comment by CloseOutSoft** [comment]
Hi Team

Actually we are going to use Aspose API’s in our web application(.NET MVC c# 4.8.1 with SQL Server). Please kindly advise to apply license key and sample source of aspose API(PDF Editor,  CAD, GIS, 3D).

Our registered email : ***@***.******@***.***>

Thanks for your reply soon..


Please share

Thanks & Best Regards,

[signature_1100490330]

Senthilkumar N

Senior  Software Engineer
[Envelope outline]
***@***.******@***.***>
[Receiver outline]
+971 (02) 672 9802 | +971 (54) 363 2826
[Marker outline]
PO Box: 3282, 12th Floor, Office No: 1203/1204,

Sultan International Tower, Corniche, Abu Dhabi, UAE
[World outline]
www.rebus.ae<http://www.rebus.ae/>
[signature_1622149930][signature_3937797332] [About AL Kheera Steel Works]  [A logo with a leaf and text  Description automatically generated with medium confidence]  [Accreditation services marks & logos]
[facebook icon]<https://www.facebook.com/rebuscloseout>[linkedin icon]<https://www.linkedin.com/company/rebus1996/mycompany/>[twitter icon]<https://twitter.com/rebus1996/>[instagram icon]<https://www.instagram.com/rebus1996/>[youtube icon]<https://www.youtube.com/user/MyCompanyChannel>
[A blue background with white text  Description automatically generated]
The content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without the written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.

**Comment by amjad-sahi** [comment]
@CloseOutSoft,

> Please kindly advise to apply license key and sample source of aspose API(PDF Editor,  CAD, GIS, 3D)

See the documents with example code on how to apply/set metered licensing for your reference.
CAD
https://docs.aspose.com/cad/net/metered-licensing/

GIS
https://docs.aspose.com/gis/net/licensing/#applying-metered-key

3D
https://docs.aspose.com/3d/net/licensing/#apply-metered-license

Hope, this helps a bit.

PS. We also appreciate if you could post your queries/issues in respective forums, our forum support is efficient.

**Comment by CloseOutSoft** [comment]
Hi Amjad

Thanks for the response.. once everything will fine means we build all the plugins in our app. We will buy the yearly based license key. Is it no issues...

[signatureImage]

________________________________

**Comment by amjad-sahi** [comment]
@CloseOutSoft,

Yes, sure, there would be no issues. Should you have further queries or issue, please feel free to write us back.

**Comment by CloseOutSoft** [comment]
Hi Amjad

I will try to run the demo project of Aspose.PDF sample, but I got an error. Please find the attachment.

We need to build the Aspose.PDF, CAD, GIS Editor to our .net web application…

Please give me some samples open pdf editor in browser itself.

Please find the attachments.

Thanks & Best Regards,

[signature_1100490330]

Senthilkumar N

Senior  Software Engineer
[Envelope outline]
***@***.******@***.***>
[Receiver outline]
+971 (02) 672 9802 | +971 (54) 363 2826
[Marker outline]
PO Box: 3282, 12th Floor, Office No: 1203/1204,

Sultan International Tower, Corniche, Abu Dhabi, UAE
[World outline]
www.rebus.ae<http://www.rebus.ae/>
[signature_1622149930][signature_3937797332] [About AL Kheera Steel Works]  [A logo with a leaf and text  Description automatically generated with medium confidence]  [Accreditation services marks & logos]
[facebook icon]<https://www.facebook.com/rebuscloseout>[linkedin icon]<https://www.linkedin.com/company/rebus1996/mycompany/>[twitter icon]<https://twitter.com/rebus1996/>[instagram icon]<https://www.instagram.com/rebus1996/>[youtube icon]<https://www.youtube.com/user/MyCompanyChannel>
[A blue background with white text  Description automatically generated]
The content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without the written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.

**Comment by asadalikhan90** [comment]
@CloseOutSoft 

We were unable to find any attachment with your message. Furthermore, it looks like you want to achieve something like Aspose Free Online Apps (https://aspose.app/).

We would like to clarify that all Aspose On-Premise APIs are available to be used in the backend only. They do not provide any control or component that can be integrated in the applications. Some custom components can be developed however with the integration of Aspose APIs in the backend to obtain desired functionalities.

About online PDF editor (https://products.aspose.app/pdf/editor), right place to inquire about it is [Aspose Apps Forum](https://forum.aspose.app/). You can freely signup there and post your question about the source code of the applications in which you are interested. 

> I will try to run the demo project of Aspose.PDF sample, but I got an error. Please find the attachment.

Would you kindly share the link from where you downloaded the sample project along with a screenshot of the error that you are facing? We will definitely try to assist you at our best.

**Comment by CloseOutSoft** [comment]
Hi Mr.Asad

I download sample demo project source code from the following link

https://aspose.github.io/

Herewith I have attached the error I got while running the demo application…

We would like to build your editors in our .net web application itself… please advise…

Thanks & Best Regards,

[signature_1100490330]

Senthilkumar N

Senior  Software Engineer
[Envelope outline]
***@***.******@***.***>
[Receiver outline]
+971 (02) 672 9802 | +971 (54) 363 2826
[Marker outline]
PO Box: 3282, 12th Floor, Office No: 1203/1204,

Sultan International Tower, Corniche, Abu Dhabi, UAE
[World outline]
www.rebus.ae<http://www.rebus.ae/>
[signature_1622149930][signature_3937797332] [About AL Kheera Steel Works]  [A logo with a leaf and text  Description automatically generated with medium confidence]  [Accreditation services marks & logos]
[facebook icon]<https://www.facebook.com/rebuscloseout>[linkedin icon]<https://www.linkedin.com/company/rebus1996/mycompany/>[twitter icon]<https://twitter.com/rebus1996/>[instagram icon]<https://www.instagram.com/rebus1996/>[youtube icon]<https://www.youtube.com/user/MyCompanyChannel>
[A blue background with white text  Description automatically generated]
The content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without the written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.

**Comment by asadalikhan90** [comment]
@CloseOutSoft 

This is how we receive your message here and we do not see any attachments: 
![image](https://github.com/aspose-free-consulting/projects/assets/22503496/880927f1-fa2c-4a3f-af9c-e11ddafff8d4)

Furthermore, when you mention online editor, can you please be more specific? For example, we showcase two types of PDF editor on our sites:

* https://products.aspose.app/pdf/editor
* https://github.com/aspose-pdf/Aspose.PDF-for-.NET/tree/master/Showcases/aspose-pdf-editor

Both editors are presented for different purposes and are managed by different Aspose ventures. Also, the original and main repository of [Aspose.PDF for .NET examples](https://github.com/aspose-pdf/Aspose.PDF-for-.NET/tree/master) contains more than one project. Please be specific which one are you trying and what kind of error are you facing?

In case you are trying the example other than Aspose.PDF for .NET, please do mention them as well. This way we will be able to assist you accordingly.

PS: It would really be appreciated, if you can please post a topic in our [dedicated support forum](https://forum.aspose.com/). As shared earlier, its the right place for such discussions.
