### ISSUE TITLE
Word merge. Document creation by replacing tokens in template

### ISSUE THREAD

**Issue by hemantthote** [aspose-free-consulting/projects#372]
I am working on the program to create document on the basis of tokenized template. I have written program to replace simple text but having issue replacing tables. Attaching template here with tow table. We can have more or less. How to I replace table tokens to generate table row with data rows
[NewTemplateHT.docx](https://github.com/aspose-free-consulting/projects/files/13796534/NewTemplateHT.docx)

Can you please provide sample code? I want code for aspose.word java

**Comment by AlexNosk** [comment]
@hemantthote The question is already answered in Aspose.Words support forum:
<https://forum.aspose.com/t/word-merge-document-generation-on-the-basis-of-tokenized-template/276894/2>
