### ISSUE TITLE
I wanna use API as self hosted.

### ISSUE THREAD

**Issue by jjikkobro** [aspose-free-consulting/projects#373]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>
** We want to use Aspose HTML to DOCX conversion API as self hosted.
Because we can pay our server fee and we only need function which can convert HTML to DOCX and give us link for downloading the document. 
This hosting is on virtual machine(Linux) on East US and we can use .NET, Laravel framwork.

So For using above functions, How can we use and How price it is.
0831ww59@gmail.com **

**Comment by sheralikhan90** [comment]
@jjikkobro 

Aspose Provides both on-premise and cloud APIs which you can select as per your project requirements. By looking at your inquiry, it looks like Cloud API would be appropriate and right choice for your project. About HTML to DOCX Conversion, below Aspose APIs can be used:

* Aspose.PDF
* Aspose Words
* Aspose.HTML

We are further gathering details at our end to share with you about the sample code and examples. Meanwhile, you can please contact our [Sales Team](https://forum.aspose.com/c/purchase) for the pricing details.

**Comment by asadalikhan90** [comment]
@jjikkobro 

Aspose provides both Cloud and on-premise APIs. You can select them as per your project environment. In a self hosted API, using  and integrating Cloud API would be a viable and easy to use solution. HTML to DOCX Conversion can be carried out using below Aspose APIs:

* Aspose.HTML
* Aspose.PDF
* Aspose.Words

You can select any of the above API to carry out the operation. We are collecting necessary information to share with you here. However, please create a post in our [Purchase forum](https://forum.aspose.com/c/purchase) for our sales team to explain pricing information.
