### ISSUE TITLE
License type

### ISSUE THREAD

**Issue by CamaEdvin** [aspose-free-consulting/projects#374]
Hi free consulting,
I have an web app that will be hosted publicly and locally. The os is ubuntu 20.04 and the app and its requirements are packed in docker. It requires nginx also. The app is written in python django and the app will hold thousands of pdf files that will be edited and sent via email. Which Apose.PDF is better python via .net or via java? I assume via java but just to make sure. Also, based on the hosting conditions; will the price stay at 1999USD or will it be a different one? 

Sincerely,
Edvin Cama

**Comment by asadalikhan90** [comment]
@CamaEdvin 

Looking at your environment and project type, [Aspose.PDF for Python via Java](https://docs.aspose.com/pdf/python-java/) seems right choice at it will require less efforts to setup. You can please refer to its documentation and post your technical inquiries in our [support forum](https://forum.aspose.com/c/pdf) in case you have some.

Furthermore, we also encourage you to check [Aspose.PDF Cloud API](https://products.aspose.cloud/pdf/?gclid=Cj0KCQiAnfmsBhDfARIsAM7MKi06CQiAiWMWE1sqvulLhJu4VTl-ftTuDdwZe1tLxJyORhEaBa9Vgy8aAmPEEALw_wcB) that can be a viable choice for your project and will require minimum efforts to set it up. We also have a [dedicated forum](https://forum.aspose.cloud/) for Cloud APIs. In case you have less operations to carry out for the PDFs and do not have much requirements for on-premise API, it can be a good choice.

About pricing, we request you please contact our [Sales Team](https://forum.aspose.com/c/purchase) to get details.
