### ISSUE TITLE
I would like to know how and why pdf becomes uneditable after aspose.cad export

### ISSUE THREAD

**Issue by labman003** [aspose-free-consulting/projects#375]
After the dwg file is exported to pdf, pdf can not be edited, and I want to know how to set the font size of the exported pdf?

**Comment by OleksiiGor** [comment]
@labman003,
Hi. 
We need more information to assist. What is exactly not editable in pdf, how do you try to edit? What is the export code? There are few ways to set/change font size as it depends on the DWG file and the entity that stores text/font. Please consider posting the additional information and the initial DWG file in our [free support forum](https://forum.aspose.com/c/cad/19) so we can research the details.
