### ISSUE TITLE
I want to create/build online ppt editor in our reactjs app

### ISSUE THREAD

**Issue by Murtaza-arif** [aspose-free-consulting/projects#377]
I wanted to integrate a online ppt editor in our reactjs application.
Can anyone suggest how I can use aspose in our application.

Or anyone suggest a third party or open source for a online ppt viewe and editor as a sdk .

**Comment by andreypotapovaspose** [comment]
@Murtaza-arif,
With the [Aspose.Slides](https://products.aspose.com/slides/family/) library, you can convert presentation slides into SVG images and then edit them in your web app using an SVG editor.
For example, the following code snippet in C# shows you how to convert PPTX to SVG:
```cs
using var presentation = new Presentation("sample.pptx");

for (var i = 0; i < presentation.Slides.Count; i++)
{
    using var imageStream = File.OpenWrite($"image_{i + 1}.svg");
    presentation.Slides[i].WriteAsSvg(imageStream);
}
```
You can do the same in Java, Python, or another programming language.
