### ISSUE TITLE
I want to create/build a PPT template based on GUI based actions

### ISSUE THREAD

**Issue by bazooka720** [aspose-free-consulting/projects#379]
We have a capability where we can add static and dynamic components (Text, Comments, Images, Charts, Bullet points) to a powerpoint template. This is possible by adding "placeholders" on an actual powerpoint and another interface where we can be providing the inputs for static components (e.g. static text, image etc) by saying placeholder {1}=Static Text ="XXX", {2}=Dynamic Text ->Based on result of query, etc So Currently the placeholders are manually added on powerpoint and the placeholder to content linkage done separately. We want to know if you support ability to add these placeholders directly on a web interface (we do have a powerpoint add-in that allows but its in ppt app) and as its being added, have the data available for us so we can enable user to link placeholder to content and when all this is saved. The PPT with placeholders is saved as well

**Comment by andreypotapovaspose** [comment]
@bazooka720,
Could you please share a sample PowerPoint template and describe a use case in more detail?

**Comment by bazooka720** [comment]
So this is completed? @awaishafeez

**Comment by andreypotapovaspose** [comment]
@bazooka720,
>We want to know if you support ability to add these placeholders directly on a web interface

Unfortunately, Aspose.Slides does not work with web interfaces directly. This library allows you to manage PowerPoint documents (add/change/remove document elements, convert presentations to other file formats, etc.).

As for adding placeholders to presentations, please take a look at the following article:
https://docs.aspose.com/slides/net/manage-placeholder/
I hope this will help you a bit.
