### ISSUE TITLE
Add QR Code on Existing PDF or Word Doc

### ISSUE THREAD

**Issue by mchegge** [aspose-free-consulting/projects#38]
My requirement is to take corespondent letters created in another system in docx files, could be converted to PDF if DOCX creates complexity, and add a QR Code in a static position.  The QR Code is to be encoded with the filename of the input PDF or DOCX and output saved to file.

Can I perform the following with a combination of the Words/PDF/Barcode .NET APIs 

Thank you,

**Comment by awaishafeez** [comment]
@mchegge,

Sure, you can meet this requirement by using 'Aspose.BarCode for .NET' and 'Aspose.Words for .NET' APIs.

You can first use 'Aspose.BarCode for .NET' API to create a QR Code and then obtain an Image of QR Code. For example, the following code demonstrates how to generate a QR Code.

```
string dataDir = RunExamples.GetDataDir_CreateAndManage2DBarCodes();
// Initialize a BarcodeGenerator  class object and Set CodeText & Symbology Type
BarcodeGenerator  generator = new BarcodeGenerator (EncodeTypes.QR, "12345TEXT");
// Set ForceQR (default) for standard QR and Code text
generator.Parameters.Barcode.QR.QrEncodeMode = QREncodeMode.Auto;
generator.Parameters.Barcode.QR.QrEncodeType = QREncodeType.ForceQR;
generator.Parameters.Barcode.QR.QrErrorLevel = QRErrorLevel.LevelL;
// Get barcode image Bitmap and Save QR code
Bitmap lBmp = generator.GenerateBarCodeImage();
lBmp.Save(dataDir + "EncodeQA_out.bmp", ImageFormat.Bmp);
```

After that you can use 'Aspose.Words for .NET' API to insert QR Code Image at any place in Word DOCX Document. Please see the following sample code:

```
Document doc = new Document("input.docx");
DocumentBuilder builder = new DocumentBuilder(doc);
builder.MoveToDocumentEnd(); // or move cursor to any Node position
builder.InsertImage("image.bmp");
doc.Save("output.docx");
doc.Save("output.pdf");
```

Hope, this helps.

**Comment by shahzad-latif** [comment]
This solution has been published in the following repository as well: [Generate QR Code & Save it to BMP Image, Insert QR Code Image Stream in Document & Convert Word to PDF](https://github.com/aspose-free-consulting/Generate_QR_Code_Insert_Image_in_Word_PDF#generate-qr-code--save-it-to-bmp-image-insert-qr-code-image-stream-in-document--convert-word-to-pdf)
