### ISSUE TITLE
Import EML files into an Office 365 Shared Mailbox

### ISSUE THREAD

**Issue by brianstittsr** [aspose-free-consulting/projects#380]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

I want assistance with learning how to use the Apose Python library to import .EML files in a folder into an Office 365 Mailbox.  I just need a simple working python example so I can integrate it with my ETL tool. The EML files will be stored in a directory on a server that I will have local access to read from.  My plan is configure the Python program to accept the following variables as input :
1. Server URL
2. Path to Shared MailBox
3. Apose O365 Oauth sign in credientials

I have a test the import on if needed.

< which platform you're working on -- operating system, development environment etc.> 
The EML import solution will be hosted on a Linux server and the files will be stored on the Linux server.  If there's no difference between Windows or Linux, I will be ok with testing on Linux.

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by dmitrysamodurov** [comment]
Hello @brianstittsr,

Unfortunately, the Aspose.Email for Python library doesn't provide a direct API for accessing Office 365 Shared Mailboxes via Exchange Web Services (EWS) or Microsoft Graph.

However, you might want to explore Aspose.Email for .NET or Aspose.Email for Java. These libraries offer more extensive capabilities, including the ability to work with Office 365 Shared Mailboxes without the mentioned limitations.

**Comment by brianstittsr** [comment]
Hi,The ETL solution I am using is based on Java, therefore Java can be an option. Can you share with me how to import the EMLs using the Java solution?Brian StittOn Jan 22, 2024, at 4:04 AM, dmitrysamodurov ***@***.***> wrote:﻿
Hello @brianstittsr,
Unfortunately, the Aspose.Email for Python library doesn't provide a direct API for accessing Office 365 Shared Mailboxes via Exchange Web Services (EWS) or Microsoft Graph.
However, you might want to explore Aspose.Email for .NET or Aspose.Email for Java. These libraries offer more extensive capabilities, including the ability to work with Office 365 Shared Mailboxes without the mentioned limitations.

**Comment by sergviva** [comment]
Hello @brianstittsr,

Sorry for the late reply.
Shared MailBox code sample:
~~~java
ITokenProvider provider = new AzureROPCTokenProvider(tenant, clientId, "", userName, pwd, new String[]{"https://outlook.office.com/EWS.AccessAsUser.All"});
NetworkCredential credentials = new OAuthNetworkCredential("shared_1@xxx.onmicrosoft.com", provider);

try (IEWSClient client = EWSClient.getEWSClient(ExchangeVersion.Exchange2016,
        "https://outlook.office365.com/ews/exchange.asmx", credentials, null)) {
    MailMessage eml = new MailMessage("test1@xxx.onmicrosoft.com", "test2@xxx.onmicrosoft.com", "test shared", "body");
    client.appendMessage("Inbox", eml);
    //credentials.setUserName("shared_2@xxx.onmicrosoft.com");
    //...
}
~~~

The AzureROPCTokenProvider implementation is described in the link:
https://docs.aspose.com/email/java/microsoft-graph-utility-features/

**Comment by jackera1111** [comment]
There are two ways to [import EML to Office 365](https://www.adviksoft.com/blog/import-eml-files-to-office-365/
shared mailbox. One is a manual solution via Outlook and the other one is an automated solution. 

Method 1. Transfer EML to Office 365 via Outlook
1. Open Outlook and create a new folder.
2. Go to the location on your system where EML files are stored.
3. Drag & drop these files into the newly created folder.
4. Export this folder .pst format via Import/Export.
5. Add Office 365 account with Outlook.
6. Import exported file into Office 365 mailbox.
Done! That's how you can upload EML files to Office 365.

Method 2. Import EML to Office 365 via Third Party Tool
**Advik EML Converter** allows users to directly open EML file in Office 365. The software can import multiple EML files at once. It preserves data integrity and folder hierarchy as well during the process. Download its free version and complete the process in a few simple clicks.

1. Run this software on your system.
2. Add EML files into the software.
3. Choose Office 365 as a saving option.
4. Enter Office 365 login credentials.
5. Click on Next button to start the process.
The software will start importing EML files to office 365 shared mailbox. It will complete the process in a few seconds.
![eml-to-office4](https://github.com/user-attachments/assets/615c57be-ad42-4b14-a8b9-bdb032b01eb3)
