### ISSUE TITLE
I want to have a list of all users in a tenant

### ISSUE THREAD

**Issue by GabrieleDelPanno** [aspose-free-consulting/projects#381]
Aspose for .NET C#

Using Graph Service Client I can do something like:

var users = await graphServiceClient.Users.Request().GetAsync();

    foreach (var user in users) 
        Console.WriteLine(user.DisplayName);

Is there a way to obtain the same list using Aspose for .Net library ?

**Comment by dmitrysamodurov** [comment]
Hello @GabrieleDelPanno,

Aspose.Email does not support retrieving a list of users from a Graph API. 
Aspose.Email is geared towards email-related operations.
