### ISSUE TITLE
I want to convert word to pdf ,but my word contains comment

### ISSUE THREAD

**Issue by zhanghaijie1** [aspose-free-consulting/projects#382]
fisrt,When my word contains comments and there are replies to the comments, the original part of the text displayed in the converted pdf is not highlighted,
my code 
`String path = "/Users/icourt/Downloads/批注修订版_股权代持协议-测试_一轮-实际出资人.docx";
            Document document = new Document(path);
            document.save("/Users/icourt/Downloads/试i31据33rd.pdf", SaveFormat.PDF);
`
my word 
[批注修订版_股权代持协议-测试_一轮-实际出资人.docx](https://github.com/aspose-free-consulting/projects/files/14061352/_.-._.-.docx)
![image](https://github.com/aspose-free-consulting/projects/assets/89920034/f37eb32e-11c9-42e8-94c0-5e3b57dcea43)
converted pdf 
[试i31据33rd.pdf](https://github.com/aspose-free-consulting/projects/files/14061355/i31.33rd.pdf)
![image](https://github.com/aspose-free-consulting/projects/assets/89920034/0b12da7a-e823-4c10-ba4f-a1fb69562213)
 use 
<dependency>
            <groupId>com.aspose</groupId>
            <artifactId>aspose-words</artifactId>
            <version>20.1.0</version>
</dependency>

**Comment by AlexNosk** [comment]
@zhanghaijie1 Aspose.Words mimics MS Word when convert comments to PDF. If you convert your document to PDF using MS Word, the result will be similar to Aspose.Words result. 

PS: The main place for getting support is [Aspose support forums.](https://forum.aspose.com/c/words/8/)
