### ISSUE TITLE
I want to create new pages I Visio through aspose.Diagram API . Using python through Java on a MAC

### ISSUE THREAD

**Issue by gp52** [aspose-free-consulting/projects#385]
Hello

Thanks for a good product!

I have purchased aspose.diagram library.

How i try i cannot add new pages to an existing visio document.

I can create new visio files, change name of active page and create shapes. 

I have tried lots of methods and combinations:

This is one:
 bpmn.getPages().add(sida)

But get this error:

bpmn.getPages().add(sida)
TypeError: No matching overloads found for com.aspose.diagram.PageCollection.add(str), options are:
public int com.aspose.diagram.PageCollection.add(com.aspose.diagram.Page)

Please help me!

Another question about my license:

I am using a Mac M3

The following code:

import the License class
from asposediagram.api import License
license = License()
license.setLicense(“Aspose.Diagram.Product.Family.lic”)

Is the license active?

Best Regards

Göran Pettersson

**Comment by asadalikhan90** [comment]
@gp52 

It looks like you have opened[ similar topic](https://forum.aspose.com/t/add-pages-in-visio-with-aspose-python-java/278510) in our dedicated forum where we have responded you already. You can please keep following up there in case your issue still persists.

**Comment by gp52** [comment]
Hello Asad and Philip

I am quite new	 working with Aspose. I was not sure which forum was the best to get som help. Philip helped men and I am on track again. 

Thanks for all help. 

BR

Göran
