### ISSUE TITLE
PDF to PDF/A conversion with embedding fonts (subsets or all fonts)

### ISSUE THREAD

**Issue by dfashen** [aspose-free-consulting/projects#39]
Hi, before buying a license we want to do some tests and one of them is converting PDF to PDF / A. Our goal is to convert a PDF file (with or without embedded fonts) to compatible PDF / A standard  document (with all embedded fonts or subsets). We tried the presented code and found that after the conversion, file size increases many times (from 286KB to 35MB), we expected 5-10% growth depending on the size of the embedded fonts used. Are there any additional settings for the conversion process or file compression so that the output file size is acceptable?
[InputFile.pdf](https://github.com/aspose-free-consulting/projects/files/4493129/InputFile.pdf)
Output file can not be attached because of it's size (more than 10MB)

`Aspose.Pdf.Document pdfDocument = new Aspose.Pdf.Document(file);
            pdfDocument.Convert(input + "validationLog.xml", PdfFormat.PDF_A_2B, ConvertErrorAction.Delete);

//Linearization
pdfDocument.Optimize();
//Save doc
pdfDocument.Save(output);`

**Comment by shahzad-latif** [comment]
@dfashen 

Thanks for your interest in Aspose APIs. 

Could you please move your query to our forums, so the support team can better help you in a timely manner? https://forum.aspose.com/c/pdf

In fact, this place is dedicated for free consulting projects. I would really appreciate your cooperation and looking forward to help you out.

**Comment by dfashen** [comment]
@shahzad-latif Ok, I'll move my question to the forum, thx
