### ISSUE TITLE
Pricing 

### ISSUE THREAD

**Issue by pankajkrmca** [aspose-free-consulting/projects#394]
We have two requirements:

Load the Word document (.doc and .docx) and convert it into HTML.
Load the HTML and convert it into a Word document (.doc and .docx).

Could you please provide the pricing for these two requirements?

**Comment by AlexNosk** [comment]
@pankajkrmca Please contact our sales team in [Aspose.Purchse forum](https://forum.aspose.com/c/purchase/6). My colleagues will help you to select the right license type for your needs.
