### ISSUE TITLE
I want to use your library in an iOS app

### ISSUE THREAD

**Issue by iOS-hhjiang** [aspose-free-consulting/projects#395]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< I want to use your Aspose.Total for Java in an iOS application, but I have no idea how I need to integrate it, or what technical solution I need to use your library to integrate it. I can use swift / Object-C / React Native for development.Please help me.>

< iOS or React Native> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by amjad-sahi** [comment]
We have not tried it (using Java library in an iOS app). But apparently, there is no better way to cope with it. Java requires runtime to interpret (JRE) and you don't have that on iOS. I think you may try browsing online for some assistance.
https://stackoverflow.com/questions/1193524/can-we-run-java-applications-on-iphone
[how to use java API in react native](https://www.google.com/search?q=use+java+api+in+react+native&oq=use+java+api+in+reac&gs_lcrp=EgZjaHJvbWUqCQgBECEYChigATIGCAAQRRg5MgkIARAhGAoYoAEyCQgCECEYChigATIJCAMQIRgKGKAB0gEIODQ4NWowajeoAgCwAgA&sourceid=chrome&ie=UTF-8)

I guess you may either use our [REST APIs](https://products.aspose.cloud/total/) or .NET APIs. Please note, we used to provide separate Xamarin.iOS libraries (we do not include them in recent version archives) for it. We think you should go for our [REST (cloud) APIs](https://products.aspose.cloud/total/) to work in your iOS applications as any language/tool which supports REST Client can use our Cloud APIs.
