### ISSUE TITLE
Accidental line wrap

### ISSUE THREAD

**Issue by ZtionJam** [aspose-free-consulting/projects#398]
In the process of converting a word file to a pdf file, the paragraph encountered a "-" and the line was unexpectedly wrapped
![image](https://github.com/aspose-free-consulting/projects/assets/76614081/14ce001f-b9c7-43ec-9fb5-b68dc636a765)

**Comment by AlexNosk** [comment]
@ZtionJam Could you please attach your input and output documents here for testing? We will check the issue and provide you more information. 

PS: The main place for getting support is [Aspose.Words support forum](https://forum.aspose.com/c/words/8/). So it is better to report problems there,
