### ISSUE TITLE
Aspose presentation numbered bullet format issue

### ISSUE THREAD

**Issue by sfgny** [aspose-free-consulting/projects#399]
Hi,

I am using aspose slides to generate a PDF document in asp.net MVC.
The system has a rich text input which stored as an html string then it can be generated into pdf.

This is a sample input:
![numberedbullet-html](https://github.com/aspose-free-consulting/projects/assets/168066542/c7e2be85-cba4-4ca1-9feb-cddb0cd76017)

I am using the following function to render the html input.

**ITextFrame textFrame;
textFrame.Paragraphs.AddFromHtml(@htmlText);**

However, there is a problem in rendering the numbered bullet. It is being formatted based on the very first text format. The problem is the **Bold** and _Italicize_,

![numberedbullet](https://github.com/aspose-free-consulting/projects/assets/168066542/21d67868-f3be-4cfb-99f5-292954b8642c)

Removing the styles in portion text seems to work in removing the bullet format. But this is not the solution since we needed to retain the actual style that is entered in the rich text editor.

**foreach (var portionText in paragraph.Portions)**
**{**
    **portionText.PortionFormat.FontItalic = NullableBool.False;**
    **portionText.PortionFormat.FontBold = NullableBool.False;**
**}**

What I needed is to make the numbered bullet in plain format, just like in the html rendering. Is there any solution for this?
Thanks in advance.

**Comment by andreypotapovaspose** [comment]
@sfgny,
We are sorry that you had to encounter this problem. We need more details to investigate the case and help you. Please share the following files and information:
- input HTML string
- output presentation file
- Aspose.Slides version you used

**Comment by sfgny** [comment]
Hi, thank you for looking into this. For your reference.

Input HTML string:
`<p></p><ol><li>Normal text - correct bullet format</li><li><b>Bold text</b> - wrong bullet format</li><li><u>Underline text</u> - correct bullet format</li><li><i>Italicize text</i> -&nbsp; wrong bullet format</li><li><b><i><u>Bold underline italicize text</u></i></b> -&nbsp; wrong bullet format</li></ol><p></p>`

Aspose.Slides version:
**Aspose.Slides
	Version 17.5.0.0
	Runtime version v4.0.30319**


Output presentation file:
[Sample-Generated-PDF.pdf](https://github.com/aspose-free-consulting/projects/files/15110495/Sample-Generated-PDF.pdf)

**Comment by andreypotapovaspose** [comment]
@sfgny,
Thank you for the details. I am working on the issue and will get back to you soon.

**Comment by andreypotapovaspose** [comment]
@sfgny,
Thank you for your patience. I reproduced the problem you described. We apologize for any inconvenience caused.

We have opened the following new ticket(s) in our internal issue tracking system and will deliver their fixes according to the terms mentioned in [Free Support Policies](https://forum.aspose.com/t/free-support-policies/162313).

    Issue ID(s): SLIDESNET-44541

You can obtain [Paid Support Services](https://helpdesk.aspose.com/) if you need support on a priority basis, along with the direct access to our Paid Support management team.

**Comment by sfgny** [comment]
@andreypotapovaspose do we have an update of fix regarding this issue? Thank you!

**Comment by amjad-sahi** [comment]
@sfgny, 

We are pleased to inform you that the issue you reported earlier as "SLIDESNET-44541" has been resolved. The fix will be included in the upcoming release (Aspose.Slides v24.6), which we plan to release before the end of this month. We will notify you when the fixed version is released.

Please feel free to contact us or follow up on your ticket.

**Comment by sfgny** [comment]
Hi, I'm very grateful for the  assistance! Everything looks good after using the v24.6.

PDF Result:
![image](https://github.com/user-attachments/assets/08d6a7ce-ab77-4066-9aa1-d133a7879f2a)

**Comment by andreypotapovaspose** [comment]
@sfgny,
We are glad that the issue has been resolved on your end. Thank you for using Aspose.Slides.
