### ISSUE TITLE
I want to create/build a an image rendered from Author and session title information passed as parameters to display / be transposed onto image that is generated as PNG or JPG ot GIF

### ISSUE THREAD

**Issue by RazDynamics** [aspose-free-consulting/projects#4]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by shahzad-latif** [comment]
@razdynamics

If I understand correctly, you want to show Author Name and Session Name in the form of an image. That's easy and we can do that quickly.

However, it would be great if you share a sample of the output the way you want to view it.

And if there is more to the requirements please do share that as well.

**Comment by shahzad-latif** [comment]
@RazDynamics 

Please this code at your end: https://github.com/aspose-free-consulting/Build-Image-Rendered-from-Author-Name-and-Session-Title

This provides the code which you need to convert text to image. This code can be reused in SharePoint as WebPart or other coding options as you like. Please let me know if you need any further details or changes in the code etc. Also share if this can help in your case.
