### ISSUE TITLE
I want to import calendar in Office365 without notifications

### ISSUE THREAD

**Issue by ritadcc126** [aspose-free-consulting/projects#40]
Trying to create appointment in Office365 with MapiCalendar but throws an Extended property exception. The main problem is that appointment doesn't support 'suppress invitation' that can be done with MapiCalendar. I don't want invitations to sent to attendees from Office365 , I just want to export appointments and calendars from .ics file to Office365 calendar but invitations should not be sent.
I had cleared all the reminders from appointment using appointment.reminders.clear();
Please help on this issue

**Comment by shahzad-latif** [comment]
@ritadcc126 

Which API are you using to import calendar?

**Comment by ritadcc126** [comment]
Aspose.email

**Comment by mudassirfayyaz** [comment]
@ritadcc126 ,

I have observed your requirements w.r.t Aspose.Email and like to share that there is no provision in API that when you push appointments and calendars from .ICS file to Office365 calendar the invitations should not be sent. The only possible option is that you should remove attendee collection in ICS file before exporting to Office 365 account.

            meeting.Attendees.AppointmentRecipients.Clear();
            meeting.Attendees.AppointmentUnsendableRecipients.Clear();

For your second issue related to extended property exception being thrown, we request you to please provide the source code and used sample file with which you are able to reproduce the issue.

I am assuming that your already using Aspose.Email for .NET 20.4 on your end.
