### ISSUE TITLE
To make a point visible.

### ISSUE THREAD

**Issue by VavoosAnjana** [aspose-free-consulting/projects#400]
I have created a ppt using aspose and creating a graph using aspose.slides.IChart. what the issue is it is setting the x axis interval by default. For example my x axis values are 0,1,2,3.......101 it is displaying as 0,2,4.....,98,100. Taking interval as 2. What I need is I need to visible a point I like in axis. For example I need to make visible point 3 so x axis should display as 0,2 ,3,4....100. How can I do this

**Comment by andreypotapovaspose** [comment]
@VavoosAnjana,
It looks like you can't do this in PowerPoint presentations. If I'm wrong, please share a presentation file with a chart whose X-axis has the desired appearance.
