### ISSUE TITLE
I am trying to convert a glb file with textures into 3Ds while preserving textures

### ISSUE THREAD

**Issue by hejdamax** [aspose-free-consulting/projects#404]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

Hello I am trying to figure out how to export a glb file into 3Ds (and if possible Collada) while preserving textures embedded in the glb file. 

.Net, linux

[one_module_colored_glb.zip](https://github.com/aspose-free-consulting/projects/files/15456817/one_module_colored_glb.zip)

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by hejdamax** [comment]
I figured out how to make it export the textures but no viewer will apply them. Been using just web viewers... Would like to know if I can package them somehow so that viewers will apply them.

**Comment by asadalikhan90** [comment]
@hejdamax 

Looks like you have opened similar inquiries in our dedicated support forum where discussions have already been started in the respective [thread(s)](https://forum.aspose.com/t/convert-from-glb-to-autocad-importable-file/284408). We request that you can please follow up there and post new inquiries as well if you have additional requirements. We will respond and assist you accordingly.

**Comment by hejdamax** [comment]
@asadalikhan90 

Yeah I had a couple of questions which I posted to the forum and one more coding problem which I posted here. Hope that is OK. I can move this query to the forum too if it would be better :)

**Comment by asadalikhan90** [comment]
@hejdamax 

Yes, we would always encourage to post such topics in our dedicated support forum. Thank for posting the questions there.
