### ISSUE TITLE
I want to transform CSV coordinates from EPSG 2177 to epsg 3266

### ISSUE THREAD

**Issue by Coolkizzz** [aspose-free-consulting/projects#405]
Hello,
What I exactly want to do is to convert a file with extension .csv which consist of data in epsg 2177 and transform it into the epsg 3266 system with the same file extension.
Is that even possible? Since GIS app called transformation has only one record field to fill?
And when I 've tried to do that by app conversion it keeps shouting about wkt col name ble ble which is being not found in the file.
Looking forward for message back.
Best regards,

**Comment by atirtahirgroupdocs** [comment]
@Coolkizzz 

Could you please share the problematic/source file with us and the app link that you are using? We'll further investigate this scenario. 
Thanks
