### ISSUE TITLE
Custom headers gets removed while dowloading DRAFT using MapiMessage.SetMessageFlags(MapiMessageFlags.MSGFLAG_UNSENT)

### ISSUE THREAD

**Issue by ranakomal90** [aspose-free-consulting/projects#407]
When I create an email then save as DRAFT status using MapiMessage.SetMessageFlags(MapiMessageFlags.MSGFLAG_UNSENT) and then save this email to file as a .MSG file, reopen and send, I can see the email in my inbox. But the custom headers that I added before saving the draft are somehow getting removed. Is there a way to retain the cutom headers in the draft?

**Comment by MargaritaSamodurova** [comment]
Hello @ranakomal90 ,

Thank you for reporting your issue. I can see the same request from you on the Aspose.Email free support forum. And this is the right place for solving issues. Please, return to our [thread](https://forum.aspose.com/t/custom-headers-gets-removed-while-dowloading-draft-using-mapimessage-setmessageflags-mapimessageflags-msgflag-unsent/284659/2?u=margarita.samodurova) with an open conversation and we'll do our best to help you with the problem.
