### ISSUE TITLE
How i  can add svg image to header and footer in aspose.cell

### ISSUE THREAD

**Issue by sofiansamamr** [aspose-free-consulting/projects#409]
How i  can add svg image to header and footer in aspose.cell , and if its not available when it will be ?

**Comment by amjad-sahi** [comment]
I think currently MS Excel does not directly support adding SVG images to headers or footers. This is a known limitation. Aspose.Cells follows MS Excel standards and specifications, so it also does not support adding SVG images to headers/footers. However, you can achieve this by converting the SVG image to a supported format like PNG or JPEG and then inserting it via Aspose.Cells APIs.
