### ISSUE TITLE
I want to create/build 

### ISSUE THREAD

**Issue by velpaybrasil** [aspose-free-consulting/projects#41]
Olá pessoal!

Eu tenho um site FACEDOC.COM.BR quero colocar um CRIADOR DE DOCUMENTOS NO EDITOR.FACEDOC.COM.BR um serviço em subdominio.

Me ajudem a faze-lo.

Hello people!

I have a FACEDOC.COM.BR website I want to put a DOCUMENT CREATOR IN EDITOR.FACEDOC.COM.BR a service in a subdomain.

Help me do it.

**Comment by shahzad-latif** [comment]
@velpaybrasil 

Thanks for getting in touch. What types of documents you want to edit? And what kind of editing you're planning to do on that site? Also which programming language you use? 

Are you looking for some "editor" out of the box or you want to build an editor at your own and just looking for APIs to build that? 

Please clarify above questions and then we'll be able to help you out.

**Comment by velpaybrasil** [comment]
**My users need to edit documents in .DOC .DOCX. For now, I will not do any integration. Users must upload files, or drag and drop, and will be able to edit online.**

Editing documents .DOC .DOCX and other formats...

Used PHP.

I'm looking for something ready, that I can just install on my deploy (editor.facedoc.com.br)

**Comment by atirtahirgroupdocs** [comment]
@velpaybrasil ,

Please have a look at this online document editing [application](https://products.groupdocs.app/editor). You can edit Word processing, Presentation, PDF and many other documents. 
This application is developed using GroupDocs.Editor API and this API is available for Java and .NET platforms only.
One possible solution could be to develop your own document editing solution/web app (like [this one](https://github.com/groupdocs-editor/GroupDocs.Editor-for-.NET-MVC) using GroupDocs.Editor for .NET or Java API and embed or load it in iframe on your subdomain.
