### ISSUE TITLE
I want to autofitcolumns using Aspsoe.CellsI on the formatted columns. 

### ISSUE THREAD

**Issue by larryfan2023** [aspose-free-consulting/projects#412]
[AutoFitIssue.xlsx](https://github.com/user-attachments/files/15775651/AutoFitIssue.xlsx)

I have a columns formatted as currency, see attached file. I tried to use the code below to auto fit the columns width, but it didn't adjust the columns width. Please advise.

AutoFitterOptions options = new AutoFitterOptions();
options.FormatStrategy = CellValueFormatStrategy.DisplayString;

.....

//auto fit width
foreach (Worksheet w in workbook.Worksheets)
{
   
    w.AutoFitColumns(options);

}

**Comment by larryfan2023** [comment]
I modified font that is available in my machine and tested it worked. Thank you so much for resolving this issue.

**Comment by amjad-sahi** [comment]
@larryfan2023,

It is nice to know that after changing to the installed font on your machine, your issue is sorted out. Please feel free to contact us any time if you have further queries or comments. You may also post your queries in the dedicated [forums](https://forum.aspose.com/c/cells/9).
