### ISSUE TITLE
the Effects of Layer Set don't work

### ISSUE THREAD

**Issue by jakefroz1** [aspose-free-consulting/projects#414]
when I use Aspose.PSD.Image.Load to load .psd, the  Effects of 'Layers' can work, but 'Layer Set' can not
I want to know if there are corresponding parameters

```c#
var loadOptions = new PsdLoadOptions()
            {
                LoadEffectsResource = true,
            };
            
        using var im = (PsdImage)Aspose.PSD.Image.Load(sourcePsdPath,loadOptions)
```

**Comment by dimsa** [comment]
@jakefroz1 could you please provide input file? Aspose.PSD supports not all effects. Could you please provide additional code with "Layer Set".

**Comment by jakefroz1** [comment]
> @jakefroz1您能否提供输入文件？Aspose.PSD 并非支持所有效果。您能否提供带有“图层集”的附加代码。

sorry，image is too large to upload 'Layer Set' means 'Floder',
