### ISSUE TITLE
About the font authority for converting PDF using apose.words python via .net

### ISSUE THREAD

**Issue by PH8919** [aspose-free-consulting/projects#416]
Hi Guy,
I am using the apose.words python via .net to convert DOCX into PDF on linux. i need to install the MS fonts on Linux.  as you suggested on https://docs.aspose.com/words/python-net/installing-truetype-fonts-on-linux/,  there are two ways to put the MS fonts on Linux. but you also hint that font license may be required. Does both of the two ways need license authority or something else?
Thanks!

**Comment by AlexNosk** [comment]
@PH8919 Aspose. Words does not provide fonts, except the Fanwood font embedded into Aspose.Words library, which is used as the last resort font. Different fonts have different licenses and you should consider licenses when use the fonts as any other intellectual property. Regarding using Microsoft fonts, it is better to consult with Microsoft, since they are owners of the fonts.

**Comment by PH8919** [comment]
@AlexNosk thanks for your answer. I think you mean either of the two methods you mentioned at  https://docs.aspose.com/words/python-net/installing-truetype-fonts-on-linux/ cannot avoid license obligation on Linux, is it right?
At the same time, when i convert DOCX into PDF including picture, the characters in picgure will be displayed abnormally in generated PDF if i donot bring MS font in, like below, the text is presented using picture instead of raw text in DOCX:
DOCX: 
![image](https://github.com/aspose-free-consulting/projects/assets/84227812/43fdc5a2-15f8-4b3d-9394-4b7ca9f42aa8)
Generated PDF: 
![image](https://github.com/aspose-free-consulting/projects/assets/84227812/d05f4e7a-7649-4bbe-b708-1b8fe8d1140b)
What is the reason to that? as my understanding, the picture should be converted normally.

Hope for your check and reply!

**Comment by AlexNosk** [comment]
@PH8919 Please attach your input and output documents for testing. We will check the issue and provide you more information. 

PS: Please post your questions in the public [Aspose.Words support forum](https://forum.aspose.com/c/words/8), which is the main place for getting support.

**Comment by PH8919** [comment]
@AlexNosk Sorry that i cannot upload it to the forum now due to extra approval is needed(Maybe it is forbidden). before that, i can tell you that the picture only contain text and is an EMF file, and the font used in it is Calibri. Maybe this information can help you to figure out the reason.

**Comment by AlexNosk** [comment]
@PH8919 Thank you for additional information. In EMF metafiles exact position of glyphs are specified. So in case of font substitution, if the substitution font has different metrics, the result of rendering might be as on your screenshot. Unfortunately, it is difficult to say for sure without a real file.

**Comment by PH8919** [comment]
@AlexNosk I had uploaded the word to your support forum and let's move there to talk about it.
