### ISSUE TITLE
java集成aspose将PDF文件转成Excel文件，本地转换60s，测试只要8s,这是什么原因呢？ 字体原因吗？ 

### ISSUE THREAD

**Issue by aurorawill** [aspose-free-consulting/projects#417]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by aurorawill** [comment]
[Uploading 对账单_民泰银行_0015_202404.pdf…]()

**Comment by asadalikhan90** [comment]
@aurorawill 

衡量API性能的正确方法是在发布模式下进行测试。在本地开发环境中，API首先在内存中加载必要的资源（例如字体），然后处理文件。但是，如果您随后在本地环境中运行相同的代码，您会发现比第一次运行的转换时间更少。

**Comment by aurorawill** [comment]
@asadalikhan90 现在就是在发布模式下进行测试，发现转换时间也是非常慢的，其它Pdf文件转换挺快的，就这个Pdf文件慢，您可以使用我上传的附件测试一下       

public static void changeToExcel(String filePath, String folderNm, Integer page, List<String> excelPathList) {
        Document pdfDocument = new Document(filePath);
        // Instantiate ExcelSave Option object
        ExcelSaveOptions excelsave = new ExcelSaveOptions();
        excelsave.setInsertBlankColumnAtFirst(false);
        // Save the output in XLS format
        //定义文件名 
        String excelPath = folderNm + page + ".xls";
        pdfDocument.save(excelPath, excelsave);
        excelPathList.add(excelPath);
    }

**Comment by asadalikhan90** [comment]
@aurorawill 

我们相信您已经通过以下链接在我们的支持论坛中创建了一个主题。我们已经通过记录票证解决了您的问题。我们将在相应的线程中向您通报有关故障单解决的最新信息。

> https://forum.aspose.com/t/pdf-excel/287677
