### ISSUE TITLE
Aspose Slide ChartType LineWithMarkers Line Issue

### ISSUE THREAD

**Issue by sfgny** [aspose-free-consulting/projects#419]
Hi,

I am trying to convert this chart which uses System.Web.UI.DataVisualization.Charting to a new line graph which uses the **Aspose Slide** library.

DataVisualization:
![image](https://github.com/user-attachments/assets/308d7a10-3c16-4c19-a5bd-5c0cae8d2964)

However, upon plotting the datapoint. This is what I'm getting:

**Aspose using ChartType.LineWithMarkers**
![image](https://github.com/user-attachments/assets/64e99934-6cb3-4005-9fc9-1f432f54d8cc)

We are using **2500+ data points** in the chart to plot it.

My only concern is how I can achieve that kind of lines using line chart.
Can you advice the best course or can you provide a sample code that will generate similar to the DataVisualization one? Thank you.

**Aspose.Slides version:**
Aspose.Slides.NET
Version 24.6.0

**Comment by andreypotapovaspose** [comment]
@sfgny,
We would like more details to investigate the case and help you. Please share the following files and information:
- input presentation file
- code example to reproduce the problem
- output presentation file

**Comment by sfgny** [comment]
Hi, this issue can be closed now. I was able to fix the code. 
The solution is to add data points altogether so that they are connected.

Reference:
```
IChartDataPoint point = series.DataPoints.AddDataPointForLineSeries(fact.GetCell(defaultWorksheetIndex, 1, 1, (double)4.5));

point = series.DataPoints.AddDataPointForLineSeries(fact.GetCell(defaultWorksheetIndex, 2, 1, (double)2.5));

point = series.DataPoints.AddDataPointForLineSeries(fact.GetCell(defaultWorksheetIndex, 3, 1, (double)3.5));
```

Output:
![image](https://github.com/user-attachments/assets/7bac39a7-0f7d-4f89-9903-cc4fbbe1277e)
