### ISSUE TITLE
I want to scan image files in c++ ( to extend python)

### ISSUE THREAD

**Issue by RyskiQN** [aspose-free-consulting/projects#42]
I want to make a c++ python extension using this SDK but I am inexperienced with managed c++ and am having issues simply compiling just the includes from the documentation samples.
If you can help me get it working in c++ I should be able to get the rest of the way to python.
[AsposeTest.txt](https://github.com/aspose-free-consulting/projects/files/4537794/AsposeTest.txt)  *.cpp
I've tried setting some includes to be unmanaged with #pragma and moved stuff around but nothing worked, and I can't remember the order everything is meant to be in.
Cheers for any help.

**Comment by amjad-sahi** [comment]
@RyskiQN ,
I think you may download the ready to use VS.NET project (Aspose.BarCode for C++ examples) [here](https://github.com/aspose-barcode/Aspose.Barcode-for-C). It has solution file, so you may open it into VS.NET and then edit or change code and run easily. This will give you understanding and help you to built your own to get it working in C++.

**Comment by RyskiQN** [comment]
@amjad-sahi ,
That was definitely helpful, I've got a working python extension now.
I was wondering if you could point me to any settings I can tweak to increase the read rate?
I am mainly using this dataset of qr codes:
https://boofcv.org/notwiki/regression/fiducial/qrcodes_v3.zip
with the addition of printed and then scanned images from our workflow.
I've attached some for reference, they're usually .tiff format but Github doesn't support that.
Thanks for the help so far.
![chart_easy_12](https://user-images.githubusercontent.com/32590384/81893326-cb140d00-95f0-11ea-921d-44e170ca52bb.jpg)
![chart_hard_13](https://user-images.githubusercontent.com/32590384/81893328-cd766700-95f0-11ea-80f4-a87cc6383e41.jpg)
![chart_med_12](https://user-images.githubusercontent.com/32590384/81893332-cea79400-95f0-11ea-8e65-2de0c8dc99ef.jpg)

**Comment by amjad-sahi** [comment]
@RyskiQN ,

It looks like you find issues in reading the qr codes in some images (you attached an archive of long list of images). There can be an issue in reading barcodes for some low quality images. This is kind of known issue but we need to evaluate and try to sort these out (if possible). We appreciate if you could post your issues by instantiating new threads in respective [forum](https://forum.aspose.com/c/barcode). This will help us evaluate your issues precisely to figure these out.

**Comment by RyskiQN** [comment]
Hi Amjad,
Could you explain how I can go about using the QualitySettings class in native C++? I keep getting Incomplete types trying any BarCodeRecognition::QualitySettings::…
And also are there any other meaningful settings or is it all encapsulated in this class?
Thank you,
Ryan.

**Comment by amjad-sahi** [comment]
@RyskiQN,

See the [document](https://docs.aspose.com/display/barcodecpp/Improve+Barcode+Recognition#ImproveBarcodeRecognition-BarcodeRecognitionModes) for your reference on how to specify barcode recognition modes and try if it works or not. May be you are trying with some low quality images which is not working. Anyways, we recommend you to to post your issues by instantiating new threads in respective forum as asked earlier.
