### ISSUE TITLE
Not able to read the clipping path embedded in the tiff file as directed in https://docs.aspose.com/imaging/net/create-vector-path-in-tiff-format-and-export-it-to-psd-image/

### ISSUE THREAD

**Issue by Eakshitha11** [aspose-free-consulting/projects#421]
Hi Team

I am trying to work with the creating clipping path and embedding it into the tiff file using the dotnet support as given here-
https://docs.aspose.com/imaging/net/create-vector-path-in-tiff-format-and-export-it-to-psd-image/. 

I have a tiff image file with an object in between whose path is required and a grey background, and I read the path resource in block id 2000. 

I am loading the path from PathPoints.txt file as shown in the link. 
As per my understanding, each line in the txt contains 3 relative coordinates in the order - Control point, Anchor point, Control point. 
Each of this point contains two components - vertical coordinate relative to height, horizontal coordinate relative to width.
I have kept single space between each component and each point.
Example of how my txt file looks with a test clipping path :

0.66225 0.06725 0.66225 0.06725 0.66225 0.06725
0.64075 0.06925 0.64075 0.06925 0.64075 0.06925
0.62675 0.07125 0.62675 0.07125 0.62675 0.07125
0.61125 0.072 0.61125 0.072 0.61125 0.072
0.59275 0.07075 0.59275 0.07075 0.59275 0.07075
0.577 0.0715 0.577 0.0715 0.577 0.0715

Issues:
--------
1. Here, above path has total 18 points. But when I try to embed the same into the tiff file and read the count of records in the tiff, it gives 19 instead of 18.

2. Also after saving the tiff with clipping path embedded into it, the background color of the image gets changed from grey to bluish tone somehow.

3. While I try to load the tiff file with embedded clipping path in photoshop, it errors out saying "Could not open 'SampleWithPaths.tif' because of a problem parsing the path data". 

Sharing here the code that I have used to embed the path:

    using Aspose.Imaging.FileFormats.Tiff;
    using Aspose.Imaging.FileFormats.Tiff.PathResources;
    using Aspose.Imaging;
    using Aspose.Imaging.FileFormats.Core.VectorPaths;
    using Aspose.Imaging.ImageOptions;

    class Program
    {
        static void Main()
        {
            using (var image = (TiffImage)Image.Load(@"D:\clipping_path\dotnet_code\Test_embedding\SampleNoPaths.tif"))
            {
                image.ActiveFrame.PathResources = new List<PathResource> { new PathResource
                {
                    BlockId = 2000, // Block Id according to Photoshop specification
                    Name = "Without Shadow", // Path name
                    // Records = CreateRecords(0.2f, 0.2f, 0.8f, 0.2f, 0.8f, 0.8f, 0.2f, 0.8f) // Create path records using coordinates
                    Records = CreateRecords(LoadPathPoints(@"D:\clipping_path\dotnet_code\Test_embedding\PathPoints.txt")) // Create path records using coordinates
                }};

                image.Save(@"D:\clipping_path\dotnet_code\Test_embedding\SampleWithPaths.tif");
                using (var img = Image.Load(@"D:\clipping_path\dotnet_code\Test_embedding\SampleWithPaths.tif"))
                {
                    image.Save(@"D:\clipping_path\dotnet_code\Test_embedding\SampleWithPaths.psd", new PsdOptions());
                }
                Console.WriteLine("Hello, World!");
            }
        }
    
     
        // static void Main()
        // {
        //     // using (var image = (TiffImage)Image.Load(@"D:\clipping_path\dotnet_code\Test_embedding\image.tif"))
        //     using (var image = (TiffImage)Image.Load(@"D:\clipping_path\dotnet_code\Test_embedding\SampleWithPaths.tif"))
        //     {
        //         // Get path resources from TIFF image
        //         var pathResources = image.ActiveFrame.PathResources;
    
        //         if (pathResources != null)
        //         {
        //             foreach (PathResource path in pathResources)
        //             {
        //                 Console.WriteLine("pathresource: ", pathResources);
        //                 var x = pathResources.Take(3).ToList();
        //                 Console.WriteLine("x: ", x);
    
        //                 if (path.BlockId == 2000)
        //                 {
        //                     // Determine clipping path name
        //                     var clippingPathName = path.Name;
        //                     // Get clipping path
        //                     var clippingPath = path;
        //                     // Write record count to the console
        //                     Console.WriteLine("Clipping path record count: " + clippingPath.Records.Count);
        //                     Console.WriteLine("path name: " + clippingPathName);
        //                     Console.WriteLine("path: ", clippingPath.Records);
        //                 }
        //             }        
        //         }
        //     }
        // }
    
        private static float[] LoadPathPoints(string filePath)
        {
            return File.ReadAllText(filePath)
                .Split(new[] { " ", "\r\n" }, StringSplitOptions.RemoveEmptyEntries)
                .Select(float.Parse)
                .ToArray();
        }
    
        private static List<VectorPathRecord> CreateRecords(params float[] coordinates)
        {
            var records = CreateBezierRecords(coordinates); // Create Bezier records using coordinates
    
            records.Insert(0, new LengthRecord // LengthRecord required by Photoshop specification
            {
                IsOpen = false, // Lets create closed path
                RecordCount = (ushort)records.Count // Record count in the path
            });
    
            return records;
        }
    
        private static List<VectorPathRecord> CreateBezierRecords(float[] coordinates)
        {
            return CoordinatesToPoints(coordinates)
                .Select(CreateBezierRecord)
                .ToList();
        }
    
        private static IEnumerable<PointF> CoordinatesToPoints(float[] coordinates)
        {
            for (var index = 0; index < coordinates.Length; index += 2)
                yield return new PointF(coordinates[index], coordinates[index + 1]);
        }
    
        private static VectorPathRecord CreateBezierRecord(PointF point)
        {
            return new BezierKnotRecord { PathPoints = new[] { point, point, point } };
        }
    }

Do let me know where I am going wrong. The coordinates estimated in the txt file are for testing. Let me know if my understanding in creating the path points in txt file is wrong, or if you can share me any test path points (since the points are relative, it should work, though it would not necessarily outline the object) that would work might also help me.

Aspose.Imaging Version : 24.6.0

Thanks and Regards

**Comment by sam199008** [comment]
@Eakshitha11 , we will investigate issue and reply.

**Comment by alex-p-k** [comment]
@Eakshitha11 Hello! Thank you for your interest in our product and for your patience.

We have thoroughly investigated the issue you reported and would like to provide the following guidance. To resolve the problem, please update the usage of the `RecordCount` property in the `CreateRecords` method to the `BezierKnotRecordsCount` property. The corrected line of code should be:

```csharp
BezierKnotRecordsCount = (ushort)records.Count // Record count in the path
```

Regarding your question about the record count, it is important to note that an additional "length" record is required. Therefore, the inclusion of this extra record is indeed the correct behavior.

We apologize for any inconvenience this may have caused and appreciate your understanding. The documentation will be updated shortly to reflect this change.

Thank you for bringing this to our attention, and please do not hesitate to reach out if you have any further questions or concerns.

**Comment by Eakshitha11** [comment]
Hi @alex-p-k, My Apologies for a delayed response, and thank you so much for such a detailed explanation.
This indeed helped me understand the code and the nature of Bezier Curve that has been used here.

Also the visual representation cleared most of my confusion with respect to which is anchor and which being the control points, confirming my understanding of the same.

Now, I can easily get the anchor points that I believe that which lie on the edges of the object. 
But I am curious to know how about calculating the coordinates of these control point pairs for a given anchor point (if this is in the scope of discussion). Is there any given formulae that can be useful for the same. (Sorry, if I am sounding naive at this point, I am relatively new to the whole Bezier curve concepts ). Also, I tried looking up in the internet about them but it all seemed pretty confusing.

Thank You so much your help so far. Greatly Appreciated!!
Regards
Eakshitha K

**Comment by sam199008** [comment]
@Eakshitha11 , we will investigate and answer you.

**Comment by alex-p-k** [comment]
@Eakshitha11 Could you please clarify what you mean by calculating control point coordinates? The formulas for calculating Bezier curves allow you to obtain intermediate coordinates on the curve, which is necessary for rendering, but Aspose.Imaging handles this automatically, so there's no need to do these calculations manually. As for choosing control points to achieve the desired curve shape, it's mainly a matter of adjusting points based on the resulting curves to fit your desired outcome. If you're talking about converting a set of simple points to a smoother curve or matching a specific smooth curve, that's a more complex topic. Please specify what you're interested in.

**Comment by Eakshitha11** [comment]
@alex-p-k , Sure.
By calculating control point coordinates,
 I mean I have the specific curve, I have the anchor points, but instead of manually finding out the control points by adjusting it attain designed curve shape, how can we automate finding out the control points?
 So yes, I am essentially talking about converting a set of simple points (that lie on this curve ) to a smoother bezier curve (that matches this curve). Let me know if you have any insights on this, any supporting blogs/articles that can be of help to reverse engineer the process.
 
 Thanks and Regards
 Eakshitha K

**Comment by alex-p-k** [comment]
@Eakshitha11 I'm afraid this topic falls outside the scope of our free services related to explaining Aspose.Imaging product capabilities. You can obtain [Paid Support Services](https://helpdesk.aspose.com/) if you need support on a priority basis, along with the direct access to our Paid Support management team.
