### ISSUE TITLE
I need to extract MathML equations from an ODT file

### ISSUE THREAD

**Issue by vincent-lg** [aspose-free-consulting/projects#422]
I would need to import an ODT file containing text and mathematical equations (as OfficeMath nodes). I would need to extract these nodes: the mathematical equations should be available in MathML (XML variant).

Ideally, I would need to do the reverse: write a document to be exported as ODT containing text and mathematical equations (again, from MathML).

#### Platform

* Operating system: Windows ;
* Programming language: Python 3.11+.

#### Attachments

[demo-to-aspose.odt](https://github.com/user-attachments/files/16235106/demo-to-aspose.odt)
See `demo-to-aspose.odt` for an example of a basic file to import.

**Comment by andreypotapovaspose** [comment]
@vincent-lg,
I am working on your requirements and will get back to you soon.

**Comment by AlexNosk** [comment]
@vincent-lg You can use the following code to convert OfficeMath nodes to MathML:
```py
doc = aw.Document("C:\\Temp\\in.odt")
html_options = aw.saving.HtmlSaveOptions()
html_options.pretty_format = True
html_options.office_math_output_mode = aw.saving.HtmlOfficeMathOutputMode.MATH_ML
# Loop through office math nodes
for m in doc.get_child_nodes(aw.NodeType.OFFICE_MATH, True) :
    # Check whether office math is top level
    if m.get_ancestor(aw.NodeType.OFFICE_MATH) == None:
        print(m.to_string(html_options))
        print("===============================")
```

**Comment by vincent-lg** [comment]
Thank you very much. It works as expected.

As mentioned, we would also need to do the reverse (from some text and MathML, get a document structure we could save to an ODT file). Could you provide the code to showcase the operation, or would it be considered a different project? I guess I can create the node hierarchies (body, paragraph, OMATH, run) if needed, but again, there might be a better solution already provided by the tool.

Thank you again,

**Comment by AlexNosk** [comment]
@vincent-lg You can using [DocumentBuilder](https://reference.aspose.com/words/python-net/aspose.words/documentbuilder/) to build the document. For example to insert MathML, you can use [DocumentBuidler.insert_html](https://reference.aspose.com/words/python-net/aspose.words/documentbuilder/insert_html/) method.
