### ISSUE TITLE
We have implemented end to end encryption at our frontend (angular), I would like to know if aspose file viewer is applicable to our case

### ISSUE THREAD

**Issue by lmatanov** [aspose-free-consulting/projects#425]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by atirtahirgroupdocs** [comment]
@lmatanov 

Please note that [Aspose document viewer](https://products.aspose.app/words/viewer) app is developed using [Aspose.Words for .NET](https://docs.aspose.com/words/net/product-overview/). Aspose.Words for .NET is a UI-agnostic, back-end API that could be integrated in any .NET application, regardless of the front-end framework.
Could you please confirm whether you are using .NET or Java for the backend?

Thanks
