### ISSUE TITLE
I want to create/build Batch process jpgs to excel where each picture populates a row with data in dolumns

### ISSUE THREAD

**Issue by msweda** [aspose-free-consulting/projects#426]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:
We wish to add item number/part numbers and other item information from a jpg taken from the box itself. We will need to process as many images as possible, the more the better. The output would populate a excel row and each image would populate corresponding rows within that same excel file. We know we will need to  manipulate the excel file to organize the data.  Don't know if this qualifies under this program. 
< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 
Testing the program using your android app. It's working very well. We would like to "share" pictures from android to email on a windows email app. 
<attach input documents>
![jpg_1](https://github.com/user-attachments/assets/3a752935-da3e-45a0-83d5-f9393f455d11)

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by amjad-sahi** [comment]
@msweda,

It appears you wish to insert pictures into an Excel file. You can use [Aspose.Cells](https://products.aspose.com/cells/family/) to manipulate (insert, update, remove) images and data in Excel spreadsheets. Refer to the documentation on how to [manipulate pictures](https://docs.aspose.com/cells/java/managing-pictures/)) in the worksheet of an Excel workbook/file. Additionally, consult the documentation on how to [add/update data in the worksheet](https://docs.aspose.com/cells/java/add-and-retrieve-data/)) for your reference.

If you still have any confusion or difficulty in completing your task, please zip and attach your final/desired Excel file with all the images pasted in the order you need. Additionally, provide us with the original images, and we can then write a sample code for your reference.

> We wish to add item number/part numbers and other item information from a jpg taken from the box itself. We will need to process as many images as possible, the more the better

To extract item number and other details from JPG images, you could use barcode scanning or optical character recognition (OCR) techniques. If the images contain barcodes, you may leverage a barcode reading API like [Aspose.BarCode](https://products.aspose.com/barcode/). Alternatively, if the images contain ordinary text, you could utilize [Aspose.OCR](https://products.aspose.com/ocr/) API such as Aspose.OCR to extract the required information.

We also encourage you to post your queries/issues in the [forums](https://forum.aspose.com/categories).









Is it possible to let him to share a desired Excel manually made in Excel? Also a demo project with source files(e.g. jpg image)

yes, after he sharing the desired Excel file and source images, we can write some demo code for him.

moreover, I will also share docs links on how to insert pictures and how to manipulate data to Excel spreadsheet
thanks

Peyton, 3:01 PM
yes. e.g. https://docs.aspose.com/cells/java/managing-pictures/
https://docs.aspose.com/cells/java/add-and-retrieve-data/
https://products.aspose.com/ocr/
https://forum.aspose.com/categories


Managing Pictures
https://docs.aspose.com
