### ISSUE TITLE
我想在ppt中创建一个从左下到右上的连接线

### ISSUE THREAD

**Issue by 1219605557** [aspose-free-consulting/projects#427]
我想在ppt中创建一个从左下到右上的连接线，使用slide.getShapes().addConnector(ShapeType.BentConnector3,100,100,200,200)创建的连接线是从左上到右下的，但我需要一个从左下到右上的连接线，该怎么进行修改呢

**Comment by andreypotapovaspose** [comment]
@1219605557,
在 PowerPoint 演示文稿中，垂直轴是从下到上的。请尝试按如下方式添加连接线：
```java
slide.getShapes().addConnector(ShapeType.BentConnector3, 100, 200, 200, 100);
```

**Comment by 1219605557** [comment]
你可能理解错了我的意思，我是想要创建一个类似于这样的连接线，
![image](https://github.com/user-attachments/assets/01153a27-38d0-4491-a178-4f778bf6a7ad)；使用以上代码创建的仍然是从左上到右下的连接线

**Comment by andreypotapovaspose** [comment]
@1219605557,
您能否详细描述一下问题并分享一个PowerPoint演示文稿的示例？

**Comment by 1219605557** [comment]
@andreypotapovaspose 在ppt中，使用slide.getShapes().addConnector(ShapeType.BentConnector3, 100, 200, 200, 100);创建的是图中左边的连接线，但我想要右边的效果，在文档中似乎没找有对应的方法能实现，相当于Line和LineInverse的关系
![image](https://github.com/user-attachments/assets/a3f76dcc-b705-40b1-9e32-da3ca4460517)

**Comment by andreypotapovaspose** [comment]
@1219605557,
通常情况下，连接线用于连接图形，因此它们在PowerPoint演示文稿中的显示会自动调整。请您说明一下，为什么您需要这种特定的连接线显示方式？

**Comment by 1219605557** [comment]
@andreypotapovaspose 因为我们需要做一个导出ppt的功能，将我们服务里的一个画布内容导出为ppt，其中会涉及这种折线，用户可以按自己需求进行调整，所以可能会出现上图右边的那种形式

**Comment by andreypotapovaspose** [comment]
@1219605557,
感谢您提供的详细信息。我已经重现了您描述的问题。

我们在内部问题跟踪系统中开立了以下新的工单，并将根据[Free Support Policies](https://forum.aspose.com/t/free-support-policies/162313)中提到的条款交付其修复。

    SLIDESJAVA-39513

如果您需要优先支持并希望直接联系我们的付费支持管理团队，可以获取[Paid Support Services](https://helpdesk.aspose.com/)。

**Comment by 1219605557** [comment]
@andreypotapovaspose 刚刚在不断尝试中发现了个可以实现的方法，可以通过在起点终点位置新建矩形，然后通过setStartShapeConnectedTo和setEndShapeConnectedTo后把这两个矩形删除，就可以得到目标的效果

**Comment by andreypotapovaspose** [comment]
@andreypotapovaspose,
我们很高兴您找到了一个解决方法，并且您的问题已经解决。感谢您使用Aspose.Slides。

**Comment by andreypotapovaspose** [comment]
@1219605557,
请尝试使用以下方法：
```java
IConnector connector = slide.getShapes().addConnector(ShapeType.BentConnector3, 100, 100, 200, 200);

IShapeFrame connectorFrame = connector.getFrame();

ShapeFrame flippedXShape = new ShapeFrame(
        connectorFrame.getX(), connectorFrame.getY(), connectorFrame.getWidth(), connectorFrame.getHeight(),
        NullableBool.True, connectorFrame.getFlipV(), connectorFrame.getRotation());

connector.setFrame(flippedXShape);
```
