### ISSUE TITLE
I want to use Aspose.HTML for Java. 

### ISSUE THREAD

**Issue by SeayoungKim123** [aspose-free-consulting/projects#429]
I would like to use Aspose.HTML for Java.
I am curious about which of the three versions you have for sale would be suitable for my needs.

Which one should I purchase to apply in a distributed server environment?

**Comment by asadalikhan90** [comment]
@SeayoungKim123 

For a distributed server environment, where you expect to deploy across many servers and potentially distribute the software as part of other applications, the Developer OEM License or Site OEM License would be the most suitable. Here’s why:

**Unlimited Deployment:** Both OEM licenses allow for unlimited deployment, which is crucial for a distributed server environment.
**Distribution Rights:** The OEM licenses grant you the right to distribute the Aspose.HTML API as part of your own software applications without additional costs or restrictions.
**Scalability:** These licenses support scaling your deployment as needed, whether it’s adding more servers or integrating the library into multiple applications.

Furthermore, we also recommend that you please create a post in our [official support forum](https://forum.aspose.com/c/purchase) where you will be provided with the best information and guided accordingly.
