### ISSUE TITLE
Aspose Excel Print area using page break and add it into aspose slides

### ISSUE THREAD

**Issue by Rajendiran1990** [aspose-free-consulting/projects#43]
I have an issue while printing worksheet with multiple page break in aspose slides...while printing I'm getting the white space below the image..it's not fitting to the IOleobjectframe height..
Suppose if I set "OnePagePerSheet=true" then the height was matching with object frame.. I have added page break so I was changed OnePagePerSheet=false then image size is changed.. it's not fit to the object frame..could you suggest me how to set the image based on sheet content of print area.. how to set height of page break rows and apply same height to the image

**Comment by shahzad-latif** [comment]
@Rajendiran1990 

I think you meant Aspose.Cells (not Aspose.Slides). Please note that this place is reserved for free consulting projects. For such issues, we have free support forums at our website. Kindly post your query in this forum forum.aspose.com/c/cells along with the code samples you're using and the input/output samples for testing. Our team will help you out soon. Thanks for your cooperation.

**Comment by Rajendiran1990** [comment]
@shahzad-latif Thank you for your update..
