### ISSUE TITLE
Production Error - aspose cells python 

### ISSUE THREAD

**Issue by felipebpl** [aspose-free-consulting/projects#430]
**Project requirements:**
- Need to use aspose cells python in production for handling corrupted excel files. Right now I'm having an issue installing the lib via dockerfile. Already installed the `libgdiplus`

- Production OS: Ubuntu 20.04 

- ```ERROR: No matching distribution found for aspose-cells-python==24.8.0```

**Comment by amjad-sahi** [comment]
@felipebpl,

Please note, the current Linux version of Aspose.Cells for Python via .NET only supports the Linux x86 architecture. Ensure your architecture is not ARM. If your Docker is using the Linux ARM architecture, please use the following command in Dockerfile:
```
FROM --platform=linux/amd64 python:3.11-bullseye
Additionally, here is a working Dockerfile for your reference.

FROM python:3.11 AS base

# For drawing,e.g. convert to PDF
RUN apt-get update && apt-get install -y libgdiplus

# Install ICU version supported by .NET Core 3.1
RUN wget http://archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu70_70.1-2_amd64.deb
RUN dpkg -i libicu70_70.1-2_amd64.deb

RUN pip install -i aspose-cells-python
CMD ["python", "aspose_test.py"]
```
Let us know if you still find any issue.
