### ISSUE TITLE
aspose word for java 版 在 套版時候會出現 日期格式

### ISSUE THREAD

**Issue by ryan12081208** [aspose-free-consulting/projects#434]
aspose  version aspose-words-24.7-jdk17
json 格式 {"amount4":"1,003","amount3":"1,002","amount2":"1,001","amount1":"1,000"}
word 套版 <<[r.amount1]>><<[r.amount2]>><<[r.amount3]>><<[r.amount4]>>
匯出後出現 
1,000
1,001
Sun Jan 01 08:00:00 CST 2
Sun Jan 01 08:00:00 CST 3

**Comment by AlexNosk** [comment]
@ryan12081208 您可以设置精确的日期解析格式以避免这种情况：

```java
JsonDataLoadOptions opt = new JsonDataLoadOptions();
opt.setExactDateTimeParseFormats(Arrays.asList(new String[] {""}));
JsonDataSource data = new JsonDataSource("C:\\Temp\\data.json", opt);
    
Document doc = new Document("C:\\Temp\\in.docx");
ReportingEngine engine = new ReportingEngine();
engine.buildReport(doc, data, "r");
doc.save("C:\\Temp\\out.docx");
```

[data.json](https://github.com/user-attachments/files/16836868/data.json)
[in.docx](https://github.com/user-attachments/files/16836869/in.docx)
[out.docx](https://github.com/user-attachments/files/16836870/out.docx)
