### ISSUE TITLE
Is there a special offer/license available for education (university)

### ISSUE THREAD

**Issue by atobiaSGH** [aspose-free-consulting/projects#438]
We are looking for a license for Aspose.OCR for .NET. 
I would like to ask if you offer a special education/university license?

**Comment by markos-aspose** [comment]
Hi @atobiaSGH,

thank you for your inquiry.

You can find out more about Aspose discount policies [here](https://purchase.aspose.com/policies/discounts/#:~:text=Non%2Dprofit%2C%20Educational%2C%20Government%20and%20Start%2DUp%20Discount).

For more information, please reach us at sales@aspose.com.

Best regards,
Marko
