### ISSUE TITLE
在学习过程中，发现maven无法下载链接中提供的依赖

### ISSUE THREAD

**Issue by shenwenye** [aspose-free-consulting/projects#439]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>
在学习过程中，发现maven无法下载链接中提供的依赖（https://blog.aspose.cloud/zh/imaging/deskew-image-in-java/）
<repositories> 
    <repository>
        <id>aspose-cloud</id>
        <name>artifact.aspose-cloud-releases</name>
        <url>http://artifact.aspose.cloud/repo</url>
    </repository>   
</repositories>

<dependencies>
    <dependency>
        <groupId>com.aspose</groupId>
        <artifactId>aspose-imaging-cloud</artifactId>
        <version>22.4</version>
    </dependency>
</dependencies>
![maven](https://github.com/user-attachments/assets/09acc4dc-5efd-43d1-b2fc-d174b7e04fe5)

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by awaishafeez** [comment]
@shenwenye 

请注意，技术支持的主要途径是通过我们的官方论坛。因此，我建议您在以下论坛类别中创建新帖子：

https://forum.aspose.cloud/c/imaging/10

当您在论坛中创建新帖子时，请确保提供问题/用例的完整详细信息，并提供任何工件（示例文档、源代码等）。这将帮助我们重现您所面临的完全相同的问题，我们将能够更好地解决您的问题。
