### ISSUE TITLE
I want to be able to export my knowledge base articles that are custom WordPress posts

### ISSUE THREAD

**Issue by zainanabtawi** [aspose-free-consulting/projects#44]
This is the plugin we are currently using fort our knowledge base - https://herothemes.com/plugins/heroic-wordpress-knowledge-base/

I attempted to export from the drop-down on the articles page but the option doesnt show. 

The custom post type is labeled post_type=ht_kb

Any help with this?

**Comment by shahzad-latif** [comment]
@zainanabtawi 

Are you using Aspose WordPress Plugin to export your posts? If so, please post your query in our free support forums, so that our team can help you properly: https://forum.aspose.cloud/c/words. 

This space is resolved for free consulting projects. Thanks.
