### ISSUE TITLE
I want to create a homebuilder mobile application that renders the points drawn into a .obj file

### ISSUE THREAD

**Issue by maister91** [aspose-free-consulting/projects#45]
### Homebuilder application for Aspose3ds

I am working on an android application that with the help of augmented reality draws the walls of the room. How it works is that the user can put a point in each corner of the room. A wall being 2 points. So a room with 4 walls would have 8 points in that room. 

**This would be sent to the API** 
`{
    "points": [
        {
            "x": -0.3715828,
            "y": -0.6037042,
            "z": -0.70598465
        },
        {
            "x": -1.8555146,
            "y": -0.60370415,
            "z": -0.53111166
        },
        {
            "x": -2.2446227,
            "y": -0.6037042,
            "z": -0.1003091
        },
        {
            "x": -1.4724422,
            "y": -0.60370415,
            "z": 1.0776274
        },
        {
            "x": -0.46731365,
            "y": -0.60370415,
            "z": 0.9549265
        }
    ]
}`

I have checked the examples that can be used within the api but i am not sure wheter it is possible to have a node just as a point. So each x,y,z being a small point and then linking these points with lines. The output would be sent back to the application where the user can see their  room layout in 3D.

**Comment by shahzad-latif** [comment]
@maister91 

Thanks for getting in touch. We're looking into your requirements and will get back to you soon.

**Comment by asadalikhan90** [comment]
@maister91 

Meanwhile, we are looking into your requirements, would you kindly share the sample input and expected output files with us.

> I have checked the examples that can be used within the api but i am not sure wheter it is possible to have a node just as a point.

Also, would you kindly share which example you are referring to? We will further proceed to assist you accordingly.

**Comment by maister91** [comment]
So i tried modifying the meshGeometry file in the examples on github. 
The vectors are the position of each corner in the room. 

namespace Aspose._3D.Examples.CSharp.Geometry_Hierarchy
{
    class MeshGeometryData
    {
        public static void Run()
        {   
            // ExStart:ShareMeshGeometryData          
            // Initialize scene object
            Scene scene = new Scene();

            // Define color vectors
            Vector3[] coords = new Vector3[] {
            new Vector3(-3.715828, -0.6037042, 7.0598465),
            new Vector3(-18.555146, -0.6037042, -5.3111166),
            new Vector3(-22.446227, -0.6037042, -1.003091),
            new Vector3(-14.724422, -0.6037042, 10.776274),
            new Vector3(-4.6731365,-0.6037042, 9.549265),

};

            // Call Common class create mesh using polygon builder method to set mesh instance 
            Mesh mesh = Common.CreateMeshUsingPolygonBuilder();

            foreach (Vector3 coord in coords)
            {
                // Initialize cube node object
                Node point = new Node("point");
                point.Entity = mesh;
                LambertMaterial mat = new LambertMaterial();
                // Set color
                mat.DiffuseColor = coord;
                // Set material
                point.Material = mat;
                // Set translation
                point.Transform.Translation = coord;
                // Add point node
                scene.RootNode.ChildNodes.Add(point);
            }

            // The path to the documents directory.
            var output = RunExamples.GetOutputFilePath("MeshGeometryData.obj");
        
            // Save 3D scene in the supported file formats
            scene.Save(output, FileFormat.WavefrontOBJ);
            // ExEnd:ShareMeshGeometryData
            Console.WriteLine("\nMesh’s geometry data shared successfully between multiple nodes.\nFile saved at " + output);

        }
    }
}
`
- The vectors being the position of cornerns in a room. I made changes to `CreateMeshUsingPolygonBuilder`, made the object 10x smaller to make it more relative
`   Vector4[] controlPoints = new Vector4[]
            {
                new Vector4( -.5, 0.0,.5, 1.0),
                new Vector4( .5, 0.0,.5, 1.0),
                new Vector4( .5, 1, .5, 1.0),
                new Vector4( -.5, 1, .5, 1.0),
                new Vector4( -.5, 0.0, -.5, 1.0),
                new Vector4( .5, 0.0, -.5, 1.0),
                new Vector4( .5, 1, -.5, 1.0),
                new Vector4( -.5, 1, -.5, 1.0)
            };`

This resulted in the file below

If you open this file in an 3d viewer it resembles the room layout. However i want to connect the points with lines and add a set height to it to create 'walls'

**Comment by maister91** [comment]
Contents of MeshGeometryDate.obj

# Aspose.3D Wavefront OBJ Exporter
# Copyright 2004-2019 Aspose Pty Ltd.
# File created: 17/05/2020 15:40:02

mtllib MeshGeometryData.mtl

#
# object point
#

v -0.3715828 -0.6037042 -0.70598465
v -1.8555146 -0.6037042 -0.53111166
v -2.24462269999999984 -0.6037042 -0.1003091
v -1.47244219999999992 -0.6037042 1.0776273999999999
v -0.46731365 -0.6037042 0.9549265
# 5 vertices

g point
usemtl mat_37320431
s 1
f 1 2 3 4
f 2 6 7 3
f 6 5 8 7
f 5 1 4 8
f 1 5 6 2
f 4 3 7 8
#6 polygons


#
# object point
#

v 19.6284172000000012 -0.6037042 -0.70598465
v 18.14448540000000066 -0.6037042 -0.53111166
v 17.7553772999999992 -0.6037042 -0.1003091
v 18.52755780000000032 -0.6037042 1.0776273999999999
v 19.53268634999999872 -0.6037042 0.9549265
# 5 vertices

g point
usemtl mat_339559
s 2
f 6 7 8 9
f 7 11 12 8
f 11 10 13 12
f 10 6 9 13
f 6 10 11 7
f 9 8 12 13
#6 polygons


#
# object point
#

v 39.6284172000000012 -0.6037042 -0.70598465
v 38.14448540000000066 -0.6037042 -0.53111166
v 37.7553772999999992 -0.6037042 -0.1003091
v 38.52755779999999672 -0.6037042 1.0776273999999999
v 39.53268634999999872 -0.6037042 0.9549265
# 5 vertices

g point
usemtl mat_3056034
s 4
f 11 12 13 14
f 12 16 17 13
f 16 15 18 17
f 15 11 14 18
f 11 15 16 12
f 14 13 17 18
#6 polygons


#
# object point
#

v 59.6284172000000012 -0.6037042 -0.70598465
v 58.14448540000000066 -0.6037042 -0.53111166
v 57.7553772999999992 -0.6037042 -0.1003091
v 58.52755779999999672 -0.6037042 1.0776273999999999
v 59.53268634999999872 -0.6037042 0.9549265
# 5 vertices

g point
usemtl mat_27504314
s 8
f 16 17 18 19
f 17 21 22 18
f 21 20 23 22
f 20 16 19 23
f 16 20 21 17
f 19 18 22 23
#6 polygons


#
# object point
#

v 79.6284172000000012 -0.6037042 -0.70598465
v 78.14448539999999354 -0.6037042 -0.53111166
v 77.7553773000000064 -0.6037042 -0.1003091
v 78.52755779999999672 -0.6037042 1.0776273999999999
v 79.53268635000000584 -0.6037042 0.9549265
# 5 vertices

g point
usemtl mat_46212239
s 16
f 21 22 23 24
f 22 26 27 23
f 26 25 28 27
f 25 21 24 28
f 21 25 26 22
f 24 23 27 28
#6 polygons

**Comment by asadalikhan90** [comment]
@maister91 

Thanks for providing these details. We are checking them in our environment and will get back to you soon with our feedback.
