### ISSUE TITLE
I want to create an application which can read the .vss stencil file and the save the all the images in png files with their connectors info intact.

### ISSUE THREAD

**Issue by Sandeep321** [aspose-free-consulting/projects#46]
I am trying the demo version of Aspose.Diagram - 20.5.0 on .Net core 3.1.  I want to create an application that can read the .vss stencil file and save all the images in png files with their connectors info intact. The idea here to have the stencil images from stencil masters to be saved as different PNG files. I tried doing that but I see that the quality of images is completely gone and also I am not sure how do I get the connectors info. I would need to have the location of all its connectors on the image exported.

 Windows 10, .Net core 3.1, VS 2019>

Get Any Stencil file from [HERE](http://www.visiocafe.com/dell.htm)

**Comment by shahzad-latif** [comment]
@Sandeep321 

Sorry for replying late to this. This got overlooked. We'll answer this soon. Thanks.

**Comment by asadalikhan90** [comment]
@Sandeep321 

Aspose.Diagram allows you to generate icons of master shapes in your stencil file as well as you can get connector information using **Shape.ConnectedShapes()** Method. We will surely check to improve the quality of output images and create a sample application for you. However, it is unclear to us how you want to have the location of connectors on the exported images. Would you kindly share an expected output image (having connectors' information on it)? It would help us understand the scenario and share our feedback with you accordingly. Your response is awaited.
