### ISSUE TITLE
I want to generate Excel file and convert Excel file to PDF by using Aspose Cells

### ISSUE THREAD

**Issue by SenthilRG** [aspose-free-consulting/projects#47]
Hi Team,

  We are planning to use Aspose.Cells in ASP.NET Core 3.1 Web API application to generate Excel file and deployed in AWS environment. We have to apply color formatting in Excel file (.xlsx format) and PDF file as well. 

  Front End: angular 8

  Back End: ASP.NET Core 3.1 Web API

  Environment: AWS (Lambda)

Could you please confirm that which version we have to use to work in above environment and also cost details to procure new licence?

**Comment by amjad-sahi** [comment]
See the [reply](https://forum.aspose.com/t/i-want-to-generate-excel-file-and-convert-excel-file-to-pdf-by-using-aspose-cells/212994/2?u=amjad_sahi) in the forums for your reference. You may follow up your forum thread for further assistance.
