### ISSUE TITLE
Need solutions for editing docx files on my web application and save them back as docx

### ISSUE THREAD

**Issue by mosesm** [aspose-free-consulting/projects#50]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>:
I'm looking for your solutions for editing docx/doc/rtf files on my web application and save them back as docx/doc/rtf.

My web application is built on React and backend is on node.js.
I have a requirement to be able to display docx or doc or rtf files on my web application so that the user can view the file and add more content to it and save it back as a docx or doc or rtf respectively.

I have gone through your website and want to know if the solution below is possible:
1. Deploy Aspose.Words cloud docker on my Premises that exposes the cloud APIs which can convert docx/doc/rtf to html and vice versa

2. use node.js to talk to my cloud APIs to convert docx/doc/rtf to html and vice versa

3. Use any WSIWYG editor to edit the docx/doc/rtf on the web app

< which platform you're working on -- operating system, development environment etc.> 
My OS is CentOS and developers are node.js and react.js

<attach input documents>
[prod3.docx](https://github.com/aspose-free-consulting/projects/files/4744665/prod3.docx)

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by tilalahmad** [comment]
@mosesm 

> Deploy Aspose.Words cloud docker on my Premises that exposes the cloud APIs which can convert docx/doc/rtf to html and vice versa
> 
> use node.js to talk to my cloud APIs to convert docx/doc/rtf to html and vice versa

You can deploy [Aspose.Words Cloud Docker](https://hub.docker.com/r/aspose/words.cloud) on your premises and use [Aspose.Words Cloud SDK for Node.js](https://github.com/aspose-words-cloud/aspose-words-cloud-node) for required conversion.  You have posted a similar query in [Aspose Cloud Forums](https://forum.aspose.cloud/t/how-to-convert-docx-html-to-html-docx-in-docker-container-using-aspose-words-rest-api/4453). Please check your post for more details along with the sample code.

**Comment by mosesm** [comment]
Thanks for the response. I will check it out and get back if I need any further clarifications.
