### ISSUE TITLE
OutOfMemoryException for Aspose.Pdf with .net api

### ISSUE THREAD

**Issue by ketand1** [aspose-free-consulting/projects#52]
Hello Team

We are using Aspose.Pdf for converting document to PDF. 

We are using windows azure server.

We are trying to convert 100mb file and facing above issue.

Thanks
Ketan

**Comment by shahzad-latif** [comment]
@ketand1 

This is an exception and I would recommend you to post this query in our forums so that our suport team can help you properly: https://forum.aspose.com/c/pdf. This space is reserved for free consulting projects. Thanks for the understanding.
