### ISSUE TITLE
I want to create multipage report with running sum in footer

### ISSUE THREAD

**Issue by kosma-bienkowski-nxm** [aspose-free-consulting/projects#53]
I want to create multipage report containing table of arbitrary length, with rows having different heights (due shorter or longer texts in it).
Each page footer must have running sum of items (rows) actually displayed on it.
How to achieve this ?

**Comment by shahzad-latif** [comment]
@kosma-bienkowski-nxm 

In which document format you want to create this report?

**Comment by kosma-bienkowski-nxm** [comment]
PDF

**Comment by shahzad-latif** [comment]
@asadalikhan90 

Please have a look into these requirements and provide a sample to @kosma-bienkowski-nxm.

**Comment by asadalikhan90** [comment]
@kosma-bienkowski-nxm 

Tables can be added in the PDF document at the time of generation and they expand to subsequent pages of the document as their length increases. Also, you can add a table to PDF document by integrating it with the database using Aspose.PDF. Would you kindly share in which platform you working e.g. .NET or Java and please share a sample expected PDF output with us. We will prepare a sample for you accordingly. Meanwhile, you may also check the following useful articles to work with tables:

- [Manipulate and Integrate Table](https://docs.aspose.com/display/pdfnet/Manipulate+and+Integrate+Table#ManipulateandIntegrateTable-IntegrateTablewithDatabase(DOM))
- [Add and Extract a Table](https://docs.aspose.com/display/pdfnet/Add+and+Extract+a+Table#AddandExtractaTable-AddTable)
