### ISSUE TITLE
Manipulate DWG (CAD) file to identify land and change background color according to database

### ISSUE THREAD

**Issue by spadinha1** [aspose-free-consulting/projects#54]
Good afternoon,

we are a real estate development company in Brazil
and we are looking for a tool to manipulate DWG (CAD) projects to identify lots of land that have been sold and to be able to change the background color of these according to the data in a database.

does the aspose.CAD tool meet this need?

**Comment by shahzad-latif** [comment]
@spadinha1 Thanks for getting in touch. We'll get back to you with details soon. Thanks.

**Comment by mudassirfayyaz** [comment]
@spadinha1 ,

Can you please share the details of your requirements in the form of sample source DWG file  and the desired one that you want to create using API. I also like to add here that Aspose.CAD for .NET is able to load the DWG files but can save them as PDF or Image using API.

**Comment by spadinha1** [comment]
I will do some example

In Example we have 4 lots of land... called Layer1 Layer2 Layer3 Layer4
I will consult that Layer3 is sold... I would like to change hatch color from layer to Green. And rasterize it to A4 or A3 size.

If can I change an block to another layer it will solve because the layer background is specify early. 

Example link. 

[Example](https://drive.google.com/drive/folders/1RPhGwy-zlB7EVUOpQEGaUmaBb2hqGpxY?usp=sharing)

**Comment by mudassirfayyaz** [comment]
@spadinha1 

I have made request for access to [Example link.](https://drive.google.com/drive/folders/1RPhGwy-zlB7EVUOpQEGaUmaBb2hqGpxY?usp=sharing). Can you please grant permission.

**Comment by spadinha1** [comment]
Sorry

https://drive.google.com/file/d/1KB9YoD_jQ3pJD2nWEtER4b7TdalKrj55/view?usp=drivesdk


Em sáb, 27 de jun de 2020 às 05:20, mudassirfayyaz <notifications@github.com>
escreveu:

**Comment by mudassirfayyaz** [comment]
@spadinha1 ,

I have observed the PDF file shared by you. It has not been that much helpful in understanding as we requested for a source DWG and desired output PDF. I have created a sample project for your convenience with a sample file fulfilling your requirements. I hope this will be helpful.

[Sample Project](https://drive.google.com/file/d/1uClhQ9B73YaGyn6epjzcKycjHhPNb1e5/view?usp=sharing)

**Comment by spadinha1** [comment]
https://drive.google.com/file/d/16A2ne49xyZBekHJ8IMkchJ53eyUnOska/view?usp=drivesdk

Sorry again I Think Have shared the 2 files

Em dom, 28 de jun de 2020 às 09:39, mudassirfayyaz <notifications@github.com>
escreveu:

**Comment by mudassirfayyaz** [comment]
@spadinha1 ,

I have observed the DWG file on my end. It has got for entities and all are of polylines types. Unfortunately, there is no fill for area encapsulated by a polyline type object. I suggest you to please consider using the example that I have provided with a sample DWG file.

In our file, we have added Insert type entity which is bounded. You can identify the entity based on name and then you can fill that accordingly on your end. Can you please give a try to solution that we have shared.

**Comment by spadinha1** [comment]
Thanks,

I Will try do it

If will it work, we Will want to adquire the lib

Best regards

Em dom, 28 de jun de 2020 às 14:15, mudassirfayyaz <notifications@github.com>
escreveu:
