### ISSUE TITLE
I want to render a PDF using another PDF, an email and an excel

### ISSUE THREAD

**Issue by Yishay** [aspose-free-consulting/projects#55]
How can we achieve the following:
We have 3 files:
1. PDF which holds the cover page.
2. An email.
3. Excel which is ready to be saved as PDF.
We would like to use Aspose (preferably cloud) to bundle them together in that order into one PDF.

Thanks,
Yishay

**Comment by shahzad-latif** [comment]
@Yishay 

We're working on a sample with Cloud APIs and will share with you soon.

**Comment by tilalahmad** [comment]
@Yishay 

You can accomplish your task with the collaboration of [Aspose.Email Cloud API](https://products.aspose.cloud/email), [Aspose.Words Cloud API](https://products.aspose.cloud/words), [Aspose.Cells Cloud API](https://products.aspose.cloud/cells) and [Aspose.PDF Cloud API](https://products.aspose.cloud/pdf) as follows. First, you have to convert your Email and Excel files to PDF and later merge all the PDF documents into a single PDF.

If you have any questions and/or comments you may approach us via [aspose.cloud support forum](https://forum.aspose.cloud/) as well.

**STEP 1: Convert Email to PDF**

Aspose.Email Cloud API does not support direct conversion of Email to PDF. So we will first convert Email to MTHML using Aspose.Email Cloud API and later will convert MHTML to PDF using Aspose.Words Cloud API.

```
// First get JWT Access Token
// Get App Key(client_secret) and App SID(client_id) from https://dashboard.aspose.cloud/
curl -X POST "https://api.aspose.cloud/connect/token" 
-d "grant_type=client_credentials&client_id=xxxx-xxxx-xxxx-xxxx-xxxxxxxxx&client_secret=xxxxxxxxxxxxxxxxxxxxxxxxxxx" 
-H "Content-Type: application/x-www-form-urlencoded" 
-H "Accept: application/json"

//Convert Mail to MHTML using Aspose.Email Cloud API
curl -X PUT "https://api.aspose.cloud/v3.0/email/convert/Mhtml" 
-H "accept: multipart/form-data" 
-H "authorization: Bearer [Access_Token]" 
-H "Content-Type: multipart/form-data" 
-H "x-aspose-client: Containerize.Swagger" 
-F "File=@C:/Temp/appointment-draft.msg" 
--output C:/Temp/appointment-draft.mhtml

//Convert MHTML to PDF using Aspose.Words Cloud API
curl -X PUT "https://api.aspose.cloud/v4.0/words/convert?format=pdf&outPath=Temp/appointment-draft.pdf&fileNameFieldValue=sourceFilename" 
-H "accept: application/octet-stream" 
-H "Authorization: Bearer [Access_Token]" 
-H "Content-Type: multipart/form-data" 
-H "x-aspose-client: Containerize.Swagger" 
-F "File=@C:/Temp/appointment-draft.mhtml"
```

**STEP 2: Convert Excel to PDF**

Convert your Excel file to PDF using Aspose.Cells Cloud API.

```
//Convert Excel to PDF using Aspose.Cells Cloud API
curl -X GET "https://api.aspose.cloud/v3.0/cells/Test.xlsx?format=pdf&isAutoFit=false&onlySaveTable=false&folder=Temp&outPath=Temp/Test_excel.pdf" 
-H "accept: multipart/form-data" 
-H "authorization: Bearer [Access_Token]" 
-H "x-aspose-client: Containerize.Swagger"

```

**STEP 3: Merge multiple PDF documents into a single PDF**

Merge multiple PDF documents into a singe PDF document using Aspose.PDF Cloud API.

```
//Merge PDF documents together into a single PDF using Aspose.PDF Cloud API
curl -X PUT "https://api.aspose.cloud/v3.0/pdf/Merge_output.pdf/merge?folder=Temp" 
-H "accept: application/json" 
-H "authorization: Bearer [Access_TOken]" 
-H "Content-Type: application/json" 
-H "x-aspose-client: Containerize.Swagger" 
-d "{ "List": [ "Temp/Test.pdf","Temp/appointment-draft.pdf","Temp/Test_excel.pdf" ]}"

```

**Comment by shahzad-latif** [comment]
The complete code can be found here: [Merge PDF, Email and Excel files into a single PDF document with Aspose REST APIs](https://github.com/aspose-free-consulting/Merge-PDF-an-Email-and-an-Excel-to-a-PDF-with-Aspose-REST-APIs)
