### ISSUE TITLE
can aspose convert from .rtf or .doc or .docx to .txt file retaining table formatting. I tried online tool but its not keeping table formatting

### ISSUE THREAD

**Issue by AnshulNigam** [aspose-free-consulting/projects#57]
[Test.docx](https://github.com/aspose-free-consulting/projects/files/4896244/Test.docx)

While converting this file using online tool it is not able to maintain table formatting. I have a requirement where we are looking for tool which can do the same.

**Comment by shahzad-latif** [comment]
@AnshulNigam 

Which tool did you use for this conversion? aspose.app or groupdocs.app?

**Comment by AnshulNigam** [comment]
I used online tool for evaluation purpose.

https://products.aspose.app/words/conversion/doc-to-txt

**Comment by AnshulNigam** [comment]
Any update on this?

**Comment by shahzad-latif** [comment]
@AnshulNigam 

Would you be kind enough to move this query to https://forum.aspose.app/c/slides so the relevant team can help you properly? I would have moved it myself, but I don't have your email ID. So your cooperation would be greatly appreciated. Thanks.

**Comment by AnshulNigam** [comment]
Thanks Latif i will , but just wanted to make sure I want to confirm I am
facing a problem with converting from .rtf to text and the link which you
have given is for .ppt.

So I wanted to make sure that I got a timely response.

**Comment by shahzad-latif** [comment]
@AnshulNigam 

Sorry about that. It was my mistake. Please post here: https://forum.aspose.app/c/words. Though our team would have moved it to appropriate forum. Thanks for your cooperation. :)
