### ISSUE TITLE
Image conversion from PNG to PDF has very large output fileSize

### ISSUE THREAD

**Issue by vckSekhar** [aspose-free-consulting/projects#58]
Hi Aspose Support

We have recently purchased ASPOSE TOTAL license and have used it for our image conversion.  We kind of have a problem with  output pdf filesize  after conversion 
We have business case where output file size should be either equal to input size or less than it.   We are trying to achieve this based online samples what you have shared in web-site

We have tuned this via code and it works ok  for few files but for some files we have twice the filesize of input png.
Worst case was attached png file when converted to PDF had 4 times the size of the png file.    Also attached piece of code we have used

Can you please help us with your valuable suggestions as to we can compress the output pdf file.
Our goal is to have output pdf with filesize either equal or less than input png file.

**Comment by bepmpro-com** [comment]
@vckSekhar 

Please post the issues or queries related to the Aspose APIs in our forums, so that our team would be able to help you quickly and on time. https://forum.aspose.com/ Thanks for the understanding.

**Comment by shahzad-latif** [comment]
@vckSekhar 

Please post the issues or queries related to the Aspose APIs in our forums, so that our team would be able to help you quickly and on time. https://forum.aspose.com/ Thanks for the understanding.
