### ISSUE TITLE
I want to create zigzag line by using Aspose.Pdf 

### ISSUE THREAD

**Issue by 6666** [aspose-free-consulting/projects#6]
Hi ,
Trying to create a zigzag line as a top border of rectangle by using aspose.pdf . But not getting result. Please suggest me how i can achieve this.

**Comment by shahzad-latif** [comment]
@6666 

Can you please elaborate it "the zigzag" line a bit? If you have any example of that, please share. Or you can elaborate with a handmade diagram as well. We need to better understand your requirement to be able to help you. Thanks.

**Comment by 6666** [comment]
Hi,
Please find the drawing for this scenario from attachment, and please suggest me what should i need to do to draw by using Aspose.PDF.
![Capture](https://user-images.githubusercontent.com/434142/63904710-985cc100-ca2f-11e9-8d75-4a07ef981c80.PNG)

Thanks

**Comment by 6666** [comment]
Hi Shahzad,

Any suggestions or any idea about this

Thanks,
Gyan

**Comment by shahzad-latif** [comment]
@6666 

Sorry for the delayed response. Let's investigate this further in detail as this requirement is quite different and we will get back to you with the update soon.

**Comment by 6666** [comment]
Yes, Waiting for your response.


Me also trying but approach is different . Like by using Java.awt.Graphics API first drawing the stokes as a zigzag line and saving in temp folder as a PNG extension then importing this as a FileStream to Aspose.PDF image. But this approach is looks like a not acceptable because if aspose has a drawing option then why we will import another one. That's why we want solution with depends on advise.pdf

**Comment by shahzad-latif** [comment]
@6666 

We have prepared a sample project for you which produces an output PDF file with the zigzag lines. Please have a look at this repository: https://github.com/aspose-free-consulting/add-zigzag-line-and-border-to-pdf-file

You need to first go through the readme file to see the output screenshots and the sample output PDF file attached. 

After that, please check the code, how we tried to achieve it. Following the same approach you can achieve your goal as well. 

Anyway, please feel free to share your thoughts.
