### ISSUE TITLE
XLS转换xlsx

### ISSUE THREAD

**Issue by Beful** [aspose-free-consulting/projects#60]
```
const XLSX = require('xlsx');
var oldFile= XLSX.readFile('./test.xls');
XLSX.writeFile(oldFile, './test.xlsx');

```

利用js-xlsx包 ,可以在NodeJs环境中进行xls到xlsx的转换，非常简单，示例代码如下:
先安装依赖npm install xlsx

这个不好使，有没有什么方便的方法，ie11使用，或者有个小例子demo！！

ie报错堆栈溢出，谷歌浏览器没事

**Comment by amjad-sahi** [comment]
看来您正在使用js-xlsx库，所以我们不能为您提供太多帮助，因为它超出范围。如果您通过Java API将Aspose.Cells用于Node.js (https://products.aspose.com/cells/nodejs-java)，我们只能为您提供帮助。
