### ISSUE TITLE
Customizable solution for Aspose PDF Convertor

### ISSUE THREAD

**Issue by rachittaneja** [aspose-free-consulting/projects#61]
We are looking for a customizable solution for Aspose PDF Convertor. Below are our requirements.

- An automated solution that can be implemented on our servers through API or jar file to extract HTML from each PDF file	
- Should be scalable to handle parallel requests
- Conversion time is important so should be on the lower end
- Should be able to 
           - Retain formatting, styling & order of text
           - Extract text where there is text present in original PDF without converting text blocks into images
           - Don't merge vertical sections' text into each other
           - Placement of words and images in the PDF as close to original format using extracted HTML

We are happy to discuss this over the call.

**Comment by shahzad-latif** [comment]
@rachittaneja 

Thanks for reaching out. We'll check the requirements in detail and get back to you. If we need any further information, we'll ask here.

**Comment by asadalikhan90** [comment]
@rachittaneja 

We will surely prepare a sample application demonstrating the funcationality that you require (implemented using Aspose.PDF for Java API). However, we would like to make some clarifications before we continue further.

When you say "extract HTML from each PDF file", do you mean converting PDF document into HTML?

>  Should be scalable to handle parallel requests
Conversion time is important so should be on the lower end
Should be able to retain formatting, styling & order of text
Extract text where there is text present in original PDF without converting text blocks into images
Don't merge vertical sections' text into each other

If yes, then above all points are about obtained output HTML as per our assumptions.

> Placement of words and images in the PDF as close to original format using extracted HTML

As per our understandings, you are intending to have similar formatting in output HTML that is present in the source PDF document. Furthermore, it would also be great if you can provide some sample source document with expected output. This would help us preparing the sample accordingly and share it with you.
