### ISSUE TITLE
I want to extract Excel Chart as HTML document from Worksheet using Aspose.Cells

### ISSUE THREAD

**Issue by MicFus** [aspose-free-consulting/projects#62]
Hi,
I need to convert Excel Chart into HTML document and be able to reload it as editable in the future. Is there a way to do so without conversion of the entire excel workbook?

**I was looking for similar way as it's possible to do with Range object:**
Worksheet ws = workbook.Worksheets[range.Worksheet.Index];
ws.PageSetup.PrintArea = range.Address;
HtmlSaveOptions options = new HtmlSaveOptions
{
   ExportPrintAreaOnly = true
}

I tried to use **chart.ChartArea/chart.ChartObject** but I cannot find the equivalent of **range.Address** for Chart object.

Can you please help me to find the way to export chart as HTML?

**Comment by amjad-sahi** [comment]
You can get the rectangular area/range (starting from upper left corner (cell) to lower right corner (cell)) for the chart and set the printable area (as you have done for the range above) for the worksheet. See the sample code segment for your reference:
   
```
//Accessing the first chart
Chart chart = worksheet.Charts[0];
//Get the chart area.
string startCell = CellsHelper.CellIndexToName(chart.ChartObject.UpperLeftRow, chart.ChartObject.UpperLeftColumn);
string endCell = CellsHelper.CellIndexToName(chart.ChartObject.LowerRightRow, chart.ChartObject.LowerRightColumn);
```

Hope, this helps a bit.

**Comment by MicFus** [comment]
Thank you. 
It will be helpful if I will be exporting an image. I figure out that it's imposible to export chart as **editable** to HTML therefore I need to export the data source and chart metadata and build from scratch every time I need to add it. So my second question will be:
Is there any property which I can use to determine whole range of the data source for chart (e.g "A1:D4")? I know that I can use NSeries collection to get range of all the items separetly but I am wondering about one property holding the range of whole data source. Does similar property exist within Chart object?

**Comment by MicFus** [comment]
Thank you for your response.
