### ISSUE TITLE
I want to set up an image to pdf demo

### ISSUE THREAD

**Issue by sammyRuoff** [aspose-free-consulting/projects#63]
I am trying to set up a demo of Aspose.PDF to determine if the company should use the product or not. Our goal is to at the very least to convert images to pdfs and if the image is upside down, rotate it. I am struggling just to get the project set up (the project is a MVC .NET Framework 4.7.2.) I have followed just about every guide I could find but whenever I run the program the following error happens.
![aspose error](https://user-images.githubusercontent.com/68967188/88840715-e7b0f180-d1aa-11ea-92f8-f883113b96ae.png)

Thank you for the help.

**Comment by shahzad-latif** [comment]
@sammyRuoff,

The best place to get help for Aspose API features and any issues is our [free support forums](https://forum.aspose.com). Please post your query here in [Aspose.PDF free support forum](https://forum.aspose.com/c/pdf) and our team will be able to provide you quick help. Thanks for the understanding.
