### ISSUE TITLE
I want to count page number of docs

### ISSUE THREAD

**Issue by vegaweb1** [aspose-free-consulting/projects#64]
I want to create a web page that users can upload document such as docs then we can count page number of docs
please help me

**Comment by awaishafeez** [comment]
@vegaweb1,
You can use **Document.PageCount** property of "**Aspose.Words for .NET**" API to get the total number of pages in Word document (_DOCX, DOC, RTF, ODT etc_). The following C# code example shows how to retrieve the number of pages in Word document.
```
Document doc = new Document("C:\\Document.doc");
int pageCount = doc.PageCount;
```

_P.S. The main avenue of technical support is through our [forums](https://forum.aspose.com/). So, I suggest you to please post any further queries in "Aspose.Words Product Family" forum._
