### ISSUE TITLE
I want the header to be left, center, and right

### ISSUE THREAD

**Issue by felixXian** [aspose-free-consulting/projects#65]
There are two sentences in the header, one on the left and one on the right，No method was found in the API。
Please help me，thank you!

**Comment by shahzad-latif** [comment]
@felixXian,

Could you please post this query to our free support forums, so the team can help you properly? https://forum.aspose.com/ Please select the API you're working with and post your question. 

Also, please provide the related sample document, along with code sample and output you're working with, so we can see the exact issue and then guide you accordingly.
