### ISSUE TITLE
I want to apply encrypt decrypt password in adpose pdf in dot net Core. Is it feasible to set privilege?

### ISSUE THREAD

**Issue by nandarko** [aspose-free-consulting/projects#67]
Is it possible to set privileges encrypt and decrypt pdf file in .net core? It is related to adpose dll.

**Comment by asadalikhan90** [comment]
@nandarko 

Yes, it is possible to [set Privileges, Encrypt, and Decrypt PDF documents using Aspose.PDF for .NET](https://docs.aspose.com/pdf/net/set-privileges-encrypt-and-decrypt-pdf-file/) under .NET Core environment. You can please try using a linked-example at your side. Please also note that we recommend posting such inquiries/issues in our [Aspose.PDF forum](https://forum.aspose.com/c/pdf). So, you can please create a post there in case you face any issue while implementing the suggested approach and you will be assisted accordingly.

**Comment by asadalikhan90** [comment]
@nandarko 

We have published a sample project (in .NET Core 3.1) over the following link which showcases the functionality to set privileges, encrypt and decrypt PDF file in .NET Core using Aspose.PDF.

https://github.com/aspose-free-consulting/Create-TOC-in-Existing-PDF-by-Extracting-Page-Titles
