### ISSUE TITLE
Failed to retrieve information about 'Aspose.PDF' from remote source

### ISSUE THREAD

**Issue by gest111** [aspose-free-consulting/projects#68]
Hi, I'm getting the following error when building the application in TeamCity. Any idea what's wrong? 
Please note, that when I click on the link I can access the information without any problems.
Thanks

 C:\Program Files\dotnet\sdk\3.1.301\NuGet.targets(128,5): error : Failed to retrieve information about 'Aspose.PDF' from remote source '**https://pkgs.dev.azure.com/ETGBSG/ETGBSG/_packaging/BSG/nuget/v2/FindPackagesById()?id='Aspose.PDF'&semVerLevel=2**

**Comment by shahzad-latif** [comment]
@gest111 

Please post any Aspose related issues in the support forums https://forum.aspose.com/ so our team can help you in a timely manner. In case of Aspose.PDF, you can post it here https://forum.aspose.com/c/pdf

Thanks for your cooperation.
