### ISSUE TITLE
I want to change EMail body with Aspose email

### ISSUE THREAD

**Issue by neogeoss** [aspose-free-consulting/projects#7]
Hi. My company bought Aspose.EMAIL library last year.
I am using the Aspose.EMAIL library to remove attachment without any problem.
I would like to extract any URL like string from the body and replace it with blank.
Is the way to do so to use Body property and read the body and replace any url string with my own one?

**Comment by shahzad-latif** [comment]
@neogeoss 

Thanks for getting in touch. Let's check your requirement in detail and we'll get back to you with further update ASAP. Thanks.

**Comment by shahzad-latif** [comment]
@neogeoss 

We have started working on a project based upon the information you provided. However, if you can share which body type you process like HTML, Plain Text or RTF, that will help us better focus on your particular case. Also we'll be able to see how the links are formatted in your case.

**Comment by shahzad-latif** [comment]
@neogeoss 

Please have a look at the following sample code to replace URL in an email: https://github.com/aspose-free-consulting/replace-url-in-email-body

Please share if you need some changes in this project.
