### ISSUE TITLE
Is aspose document viewer can be integrated with angular application

### ISSUE THREAD

**Issue by ajaykumarj53** [aspose-free-consulting/projects#70]
We have an existing angular application we want to provide online word, Excel view ability to out users can we do that with aspose
if yes can you provide some sample applications or code

**Comment by shahzad-latif** [comment]
@ajaykumarj53 

Please check this thread https://github.com/groupdocs-free-consulting/projects/issues/8 
Does that help in your scenario? If not, please do let us know.

**Comment by shahzad-latif** [comment]
@ajaykumarj53 Please see if this sample project helps in your scenario https://github.com/groupdocs-free-consulting/display-document-in-browser-without-downloading
