### ISSUE TITLE
i am unable to create PDF file by URL using ASPOSE.PDF in C#,i am getting the following problem. 

### ISSUE THREAD

**Issue by ubaid4** [aspose-free-consulting/projects#72]
i want to create PDF file by  URL using ASPOSE.PDF and try the following code

```c#
string dataDir =@"C:\Users\UbaidUllah\Documents\Visual Studio 2015\Projects\aspose\Data\AsposePDF\DocumentConversion\";
WebRequest request = WebRequest.Create("https://www.cricbuzz.com/cricket-stats/icc-rankings/men/batting");
request.Credentials = CredentialCache.DefaultCredentials;
HttpWebResponse response = (HttpWebResponse)request.GetResponse();
Stream dataStream = response.GetResponseStream();
StreamReader reader = new StreamReader(dataStream);
string responseFromServer = reader.ReadToEnd();
reader.Close();
dataStream.Close();
response.Close();
MemoryStream stream = new MemoryStream(System.Text.Encoding.UTF8.GetBytes(responseFromServer));
HtmlLoadOptions options = new HtmlLoadOptions("https://www.cricbuzz.com/");
Document pdfDocument = new Document(stream, options);//----not execute this line nor give any error-----
pdfDocument.Save(dataDir + "WebPageToPDF_out.pdf");
```
**when i debug this code, it does not go forward from the second last line(as described in comment) nor give any error, i wait much time but do not get any response.**
I don't know where the mistake is. please review the code and help me to solve the issue.
Thank you very much!

**Comment by shahzad-latif** [comment]
@ubaid4 

I can see that you're already in discussion with our support lead in the [forum](https://forum.aspose.com/) here [Create a PDF File from Website URL](https://forum.aspose.com/t/i-am-unable-to-create-pdf-file-by-url-using-aspose-pdf-in-c-i-am-getting-the-following-problem/217898/2).

**Comment by ubaid4** [comment]
Yes, I am.
but my question is just about that there is only one way to create a PDF
file by URL, which is under discussion.
OR
Is there also another way?

**Comment by shahzad-latif** [comment]
@ubaid4 ,

As shared in the forum thread there is no other way. There is only one way and we have already logged the issue. https://forum.aspose.com/t/i-am-unable-to-create-pdf-file-by-url-using-aspose-pdf-in-c-i-am-getting-the-following-problem/217898/3
