### ISSUE TITLE
I want to convert this xlsm/vb to a website

### ISSUE THREAD

**Issue by j1223aw** [aspose-free-consulting/projects#73]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by j1223aw** [comment]
I want to convert this xlsm/vl to a webpage
[Infinite Sprint Sou Sou v1.1.zip](https://github.com/aspose-free-consulting/projects/files/5159159/Infinite.Sprint.Sou.Sou.v1.1.zip)

**Comment by j1223aw** [comment]
Thanks in advance for any help

**Comment by ahsaniqbalsidiqui** [comment]
You can convert XLSM file to HTML (Webpage) with following code:

// Open the template file
Workbook workbook = new Workbook(dataDir + "Infinite Sprint Sou Sou v1.1.xlsm");

HtmlSaveOptions options = new HtmlSaveOptions();

// Save as HTML
workbook.Save(dataDir + "Html_out.html", options);

[HTML.zip](https://github.com/aspose-free-consulting/projects/files/5167838/InfiniteHTML.zip)

But you can render such file to static HTML only, even with MS Excel, and macro buttons will render as static pictures. If your expected output is different then share expected output files for our analysis.
You can also reach us at [Aspose Forums](https://forum.aspose.com/c/cells).
