### ISSUE TITLE
I cannot to install the 3D ASPOSE JAVA API in my EC2 instance

### ISSUE THREAD

**Issue by Convertacad** [aspose-free-consulting/projects#74]
Hello,

 I’m trying to install Aspose 3D java library on my AWS EC2 instance and I’m getting into a problem while installing/extracting the library, here is the screenshot for that (https://prnt.sc/uf5os7). Kindly let us know the procedure or help us to get this sorted from your side, we can provide the SSH key if needed. 

Thank you in advance for your help. Thanks, Pedro

**Comment by shahzad-latif** [comment]
@Convertacad 

Please post your query in [Aspose.3D support forum](https://forum.aspose.com/c/3d/18), so the team can coordinate you with you and help you properly.  This place is reserved for free consulting projects only. Thanks.
