### ISSUE TITLE
Compile Time Error while using  FileFormatType.Excel2007Xlsx 

### ISSUE THREAD

**Issue by Sindhu0234** [aspose-free-consulting/projects#75]
Upgraded Aspose version from V 8.0 to V20.8

1)  FileFormatType.Excel2007Xlsx was not supported, is there any alternative method to use  FileFormatType.Excel2007Xlsx?

**Please find the sample code** 

public static bool IsAllowedFormat(Workbook wb)
        {
            var validFileFormats = new[]
            {
                FileFormatType.CSV,
                FileFormatType.Excel2003XML,
                FileFormatType.Excel2007Xlsx,
                FileFormatType.Excel97To2003,
                FileFormatType.Xlsx,
            };
            return validFileFormats.Contains(wb.FileFormat);
        }

**Comment by shahzad-latif** [comment]
@Sindhu0234 

Kindly post your query in our [forums](https://forum.aspose.com/), specifically for this query, please post it in [Aspose.Cells forums ](https://forum.aspose.com/c/cells/9)so our team can reply in a timely manner. This space is only reserved for free consulting projects. Thanks for your cooperation.
