### ISSUE TITLE
I use it in. Net core 3.1 Aspose.CAD , convert the DWG file to PDF, my program can run on the windows10 platform, but it reports errors in the Linux platform, ask God to solve it!!!

### ISSUE THREAD

**Issue by yongxin-it** [aspose-free-consulting/projects#76]
Aspose.CAD.CadExceptions.lmageSaveException: Image saving failed.---> Aspose.CAD.CadExceptions.ImageSaveException: Image export failed. The type initializer for 'Gdip' threw an exception---> System.TypelnitializationException: The type initializer for 'Gdip threw an exception.--> System.DllNotFoundException: Unable to load shared library "libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD DEBUG environment variable: liblibgdiplus: cannot open shared object file: No such file or director)at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr&token, Startuplnput& input, StartupOutput& output)at System.Drawing.SafeNativeMethods.Gdip..cctor0--End of inner exception stack trace -at System.Drawing.SafeNativeMethods.Gdip.GdipCreateMatrix2(Single m11, Single m12, Single m21, Single m22, Single dx, Single dy, IntPtr& matrix)at System.Drawing.Drawing2D.Matrix..ctor(Single m11, Single m12.Single m21, Single m22, Single dx, Single dy).at Aspose.Drawing.DrMatrix.Invertoat. (ApsCanvas , ApsRenderingMode , DrColor o, Single , Single -, Boolean a)ata.o (ImageOptionsBase ,Int32 )ato. (Image ,o o, Stream a, ImageOptionsBase a, Rectangle o) ata .Export(Image , Stream , ImageOptionsBase a. Rectangle c) at Aspose.CAD.Image.a. Cat Aspose.Base.LongOperationHandler.ExecuteLongOperation(LongOperation operation, Int32 timeout, InterruptionToken token)at Aspose.CAD.Image.Savelnternal(Stream stream, ImageOptionsBaseoptionsBase).-End of inner exception stack traceat Aspose.CAD.Image.Savelnternal(Stream stream, ImageOptionsBaseoptionsBase)at Aspose.CAD.Image.Savelnternal(String filePath, ImageOptionsBase options)--- End of inner exception stack traceat Aspose.CAD.Image.Savelnternal(String filePath, ImageOptionsBase options)

**Comment by shahzad-latif** [comment]
@yongxin-it 

Please post this issue in [Aspose.CAD forum](https://forum.aspose.com/c/cad/19) so our team can guide you properly. Please note our [free support forums](https://forum.aspose.com/) are the main avenue to get support of this kind. Thanks for your cooperation.
