### ISSUE TITLE
Using Aspose.Cells for .NET, I want to bulk copy an Excel file to a MS SQL Server database table with the same format and column names.

### ISSUE THREAD

**Issue by thomas-morrison-CP** [aspose-free-consulting/projects#77]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< We're currently importing Excel files into SQL reading them line-by-line and cell-by-cell. Very inefficient. We want to bulk read the files into SQL. >

<  We're using Aspose.Cells for .NET | Windows 2012R2 | MS SQL Server 2016 > 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>
[GL_TOTAL_202007_081120.xlsx](https://github.com/aspose-free-consulting/projects/files/5247969/GL_TOTAL_202007_081120.xlsx)

**Comment by shahzad-latif** [comment]
@thomas-morrison-CP 

Could you please also share your code which you're currently using to read excel files using Aspose.Cells so we can see how you're doing currently and suggest a better approach? Our team is looking into this and will provide you a sample soon.

**Comment by shahzad-latif** [comment]
This was published here https://github.com/aspose-free-consulting/Bulk-Copy-Excel-Data-to-SQL-Server-Database-using-dotNET
