### ISSUE TITLE
speed of convert word to pdf

### ISSUE THREAD

**Issue by 201624133116** [aspose-free-consulting/projects#78]
I want to know the speed of word to pdf. How many pages can you turn in a second? How long does it take for 100 pages? What about 1000 pages? 2000?...

**Comment by shahzad-latif** [comment]
@201624133116 

Please post this question in our [free support forums](https://forum.aspose.com/) specifically in [Aspose.Words Forums](https://forum.aspose.com/c/words/8). Thanks.
