### ISSUE TITLE
Document processing capability in web application

### ISSUE THREAD

**Issue by arpanb17** [aspose-free-consulting/projects#82]
We are in the process of evaluating the appropriate tool with word document processing capabilities which involves template designing (mail merge, place holder’s ,prompts,  IF block , loops , Preview, fillable forms, document’s merging. E-signature, field codes etc) and document rendering (Preview, Printing, Export to PDF, Annotations, Watermarking  etc).

We need all this capability to be integrated in web application developed in .Net core(v3.1) application with UI being developed in Angular 9 and it will be hosted in Microsoft’s azure cloud. 

I would like to understand if not all what all features are supported in Aspose document processing products that can help up us achieve above features.

**Comment by awaishafeez** [comment]
@arpanb17,

[Aspose.Words for .NET](https://products.aspose.com/words/net) class library **supports .NET Core 3.1** and with it you can programmatically generate, modify, convert and render word processing documents. But it does **not** offer any **UI or web control** for performing these document processing tasks. However, you may want to take a look at our sister company’s [GroupDocs.Editor](https://products.groupdocs.com/editor) and [GroupDocs.Viewer](https://products.groupdocs.com/viewer) solutions.

Please refer to the following resources for more details:

**Mail Merge**: [Programmatic way of creating a Mail Merge template](https://docs.aspose.com/words/net/mail-merge-template/#create-a-mail-merge-template)

**Place Holder’s**: [Use Find and Replace](https://docs.aspose.com/words/net/find-and-replace/) functionality to replace keywords in Word document with Text, Images, Table, HTML etc

**Prompts**: [Inserting ASK field into a Document without using DocumentBuilder](https://docs.aspose.com/words/net/inserting-fields/#inserting-ask-field-into-a-document-without-using-documentbuilder) to prompt the user for text to assign to a Bookmark in Word document.

**IF Blocks**: Please check [Table inside true part of IF field.zip](https://github.com/aspose-free-consulting/projects/files/5333078/Table.inside.true.part.of.IF.field.zip) where I placed a Table inside True part of IF field. Following C# code will show the Table while specifying false to merge field will hide it.
```
Document doc = new Document("E:\\Table inside true part of IF field.docx");
doc.MailMerge.Execute(new String[] { "show" }, new String[] { "true" });
doc.Save("E:\\output.docx");
```
**Loops**: There are two ways to implement this - using [Mail Merge with Regions](https://docs.aspose.com/words/net/types-of-mail-merge-operations/#mail-merge-with-regions) and [foreach tags](https://docs.aspose.com/words/net/template-syntax/#outputting-sequential-data) of advanced LINQ Reporting Engine

**Preview**: You can convert all pages in Word document to separate JPEG (or PNG, BMP etc) images by using the following C# code and then display images on web:
```
Document doc = new Document("C:\\temp\\input.docx");
ImageSaveOptions options = new ImageSaveOptions(SaveFormat.Jpeg);
options.PageCount = 1;
int pageCountDoc = doc.PageCount;
for (int pageCount = 0; pageCount < pageCountDoc; pageCount++)
{
    options.PageIndex = pageCount;
    doc.Save("C:\\Temp\\out_" + pageCount + ".jpg", options);
}
```
**Fillable Forms**: Please refer to this page - [Working with Form Fields](https://docs.aspose.com/words/net/working-with-form-fields/)

**Document’s Merging**: Please refer to this section of documentation - [Joining and Appending Word Documents](https://docs.aspose.com/words/net/join-and-append-documents/)

**E-signature**: Please post a query in **[Aspose.Words forum](https://forum.aspose.com/c/words/8)** and attach a sample Word document containing E-signature for our reference. We will then reply to your forum post accordingly.

**Field Codes**: Please check [Working with Fields](https://docs.aspose.com/words/net/working-with-fields/) and its child pages.

**Printing**: [Print a Document Programmatically or Using Dialogs](https://docs.aspose.com/words/net/print-a-document-programmatically-or-using-dialogs/)

**Export to PDF**: [Convert a Document to PDF](https://docs.aspose.com/words/net/convert-a-document-to-pdf/)

**Annotations**: See [Working with Comments](https://docs.aspose.com/words/net/working-with-comments/) and [Track Changes in a Document](https://docs.aspose.com/words/net/track-changes-in-a-document/)

**Watermarking**: [Working with Watermark](https://docs.aspose.com/words/net/working-with-watermark/)

Also, Aspose.Words for .NET works well in the Azure cloud platform. We suggest you please read about [Windows Azure Platform](https://docs.aspose.com/words/net/windows-azure-platform/) and its following child pages:

- [Converting Documents in Windows Azure](https://docs.aspose.com/words/net/converting-documents-in-windows-azure/) and 
- [Converting a Document with Images using Aspose.Words in Azure Functions](https://docs.aspose.com/words/net/converting-a-document-with-images-using-aspose-words-in-azure-functions/)
