### ISSUE TITLE
divide ms Excel document into HTML according to regular expression and font features (font-size, font-family, font-color).

### ISSUE THREAD

**Issue by shun-shiranita** [aspose-free-consulting/projects#84]
Dear Aspose,
Could I ask you to do some coding about the project below in Free consulting place?
This project is Excel version of #83 (#83 for Word).

**Specification for division of ms Excel document into HTML**

**input/output/parameters**
input: ms Excel document
output: divided HTML
param: three different sets of regex, font-size, font-family, font-color

**environment**
docker + Linux

**Requirements:**
It's necessary to split a ms Excel document depending on three criteria i.e. section, subsection, item.
Each criterion consists of specified regex, font-size, font-family, font-color.

In the first cycle, an input document will be splitted base on the pieces of information of the "section"
(regex, font-size, font-family, font-color).
In details, the criterion searches over a document for a string with specified regex, font-size, font-family and font-color.
If it finds a string matched, the script splits the document just before the string.

In the second cycle, each splitted document will then divided based on the pieces of information of the "subsection" likewise.
(regex, font-size, font-family, font-color).
In the third cycle, the splitted parts in the second cycle will be divided further based on the pieces of information of the "item" in the same way.
(regex, font-size, font-family, font-color).

The final output should be forms of HTML.
What is important is never to let objects in the original document move from where they are displayed in it.
I assume that the functions above can be realized using some components of Aspose.Total.

**Comment by amjad-sahi** [comment]
1) Searching specific string is not an issue and Aspose.Cells can find the cell containing the specified string (it also supports regex) in the spreadsheet, see the [document](https://docs.aspose.com/cells/net/find-or-search-data/) for your reference.  But for finding a string with respect to font attributes looks out of context for MS Excel if you talk about any specific option. And, browsing sheet cell by cell to get font attributes/style is not an efficient approach if there is long list of data in the sheet. Could you provide details with sample Excel files, screenshots etc., on how will you accomplish the task via MS Excel manually regarding matching font attribute, so we could get better idea of your requirements as well. 

2) Could you explain splitting documents so we understand your requirements to suggest the relevant APIs or approach. Do you need to insert line break once you find the matched string in the sheet? You may share more details, sample Excel files (input file, expected file, etc.) for his task.

Moreover, you may also reach us via Aspose.Cells [forum](https://forum.aspose.com/c/cells/9) where we handle clients queries and issues actively.

**Comment by shun-shiranita** [comment]
@amjad-sahi 

Thank you for your reply.
To clarify our requirements in details, I would like to offer an input file and expected output files.
However it is necessary to make these files private since they come from one of our clients.
(Of course it's not problem to make scripts and posts public for us.)
Are there some ways of passing down the files to you by meeting this constraint?

**Comment by shahzad-latif** [comment]
@shun-shiranita ,

Please share the files and other details along with reference to this github thread in our [support forums](https://forum.aspose.com/).  In case of Excel related queries, please post in [Aspose.Cells Support Forum](https://forum.aspose.com/c/cells/9).

You can mark the forum thread as private so it will be only accessible by you and our team. I hope that helps.

**Comment by shun-shiranita** [comment]
@shahzad-latif 

I have shared the files and supplementary details on Forum.
Please check it out.

**Comment by shahzad-latif** [comment]
This issue will be taken care of in the forums.
