### ISSUE TITLE
Aspose.Email Issue "2 CR Found" and recommended approach

### ISSUE THREAD

**Issue by curiousreedhub** [aspose-free-consulting/projects#86]
Hi,

I randomly get the issue "2 CR Found" but I am unable to find description anywhere what causes this exception.
Could you please share what are the possible reasons for this exception? 

We are using the Aspose Email to read all emails, move that email in other folder.
Connectivity approach is using clientId, secret, tenant, mailboxID, password .
PostRequest simply invokes oauth2 for authentication 

```
String url = "https://login.microsoftonline.com/"+ tenantId + "/oauth2/token";

        HttpClient httpclient = HttpClients.createDefault();
        HttpPost httppost = new HttpPost(url);

        // Request parameters and other properties.
        httppost.setEntity(requestData);

        //Execute and get the response.
        HttpResponse httpResponse = null;
            httpResponse = httpclient.execute(httppost);
            HttpEntity entity = httpResponse.getEntity();

            if (entity != null) {
                try (InputStream instream = entity.getContent()) {
                    response = IOUtils.toString(instream);
                }
            }

```
Then initialize EWSClient in following manner:-       
 ```
bearerToken = new Gson().fromJson(response, BearerToken.class);
        OAuthNetworkCredential oAuthCredential = new OAuthNetworkCredential(bearerToken.access_token);
        iewsClient = EWSClient.getEWSClient(mailboxuri, oAuthCredential);
        iewsClient.setTimeout(-1); 

```

For every operation (readMail , moveMail) , new ewsClient is instantiated and disposed by setting it to null.
It is being used by multiple applications.
Multiple applications are creating ewsClient, performing operation on mailbox and then disposing.

What's the recommended approach to handle such scenario?
I found following article, after which I changed static client to be shared by all applications into current non-static architecture.
https://forum.aspose.com/t/iewsclient-methods-threadsafe/35592/2

Thanks

**Comment by shahzad-latif** [comment]
@curiousreedhub ,

Could you please post your query in our [free support forums](https://forum.aspose.com/)? Please post it in [Aspose.Email support forum](https://forum.aspose.com/c/email/12) so that you can get a timely and proper support. As our forums are the main venue to get support in such cases. This place is reserved for free consulting projects only. Thanks for your cooperation.
