### ISSUE TITLE
I want to compare 2 documents using iframe.once i click the button it will need to  show the compared documents through the aspose url. example : https://products.groupdocs.app/comparison/6276ff1c-37d9-46df-b147-647d5743e2c7/target1.docx/target2.docx/#page-view-1

### ISSUE THREAD

**Issue by christina3169** [aspose-free-consulting/projects#87]

**Comment by atirtahirgroupdocs** [comment]
@christina3169 

You basically want to view source and target documents in browser (within iframes). And by pressing a "compare" button, output or the resultant document must be displayed in browser.

> It will need to show the compared documents through the aspose url.
Can you please elaborate this? The resultant document will be displayed in browser within an iframe.
