### ISSUE TITLE
I want to create/build powerpoint SEARCH software running on local drive (not cloud)

### ISSUE THREAD

**Issue by sethferriss** [aspose-free-consulting/projects#88]
Please check if it satisfies the following requirements: 

[YES] It is a small project satisfying a particular scenario
* It is related to Aspose APIs
[YES] It takes 8 or less hours for us to complete
[YES] It is not a bug
[YES] It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>
I have to search through powerpoint files a lot. I am in need of a software that can run on my local computer (not cloud) to search through the headers of powerpoint files so that I can find the correct slide among the many I have.

< which platform you're working on -- operating system, development environment etc.> 
windows 10

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by shahzad-latif** [comment]
@sethferriss 

Are you looking for an off the shelf software which can provide such search facility? Please note that we do not offer such prebuilt software, rather we offer APIs which developers use to build their own applications. The functionality which you're looking for can be built using Aspose.Slides. But again, this is something you'll have to build at your end once you buy the API. 

Please let me know what your exact requirement is. Thanks.
