### ISSUE TITLE
I want to create/build a GIS map using Aspose.GIS

### ISSUE THREAD

**Issue by tal045** [aspose-free-consulting/projects#89]
We have some GIS maps/shapes stored in a SQL Server database. The goal is to read the shapes from 4 separate tables, render them together into 1 map, with custom labels on certain shapes. Not sure as to the usage of Aspose.GIS in reading from several different tables, pulling all the shapes, and rendering them together in one map. 

Windows 10 X64 environment, Visual Studio 2019, Aspose.Total 20.9 license, SQL Server 2017, ASP.NET web page that will be displaying the rendered map.

**Comment by shahzad-latif** [comment]
@tal045 

We're looking into your requirements and will get back to you with further updates soon.

**Comment by shahzad-latif** [comment]
@tal045 

We have prepared a sample for you as per your requirements. Please see if this sample helps you achieve creating [GIS Maps from SQL Server database in .NET](https://github.com/aspose-free-consulting/Create-GIS-Map-in-.NET).

**Comment by tal045** [comment]
Thank you. It turns out my code worked, I just found that it did not work with any other scheme other than default/dbo. Working with one of your developers to get this resolved.

**Comment by evgeniy-timofeev-aspose** [comment]
We have discussed this question on the forum (more details at [this link](https://forum.aspose.com/t/aspose-gis-sqlexception-when-reading-from-a-table-with-spatial-data/220043)).  I posted this comment to link topics.
