### ISSUE TITLE
I want to create/build a new endpoint in ASP.NET MVC Web API 

### ISSUE THREAD

**Issue by NarayanaGara** [aspose-free-consulting/projects#9]
I want to create/build a new endpoint in ASP.NET MVC Web API or ASP.NET Core that accepts a list of Base64 pdf file streams of max size is not greater than 50MB all streams together. when we implement concatenate memory streams, UI is not responsive and didn't get the response for 20MB. Would you please recommend server requirements or best practices for merging a list of base64 streams of max size 50MB and return the merged file as Base64 stream.

Thanks for your support!!!

**Comment by NarayanaGara** [comment]
we are using Aspose.Pdf" version 17.4.0 with ASP.NET MVC web api.

**Comment by shahzad-latif** [comment]
@NarayanaGara 

Thanks for the update. We'll get back to you with updates soon.

**Comment by shahzad-latif** [comment]
@NarayanaGara 

We have looked into this and this seems like a support issue instead of a consulting project. So please post it in our support forum and the team will guide you appropriately: https://forum.aspose.com/c/pdf. I'll close this as support request.
