### ISSUE TITLE
I want to have an On-Premise Setup for HTLM Document Viewer 

### ISSUE THREAD

**Issue by siddharthach** [aspose-free-consulting/projects#90]
Hi Team,

Our Requirement is to have an On-Premise Solution for the HTML viewer for Document. (Document can be Word, XL or other doc type).
We want to view the Document in browser.
We do not want any edit option for the Document in HTML View in Browser.
Document Type can be : XLSX, DOCX, etc
The Requirement is that the Document being confidential cannot be uploaded to the Aspose Cloud.
Can we have an On-Premise Cloud (Private Cloud ) Setup with Aspose.
We would be interested even if the solution is Paid and suffice our requirement.

**Comment by shahzad-latif** [comment]
@siddharthach 

Thanks for getting in touch. We're checking your requirements and will get back to you with more details soon.

**Comment by atirtahirgroupdocs** [comment]
@siddharthach 

> Our Requirement is to have an On-Premise Solution for the HTML viewer for Document.

Please clarify, will you be providing a _Word, Excel or other file formatted document_ as a source/input file or _the HTML view_ of these files to the application?

**Comment by siddharthach** [comment]
Hi,

We will be providing the Word, Excel and other file formats as source/input
files.
We want the corresponding HTML display in the Browser in our
Application(Web Based).

Thanks,
Siddhartha

**Comment by atirtahirgroupdocs** [comment]
@siddharthach 

Please have a look at this free consulting [project](https://github.com/groupdocs-free-consulting/display-document-in-browser-without-downloading). It takes a source file as input and renders it to HTML that is then displayed in the browser. 
You will find two projects in this repository, one is Angular based and the other one is a simple ASP.NET MVC project. Let us know if you need any further details.

**Comment by siddharthach** [comment]
Hi Atir,

Thanks for the Response. Do you have something similar in Java Based?

Thanks,
Siddhartha

**Comment by atirtahirgroupdocs** [comment]
@siddharthach 
Please have a look at this showcase [project](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-Java-Spring).
