### ISSUE TITLE
I want to create/build a program to take in a folder with a series of pdf's and convert them all to .xlsm.

### ISSUE THREAD

**Issue by coal175** [aspose-free-consulting/projects#91]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>
I have a folder with a bunch of pdf documents.  I need each to be converted into its own individual .xlsm file and saved into an output folder using the C# .NET Aspose.PDF API.
< which platform you're working on -- operating system, development environment etc.> 
Mac on Visual Studio.
<attach input documents>
[sample.pdf](https://github.com/aspose-free-consulting/projects/files/5417692/sample.pdf)
[dummy.pdf](https://github.com/aspose-free-consulting/projects/files/5417695/dummy.pdf)

<attach any sample required output documents if you have> 
[sample.xlsx](https://github.com/aspose-free-consulting/projects/files/5417702/sample.xlsx)
[dummy.xlsx](https://github.com/aspose-free-consulting/projects/files/5417703/dummy.xlsx)

<attach any additional supporting material to help us understand the requirement>

**Comment by asadalikhan90** [comment]
@coal175 

Thanks for posting your requirements here. We are looking into them and will get back to you shortly with our feedback.

**Comment by coal175** [comment]
Thanks Asad.  Excited to get a hang of the platform, it seems like a very
useful tool.

**Comment by asadalikhan90** [comment]
@coal175 

Thanks for your patience.

At this moment Aspose.PDF supports Excel 2003 XML Format, CSV, XLSX formats only. Excel 2003 XML Format support does not include macros and we are afraid that generating XLSM files would not be possible at the moment. However, you can surely generate XLS/XLSX/CSV files as per your requirements by using a fairly simple code snippet as below:

```
string pdfDir = @"D:\PDFs";
string xlsDir = @"D:\XLSs";

string[] files = Directory.GetFiles(pdfDir);
foreach(string file in files)
{
 Document document = new Document(file);
 ExcelSaveOptions saveOptions = new ExcelSaveOptions();
 saveOptions.Format = ExcelSaveOptions.ExcelFormat.XLSX;
 //saveOptions.InsertBlankColumnAtFirst = false;
 saveOptions.MinimizeTheNumberOfWorksheets = true;
 saveOptions.ConversionEngine = ExcelSaveOptions.ConversionEngines.LegacyEngine;
 document.Save(xlsDir + @"\" + DateTime.Now.Ticks + ".xls", saveOptions);
}
```

As far as the feature of generating XLSM files is concerned, we have logged it in our issue management system for the sake of implementation. We recommend and request that you post your this requirement in the [Aspose.PDF forum](https://forum.aspose.com/c/pdf) where we will link the logged ticket with your post and you will be able to track its progress.

**Comment by asadalikhan90** [comment]
@coal175 

We would like to share with you that PDF to XLSM support has been added to the API. Please try using following code snippet with **Aspose.PDF for .NET 20.12**:

```
Document doc = new Document("Source.pdf");
ExcelSaveOptions options = new ExcelSaveOptions();
options.Format = ExcelSaveOptions.ExcelFormat.XLSM;
doc.Save("Result.xlsm", options);
```
