### ISSUE TITLE
Parse tables and paragraphs correctly

### ISSUE THREAD

**Issue by Ruselgun** [aspose-free-consulting/projects#93]
Hi,
How can your library help us to correctly parse a pdf, lines, paragraphs, narrow tables, numbered or bulletted lists, then change them to other phrases. For ex: If 6 lines form a paragraph, change these 6 lines with a new paragraph text If there is a bulleted list change each individual line with new line texts. We don't want find and replace. We should also extract the tables to excel. 

Thanks,

**Comment by shahzad-latif** [comment]
@Ruselgun 

Could you please share some sample input and output files so we can see what the file/content looks like before and what it should look like after the update? This will help us guide you appropriately.

**Comment by Ruselgun** [comment]
Hello,
I have attached 2 files, the original and the wanted. If we can make the translation replace without loosing the format, the paragraph structure, table structure, fonts,... we will buy your library immediately. The original and the translation character length will not match. If the paragraph is 10 lines, line by line translation doesn't mean anything, we must find whole paragraph, and change the whole paragraph with the translation completely. 
Getting a table with row and column, or datatable structure is important, we will export it to excel.
Regards,

[Original.pdf](https://github.com/aspose-free-consulting/projects/files/5426230/Original.pdf)
[Wanted.pdf](https://github.com/aspose-free-consulting/projects/files/5426231/Wanted.pdf)

**Comment by asadalikhan90** [comment]
@Ruselgun 

We are checking your requirements and will get back to you shortly with our feedback.

**Comment by shahzad-latif** [comment]
@Ruselgun 

We have certain limitations in the API which we're looking into at our end. Some specific features need to be implemented possibly to fulfill his complete requirements. We're further trying to generate the output closest to your expected results. We'll let you know once it is ready. Thanks.

**Comment by dongsp** [comment]
Hello, is it possible to accurately extract paragraphs and tables through Java

**Comment by dongsp** [comment]
how to accurately extract PDF paragraphs and tables from Java

**Comment by asadalikhan90** [comment]
@dongsp 

Aspose.PDF offers both functionalities i.e. extract paragraphs and tables from a PDF document. In order to perform this operation, you need to use ParagraphAbsorber and TableAbsorber Classes. Please check the following sample code snippet:

```
Document doc = new Document(dataDir + "8.pdf");
ParagraphAbsorber pa = new ParagraphAbsorber();
pa.visit(doc);
for (PageMarkup pm:pa.getPageMarkups()){
for (MarkupSection ms:pm.getSections()){
  for (MarkupParagraph mp:ms.getParagraphs()){
   StringBuilder sb =new StringBuilder();
	 for(List< TextFragment> tflist : mp.getLines()){
		for(TextFragment tf:tflist ){
			sb.append(tf.getText());
		}
		sb.append("/r/n");
	  }
	  sb.append("/r/n");
	  System.out.println(sb);
  }
 }
}
		
try {
	TableAbsorber absorber = new TableAbsorber();
	PageCollection pc = doc.getPages();
	for(Page pg:pc){
	absorber.visit(pg);
	com.aspose.pdf.internal.ms.System.Collections.Generic.IGenericList<AbsorbedTable> l = absorber.getTableList();
	for(AbsorbedTable table:l){
	 for(AbsorbedRow row:table.getRowList())
	 {
		for(AbsorbedCell cell:row.getCellList())
		{
		 System.out.println(cell.getRectangle());
		 for(TextFragment tf:cell.getTextFragments())
		 {
		  for(TextSegment ts:tf.getSegments())
		  {
	            System.out.println(ts.getText());
		  }
		 }
		}
	}
   }
 }
} catch (Exception e) {
// TODO Auto-generated catch block
e.printStackTrace();
}
```

The above code snippet extracts the text as paragraphs and table content from a PDF document. In case you face any issue while achieving the desired functionality, it is recommended to create a post in the [Aspose.PDF official support forum](https://forum.aspose.com/c/pdf) where we will assist you accordingly.

**Comment by dongsp** [comment]
> 您好，
> 我附上了两个文件，原始文件和通缉犯。如果我们可以在不损失格式，段落结构，表格结构，字体等的情况下替换译文，我们将立即购买您的库。原始字符和翻译字符长度不匹配。如果段落为10行，那么逐行翻译没有任何意义，我们必须找到整个段落，并使用翻译完全更改整个段落。
> 获取具有行和列或数据表结构的表很重要，我们将其导出到excel。
> 问候，
> 
> [Original.pdf](https://github.com/aspose-free-consulting/projects/files/5426230/Original.pdf)
> [想要的.pdf](https://github.com/aspose-free-consulting/projects/files/5426231/Wanted.pdf)

Hi, I have met the same problem as you. Is there any solution at present

**Comment by asadalikhan90** [comment]
@dongsp 

> We have certain limitations in the API which we're looking into at our end. Some specific features need to be implemented possibly to fulfill your complete requirements. We're further trying to generate the output closest to your expected results. We'll let you know once it is ready.

As shared previously in this thread, there are certain limitations in the API against your complex requirements and we need to investigate how an expected output PDF can be generated using Aspose.PDF. We are investigating the scenario at our end and as soon as we have some feedback, we will update you here. Please give us some time.

**Comment by shahzad-latif** [comment]
@dongsp 

Please raise this issue in our support forums. As this involves detailed investigation of the matter which can't be done in short time. So the forums would be a better place to log, track, and follow up this matter properly. So I'm going to close this thread and we'll follow up at forums only. Thanks for your understanding and cooperation.
