### ISSUE TITLE
I want to create a ppt using template and would like to use  data binding present in the template slide

### ISSUE THREAD

**Issue by aggshikha84** [aspose-free-consulting/projects#94]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by mudassirfayyaz** [comment]
@aggshikha84 

You have shared the same question in Aspose.Slides product support forum as well. We are eager to help you further. However, we need the requested information from you to proceed further. Can you please share the requested information in [concerned forum thread](https://forum.aspose.com/t/is-data-binding-supported-by-aspose-slides-for-java/220938).

**Comment by aggshikha84** [comment]
Thanks for your reply. I am on leave currently.. will get back to you as
soon as I resume my work.
