### ISSUE TITLE
Problems with System.Drawing in Aspose.PDF used in web service

### ISSUE THREAD

**Issue by rblasco76** [aspose-free-consulting/projects#95]
Hi, 
I use Aspose in web service and I'm having a lot of performance issues.

Checking with Microsoft, they tell me that the reference to System.Drawing does not work correctly in web services.

I would like to know if it is possible to use the functionalities of Aspose.PDF without using the reference to System.Drawing.

Best regards

**Comment by asadalikhan90** [comment]
@rblasco76 

> I would like to know if it is possible to use the functionalities of Aspose.PDF without using the reference to System.Drawing.

At this moment, Aspose.PDF is delivered with a reference to System.Drawing Assembly. We have been trying to remove this dependency and replace it with our own component but that is still in raw production. So, we cannot say that System.Drawing can be replaced with Aspose.PDF as it is delivered with a reference to System.Drawing. Furthermore, we recommend posting such inquiries in the [Aspose.PDF forum](https://forum.aspose.com/c/pdf) which is the right place to ask and track such issues. Please try to post your inquiry there in case you have some.
