### ISSUE TITLE
Make editable field in an existing pdf

### ISSUE THREAD

**Issue by FrasseAnka** [aspose-free-consulting/projects#97]
Hi
I want to be able to create a new pdf from an existing pdf and in the new pdf file I want some fields to be writable so that the user can enter, for example, some comment, date and name.
In the original pdf, the fields that are to be writable are marked with, for example, a text string as "writeable". Then the program should replace the string and open up the field for writing. Is this possible to perform? Is there an example?

**Comment by shahzad-latif** [comment]
@FrasseAnka 

Do you have any sample PDF files (maybe manually created) which can show us the scenario more accurately? This will help us better understand the requirement and we'll be able to help you properly.

**Comment by FrasseAnka** [comment]
Hi Shahzad
I have attached a sample-pdf.
If you look at page 2 at the bottom you can see 4 fields that has the text
"rw" (it can be any other searchable text string but in this sample I use
"rw") in it. I want to make this fields writable. Is it possible and how do
I perform it ?

/Frasse



Den tis 8 dec. 2020 kl 07:37 skrev Shahzad Latif <notifications@github.com>:

**Comment by FrasseAnka** [comment]
continuation of my previous email.
If I make a frame around each field, can I make the whole field editable?
Is there some methods to detect the frame around each field?
The last field in the sample-pdf is a multiline text field and I want the
whole to be writable. Is it possible?
/Frasse

Den tis 8 dec. 2020 kl 08:52 skrev Frasse Anka <frasse.anka99@gmail.com>:

**Comment by asadalikhan90** [comment]
@FrasseAnka 

Aspose.PDF allows you to find a particular text phrase and extract its position. Once you have a position, you can place a form field (a text box in your case) there. We will surely prepare a sample project in order to demonstrate the functionality. However, we could not find any sample PDF attached to your previous replies. Would you please make sure to upload it again so that we may further proceed to assist you accordingly?

**Comment by FrasseAnka** [comment]
I try to send my pdf again. As in previous mail I can see the attached pdf.
Hope you will see it now.

Den tis 8 dec. 2020 kl 16:12 skrev Asad Ali <notifications@github.com>:

**Comment by FrasseAnka** [comment]
Sending a picture of page2 bottom
[image: image.png]

Den tis 8 dec. 2020 kl 16:41 skrev Frasse Anka <frasse.anka99@gmail.com>:

**Comment by asadalikhan90** [comment]
@FrasseAnka 

We could not find any attachment in the email notification or with your reply over here. Would you please try to create a post in our official forums (https://forum.aspose.com/c/pdf) where you can attach files as well. We will further proceed to create a sample application and share it with you.
