### ISSUE TITLE
I want to save a "screenshot" of my .obj file or of many .obj file

### ISSUE THREAD

**Issue by Malhaudo** [aspose-free-consulting/projects#98]
Hi,

I want to open a .obj file, change his positions / opacity and take a screenshot save in .png file of this changements.
But i get nothing on rendering.

Can you help me ?

Thanks you.

[Render3DModelImageFromCamera.zip](https://github.com/aspose-free-consulting/projects/files/5671908/Render3DModelImageFromCamera.zip)

**Comment by asadalikhan90** [comment]
@Malhaudo 

We are looking into your requirements and will get back to you shortly.

**Comment by Malhaudo** [comment]
Hello ! @asadalikhan90 thanks you. 

For helping you, another person can render, i'm the only one who have a "black screen" on rendering. I don't understand. i'm having missed libraries ?

**Comment by asadalikhan90** [comment]
@Malhaudo 

If the model is out of the camera's frustum, the camera will not be able to see it, not all obj models are centered. So it is possible that you get nothing on rendering. We checked the Run2() method and it actually rendered a box. A skybox in 3D is usually used to represent the sky, so the camera should always be inside the skybox. Here is what it looks like on our side. 

![image_2020_12_16T06_58_52_310Z](https://user-images.githubusercontent.com/22503496/102408976-2b987c00-4010-11eb-9acb-a003bd5dc8e3.png)

Furthermore, we need to investigate how to do rendering with a better model, and this task needs more time. We recommend and request you please create a topic in our [official forum](https://forum.aspose.com/c/3d) where your all requirements would be investigated and appropriate feedback will be shared accordingly.

**Comment by Malhaudo** [comment]
@asadalikhan90 ,

My problem is that the Run2() method actually rendered nothing for me, juste a black picture, like your example in Run(). I have try a lot of changes but it  changed nothing. All tries generate a black picture. If i set red background in ImageRenderOptions i'll have a red picture with nothing. 

which makes me think that there is a problem with the library, it's that your example without modifications generated me a black image each time

**Comment by asadalikhan90** [comment]
@Malhaudo 

> it's that your example without modifications generated me a black image each time

Yes, we found that our example needed to be modified to produce better results. Hence, we have modified it and added a new 3D file used for demonstration. You can please check [this commit](https://github.com/aspose-3d/Aspose.3D-for-.NET/pull/17/commits/4e2c6282da5780af40212bd200573d01c0d2d845) and please create a post in [Aspose.3D official forum](https://forum.aspose.com/c/3d) in case you face any issue.

**Comment by Malhaudo** [comment]
@asadalikhan90 

Thanks for the update, but my problem is still there.
I have used the last version you send yesterday and the same problem is there, just now it's not a "black image" but a "AliceBlue image"
![Render3DModelImageFromCamera](https://user-images.githubusercontent.com/12425775/102597038-50791600-411a-11eb-9e0a-f8433bd1f1a5.png)

Maybe drivers problems ? i have a i5 10th without graphic cards.

**Comment by asadalikhan90** [comment]
@Malhaudo 

We are looking into the issue on our side and will soon update you. Furthermore, as requested earlier -  please try to create a post in our official forum as this seems to be an issue with the API, and we need to investigate it properly. The ticket is already logged in our issue tracking system as **THREEDNET-800**. Also, you will be able to properly track the issue resolution progress if it is reported in our forum.

**Comment by shahzad-latif** [comment]
@Malhaudo 

Please create a thread in our [free support forum](https://forum.aspose.com/c/3d/) to track this issue properly. I'm going to close this thread.
