### ISSUE TITLE
distortion

### ISSUE THREAD

**Issue by wonderpan** [aspose-free-consulting/projects#99]
i tried to covert excel to pdf ,but i got a distorted pdf,like this 
![1](https://user-images.githubusercontent.com/42286379/102953952-68cba500-450d-11eb-8ab9-002077b1050b.png)
![2](https://user-images.githubusercontent.com/42286379/102953955-69fcd200-450d-11eb-864e-59d33fb81dda.png)

**Comment by shahzad-latif** [comment]
@wonderpan ,

This is an investigation matter so please post this query in our [free support forums](https://forum.aspose.com/) so that our team can properly help you out.
